---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Prima di configurare gli switch Cisco Nexus 3232c, è opportuno esaminare una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Gli switch Cisco Nexus 3232C possono essere utilizzati come switch cluster nel cluster AFF o FAS . Gli switch cluster consentono di creare cluster ONTAP con più di due nodi.


NOTE: La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

Se necessario, per ulteriori informazioni fare riferimento a quanto segue:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Requisiti di migrazione CN1610

Gli switch del cluster supportano le seguenti connessioni di nodo:

* NetApp CN1610: porte da 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3232C: porte e1/1-30 (40 o 100 o 4x10GbE)


Gli switch del cluster utilizzano le seguenti porte di collegamento inter-switch (ISL).

* NetApp CN1610: porte da 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3232C: porte 1/31-32 (100GbE)


[NOTE]
====
È necessario utilizzare cavi breakout 4x10G sullo switch cluster Cisco Nexus 3232C.

====
Nella tabella seguente sono indicati i collegamenti dei cavi necessari in ogni fase della transizione dagli switch NetApp CN1610 agli switch cluster Cisco Nexus 3232C:

|===
| Palcoscenico | Descrizione | Cavi richiesti 


 a| 
Iniziale
 a| 
Da CN1610 a CN1610 (da SFP+ a SFP+)
 a| 
4 cavi SFP+ in fibra ottica o rame a collegamento diretto



 a| 
Transizione
 a| 
Da CN1610 a 3232C (da QSFP a SFP+)
 a| 
1 QSFP e 4 cavi breakout in fibra ottica o rame SFP+



 a| 
Finale
 a| 
Da 3232C a 3232C (da QSFP a QSFP)
 a| 
2 cavi QSFP in fibra ottica o rame a collegamento diretto

|===
È necessario aver scaricato i file di configurazione di riferimento (RCF) applicabili.  Il numero di porte 10 GbE e 40/100 GbE è definito negli RCF disponibili sulink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] .

Le versioni ONTAP e NX-OS supportate in questa procedura sono elencate inlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] .

Le versioni ONTAP e FASTPATH ​​supportate in questa procedura sono elencate inlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Switch NetApp CN1601 e CN1610"^] .

.Informazioni sugli esempi utilizzati
Gli esempi nella procedura di migrazione utilizzano quattro nodi:

* Due nodi utilizzano quattro porte di interconnessione cluster da 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Gli altri due nodi utilizzano due cavi in fibra ottica di interconnessione cluster da 40 GbE: *e4a* e *e4e*.
+
ILlink:https://hwu.netapp.com/["_Universo Hardware_"^] contiene informazioni sui cavi in fibra ottica del cluster per le tue piattaforme.



Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nodi sono *n1*, *n2*, *n3* e *n4*.
* Gli output dei comandi potrebbero variare a seconda delle diverse versioni del software ONTAP .
* Gli switch CN1610 da sostituire sono *CL1* e *CL2*.
* Gli switch Nexus 3232C che sostituiranno gli switch CN1610 sono *C1* e *C2*.
* *n1_clus1* è la prima interfaccia logica del cluster (LIF) connessa allo switch del cluster 1 (CL1 o C1) per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo *n1*.
* *n1_clus3* è il secondo LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo *n1*.
* *n1_clus4* è il secondo LIF connesso allo switch cluster 1 (CL1 o C1) per il nodo *n1*.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] .


.Cosa succederà ora?
Dopo aver esaminato i requisiti di migrazione, puoilink:cn1610-prepare-to-migrate.html["preparati a migrare i tuoi switch"] .
