---
permalink: switch-cisco-3232c/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Prima di configurare gli switch Cisco Nexus 3232c, è opportuno esaminare una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Gli switch Cisco Nexus 3232C possono essere utilizzati come switch cluster nel cluster AFF o FAS . Gli switch cluster consentono di creare cluster ONTAP con più di due nodi.

[NOTE]
====
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

====
Per maggiori informazioni, vedere:

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Requisiti Cisco Nexus 5596

Gli switch del cluster utilizzano le seguenti porte per le connessioni ai nodi:

* Nexus 5596: porte e1/1-40 (10 GbE)
* Nexus 3232C: porte e1/1-30 (10/40/100 GbE)


Gli switch del cluster utilizzano le seguenti porte Inter-Switch Link (ISL):

* Nexus 5596: porte e1/41-48 (10 GbE)
* Nexus 3232C: porte e1/31-32 (40/100 GbE)


ILlink:https://hwu.netapp.com/["_Universo Hardware_"^] contiene informazioni sul cablaggio supportato per gli switch Nexus 3232C:

* I nodi con connessioni cluster da 10 GbE richiedono cavi breakout in fibra ottica da QSFP a SFP+ o cavi breakout in rame da QSFP a SFP+.
* I nodi con connessioni cluster 40/100 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra o cavi di collegamento diretto in rame QSFP/QSFP28.


Gli switch del cluster utilizzano il cablaggio ISL appropriato:

* Inizio: Nexus 5596 (SFP+ a SFP+)
+
** 8 cavi SFP+ in fibra o rame a collegamento diretto


* Interim: da Nexus 5596 a Nexus 3232C (break-out da QSFP a 4xSFP+)
+
** 1x cavi breakout in fibra QSFP a SFP+ o cavi breakout in rame


* Finale: da Nexus 3232C a Nexus 3232C (da QSFP28 a QSFP28)
+
** 2 cavi QSFP28 in fibra o rame a collegamento diretto


* Sugli switch Nexus 3232C è possibile utilizzare le porte QSFP/QSFP28 in modalità 40/100 Gigabit Ethernet o 4 x10 Gigabit Ethernet.
+
Per impostazione predefinita, sono presenti 32 porte nella modalità Ethernet 40/100 Gigabit.  Queste 40 porte Gigabit Ethernet sono numerate secondo una convenzione di denominazione a 2 tuple.  Ad esempio, la seconda porta Ethernet da 40 Gigabit è numerata come 1/2.

+
Il processo di modifica della configurazione da 40 Gigabit Ethernet a 10 Gigabit Ethernet è chiamato _breakout_, mentre il processo di modifica della configurazione da 10 Gigabit Ethernet a 40 Gigabit Ethernet è chiamato _breakin_.

+
Quando si scompone una porta Ethernet 40/100 Gigabit in porte Ethernet 10 Gigabit, le porte risultanti vengono numerate utilizzando una convenzione di denominazione a 3 tuple.  Ad esempio, le porte break-out della seconda porta Ethernet 40/100 Gigabit sono numerate come 1/2/1, 1/2/2, 1/2/3 e 1/2/4.

* Sul lato sinistro degli switch Nexus 3232C ci sono 2 porte SFP+, denominate 1/33 e 1/34.
* Hai configurato alcune porte sugli switch Nexus 3232C per funzionare a 10 GbE o 40/100 GbE.
+
[NOTE]
====
È possibile suddividere le prime sei porte in modalità 4x10 GbE utilizzando `interface breakout module 1 port 1-6 map 10g-4x` comando.  Allo stesso modo, è possibile raggruppare le prime sei porte QSFP+ dalla configurazione breakout utilizzando `no interface breakout module 1 port 1-6 map 10g-4x` comando.

====
* Hai eseguito la pianificazione, la migrazione e letto la documentazione richiesta sulla connettività 10 GbE e 40/100 GbE dai nodi agli switch cluster Nexus 3232C.
* Le versioni ONTAP e NX-OS supportate in questa procedura sono alink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] .


.Informazioni sugli esempi utilizzati
Gli esempi in questa procedura descrivono la sostituzione degli switch Cisco Nexus 5596 con gli switch Cisco Nexus 3232C.  È possibile utilizzare questi passaggi (con modifiche) anche per altri switch Cisco più vecchi (ad esempio, 3132Q-V).

La procedura utilizza anche la seguente nomenclatura di switch e nodi:

* Gli output dei comandi potrebbero variare a seconda delle diverse versioni di ONTAP.
* Gli switch Nexus 5596 da sostituire sono *CL1* e *CL2*.
* Gli switch Nexus 3232C che sostituiranno gli switch Nexus 5596 sono *C1* e *C2*.
* *n1_clus1* è la prima interfaccia logica del cluster (LIF) connessa allo switch del cluster 1 (CL1 o C1) per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo *n1*.
* *n1_clus3* è il secondo LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo *n1*.
* *n1_clus4* è il secondo LIF connesso allo switch cluster 1 (CL1 o C1) per il nodo *n1*.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili sullink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] .
* I nodi sono *n1*, *n2*, *n3* e *n4*.


Gli esempi in questa procedura utilizzano quattro nodi:

* Due nodi utilizzano quattro porte di interconnessione cluster da 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Gli altri due nodi utilizzano due porte di interconnessione cluster da 40 GbE: *e4a* e *e4e*.
+
ILlink:https://hwu.netapp.com/["_Universo Hardware_"^] elenca le porte cluster effettive sulle tue piattaforme.



.Scenari trattati
Questa procedura copre i seguenti scenari:

* Il cluster inizia con due nodi connessi e funzionanti in un cluster composto da due switch Nexus 5596.
* L'interruttore del cluster CL2 deve essere sostituito da C2 (passaggi da 1 a 19):
+
** Il traffico su tutte le porte del cluster e sui LIF su tutti i nodi connessi a CL2 viene migrato sulle prime porte del cluster e sui LIF connessi a CL1.
** Scollegare i cavi da tutte le porte del cluster su tutti i nodi connessi a CL2, quindi utilizzare i cavi breakout supportati per ricollegare le porte al nuovo switch del cluster C2.
** Scollegare il cablaggio tra le porte ISL tra CL1 e CL2, quindi utilizzare il cablaggio breakout supportato per ricollegare le porte da CL1 a C2.
** Il traffico su tutte le porte del cluster e sui LIF connessi a C2 su tutti i nodi viene ripristinato.


* L'interruttore del cluster CL2 verrà sostituito da C2.
+
** Il traffico su tutte le porte del cluster o LIF su tutti i nodi connessi a CL1 viene migrato sulle seconde porte del cluster o LIF connesse a C2.
** Scollegare il cablaggio da tutte le porte del cluster su tutti i nodi connessi a CL1 e ricollegarlo, utilizzando il cablaggio breakout supportato, al nuovo switch del cluster C1.
** Scollegare il cablaggio tra le porte ISL tra CL1 e C2 e ricollegarlo utilizzando il cablaggio supportato, da C1 a C2.
** Il traffico su tutte le porte del cluster o LIF connesse a C1 su tutti i nodi viene ripristinato.


* Sono stati aggiunti due nodi FAS9000 al cluster con esempi che mostrano i dettagli del cluster.


.Cosa succederà ora?
Dopo aver esaminato i requisiti di migrazione, puoilink:cn5596-prepare-to-migrate.html["preparati a migrare i tuoi switch"] .
