---
permalink: switch-cisco-3232c/cn5596-complete-migration.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: È possibile utilizzare gli switch Cisco Nexus 3232C come switch cluster nel cluster AFF o FAS . 
---
= Completa la migrazione dagli switch 5596 agli switch 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Completare i seguenti passaggi per finalizzare la migrazione degli switch Nexus 5596 agli switch Nexus 3232C.

.Passi
. Verificare che siano monitorati gli switch del cluster appropriati:
+
`system cluster-switch show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network    10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
link:../switch-cshm/config-overview.html["Configurare il monitoraggio dello stato dello switch"].
