---
permalink: switch-cisco-3232c/cn5596-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: È possibile utilizzare gli switch Cisco Nexus 3232C come switch cluster nel cluster AFF o FAS . 
---
= Configura le tue porte per la migrazione dagli switch Nexus 5596 agli switch Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questi passaggi per configurare le porte per la migrazione dagli switch Nexus 5596 ai nuovi switch Nexus 3232C.

.Passi
. Disattivare le porte di interconnessione del cluster fisicamente collegate allo switch CL2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostra esempio
[%collapsible]
====
I seguenti comandi chiudono le porte specificate su n1 e n2, ma le porte devono essere chiuse su tutti i nodi:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* attendere alcuni secondi prima di eseguire il comando show per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] Spegnere gli ISL da 41 a 48 su CL1, lo switch Nexus 5596 attivo, utilizzando Cisco `shutdown` comando.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra gli ISL da 41 a 48 disattivati sullo switch Nexus 5596 CL1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/41-48*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Creare un ISL temporaneo tra CL1 e C2 utilizzando i comandi Cisco appropriati.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra un ISL temporaneo impostato tra CL1 e C2:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. Su tutti i nodi, rimuovere tutti i cavi collegati allo switch Nexus 5596 CL2.
+
Con il cablaggio supportato, ricollegare le porte disconnesse su tutti i nodi allo switch Nexus 3232C C2.

. Rimuovere tutti i cavi dallo switch Nexus 5596 CL2.
+
Collegare i cavi breakout Cisco QSFP-SFP+ appropriati che collegano la porta 1/24 del nuovo switch Cisco 3232C, C2, alle porte da 45 a 48 del Nexus 5596, CL1 esistente.

. Attivare le porte ISL da 45 a 48 sullo switch Nexus 5596 attivo CL1.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte ISL da 45 a 48 attivate:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/45-48*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verificare che gli ISL siano `up` sullo switch Nexus 5596 CL1.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte da eth1/45 a eth1/48 che indicano (P), il che significa che le porte ISL sono `up` nel porto-canale.

[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/41(D)   Eth1/42(D)   Eth1/43(D)
                                    Eth1/44(D)   Eth1/45(P)   Eth1/46(P)
                                    Eth1/47(P)   Eth1/48(P)
----
====
. Verificare che le interfacce eth1/45-48 abbiano già `modalità channel-group 1 attiva` nella loro configurazione di esecuzione.
. Su tutti i nodi, richiamare tutte le porte di interconnessione del cluster connesse allo switch 3232C C2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte specificate attivate sui nodi n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. Su tutti i nodi, ripristinare tutti i LIF di interconnessione del cluster migrati e connessi a C2:
+
`network interface revert -vserver Cluster -lif _lif-name_`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra i LIF del cluster migrato che vengono ripristinati alle loro porte home:

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus3*
----
====
. Verificare che tutte le porte di interconnessione del cluster siano ora ripristinate alla loro posizione originale:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che i LIF su clus2 sono tornati alle loro porte home e mostra che i LIF sono tornati correttamente se le porte nella colonna Porta corrente hanno uno stato di `true` nel `Is Home` colonna.  Se il `Is Home` il valore è `false` , il LIF non è stato ripristinato.

[listing]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Verificare che le porte del cluster siano connesse:
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra il risultato del precedente `network port modify` comando, verificando che tutte le interconnessioni del cluster siano `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step15]] Su ciascun nodo del cluster, migrare le interfacce associate al primo switch Nexus 5596, CL1, da sostituire:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_
-destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte o i LIF migrati sui nodi n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1 -
destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus4 -source-node n1 -
destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2 -
destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus4 -source-node n2 -
destination-node n2 -destination-port e0c*
----
====
. Verificare lo stato del cluster:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che i LIF del cluster richiesti sono stati migrati alle porte del cluster appropriate ospitate sullo switch del cluster, C2:

[listing, subs="+quotes"]
----
cluster::*> *network interface show*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0b     false
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0c     false
            n2_clus1   up/up      10.10.0.5/24       n2            e0b     false
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0c     false
8 entries were displayed.

----- ------- ----
----
====
. Su tutti i nodi, spegnere le porte dei nodi collegate a CL1:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte specificate che vengono chiuse sui nodi n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. Spegnere ISL 24, 31 e 32 sullo switch 3232C attivo C2.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra l'arresto degli ISL:

[listing, subs="+quotes"]
----
C2# *configure*
C2(Config)# *interface e1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
C2#
----
====
. Su tutti i nodi, rimuovere tutti i cavi collegati allo switch Nexus 5596 CL1.
+
Con il cablaggio supportato, ricollegare le porte disconnesse su tutti i nodi allo switch Nexus 3232C C1.

. Rimuovere il cavo breakout QSFP dalle porte e1/24 del Nexus 3232C C2.
+
Collegare le porte e1/31 ed e1/32 su C1 alle porte e1/31 ed e1/32 su C2 utilizzando cavi in ​​fibra ottica Cisco QSFP supportati o cavi a collegamento diretto.

. Ripristinare la configurazione sulla porta 24 e rimuovere il canale porta temporaneo 2 su C2.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra la configurazione sulla porta m24 ripristinata utilizzando i comandi Cisco appropriati:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *int e1/24*
C2(config-if)# *description 40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Attivare le porte ISL 31 e 32 su C2, lo switch 3232C attivo, immettendo il seguente comando Cisco : `no shutdown`
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra i comandi Cisco `switchname configure` attivato sullo switch 3232C C2:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
----
====
. Verificare che le connessioni ISL siano `up` sullo switch 3232C C2.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
Le porte eth1/31 ed eth1/32 dovrebbero indicare (P), ovvero entrambe le porte ISL sono attive nel port-channel

+
.Mostra esempio
[%collapsible]
====
[listing]
----

C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Su tutti i nodi, richiamare tutte le porte di interconnessione del cluster connesse al nuovo switch 3232C C1:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra tutte le porte di interconnessione del cluster attivate per n1 e n2 sullo switch 3232C C1:

[listing]
----

cluster::*> network port modify -node n1 -port e0a -up-admin true
cluster::*> network port modify -node n1 -port e0d -up-admin true
cluster::*> network port modify -node n2 -port e0a -up-admin true
cluster::*> network port modify -node n2 -port e0d -up-admin true
----
====
. Verificare lo stato della porta del nodo del cluster:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente verifica che tutte le porte di interconnessione del cluster su tutti i nodi del nuovo switch 3232C C1 siano attive:

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. Su tutti i nodi, ripristinare i LIF specifici del cluster sulle rispettive porte home:
+
`network interface revert -server Cluster -lif _lif-name_`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra i LIF specifici del cluster che vengono ripristinati alle loro porte home sui nodi n1 e n2:

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n1_clus4
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus4
----
====
. Verificare che l'interfaccia sia home:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra lo stato delle interfacce di interconnessione del cluster `up` E `Is Home` per n1 e n2:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step29]] Espandere il cluster aggiungendo nodi agli switch del cluster Nexus 3232C.
+
Gli esempi seguenti mostrano che i nodi n3 e n4 hanno porte cluster da 40 GbE collegate rispettivamente alle porte e1/7 ed e1/8 su entrambi gli switch cluster Nexus 3232C, ed entrambi i nodi si sono uniti al cluster.  Le porte di interconnessione del cluster 40 GbE utilizzate sono e4a ed e4e.

+
Visualizza le informazioni sui dispositivi nella tua configurazione:

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C
12 entries were displayed.
----
+

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
+

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
+

[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL1                           cluster-network   10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

4 entries were displayed.
----
====
. Rimuovere il Nexus 5596 sostituito utilizzando `system cluster-switch delete` comando, se non viene rimosso automaticamente:
+
`system cluster-switch delete -device switch-name`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch delete -device CL1
cluster::> system cluster-switch delete -device CL2
----
====


.Cosa succederà ora?
Dopo aver configurato le porte dello switch, puoilink:cn5596-complete-migration.html["completa la tua migrazione"] .
