---
permalink: switch-cisco-3232c/migrate-from-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Configura le porte per la migrazione da un cluster senza switch agli switch di cluster Cisco Nexus 3232C. 
---
= Configura le porte per la migrazione da un cluster senza switch a switch di cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configura le porte per la migrazione da un cluster senza switch a un cluster con switch a due nodi utilizzando gli switch di cluster Cisco Nexus 3232C.

.Passi
. Migra le LIF n1_clus1 e n2_clus1 alle porte fisiche dei nodi di destinazione:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.Mostra esempio
[%collapsible]
====
Devi eseguire il comando per ogni nodo locale come mostrato nel seguente esempio:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====
. Verifica che le interfacce del cluster siano state migrate correttamente:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che lo stato "Is Home" per i LIF n1_clus1 e n2_clus1 è diventato "false" dopo il completamento della migrazione:

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. Spegni le porte del cluster per i LIF n1_clus1 e n2_clus1, che sono stati migrati nel passaggio 9:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostra esempio
[%collapsible]
====
Devi eseguire il comando per ciascuna porta come mostrato nel seguente esempio:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step5]] Scollega il cavo da e4a sul nodo n1.
+
Puoi fare riferimento alla configurazione corrente e collegare la prima porta 40 GbE sullo switch C1 (porta 1/7 in questo esempio) a e4a su n1 utilizzando il cablaggio supportato per gli switch Nexus 3232C.

. Scollega il cavo da e4a sul nodo n2.
+
Puoi fare riferimento alla configurazione corrente e collegare e4a alla prossima porta 40 GbE disponibile su C1, porta 1/8, utilizzando il cablaggio supportato.

. Abilita tutte le porte rivolte verso i nodi su C1.
+
Per ulteriori informazioni sui comandi Cisco, fare riferimento alle guide elencate in link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi Cisco Nexus 3000 Series NX-OS"^].

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra l'abilitazione delle porte da 1 a 30 sugli switch cluster Nexus 3232C C1 e C2 utilizzando la configurazione supportata in RCF `NX3232_RCF_v1.0_24p10g_26p100g.txt`:

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. Abilita la prima porta del cluster, e4a, su ciascun nodo:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. Verifica che i cluster siano attivi su entrambi i nodi:
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. Per ciascun nodo, ripristina tutte le LIF di interconnessione del cluster migrate:
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Mostra esempio
[%collapsible]
====
Devi ripristinare ogni LIF alla sua porta home singolarmente, come mostrato nell'esempio seguente:

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. Verifica che tutti i LIF siano ora tornati alle loro porte home:
+
`network interface show -role cluster`

+
La `Is Home` colonna dovrebbe visualizzare un valore di `true` per tutte le porte elencate nella `Current Port` colonna. Se il valore visualizzato è `false`, la porta non è stata ripristinata.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Visualizza la connettività delle porte del cluster su ciascun nodo:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. Migra clus2 alla porta e4a sulla console di ciascun nodo:
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.Mostra esempio
[%collapsible]
====
Devi migrare ogni LIF alla sua porta home singolarmente, come mostrato nel seguente esempio:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. Arresta le porte del cluster clus2 LIF su entrambi i nodi:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come impostare le porte specificate su  `false`, disattivando le porte su entrambi i nodi:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. Verifica lo stato LIF del cluster:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. Scollega il cavo da e4e sul nodo n1.
+
Puoi fare riferimento alla configurazione corrente e collegare la prima porta 40 GbE dello switch C2 (porta 1/7 in questo esempio) a e4e sul nodo n1, utilizzando il cablaggio appropriato per il modello di switch Nexus 3232C.

. Scollega il cavo da e4e sul nodo n2.
+
Puoi fare riferimento alla configurazione corrente e collegare e4e alla prossima porta 40 GbE disponibile su C2, porta 1/8, utilizzando il cablaggio appropriato per il modello di switch Nexus 3232C.

. Abilita tutte le porte rivolte verso i nodi su C2.
+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra l'abilitazione delle porte da 1 a 30 sugli switch di cluster Nexus 3132Q-V C1 e C2 utilizzando una configurazione supportata in RCF `NX3232C_RCF_v1.0_24p10g_26p100g.txt`:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. Abilita la seconda porta del cluster, e4e, su ciascun nodo:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra la seconda porta del cluster, e4e, che viene attivata su ciascun nodo:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. Per ciascun nodo, ripristina tutte le LIF di interconnessione del cluster migrate:
+
`network interface revert`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra le LIF migrate che vengono riportate alle loro porte di origine.

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====


.Cosa succederà ora?
Dopo aver configurato le porte, puoi link:migrate-from-switchless-complete-migration.html["completa la tua migrazione"].
