---
permalink: switch-cisco-3232c/migrate-cn1610-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Per sostituire gli switch cluster CN1610 esistenti in un cluster con switch cluster Cisco Nexus 3232C, è necessario eseguire una sequenza specifica di attività. 
---
= Migrare uno switch cluster CN1610 a uno switch cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sostituire gli switch cluster CN1610 esistenti in un cluster con switch cluster Cisco Nexus 3232C, è necessario eseguire una sequenza specifica di attività.



== Requisiti di revisione

Prima della migrazione, assicurati di rivederelink:migrate-requirements-3232c.html["Requisiti di migrazione"] .


NOTE: La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

Se necessario, per ulteriori informazioni fare riferimento a quanto segue:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Migrare gli switch

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano quattro nodi: due nodi utilizzano quattro porte di interconnessione cluster 10 GbE: e0a, e0b, e0c ed e0d.  Gli altri due nodi utilizzano due cavi in fibra ottica di interconnessione cluster da 40 GbE: e4a ed e4e.  ILlink:https://hwu.netapp.com/["_Universo Hardware_"^] contiene informazioni sui cavi in fibra ottica del cluster sulle vostre piattaforme.

Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nodi sono n1, n2, n3 e n4.
* Gli output dei comandi potrebbero variare a seconda delle diverse versioni del software ONTAP .
* Gli switch CN1610 da sostituire sono CL1 e CL2.
* Gli switch Nexus 3232C che sostituiranno gli switch CN1610 sono C1 e C2.
* n1_clus1 è la prima interfaccia logica del cluster (LIF) connessa allo switch del cluster 1 (CL1 o C1) per il nodo n1.
* n1_clus2 è il primo cluster LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo n1.
* n1_clus3 è il secondo LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo n1.
* n1_clus4 è il secondo LIF connesso allo switch cluster 1 (CL1 o C1) per il nodo n1.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] .




=== Fase 1: Prepararsi alla migrazione

. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

+
[NOTE]
====
Il messaggio avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

====
. Visualizza informazioni sui dispositivi nella tua configurazione:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra quante interfacce di interconnessione cluster sono state configurate in ciascun nodo per ogni switch di interconnessione cluster:

[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*

       Local  Discovered
Node   Port   Device       Interface   Platform
------ ------ ------------ ----------- ----------
n1     /cdp
        e0a   CL1          0/1         CN1610
        e0b   CL2          0/1         CN1610
        e0c   CL2          0/2         CN1610
        e0d   CL1          0/2         CN1610
n2     /cdp
        e0a   CL1          0/3         CN1610
        e0b   CL2          0/3         CN1610
        e0c   CL2          0/4         CN1610
        e0d   CL1          0/4         CN1610

8 entries were displayed.
----
====
. Determinare lo stato amministrativo o operativo per ciascuna interfaccia del cluster.
+
.. Visualizza gli attributi della porta di rete del cluster:
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status Health Status
----- --------- ---------- ----- ----- ------------ ------ -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -
Node: n2
                Broadcast              Speed (Mbps) Health Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status Health Status
----- --------- ---------- ----- ----- ------------ ------ -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -

8 entries were displayed.
----
====
.. Visualizza informazioni sulle interfacce logiche:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

 8 entries were displayed.
----
====
.. Visualizza informazioni sugli switch del cluster rilevati:
+
`system cluster-switch show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra gli switch del cluster noti al cluster insieme ai relativi indirizzi IP di gestione:

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP
CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP

2	entries displayed.
----
====


. Verificare che sui nuovi switch 3232C siano installati l'RCF e l'immagine appropriati in base alle proprie esigenze ed effettuare eventuali personalizzazioni essenziali del sito.
+
A questo punto dovresti preparare entrambi gli interruttori.  Se è necessario aggiornare RCF e immagine, è necessario completare la seguente procedura:

+
.. Vederelink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] sul sito di supporto NetApp .
.. Annota il tuo switch e le versioni software richieste nella tabella in quella pagina.
.. Scarica la versione appropriata dell'RCF.
.. Fare clic su *CONTINUA* nella pagina *Descrizione*, accettare il contratto di licenza e quindi seguire le istruzioni nella pagina *Download* per scaricare l'RCF.
.. Scarica la versione appropriata del software di gestione delle immagini all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento per Cisco® Cluster and Management Network Switch"^] .


. Migrare i LIF associati al secondo switch CN1610 che si intende sostituire:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_ destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.Mostra esempio
[%collapsible]
====
È necessario migrare ogni LIF singolarmente, come mostrato nell'esempio seguente:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node  n1  -destination-port  e0a*
cluster::*> *network interface migrate -vserver cluster -lif n1_clus3 -source-node n1
-destination-node  n1  -destination-port  e0d*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node  n2  -destination-port  e0a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus3 -source-node n2
-destination-node  n2  -destination-port  e0d*
----
====
. Verificare lo stato del cluster:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network         Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask    Node     Port     Home
-------- ---------- ----------- --------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24    n1        e0a     true
         n1_clus2   up/up       10.10.0.2/24    n1        e0a     false
         n1_clus3   up/up       10.10.0.3/24    n1        e0d     false
         n1_clus4   up/up       10.10.0.4/24    n1        e0d     true
         n2_clus1   up/up       10.10.0.5/24    n2        e0a     true
         n2_clus2   up/up       10.10.0.6/24    n2        e0a     false
         n2_clus3   up/up       10.10.0.7/24    n2        e0d     false
         n2_clus4   up/up       10.10.0.8/24    n2        e0d     true

8 entries were displayed.
----
====




=== Passaggio 2: sostituire l'interruttore del cluster CL2 con C2

. Disattivare le porte di interconnessione del cluster fisicamente collegate allo switch CL2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le quattro porte di interconnessione del cluster che vengono chiuse per il nodo n1 e il nodo n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] Chiudere le porte ISL da 13 a 16 sullo switch CN1610 attivo CL1 utilizzando il comando appropriato.
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte ISL da 13 a 16 disattivate sullo switch CN1610 CL1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Costruisci un ISL temporaneo tra CL1 e C2:
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra un ISL temporaneo in fase di creazione tra CL1 (porte 13-16) e C2 (porte e1/24/1-4) utilizzando Cisco `switchport mode trunk` comando:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. Rimuovere i cavi collegati allo switch CN1610 CL2 su tutti i nodi.
+
Utilizzando il cablaggio supportato, è necessario ricollegare le porte disconnesse su tutti i nodi allo switch Nexus 3232C C2.

. Rimuovere quattro cavi ISL dalle porte da 13 a 16 sullo switch CN1610 CL1.
+
È necessario collegare i cavi breakout Cisco QSFP28-SFP+ appropriati che collegano la porta 1/24 del nuovo switch Cisco 3232C C2 alle porte da 13 a 16 dello switch CN1610 CL1 esistente.

+
[NOTE]
====
Quando si ricollegano i cavi al nuovo switch Cisco 3232C, i cavi utilizzati devono essere in fibra ottica o cavi Cisco twinax.

====
. Rendere dinamico l'ISL configurando l'interfaccia ISL 3/1 sullo switch CN1610 attivo per disabilitare la modalità statica.
+
Questa configurazione corrisponde alla configurazione ISL sullo switch 3232C C2 quando gli ISL vengono attivati su entrambi gli switch.

+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra l'interfaccia ISL 3/1 configurata per rendere l'ISL dinamico:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 3/1*
(CL1)(Interface 3/1)# *no port-channel static*
(CL1)(Interface 3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Attivare gli ISL da 13 a 16 sullo switch CN1610 attivo CL1.
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte ISL da 13 a 16 attivate sull'interfaccia port-channel 3/1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16,3/1*
(CL1)(Interface 0/13-0/16,3/1)# *no shutdown*
(CL1)(Interface 0/13-0/16,3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verificare che gli ISL siano `up` sullo switch CN1610 CL1.
+
Lo "Stato del collegamento" dovrebbe essere `Up` , "Tipo" dovrebbe essere `Dynamic` e la colonna "Porta attiva" dovrebbe essere `True` per le porte da 0/13 a 0/16.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra gli ISL verificati come `up` sullo switch CN1610 CL1:

[listing, subs="+quotes"]
----
(CL1)# *show port-channel 3/1*
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. Verificare che gli ISL siano `up` sullo switch 3232C C2:
+
`show port-channel summary`

+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
Le porte Eth1/24/1 fino a Eth1/24/4 dovrebbero indicare `(P)` , il che significa che tutte e quattro le porte ISL sono attive nel canale delle porte.  Eth1/31 e Eth1/32 dovrebbero indicare `(D)` poiché non sono collegati.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra gli ISL verificati come `up` sullo switch 3232C C2:

[listing, subs="+quotes"]
----
C2# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1	    Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2	    Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. Attivare tutte le porte di interconnessione del cluster collegate allo switch 3232C C2 su tutti i nodi:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come attivare le porte di interconnessione del cluster collegate allo switch 3232C C2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. Ripristina tutti i LIF di interconnessione del cluster migrati che sono connessi a C2 su tutti i nodi:
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver cluster -lif n2_clus3*
----
====
. Verificare che tutte le porte di interconnessione del cluster siano state ripristinate alle rispettive porte home:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che i LIF su clus2 vengono ripristinati alle loro porte home; i LIF vengono ripristinati correttamente se le porte nella colonna "Porta corrente" hanno uno stato di `true` nella colonna "È casa".  Se il valore "È casa" è `false` , allora il LIF non viene ripristinato.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. Verificare che tutte le porte del cluster siano connesse:
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra l'output che verifica che tutte le interconnessioni del cluster siano `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -
e0b   cluster   cluster     up    9000  auto/10000     -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -
Node: n2

                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -
e0b   cluster   cluster     up    9000  auto/10000     -
e0c   cluster   cluster     up    9000  auto/10000     -
e0d   cluster   cluster     up    9000  auto/10000     -

8 entries were displayed.
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step16]] Migrare i LIF associati al primo switch CN1610 CL1:
+
`network interface migrate -vserver cluster -lif _lif-name_ -source-node _node-name_`

+
.Mostra esempio
[%collapsible]
====
È necessario migrare ogni LIF del cluster singolarmente sulle porte del cluster appropriate ospitate sullo switch del cluster C2, come mostrato nell'esempio seguente:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver cluster -lif n1_clus4 -source-node n1
-destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus4 -source-node n2
-destination-node n2 -destination-port e0c*
----
====




=== Passaggio 3: sostituire l'interruttore del cluster CL1 con C1

. Verificare lo stato del cluster:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che i LIF del cluster richiesti sono stati migrati alle porte del cluster appropriate ospitate sullo switch del cluster C2:

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. Disattivare le porte dei nodi collegate a CL1 su tutti i nodi:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra porte specifiche che vengono chiuse sui nodi n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. Disattivare le porte ISL 24, 31 e 32 sullo switch 3232C attivo C2.
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra gli ISL 24, 31 e 32 che vengono spenti sullo switch 3232C attivo C2:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2#
----
====
. Rimuovere i cavi collegati allo switch CN1610 CL1 su tutti i nodi.
+
Utilizzando il cablaggio appropriato, è necessario ricollegare le porte disconnesse su tutti i nodi allo switch Nexus 3232C C1.

. Rimuovere i cavi QSFP28 dalla porta e1/24 del Nexus 3232C C2.
+
È necessario collegare le porte e1/31 ed e1/32 su C1 alle porte e1/31 ed e1/32 su C2 utilizzando cavi in ​​fibra ottica Cisco QSFP28 supportati o cavi a collegamento diretto.

. Ripristinare la configurazione sulla porta 24 e rimuovere il canale porta temporaneo 2 su C2:
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra il `running-configuration` file copiato nel `startup-configuration` file:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *interface e1/24*
C2(config-if)# *description 100GbE/40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
Edge port type (portfast) should only be enabled on ports connected to a single
host. Connecting hubs, concentrators, switches, bridges, etc...  to this
interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet 1/24 but will only
have effect when the interface is in a non-trunking mode.

C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Attivare le porte ISL 31 e 32 su C2, lo switch 3232C attivo.
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra gli ISL 31 e 32 che vengono portati sullo switch 3232C C2:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Verificare che le connessioni ISL siano `up` sullo switch 3232C C2.
+
Per ulteriori informazioni sui comandi Cisco , consultare le guide elencate in https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le connessioni ISL in fase di verifica.  Le porte Eth1/31 e Eth1/32 indicano `(P)` , il che significa che entrambe le porte ISL sono `up` nel porto-canale:

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
-----------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)

C2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Attivare tutte le porte di interconnessione del cluster connesse al nuovo switch 3232C C1 su tutti i nodi:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra tutte le porte di interconnessione del cluster collegate al nuovo switch 3232C C1 che vengono attivate:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin true*
cluster::*> *network port modify -node n1 -port e0d -up-admin true*
cluster::*> *network port modify -node n2 -port e0a -up-admin true*
cluster::*> *network port modify -node n2 -port e0d -up-admin true*
----
====
. Verificare lo stato della porta del nodo del cluster:
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra l'output che verifica che le porte di interconnessione del cluster sui nodi n1 e n2 sul nuovo switch 3232C C1 siano `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n2
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -

8 entries were displayed.
----
====




=== Fase 4: Completare la procedura

. Ripristinare tutti i LIF di interconnessione del cluster migrati che erano originariamente connessi a C1 su tutti i nodi:
+
`network interface revert -server cluster -lif _lif-name_`

+
.Mostra esempio
[%collapsible]
====
È necessario migrare ogni LIF singolarmente, come mostrato nell'esempio seguente:

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n1_clus4*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus4*
----
====
. Verificare che l'interfaccia sia ora nella posizione home:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra lo stato delle interfacce di interconnessione del cluster: `up` e "Is Home" per i nodi n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
3 paths up, 0 paths down (udp check)
----
--
====
. [[step4]] Espandere il cluster aggiungendo nodi agli switch del cluster Nexus 3232C.
. Visualizza le informazioni sui dispositivi nella tua configurazione:
+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`
+
.Mostra esempio
[%collapsible]
====
Gli esempi seguenti mostrano i nodi n3 e n4 con porte cluster da 40 GbE connesse rispettivamente alle porte e1/7 ed e1/8 su entrambi gli switch cluster Nexus 3232C.  Entrambi i nodi sono uniti al cluster.  Le porte di interconnessione del cluster 40 GbE utilizzate sono e4a ed e4e.

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*

       Local  Discovered
Node   Port   Device       Interface       Platform
------ ------ ------------ --------------- -------------
n1     /cdp
        e0a   C1           Ethernet1/1/1   N3K-C3232C
        e0b   C2           Ethernet1/1/1   N3K-C3232C
        e0c   C2           Ethernet1/1/2   N3K-C3232C
        e0d   C1           Ethernet1/1/2   N3K-C3232C
n2     /cdp
        e0a   C1           Ethernet1/1/3   N3K-C3232C
        e0b   C2           Ethernet1/1/3   N3K-C3232C
        e0c   C2           Ethernet1/1/4   N3K-C3232C
        e0d   C1           Ethernet1/1/4   N3K-C3232C

n3     /cdp
        e4a   C1           Ethernet1/7     N3K-C3232C
        e4e   C2           Ethernet1/7     N3K-C3232C

n4     /cdp
        e4a   C1           Ethernet1/8     N3K-C3232C
        e4e   C2           Ethernet1/8     N3K-C3232C

12 entries were displayed.
cluster::*> *network port show -role cluster*
(network port show)

Node: n1
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n2
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n3
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e4a   cluster   cluster    up    9000  auto/40000     -
e4e   cluster   cluster    up    9000  auto/40000     -        -

Node: n4
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e4a   cluster   cluster    up    9000  auto/40000     -
e4e   cluster   cluster    up    9000  auto/40000     -

12 entries were displayed.

cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true
         n3_clus1   up/up       10.10.0.9/24   n3       e4a      true
         n3_clus2   up/up       10.10.0.10/24  n3       e4e      true
         n4_clus1   up/up       10.10.0.11/24  n4       e4a     true
         n4_clus2   up/up       10.10.0.12/24  n4       e4e     true

12 entries were displayed.

cluster::> *system cluster-switch show*

Switch                      Type             Address       Model
--------------------------- ---------------- ------------- ---------
C1                          cluster-network  10.10.1.103   NX3232C

     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I6(1)
    Version Source: CDP

C2                          cluster-network  10.10.1.104   NX3232C

     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I6(1)
    Version Source: CDP
CL1                         cluster-network  10.10.1.101   CN1610

     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP
CL2                         cluster-network  10.10.1.102    CN1610

     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP 4 entries were displayed.
----
====


. Rimuovere gli switch CN1610 sostituiti se non vengono rimossi automaticamente:
+
`system cluster-switch delete -device _switch-name_`

+
.Mostra esempio
[%collapsible]
====
È necessario eliminare entrambi i dispositivi singolarmente, come mostrato nell'esempio seguente:

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch delete –device CL1*
cluster::> *system cluster-switch delete –device CL2*
----
====
. Verificare che siano monitorati gli switch del cluster appropriati:
+
`system cluster-switch show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che gli switch del cluster C1 e C2 vengono monitorati:

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C

     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I6(1)
    Version Source: CDP

C2                          cluster-network    10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
          Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I6(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
link:../switch-cshm/config-overview.html["Configurare il monitoraggio dello stato dello switch"].
