---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Quando si sostituiscono gli switch cluster CN1610 con gli switch cluster Cisco Nexus 3232C, è necessario conoscere alcune informazioni sulla configurazione, sulle connessioni delle porte e sui requisiti di cablaggio. 
---
= Requisiti di migrazione per gli switch cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di migrare agli switch cluster Cisco Nexus 3232C, rivedere le informazioni di configurazione, le connessioni delle porte e i requisiti di cablaggio.



== Requisiti di migrazione CN1610

Gli switch del cluster supportano le seguenti connessioni di nodo:

* NetApp CN1610: porte da 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3232C: porte e1/1-30 (40 o 100 o 4x10GbE)


Gli switch del cluster utilizzano le seguenti porte di collegamento inter-switch (ISL).

* NetApp CN1610: porte da 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3232C: porte 1/31-32 (100GbE)


[NOTE]
====
È necessario utilizzare cavi breakout 4x10G sullo switch cluster Cisco Nexus 3232C.

====
Nella tabella seguente sono indicati i collegamenti dei cavi necessari in ogni fase della transizione dagli switch NetApp CN1610 agli switch cluster Cisco Nexus 3232C:

|===
| Palcoscenico | Descrizione | Cavi richiesti 


 a| 
Iniziale
 a| 
Da CN1610 a CN1610 (da SFP+ a SFP+)
 a| 
4 cavi SFP+ in fibra ottica o rame a collegamento diretto



 a| 
Transizione
 a| 
Da CN1610 a 3232C (da QSFP a SFP+)
 a| 
1 QSFP e 4 cavi breakout in fibra ottica o rame SFP+



 a| 
Finale
 a| 
Da 3232C a 3232C (da QSFP a QSFP)
 a| 
2 cavi QSFP in fibra ottica o rame a collegamento diretto

|===
È necessario aver scaricato i file di configurazione di riferimento (RCF) applicabili.  Il numero di porte 10 GbE e 40/100 GbE è definito negli RCF disponibili pressolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] .

Le versioni ONTAP e NX-OS supportate in questa procedura sono elencate inlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] .

Le versioni ONTAP e FASTPATH ​​supportate in questa procedura sono elencate inlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Switch NetApp CN1601 e CN1610"^] .



== Requisiti CN5596

Gli switch del cluster utilizzano le seguenti porte per le connessioni ai nodi:

* Porte e1/1-40 (10 GbE): Nexus 5596
* Porte e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** Gli switch del cluster utilizzano le seguenti porte Inter-Switch Link (ISL):


* Porte e1/41-48 (10 GbE): Nexus 5596
* Porte e1/31-32 (40/100 GbE): Nexus 3232C
+
** ILlink:https://hwu.netapp.com/["_Universo Hardware_"^] contiene informazioni sul cablaggio supportato per gli switch Nexus 3232C:


* I nodi con connessioni cluster da 10 GbE richiedono cavi breakout in fibra ottica da QSFP a SFP+ o cavi breakout in rame da QSFP a SFP+.
* I nodi con connessioni cluster 40/100 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra o cavi di collegamento diretto in rame QSFP/QSFP28.
+
** Gli switch del cluster utilizzano il cablaggio ISL appropriato:


* Inizio: Nexus 5596 (SFP+ a SFP+)
+
** 8 cavi SFP+ in fibra o rame a collegamento diretto


* Interim: da Nexus 5596 a Nexus 3232C (break-out da QSFP a 4xSFP+)
+
** 1x cavi breakout in fibra QSFP a SFP+ o cavi breakout in rame


* Finale: da Nexus 3232C a Nexus 3232C (da QSFP28 a QSFP28)
+
** 2 cavi QSFP28 in fibra o rame a collegamento diretto
+
*** Sugli switch Nexus 3232C è possibile utilizzare le porte QSFP/QSFP28 in modalità 40/100 Gigabit Ethernet o 4 x10 Gigabit Ethernet.
+
Per impostazione predefinita, sono presenti 32 porte nella modalità Ethernet 40/100 Gigabit.  Queste 40 porte Gigabit Ethernet sono numerate secondo una convenzione di denominazione a 2 tuple.  Ad esempio, la seconda porta Ethernet da 40 Gigabit è numerata come 1/2.  Il processo di modifica della configurazione da 40 Gigabit Ethernet a 10 Gigabit Ethernet è chiamato _breakout_, mentre il processo di modifica della configurazione da 10 Gigabit Ethernet a 40 Gigabit Ethernet è chiamato _breakin_.  Quando si scompone una porta Ethernet 40/100 Gigabit in porte Ethernet 10 Gigabit, le porte risultanti vengono numerate utilizzando una convenzione di denominazione a 3 tuple.  Ad esempio, le porte break-out della seconda porta Ethernet 40/100 Gigabit sono numerate come 1/2/1, 1/2/2, 1/2/3 e 1/2/4.

*** Sul lato sinistro degli switch Nexus 3232C ci sono 2 porte SFP+, denominate 1/33 e 1/34.
*** Hai configurato alcune porte sugli switch Nexus 3232C per funzionare a 10 GbE o 40/100 GbE.
+
[NOTE]
====
È possibile suddividere le prime sei porte in modalità 4x10 GbE utilizzando `interface breakout module 1 port 1-6 map 10g-4x` comando.  Allo stesso modo, è possibile raggruppare le prime sei porte QSFP+ dalla configurazione breakout utilizzando `no interface breakout module 1 port 1-6 map 10g-4x` comando.

====
*** Hai eseguito la pianificazione, la migrazione e letto la documentazione richiesta sulla connettività 10 GbE e 40/100 GbE dai nodi agli switch cluster Nexus 3232C.
*** Le versioni ONTAP e NX-OS supportate in questa procedura sono alink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] .





