---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Prima di configurare gli switch Cisco Nexus 3232c, è opportuno esaminare una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Se si dispone di un cluster switchless a due nodi, è possibile migrare a un cluster switch a due nodi che include switch di rete cluster Cisco Nexus 3232C. Si tratta di una procedura non distruttiva.

.Prima di iniziare
Verificare le seguenti installazioni e connessioni:

* Sono disponibili porte per le connessioni dei nodi.  Gli switch cluster utilizzano le porte Inter-Switch Link (ISL) e1/31-32.
* Si dispone di cavi adatti per le connessioni del cluster:
+
** I nodi con connessioni cluster 10 GbE richiedono moduli ottici QSFP con cavi in fibra ottica breakout o cavi breakout in rame da QSFP a SFP+.
** I nodi con connessioni cluster 40/100 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra o cavi di collegamento diretto in rame QSFP/QSFP28.
** Gli switch del cluster richiedono il cablaggio ISL appropriato:
+
*** 2 cavi QSFP28 in fibra o rame a collegamento diretto.




* Le configurazioni sono impostate correttamente e funzionano.
+
I due nodi devono essere connessi e funzionare in un ambiente cluster senza switch a due nodi.

* Tutte le porte del cluster sono nello stato *attivo*.
* Sono supportati gli switch cluster Cisco Nexus 3232C.
* La configurazione di rete del cluster esistente è la seguente:
+
** Un'infrastruttura cluster Nexus 3232C ridondante e completamente funzionale su entrambi gli switch
** Le ultime versioni RCF e NX-OS sui tuoi switch
** Connettività di gestione su entrambi gli switch
** Accesso alla console per entrambi gli switch
** Tutte le interfacce logiche del cluster (LIF) nello stato *attivo* senza essere state migrate
** Personalizzazione iniziale dello switch
** Tutte le porte ISL abilitate e cablate




.Informazioni sugli esempi utilizzati
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Switch cluster Nexus 3232C, *C1* e *C2*.
* I nodi sono *n1* e *n2*.


Gli esempi in questa procedura utilizzano due nodi, ciascuno con due porte di interconnessione cluster da 40 GbE *e4a* e *e4e*.  ILlink:https://hwu.netapp.com/["_Universo Hardware_"^] contiene dettagli sulle porte del cluster sulle tue piattaforme.

* *n1_clus1* è la prima interfaccia logica del cluster (LIF) da connettere allo switch del cluster *C1* per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF ad essere connesso allo switch del cluster *C2* per il nodo *n1*.
* *n2_clus1* è il primo cluster LIF ad essere connesso allo switch del cluster *C1* per il nodo *n2*.
* *n2_clus2* è il secondo cluster LIF da connettere allo switch del cluster *C2* per il nodo *n2*.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili sul https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] pagina.


[NOTE]
====
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

====
.Cosa succederà ora?
link:migrate-from-switchless-prepare-to-migrate.html["Prepararsi alla migrazione"].
