---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Esamina i requisiti per la migrazione da un cluster senza switch a switch di cluster Cisco Nexus 3232C. 
---
= Esamina i requisiti per la migrazione da un cluster senza switch agli switch cluster Cisco Nexus 3232C
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Esamina i requisiti per la migrazione da un cluster senza switch a un cluster con switch utilizzando gli switch cluster Cisco Nexus 3232C.

.Prima di iniziare
Verificare le seguenti installazioni e connessioni:

* Sono disponibili porte per le connessioni dei nodi. Gli switch del cluster utilizzano le porte Inter-Switch Link (ISL) e1/31-32.
* Hai a disposizione i cavi appropriati per le connessioni cluster:
+
** I nodi con connessioni cluster 10 GbE richiedono moduli ottici QSFP con cavi in fibra ottica breakout o cavi breakout in rame da QSFP a SFP+.
** I nodi con connessioni cluster 40/100 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra ottica o cavi QSFP/QSFP28 in rame a collegamento diretto.
** Gli switch del cluster richiedono il cablaggio ISL appropriato:
+
*** 2x cavi QSFP28 in fibra ottica o rame con connessione diretta.




* Le configurazioni sono impostate correttamente e funzionano.
+
I due nodi devono essere connessi e funzionanti in una configurazione di cluster senza switch a due nodi.

* Tutte le porte del cluster sono nello stato *attivo*.
* Lo switch cluster Cisco Nexus 3232C è supportato.
* La configurazione di rete del cluster esistente è la seguente:
+
** Un'infrastruttura cluster Nexus 3232C ridondante e perfettamente funzionante su entrambi gli switch
** Le versioni più recenti di RCF e NX-OS sui tuoi switch
** Connettività di gestione su entrambi gli switch
** Accesso alla console di entrambi gli switch
** Tutte le interfacce logiche del cluster (LIF) nello stato *up* senza essere state migrate
** Personalizzazione iniziale dello switch
** Tutte le porte ISL sono abilitate e cablate




.Informazioni sugli esempi utilizzati
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Switch cluster Nexus 3232C, *C1* e *C2*.
* I nodi sono *n1* e *n2*.


Gli esempi in questa procedura utilizzano due nodi, ciascuno dei quali utilizza due porte di interconnessione cluster 40 GbE *e4a* e *e4e*. Il link:https://hwu.netapp.com/["Hardware Universe"^] contiene dettagli sulle porte cluster sulle tue piattaforme.

* *n1_clus1* è la prima interfaccia logica del cluster (LIF) da connettere allo switch del cluster *C1* per il nodo *n1*.
* *n1_clus2* è la prima LIF del cluster da connettere allo switch del cluster *C2* per il nodo *n1*.
* *n2_clus1* è la prima cluster LIF da connettere allo switch del cluster *C1* per il nodo *n2*.
* *n2_clus2* è la seconda cluster LIF da connettere allo switch del cluster *C2* per il nodo *n2*.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili sulla pagina  https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download del file di configurazione di riferimento per switch di rete cluster Cisco®"^].


[NOTE]
====
La procedura richiede l'utilizzo sia dei comandi ONTAP che dei comandi degli switch Cisco Nexus 3000 Series; vengono utilizzati i comandi ONTAP, salvo diversa indicazione.

====
.Cosa succederà ora?
Dopo aver esaminato i requisiti di migrazione, puoi link:migrate-from-switchless-prepare-to-migrate.html["preparati a migrare i tuoi switch"].
