---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Prima di configurare gli switch Cisco Nexus 3232c, esaminare una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Se utilizzi un cluster senza switch a due nodi, puoi migrare verso un cluster con switch a due nodi che include gli switch di rete del cluster Cisco Nexus 3232C. Si tratta di una procedura senza interruzioni.

.Prima di iniziare
Verificare le seguenti installazioni e connessioni:

* Le porte sono disponibili per le connessioni dei nodi. Gli switch del cluster utilizzano le porte ISL (Inter-Switch link) e1/31-32.
* Si dispone di cavi appropriati per le connessioni cluster:
+
** I nodi con connessioni cluster da 10 GbE richiedono moduli ottici QSFP con cavi in fibra breakout o cavi breakout in rame da QSFP a SFP+.
** I nodi con connessioni cluster da 40/100 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra o cavi a collegamento diretto in rame QSFP/QSFP28.
** Gli switch cluster richiedono il cablaggio ISL appropriato:
+
*** 2x QSFP28 cavi a collegamento diretto in fibra o rame.




* Le configurazioni sono configurate e funzionano correttamente.
+
I due nodi devono essere connessi e funzionanti in un'impostazione di cluster senza switch a due nodi.

* Tutte le porte del cluster si trovano nello stato *up*.
* Lo switch cluster Cisco Nexus 3232C è supportato.
* La configurazione di rete del cluster esistente presenta quanto segue:
+
** Un'infrastruttura di cluster Nexus 3232C ridondante e completamente funzionale su entrambi gli switch
** Le ultime versioni di RCF e NX-OS sugli switch
** Connettività di gestione su entrambi gli switch
** Accesso da console a entrambi gli switch
** Tutte le interfacce logiche del cluster (LIFF) in stato *up* senza essere state migrate
** Personalizzazione iniziale dello switch
** Tutte le porte ISL abilitate e cablate




.Informazioni sugli esempi utilizzati
Gli esempi di questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Switch cluster Nexus 3232C, *C1* e *C2*.
* I nodi sono *n1* e *n2*.


Negli esempi di questa procedura vengono utilizzati due nodi, ciascuno dei quali utilizza due porte di interconnessione cluster 40 GbE *e4a* e *E4E*. link:https://hwu.netapp.com/["_Hardware Universe_"^]Dispone di dettagli sulle porte cluster sulle piattaforme.

* *n1_clus1* è la prima interfaccia logica del cluster (LIF) ad essere collegata allo switch del cluster *C1* per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF ad essere collegato al cluster switch *C2* per il nodo *n1*.
* *n2_clus1* è il primo cluster LIF ad essere collegato al cluster switch *C1* per il nodo *n2*.
* *n2_clus2* è il secondo cluster LIF da collegare al cluster switch *C2* per il nodo *n2*.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili su https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download del file di configurazione di riferimento di Cisco® Cluster Network Switch"^] pagina.


[NOTE]
====
La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 3000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.

====
.Quali sono le prossime novità?
link:migrate-from-switchless-prepare-to-migrate.html["Preparazione per la migrazione"].
