---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: Se si desidera documentare le piattaforme supportate, è necessario completare il foglio di lavoro vuoto per il cablaggio utilizzando il foglio di lavoro di esempio completo come guida. Ogni switch può essere configurato come una singola porta 100 GbE, 40 GbE o 4 porte 10 GbE. 
---
= Completa il foglio di lavoro per il cablaggio di Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera documentare le piattaforme supportate, scaricare un PDF di questa pagina e completare il foglio di lavoro relativo al cablaggio.

Il foglio di lavoro di esempio relativo ai cavi fornisce esempi di assegnazione delle porte consigliate dagli switch ai controller. Il foglio di lavoro vuoto fornisce un modello che è possibile utilizzare per la configurazione del cluster.

Ogni switch può essere configurato come una singola porta 100 GbE, 40 GbE o 4 porte 10 GbE.



== Esempio di foglio di lavoro per il cablaggio

La definizione di porta di esempio su ciascuna coppia di switch è la seguente:

[cols="1, 1, 1, 1"]
|===
2+| Switch del cluster A 2+| Switch del cluster B 


| Porta dello switch | Utilizzo di nodi e porte | Porta dello switch | Utilizzo di nodi e porte 


 a| 
1
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
1
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
2
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
2
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
3
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
3
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
4
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
4
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
5
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
5
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
6
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
6
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
7
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
7
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
8
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
8
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
9
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
9
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
10
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
10
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
11
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
11
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
12
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
12
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
13
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
13
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
14
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
14
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
15
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
15
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
16
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
16
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
17
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
17
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
18
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE
 a| 
18
 a| 
4 x 10GbE/4 x 25GbE o nodo 40/100GbE



 a| 
19
 a| 
40g/100GbE nodo 19
 a| 
19
 a| 
40g/100GbE nodo 19



 a| 
20
 a| 
40g/100GbE nodo 20
 a| 
20
 a| 
40g/100GbE nodo 20



 a| 
21
 a| 
40g/100GbE nodo 21
 a| 
21
 a| 
40g/100GbE nodo 21



 a| 
22
 a| 
40g/100GbE nodo 22
 a| 
22
 a| 
40g/100GbE nodo 22



 a| 
23
 a| 
40g/100GbE nodo 23
 a| 
23
 a| 
40g/100GbE nodo 23



 a| 
24
 a| 
40g/100GbE nodo 24
 a| 
24
 a| 
40g/100GbE nodo 24



 a| 
da 25 a 30
 a| 
Riservato
 a| 
da 25 a 30
 a| 
Riservato



 a| 
31
 a| 
100GbE ISL alla porta B dello switch 31
 a| 
31
 a| 
100GbE ISL per commutare Una porta 31



 a| 
32
 a| 
100GbE ISL alla porta B dello switch 32
 a| 
32
 a| 
100GbE ISL per commutare Una porta 32

|===


== Foglio di lavoro di cablaggio vuoto

È possibile utilizzare il foglio di lavoro dei cavi vuoto per documentare le piattaforme supportate come nodi in un cluster. La sezione _connessioni cluster supportate_ di https://hwu.netapp.com["Hardware Universe"^] definisce le porte del cluster utilizzate dalla piattaforma.

[cols="1, 1, 1, 1"]
|===
2+| Switch del cluster A 2+| Switch del cluster B 


| Porta dello switch | Utilizzo di nodo/porta | Porta dello switch | Utilizzo di nodo/porta 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
da 25 a 30
 a| 
Riservato
 a| 
da 25 a 30
 a| 
Riservato



 a| 
31
 a| 
100GbE ISL alla porta B dello switch 31
 a| 
31
 a| 
100GbE ISL per commutare Una porta 31



 a| 
32
 a| 
100GbE ISL alla porta B dello switch 32
 a| 
32
 a| 
100GbE ISL per commutare Una porta 32

|===
.Cosa c'è dopo?
Dopo aver completato i fogli di lavoro sul cablaggio, link:install-switch-3232c.html["installare l'interruttore"].
