---
permalink: switch-cisco-3232c/setup-switch.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Se non si dispone già delle informazioni di configurazione e della documentazione necessarie, è necessario raccogliere tali informazioni prima di configurare il cluster e gli switch di rete di gestione. 
---
= Configurare lo switch del cluster 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per configurare lo switch Cisco Nexus 3232C.

.Di cosa hai bisogno
* Accesso a un server HTTP, FTP o TFTP nel sito di installazione per scaricare le release NX-OS e RCF (Reference Configuration file) applicabili.
* Versione NX-OS applicabile, scaricata da https://software.cisco.com/download/home["Download del software Cisco"^] pagina.
* Documentazione richiesta per la rete cluster e lo switch di rete di gestione.
+
Vedere link:required-documentation-3232c.html["Documentazione richiesta"] per ulteriori informazioni.

* Documentazione necessaria per il controller e la documentazione ONTAP.
+
https://netapp.com/us/documenation/index.aspx["Documentazione NetApp"^]

* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Schede di lavoro di cablaggio completate.
* RCF di rete cluster e rete di gestione NetApp applicabili, scaricati dal NetApp Support Site all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^] per gli switch ricevuti. Tutti gli switch della rete cluster e di gestione Cisco vengono forniti con la configurazione standard predefinita di fabbrica di Cisco. Questi switch hanno anche la versione corrente del software NX-OS, ma non hanno gli RCF caricati.


.Fasi
. Rack di switch e controller della rete di gestione e della rete del cluster.
+
[cols="1,2"]
|===
| Se si sta installando... | Quindi... 


 a| 
Cisco Nexus 3232C in un cabinet di sistema NetApp
 a| 
Consultare la guida _Installazione di uno switch cluster Cisco Nexus 3232C e del pannello pass-through in un cabinet NetApp_ per istruzioni sull'installazione dello switch in un cabinet NetApp.



 a| 
Apparecchiatura in un rack Telco
 a| 
Consultare le procedure fornite nelle guide all'installazione dell'hardware dello switch e le istruzioni di installazione e configurazione di NetApp.

|===
. Collegare gli switch della rete cluster e della rete di gestione ai controller utilizzando i fogli di lavoro di cablaggio completi.
. Accendere la rete del cluster e gli switch e i controller della rete di gestione.
. Eseguire una configurazione iniziale degli switch di rete del cluster.
+
Fornire le risposte appropriate alle seguenti domande iniziali di configurazione al primo avvio dello switch. La policy di sicurezza del sito definisce le risposte e i servizi da abilitare.

+
[cols="1,2"]
|===
| Prompt | Risposta 


 a| 
Interrompere il provisioning automatico e continuare con la normale configurazione? (sì/no)
 a| 
Rispondere con *sì*. Il valore predefinito è no



 a| 
Applicare lo standard di password sicura? (sì/no)
 a| 
Rispondere con *sì*. L'impostazione predefinita è sì.



 a| 
Inserire la password per admin.
 a| 
La password predefinita è "`admin`"; è necessario creare una nuova password complessa. Una password debole può essere rifiutata.



 a| 
Accedere alla finestra di dialogo della configurazione di base? (sì/no)
 a| 
Rispondere con *yes* alla configurazione iniziale dello switch.



 a| 
Creare un altro account di accesso? (sì/no)
 a| 
La risposta dipende dalle policy del sito relative agli amministratori alternativi. L'impostazione predefinita è *NO*.



 a| 
Configurare la stringa di comunità SNMP di sola lettura? (sì/no)
 a| 
Rispondere con *no*. Il valore predefinito è no



 a| 
Configurare la stringa di comunità SNMP in lettura/scrittura? (sì/no)
 a| 
Rispondere con *no*. Il valore predefinito è no



 a| 
Inserire il nome dello switch.
 a| 
Il nome dello switch può contenere al massimo 63 caratteri alfanumerici.



 a| 
Continuare con la configurazione di gestione out-of-band (mgmt0)? (sì/no)
 a| 
Rispondere con *yes* (impostazione predefinita) al prompt. Al prompt mgmt0 IPv4 address: (Indirizzo IPv4: Mgmt0), immettere l'indirizzo IP IP: ip_address (Indirizzo_ip).



 a| 
Configurare il gateway predefinito? (sì/no)
 a| 
Rispondere con *sì*. Al prompt dell'indirizzo IPv4 del gateway predefinito, immettere default_gateway.



 a| 
Configurare le opzioni IP avanzate? (sì/no)
 a| 
Rispondere con *no*. Il valore predefinito è no



 a| 
Abilitare il servizio telnet? (sì/no)
 a| 
Rispondere con *no*. Il valore predefinito è no



 a| 
Servizio SSH abilitato? (sì/no)
 a| 
Rispondere con *sì*. L'impostazione predefinita è sì.


NOTE: SSH è consigliato quando si utilizza Cluster Switch Health Monitor (CSHM) per le funzioni di raccolta dei log. SSHv2 è consigliato anche per una maggiore sicurezza.



 a| 
Inserire il tipo di chiave SSH che si desidera generare (dsa/rsa/rsa1).
 a| 
L'impostazione predefinita è *rsa*.



 a| 
Inserire il numero di bit della chiave (1024-2048).
 a| 
Immettere il numero di bit chiave compreso tra 1024 e 2048.



 a| 
Configurare il server NTP? (sì/no)
 a| 
Rispondere con *no*. Il valore predefinito è no



 a| 
Configurare il livello di interfaccia predefinito (L3/L2):
 a| 
Rispondi con *L2*. L'impostazione predefinita è L2.



 a| 
Configurare lo stato di interfaccia della porta dello switch predefinito (shut/noshut):
 a| 
Rispondere con *noshut*. L'impostazione predefinita è noshut.



 a| 
Configurare il profilo di sistema Copp (Strict/moderate/lenient/dense):
 a| 
Rispondere con *Strict*. L'impostazione predefinita è rigorosa.



 a| 
Modificare la configurazione? (sì/no)
 a| 
A questo punto, viene visualizzata la nuova configurazione. Esaminare e apportare le modifiche necessarie alla configurazione appena inserita. Rispondere con *no* al prompt se si è soddisfatti della configurazione. Rispondere con *yes* se si desidera modificare le impostazioni di configurazione.



 a| 
Utilizzare questa configurazione e salvarla? (sì/no)
 a| 
Rispondere con *yes* per salvare la configurazione. In questo modo vengono aggiornate automaticamente le immagini del sistema e del kickstart.


NOTE: Se non si salva la configurazione in questa fase, nessuna delle modifiche sarà effettiva al successivo riavvio dello switch.

|===
. Verificare le opzioni di configurazione effettuate sul display visualizzato al termine dell'installazione e assicurarsi di salvare la configurazione.
. Controllare la versione degli switch di rete del cluster e, se necessario, scaricare la versione del software supportata da NetApp sugli switch da https://software.cisco.com/download/home["Download del software Cisco"^] pagina.


.Quali sono le prossime novità?
link:prepare-install-cisco-nexus-3232c.html["Preparazione all'installazione di NX-OS e RCF"].
