---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: Se si desidera documentare le piattaforme supportate, è necessario compilare il foglio di lavoro di cablaggio vuoto utilizzando come guida il foglio di lavoro di cablaggio di esempio completato.  Ogni switch può essere configurato come una singola porta da 100 GbE, 40 GbE o 4 porte da 10 GbE. 
---
= Foglio di lavoro completo sul cablaggio Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se desideri documentare le piattaforme supportate, scarica un PDF da questa pagina e compila il foglio di lavoro sul cablaggio.

Il foglio di lavoro di cablaggio di esempio fornisce esempi di assegnazioni di porte consigliate dagli switch ai controller.  Il foglio di lavoro vuoto fornisce un modello che puoi utilizzare per configurare il tuo cluster.

Ogni switch può essere configurato come una singola porta da 100 GbE, 40 GbE o 4 porte da 10 GbE.



== Esempio di foglio di lavoro per il cablaggio

La definizione di porta di esempio su ciascuna coppia di switch è la seguente:

[cols="1, 1, 1, 1"]
|===
2+| Interruttore del cluster A 2+| Interruttore del cluster B 


| Porta di commutazione | Utilizzo di nodi e porte | Porta di commutazione | Utilizzo di nodi e porte 


 a| 
1
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
1
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
2
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
2
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
3
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
3
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
4
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
4
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
5
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
5
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
6
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
6
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
7
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
7
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
8
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
8
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
9
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
9
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
10
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
10
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
11
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
11
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
12
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
12
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
13
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
13
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
14
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
14
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
15
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
15
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
16
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
16
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
17
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
17
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
18
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE
 a| 
18
 a| 
Nodo 4x10GbE/4x25GbE o 40/100GbE



 a| 
19
 a| 
Nodo 40G/100GbE 19
 a| 
19
 a| 
Nodo 40G/100GbE 19



 a| 
20
 a| 
Nodo 40G/100GbE 20
 a| 
20
 a| 
Nodo 40G/100GbE 20



 a| 
21
 a| 
Nodo 21 40G/100GbE
 a| 
21
 a| 
Nodo 21 40G/100GbE



 a| 
22
 a| 
Nodo 22 40G/100GbE
 a| 
22
 a| 
Nodo 22 40G/100GbE



 a| 
23
 a| 
Nodo 23 40G/100GbE
 a| 
23
 a| 
Nodo 23 40G/100GbE



 a| 
24
 a| 
Nodo 40G/100GbE 24
 a| 
24
 a| 
Nodo 40G/100GbE 24



 a| 
25-30
 a| 
Prenotato
 a| 
25-30
 a| 
Prenotato



 a| 
31
 a| 
100GbE ISL per commutare la porta B 31
 a| 
31
 a| 
100GbE ISL per commutare la porta A 31



 a| 
32
 a| 
100GbE ISL per commutare la porta B 32
 a| 
32
 a| 
100GbE ISL per commutare la porta A 32

|===


== Foglio di lavoro vuoto per il cablaggio

È possibile utilizzare il foglio di lavoro di cablaggio vuoto per documentare le piattaforme supportate come nodi in un cluster.  La sezione _Connessioni cluster supportate_ del https://hwu.netapp.com["Hardware Universe"^] definisce le porte del cluster utilizzate dalla piattaforma.

[cols="1, 1, 1, 1"]
|===
2+| Interruttore del cluster A 2+| Interruttore del cluster B 


| Porta di commutazione | Utilizzo del nodo/porta | Porta di commutazione | Utilizzo del nodo/porta 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25-30
 a| 
Prenotato
 a| 
25-30
 a| 
Prenotato



 a| 
31
 a| 
100GbE ISL per commutare la porta B 31
 a| 
31
 a| 
100GbE ISL per commutare la porta A 31



 a| 
32
 a| 
100GbE ISL per commutare la porta B 32
 a| 
32
 a| 
100GbE ISL per commutare la porta A 32

|===
.Cosa c'è dopo?
Dopo aver completato i fogli di lavoro sui cavi, puoi link:install-switch-3232c.html["installare l'interruttore"].
