---
permalink: switch-cisco-3232c/smart-call-home-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: È possibile utilizzare gli switch Cisco Nexus 3232C come switch cluster nel cluster AFF o FAS. 
---
= Requisiti Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare Smart Call Home, è necessario configurare uno switch di rete cluster per comunicare tramite e-mail con il sistema Smart Call Home. Inoltre, è possibile configurare facoltativamente lo switch di rete del cluster per sfruttare la funzionalità di supporto Smart Call Home integrata di Cisco.

Smart Call Home monitora i componenti hardware e software della tua rete. Quando si verifica una configurazione critica del sistema, viene generata una notifica tramite e-mail e viene inviato un avviso a tutti i destinatari configurati nel profilo di destinazione.

Prima di utilizzare Smart Call Home, tieni presente i seguenti requisiti:

* È necessario che sia installato un server di posta elettronica.
* Lo switch deve disporre di connettività IP al server di posta elettronica.
* È necessario configurare il nome del contatto (contatto del server SNMP), il numero di telefono e l'indirizzo. Questo è necessario per determinare l'origine dei messaggi ricevuti.
* Un ID CCO deve essere associato a un contratto Cisco SMARTnet Service appropriato per la tua azienda.
* Cisco SMARTnet Service deve essere disponibile per la registrazione del dispositivo.


Il http://www.cisco.com/c/en/us/products/switches/index.html["Sito di supporto Cisco"^] Contiene informazioni sui comandi per configurare Smart Call Home.
