---
settings:
  name: Cluster and storage switches
  search: ontap-systems-switches
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti relativi agli switch AFF e FAS
    url: "/index.html"
  - title: Inizia subito
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Scopri di più sugli switch dei sistemi ONTAP
      url: "/get-started/learn-switch-concept.html"
    - title: Iniziare a lavorare
      url: "/get-started/get-up-and-running.html"
  - title: Switch del cluster
    entries:
    - section: switch-bes-53248
    - section: switch-cisco-9336c-fx2
      pdf-filename: switch-cisco-9336c-fx2-cluster
    - section: switch-nvidia-sn2100
      pdf-filename: switch-nvidia-sn2100-cluster
  - title: Switch storage
    entries:
    - section: switch-cisco-9336c-fx2-storage
      pdf-filename: switch-cisco-9336c-fx2-storage
    - section: switch-nvidia-sn2100-storage
      pdf-filename: switch-nvidia-sn2100-storage
  - title: Switch condivisi
    entries:
    - section: switch-cisco-9336c-fx2-shared
      pdf-filename: switch-cisco-9336c-fx2-storage
  - title: Switch di fine disponibilità
    entries:
    - title: Panoramica
      url: "/overview-eod.html"
    - section: switch-cisco-3232c
    - section: switch-cisco-3132q-v
    - section: switch-cisco-92300
    - section: switch-netapp-cn1610
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
