---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Scopri i nuovi switch per i sistemi FAS e AFF . 
---
= Novità per gli switch
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri i nuovi switch per i sistemi FAS e AFF .  Per ulteriori informazioni sullo switch, vedere https://hwu.netapp.com/Switch/Index["Hardware Universe NetApp"^] .



== Nuovo supporto per gli switch

[cols="25h,~,~"]
|===
| Interruttori | Descrizione | Disponibile a partire da 


 a| 
Switch Cisco a 32 porte 400GbE (X190300-CS-PI e X190300-PE)
 a| 
Supporto per switch Intra-Cluster/HA/Storage Cisco 9332D-GX2B.
 a| 
ONTAP 9.17.1



 a| 
Switch Cisco a 64 porte 400GbE (X190310-CS-PI)
 a| 
Supporto per switch Intra-Cluster/HA/Storage Cisco 9364D-GX2A.
 a| 
ONTAP 9.17.1



 a| 
Switch cluster e storage Cisco Nexus 9336C-FX2-T a 12 porte 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Supporta configurazioni cluster 10/25/40/100GbE e configurazioni di storage 100GbE (switch-attached storage).
 a| 
ONTAP 9.10.1



 a| 
Switch cluster e storage Cisco Nexus 9336C-FX2-T a 12 porte 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Supporta configurazioni cluster 10/25/40/100GbE e configurazioni di storage 100GbE (switch-attached storage).
 a| 
ONTAP 9.10.1



 a| 
Switch NVIDIA 100GbE a 16 porte (X190006-PE e X190006-PI)
 a| 
Supporto per switch di interconnessione cluster e switch di archiviazione NVIDIA SN2100, incluso il supporto per configurazioni IP MetroCluster .
 a| 
ONTAP 9.10.1



 a| 
Switch Cisco 100GbE a 36 porte (X190200-CS-PE e X190200-CS-PI)
 a| 
Supporta un'infrastruttura condivisa (cluster, HA e storage collegato allo switch) sulla stessa coppia di switch Cisco Nexus 9336C-FX2, incluso il supporto per le configurazioni IP MetroCluster .
 a| 
ONTAP 9.9.1



 a| 
Switch Cisco 100GbE a 36 porte (X190200-CS-PE e X190200-CS-PI), (X190210-FE-PE e X190210-FE-PI)
 a| 
Lo switch di interconnessione cluster e lo switch di storage Cisco Nexus 9336C-FX2 supportano i sistemi di storage AFF e ASA , nonché la connettività dati front-end.
 a| 
ONTAP 9.8



 a| 
Switch Broadcom BES-53248 (X190005 e X190005R)
 a| 
Supporto dello switch di interconnessione cluster Broadcom BES-53248 per controller AFF/ FAS con porte 10/25GbE e 40/100GbE.
 a| 
ONTAP 9.8



 a| 
Switch Cisco 100GbE a 36 porte (X190200) e switch Cisco 100GbE a 32 porte (X190100 e X190100R)
 a| 
Lo switch di archiviazione Cisco Nexus 3232C supporta la connessione di unità NVMe NS224 ai sistemi di archiviazione AFF e ASA :

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===