---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Scopri i nuovi switch per i sistemi FAS e AFF . 
---
= Novità per gli switch
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri i nuovi switch per i sistemi di storage ONTAP. Per ulteriori informazioni sugli switch, consulta link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^].



[[july-2026]]
== Luglio 2026



[[new-cisco-nexus-9808-switch-for-afx-2k]]
=== Nuovo switch Cisco Nexus 9808 per AFX 2K

I nuovi switch Cisco 9808 si connettono ai nodi controller AFX 2K con le shelf di storage. Questo nuovo switch ti permette di creare cluster ONTAP con più di due nodi. Vengono utilizzati protocolli avanzati per ottimizzare le performance. Il design si basa sul tagging VLAN con percorsi di rete multipli, oltre che su configurazioni di tech-refresh, per garantire operatività continua e facilità di upgrade.

Si tratta di switch Cisco 400GbE a 36 porte con 1 modulo Supervisor, 7 moduli Fabric e 4 unità di alimentazione (PSU) (X-N9K-C9808-B1-A) che supportano ONTAP 9.19.1 e versioni successive.



[[2025-releases]]
== Rilasci del 2025

.Ottobre 2025
[%collapsible]
====
.Cisco Nexus 9332D-GX2B e 9364D-GX2A switch per AFX 1K
Gli switch Cisco 9364D-GX2A e Cisco 9332D-GX2B ti permettono di creare cluster ONTAP con più di due nodi. Vengono utilizzati protocolli avanzati per ottimizzare le performance. Il design si basa sul tagging VLAN con percorsi di rete multipli, oltre che su configurazioni di tech-refresh, per garantire operatività continua e facilità di upgrade.

Sono switch Cisco 400GbE a 32 e 64 porte (X190300-CS-PI, X190300-PE e X190310-CS-PI) che supportano ONTAP 9.17.1 e versioni successive.

Il nuovo NetApp AFX sistema storage offre una soluzione disaggregata progettata per soddisfare i rigorosi requisiti dei carichi di lavoro NAS e S3 dalle performance elevate, incluse le applicazioni di AI/ML. I sistemi AFX offrono funzionalità specializzate per i clienti che necessitano di storage file e storage a oggetti scalabili e ad alto throughput.

====
.Maggio 2025
[%collapsible]
====
.Switch di storage Cisco Nexus 9336C-FX2-T
Questi sono switch di storage Cisco a 12 porte 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI) che supportano ONTAP 9.10.1 e versioni successive. Supportano configurazioni di storage 100GbE (switch-attached storage).

====


[[2023-release]]
== Release 2023

.Maggio 2023
[%collapsible]
====
.Switch di rete cluster Cisco Nexus 9336C-FX2-T
Questi sono switch di rete Cisco per cluster a 12 porte 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI) che supportano ONTAP 9.10.1 e versioni successive. Supportano configurazioni cluster 10/25/40/100GbE.

====


[[2022-release]]
== Release 2022

.Ottobre 2022
[%collapsible]
====
.switch NVIDIA SN2100
Il NVIDIA SN2100 è uno switch NVIDIA a 16 porte 100GbE (X190006-PE e X190006-PI) che ti permette di creare cluster ONTAP con più di due nodi, supportando ONTAP 9.10.1 e versioni successive. È uno switch di interconnessione per cluster e storage NVIDIA SN2100, incluso il supporto per configurazioni IP MetroCluster.

====


[[2021-release]]
== Release 2021

.Maggio 2021
[%collapsible]
====
.Switch Cisco Nexus 9336C-FX2
Il Cisco Nexus 9336C-FX2 è uno switch Cisco a 36 porte 100GbE (X190200-CS-PE e X190200-CS-PI). Supporta un'infrastruttura condivisa (cluster, HA e storage collegato allo switch) sulla stessa coppia di switch Cisco Nexus 9336C-FX2, incluso il supporto per configurazioni IP MetroCluster, supportando ONTAP 9.9.1 e versioni successive.

====


[[2019-release]]
== Release 2019

.Maggio 2019
[%collapsible]
====
.Switch Broadcom BES-53248
Lo switch Broadcom BES-53248 (X190005 e X190005R) supporta i controller AFF/FAS con porte 10/25GbE e 40/100GbE, supportando ONTAP 9.8 e versioni successive.

====
.Marzo 2019
[%collapsible]
====
.Switch di cluster e storage Cisco Nexus 3232C
Lo switch Cisco Nexus 3232C è uno switch Cisco a 36 porte 100GbE (X190200) e uno switch Cisco a 32 porte 100GbE (X190100 e X190100R). Lo switch di storage Cisco Nexus 3232C supporta le connessioni ai seguenti shelf di dischi NVMe NS224 e ai sistemi storage AFF e ASA:

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400


Supportano ONTAP 9.8 e versioni successive.

====