---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Identifica i componenti e i codici articolo degli switch di cluster NVIDIA SN2100 per supportare l"installazione hardware e la manutenzione continua.' 
---
= Consulta i componenti e i codici articolo degli switch di cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Identifica i componenti e i codici articolo degli switch di cluster NVIDIA SN2100 per supportare l'installazione hardware e la manutenzione continua.



[[cabinet-details]]
== Dettagli del mobile

Installare lo switch NVIDIA SN2100 (X190006) nell'armadio switch doppio/singolo NVIDIA con le staffe standard incluse con lo switch.



[[rail-kit-details]]
== Dettagli del kit ferroviario

Nella tabella seguente sono elencati i codici articolo e la descrizione degli switch e dei kit di guide SN2100:

[cols="1,2"]
|===
| Numero di parte | Descrizione 


 a| 
X190006-PE
 a| 
Switch cluster, NVIDIA SN2100, 16PT 100GbE, PTSX



 a| 
X190006-PI
 a| 
Switch cluster, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit di binari, NVIDIA Dual Switch affiancati



 a| 
X-MTEF-KIT-E
 a| 
Kit di guide, NVIDIA Single switch profondità ridotta

|===

NOTE: Per dettagli, consultare la documentazione NVIDIA link:https://networking-docs.nvidia.com/sn2000hw/latest/installation["installazione del kit di switch e rail SN2100"^].

.Cosa succederà ora?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-sn2100-cluster.html["documentazione richiesta"].
