---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati.  È possibile utilizzare switch di gestione aggiuntivi, che sono facoltativi. 
---
= Componenti e numeri di parte per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NVIDIA SN2100, assicurarsi di rivedere l'elenco dei componenti e i codici articolo del cabinet e del kit di guide.



== Dettagli del mobile

Installare lo switch NVIDIA SN2100 (X190006) nell'armadio switch doppio/singolo NVIDIA con le staffe standard incluse con lo switch.



== Dettagli del kit ferroviario

Nella tabella seguente sono elencati i codici articolo e la descrizione degli switch e dei kit di guide SN2100:

[cols="1,2"]
|===
| Numero di parte | Descrizione 


 a| 
X190006-PE
 a| 
Switch cluster, NVIDIA SN2100, 16PT 100GbE, PTSX



 a| 
X190006-PI
 a| 
Switch cluster, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit di binari, NVIDIA Dual Switch affiancati



 a| 
X-MTEF-KIT-E
 a| 
Kit di guide, NVIDIA Single switch profondità ridotta

|===

NOTE: Per i dettagli, consultare la documentazione NVIDIA https://docs.nvidia.com/networking/display/sn2000pub/Installation["installazione del kit di switch e rail SN2100"^] .

.Cosa succederà ora?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-sn2100-cluster.html["documentazione richiesta"].
