---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Per l"installazione e la manutenzione dello switch NVIDIA SN2100, consultare tutti i requisiti e la documentazione consigliata.' 
---
= Requisiti di configurazione per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NVIDIA SN2100, verificare tutti i requisiti di configurazione.



== Requisiti di installazione

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati. È possibile utilizzare switch di gestione aggiuntivi, opzionali.

Lo switch NVIDIA SN2100 (X190006) viene installato nel cabinet doppio/singolo NVIDIA con le staffe standard incluse con lo switch.

Per le linee guida relative al cablaggio, vedere link:cabling-considerations-sn2100-cluster.html["Esaminare le considerazioni relative al cablaggio e alla configurazione"].



== Supporto di ONTAP e Linux

Lo switch NVIDIA SN2100 è uno switch 10/25/40/100GbE con Cumulus Linux. Lo switch supporta quanto segue:

* ONTAP 9.10.1P3. Lo switch SN2100 serve applicazioni cluster e storage in ONTAP 9.10.1P3 su diverse coppie di switch.
* Versione del sistema operativo Cumulus Linux (CL). Per scaricare il software SN2100 Cumulus, accedere a. https://enterprise-support.nvidia.com/s/["NVIDIA Enterprise Support Portal"^]. Per accedere al software Cumulus, è necessario disporre delle credenziali di accesso. Per informazioni aggiornate sulla compatibilità, consultare https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switch Ethernet NVIDIA"^] pagina informativa.
* È possibile installare Cumulus Linux quando lo switch esegue Cumulus Linux o ONIE.

