---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Per l"installazione e la manutenzione dello switch NVIDIA SN2100, assicurarsi di leggere tutti i requisiti e la documentazione consigliata.' 
---
= Requisiti di configurazione per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NVIDIA SN2100, assicurarsi di rivedere tutti i requisiti di configurazione.



== Requisiti di installazione

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati.  È possibile utilizzare switch di gestione aggiuntivi, che sono facoltativi.

Installare lo switch NVIDIA SN2100 (X190006) nell'armadio switch doppio/singolo NVIDIA con le staffe standard incluse con lo switch.

Per le linee guida sul cablaggio, vederelink:cabling-considerations-sn2100-cluster.html["Esaminare le considerazioni sul cablaggio e sulla configurazione"] .



== Supporto ONTAP e Linux

Lo switch NVIDIA SN2100 è uno switch 10/25/40/100GbE che esegue Cumulus Linux.  Lo switch supporta quanto segue:

* ONTAP 9.10.1P3 e versioni successive
+
Lo switch SN2100 supporta applicazioni Cluster e Storage in ONTAP 9.10.1P3 e versioni successive su diverse coppie di switch.

* Versioni del sistema operativo Cumulus Linux (CL)
+
** Versioni CL specifiche sono qualificate e supportate da NetApp.  Per informazioni sulla compatibilità attuale, vederelink:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Informazioni sugli switch Ethernet NVIDIA"^] pagina o lalink:https://hwu.netapp.com["Hardware Universe NetApp"^] .
** Per scaricare il software SN2100 Cumulus da NVIDIA, è necessario disporre delle credenziali di accesso per accedere al portale di supporto aziendale di NVIDIA.  Vedi l'articolo della Knowledge Base https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Come registrarsi con NVIDIA per l'accesso al portale di supporto aziendale"^] .




* È possibile installare Cumulus Linux quando lo switch esegue Cumulus Linux o ONIE.


.Cosa succederà ora?
Dopo aver esaminato i requisiti di configurazione, puoi confermare il tuo link:components-sn2100-cluster.html["componenti e numeri di parte"].
