---
permalink: switch-nvidia-sn2100/configure-software-overview-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Panoramica della configurazione software o degli switch NVIDIA SN2100. 
---
= Workflow di installazione del software per switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare e configurare il software per uno switch NVIDIA SN2100, attenersi alla seguente procedura:

. link:install-cumulus-mode-sn2100-cluster.html["Installare Cumulus Linux in modalità Cumulus"] oppure link:install-onie-mode-sn2100-cluster.html["Installare Cumulus Linux in modalità ONIE"].
+
È possibile installare il sistema operativo Cumulus Linux (CL) quando lo switch esegue Cumulus Linux o ONIE.

. link:install-rcf-sn2100-cluster.html["Installare lo script del file di configurazione di riferimento (RCF)"].
+
Sono disponibili due script RCF per le applicazioni di clustering e storage. La procedura per ciascuno di essi è la stessa.

. link:setup-install-cshm-file.html["Installare il file CSHM"].
+
È possibile installare il file di configurazione applicabile per il monitoraggio dello stato degli switch Ethernet degli switch cluster NVIDIA.


