---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Per l"installazione e la manutenzione dello switch NVIDIA SN2100, consultare tutti i requisiti e la documentazione consigliata.' 
---
= Requisiti di configurazione per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NVIDIA SN2100, verificare tutti i requisiti di configurazione.



== Requisiti di installazione

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati. È possibile utilizzare switch di gestione aggiuntivi, opzionali.

Lo switch NVIDIA SN2100 (X190006) viene installato nel cabinet doppio/singolo NVIDIA con le staffe standard incluse con lo switch.

Per le linee guida relative al cablaggio, vedere link:cabling-considerations-sn2100-cluster.html["Esaminare le considerazioni relative al cablaggio e alla configurazione"].



== Supporto di ONTAP e Linux

Lo switch NVIDIA SN2100 è uno switch 10/25/40/100GbE con Cumulus Linux. Lo switch supporta quanto segue:

* ONTAP 9.10.1P3 e versioni successive
+
Lo switch SN2100 serve cluster e applicazioni di storage in ONTAP 9.10.1P3 e versioni successive su diverse coppie di switch.

* Versioni del sistema operativo Cumulus Linux (CL)
+
** Le versioni CL specifiche sono qualificate e supportate da NetApp. Per informazioni aggiornate sulla compatibilità, vedere la link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Informazioni sugli switch Ethernet NVIDIA"^] pagina o la link:https://hwu.netapp.com["NetApp Hardware Universe"^].
** Per scaricare il software SN2100 Cumulus da NVIDIA, è necessario disporre delle credenziali di accesso per accedere al portale di supporto di NVIDIA Enterprise. Consultare l'articolo della Knowledge base https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Come registrarsi con NVIDIA per Enterprise Support Portal Access"^] .




* È possibile installare Cumulus Linux quando lo switch esegue Cumulus Linux o ONIE.

