---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Per l"installazione e la manutenzione dello switch NVIDIA SN2100, assicurarsi di consultare tutta la documentazione consigliata.' 
---
= Requisiti di documentazione per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione dello switch NVIDIA SN2100, assicurarsi di consultare tutta la documentazione consigliata.

[cols="1,2"]
|===
| Titolo | Descrizione 


 a| 
link:https://docs.nvidia.com/networking/display/sn2000pub/Installation["Guida all'installazione dello switch NVIDIA"^]
 a| 
Descrive come installare gli switch NVIDIA SN2100.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Guida al cablaggio dello scaffale per unità NVMe NS224"^]
 a| 
Panoramica e illustrazioni che mostrano come configurare il cablaggio per gli scaffali delle unità.

|===


== Documentazione dei sistemi ONTAP

Per configurare un sistema ONTAP, sono necessari i seguenti documenti per la versione del sistema operativo.

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
Istruzioni di installazione e configurazione specifiche del controller
 a| 
Descrive come installare l'hardware NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Fornisce informazioni dettagliate su tutti gli aspetti delle versioni ONTAP .



 a| 
link:https://hwu.netapp.com/["Hardware Universe"^]
 a| 
Consente di confermare l'hardware supportato, come switch cluster e cavi, per il modello della piattaforma.

|===