---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches' 
summary: È possibile utilizzare questa procedura per installare il file di configurazione applicabile per il monitoraggio dello stato degli switch cluster degli switch cluster NVIDIA SN2100. 
---
= Installare il file di configurazione di Ethernet Switch Health Monitor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare il monitoraggio dello stato dello switch Ethernet sugli switch Ethernet NVIDIA, seguire questa procedura.

Queste istruzioni si applicano se gli switch NVIDIA X190006-PE e X190006-PI non vengono rilevati correttamente, il che può essere confermato eseguendo  `system switch ethernet show` e controlla se *OTHER* è visualizzato per il tuo modello. Per identificare il modello del tuo switch NVIDIA, trova il codice prodotto con il comando  `nv show platform hardware` per NVIDIA CL 5.8 e precedenti o  `nv show platform` per le versioni successive.

[NOTE]
====
Questi passaggi sono consigliati anche se si desidera che il monitoraggio dello stato e la raccolta dei log funzionino correttamente quando si utilizza NVIDIA CL 5.11.x con le seguenti release di ONTAP. Sebbene il monitoraggio dello stato e la raccolta dei log possano comunque funzionare anche senza questi passaggi, seguirli garantisce il corretto funzionamento di tutto.

* 9.10.1P20, 9.11.1P18, 9.12.1P16, 9.13.1P8, 9.14.1, 9.15.1 e versioni successive


====
.Prima di iniziare
* Assicurarsi che il cluster ONTAP sia attivo e in esecuzione.
* Abilitare SSH sullo switch per utilizzare tutte le funzionalità disponibili in CSHM.
* Cancellare la `/mroot/etc/cshm_nod/nod_sign/` directory su tutti i nodi:
+
.. Immettere la notoresella:
+
`system node run -node <name>`

.. Modifica dei privilegi avanzati:
+
`priv set advanced`

.. Elencare i file di configurazione nella `/etc/cshm_nod/nod_sign` directory. Se la directory esiste e contiene file di configurazione, elenca i nomi dei file.
+
`ls /etc/cshm_nod/nod_sign`

.. Eliminare tutti i file di configurazione corrispondenti ai modelli di switch collegati.
+
In caso di dubbi, rimuovere tutti i file di configurazione per i modelli supportati elencati sopra, quindi scaricare e installare i file di configurazione più recenti per gli stessi modelli.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Verificare che i file di configurazione eliminati non siano più nella directory:
+
`ls /etc/cshm_nod/nod_sign`





.Fasi
. Scaricare il file zip di configurazione dello switch Ethernet Health monitor in base alla versione di ONTAP corrispondente. Questo file è disponibile nella https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switch Ethernet NVIDIA"^] pagina .
+
.. Nella pagina di download del software NVIDIA SN2100, selezionare *Nvidia CSHM file*.
.. Nella pagina attenzione/da leggere, selezionare la casella di controllo per accettare.
.. Nella pagina Contratto di licenza con l'utente finale, selezionare la casella di controllo Accetto e fare clic su *Accetta e continua*.
.. Nella pagina file Nvidia CSHM - Download, selezionare il file di configurazione appropriato. Sono disponibili i seguenti file:




[role="tabbed-block"]
====
.ONTAP 9.15.1 e versioni successive
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP da 9.11.1 a 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]caricare il file zip applicabile sul server Web interno.
. Accedi alle impostazioni della modalità avanzata da uno dei sistemi ONTAP nel cluster.
+
`set -privilege advanced`

. Eseguire il comando di configurazione dello switch Health monitor.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. Verificare che l'output del comando termini con il seguente testo per la versione di ONTAP in uso:


[role="tabbed-block"]
====
.ONTAP 9.15.1 e versioni successive
--
Il monitoraggio dello stato dello switch Ethernet ha installato il file di configurazione.

--
.ONTAP da 9.11.1 a 9.14.1
--
SHM ha installato il file di configurazione.

--
.ONTAP 9.10.1
--
Pacchetto scaricato CSHM elaborato correttamente.

--
====
In caso di errore, contattare il supporto NetApp.

. [[step6]]attendere fino a due volte l'intervallo di polling del monitor dello stato dello switch Ethernet, rilevato eseguendo `system switch ethernet polling-interval show`, prima di completare il passaggio successivo.
. Esegui il comando `system switch ethernet configure-health-monitor show` sul sistema ONTAP e assicurarsi che gli switch del cluster vengano rilevati con il campo monitorato impostato su *True* e che il campo del numero di serie non mostri *Unknown*.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----



NOTE: Se il modello mostra ancora *ALTRO* dopo aver applicato il file di configurazione, contattare il supporto NetApp.

Vedi il https://docs.netapp.com/us-en/ontap-cli/system-switch-ethernet-configure-health-monitor.html["switch di sistema ethernet configura-monitor-stato"^] comando per ulteriori dettagli.

.Quali sono le prossime novità?
Dopo aver installato il file CSHM, puoilink:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"] .
