---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/components-9336c-storage.html 
keywords: shared storage cluster switch 
summary: A partire da ONTAP 9.9.1, è possibile utilizzare gli switch Cisco Nexus 9336C-FX2 per combinare funzionalità di storage e cluster in uno scenario di switch condiviso. 
---
= Componenti e codici articolo per gli switch di archiviazione Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch di archiviazione Cisco Nexus 9336C-FX2 e 9336C-FX2-T, assicurarsi di rivedere l'elenco dei componenti e i codici articolo.

Nella tabella seguente sono elencati i codici prodotto e la descrizione degli switch di archiviazione, delle ventole e degli alimentatori 9336C-FX2 e 9336C-FX2-T:

[cols="1,2"]
|===
| Numero di parte | Descrizione 


 a| 
X190200-CS-PE
 a| 
Interruttore a grappolo, N9336C 36Pt PTSX 10/25/40/100G



 a| 
X190200-CS-PI
 a| 
Interruttore a grappolo, N9336C 36Pt PSIN 10/25/40/100G



 a| 
X190212-CS-PE
 a| 
Interruttore a grappolo, N9336C 12Pt (9336C-FX2-T) PTSX 10/25/40/100G



 a| 
X190212-CS-PI
 a| 
Interruttore a grappolo, N9336C 12Pt (9336C-FX2-T) PSIN 10/25/40/100G



 a| 
SW-N9K-FX2-24P-UPG
 a| 
SW, licenza Cisco 9336CFX2 POD a 24 porte



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT 10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT 10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit accessori X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
Alimentatore N9K-9336C AC 1100W - Flusso d'aria di scarico lato sinistro



 a| 
X-NXA-PAC-1100W-PI2
 a| 
Alimentatore CA N9K-9336C da 1100 W - Flusso d'aria di aspirazione lato sinistro



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM, flusso d'aria di scarico lato babordo



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM, flusso d'aria di aspirazione lato sinistro

|===


== Licenze Cisco Smart solo per porte 9336C-FX2-T

Per attivare più di 12 porte sullo switch di archiviazione Cisco Nexus 9336C-FX-T, è necessario acquistare una licenza Cisco Smart.  Le licenze Cisco Smart vengono gestite tramite gli account Cisco Smart.

. Se necessario, crea un nuovo account Smart. Vedere https://id.cisco.com/signin/register["Crea un nuovo account Smart"^] per i dettagli.
. Richiedi l'accesso a un account Smart esistente. Vedere https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30["Richiedi l'accesso a un account Smart esistente"^] per i dettagli.



NOTE: Dopo aver acquistato la licenza Smart, installa l'RCF appropriato per abilitare e configurare tutte le 36 porte disponibili per l'uso.

.Cosa c'è dopo?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-9336c-storage.html["documentazione richiesta"].
