---
permalink: switch-cisco-9336c-fx2/index.html 
sidebar: sidebar 
keywords: cisco, switch, cisco 9336 switch 
summary: 'Switch Cisco 9336-FX2`' 
---
= Panoramica e requisiti: Switch Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 9336C-FX2, consultare i requisiti di configurazione e la documentazione.

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati. È possibile utilizzare switch di gestione aggiuntivi, opzionali.

È possibile installare lo switch Cisco Nexus 9336C-FX2 (X190200/X190210) in un cabinet di sistema NetApp o in un cabinet di terze parti con le staffe standard incluse nello switch.



== Componenti dello switch

La seguente tabella elenca il codice ricambio e la descrizione dello switch, delle ventole e degli alimentatori 9336C-FX2:

[cols="1,2"]
|===
| Codice del ricambio | Descrizione 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit di accessori X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C AC 1100 W PSU - flusso d'aria di scarico laterale



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C AC 1100 W PSU - flusso d'aria di aspirazione lato porta



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM, flusso d'aria di scarico lato porta



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM, flusso d'aria di aspirazione lato porta

|===


== Requisiti di configurazione

Per configurare il cluster, sono necessari il numero e il tipo di cavi e connettori appropriati per gli switch. A seconda del tipo di switch che si sta configurando inizialmente, è necessario connettersi alla porta console dello switch con il cavo console incluso; è inoltre necessario fornire informazioni di rete specifiche.



== Requisiti di rete

Sono necessarie le seguenti informazioni di rete per tutte le configurazioni dello switch:

* Subnet IP per il traffico di rete di gestione
* Nomi host e indirizzi IP per ciascuno dei controller del sistema di storage e per tutti gli switch applicabili
* La maggior parte dei controller del sistema di storage viene gestita tramite l'interfaccia e0M connettendosi alla porta di servizio Ethernet (icona chiave). Nei sistemi AFF A800 e AFF A700, l'interfaccia e0M utilizza una porta Ethernet dedicata.


Fare riferimento a. https://hwu.netapp.com["Hardware Universe"^] per informazioni aggiornate.



== Requisiti Smart Call Home

Smart Call Home monitora i componenti hardware e software della rete, per generare una notifica via email delle condizioni critiche del sistema. Quando si verifica un evento sul dispositivo, Smart Call Home genera un avviso a tutti i destinatari configurati nel profilo di destinazione.

È necessario configurare uno switch di rete del cluster per comunicare tramite e-mail con il sistema Smart Call Home. È possibile configurare lo switch di rete del cluster in modo da sfruttare la funzione di supporto Smart Call Home integrata di Cisco.

Prima di utilizzare la funzione Smart Call Home, è necessario tenere presente le seguenti considerazioni:

* È necessario che sia installato un server di posta elettronica.
* Lo switch deve disporre di connettività IP al server di posta elettronica.
* È necessario configurare il nome del contatto (contatto del server SNMP), il numero di telefono e l'indirizzo. Questo è necessario per determinare l'origine dei messaggi ricevuti.
* Un ID CCO deve essere associato a un contratto Cisco SMARTnet Service appropriato per la tua azienda.
* Cisco SMARTnet Service deve essere disponibile per la registrazione del dispositivo.


Il http://www.cisco.com/c/en/us/products/switches/index.html["Sito di supporto Cisco"^] Contiene informazioni sui comandi per configurare Smart Call Home.



== Requisiti di documentazione

Per configurare gli switch Cisco 9336-FX2 e il cluster ONTAP, è necessaria una documentazione specifica su switch e controller.



=== Documentazione dello switch

Per configurare gli switch Cisco Nexus 9336C-FX2, è necessaria la seguente documentazione disponibile sul https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Supporto degli switch Cisco Nexus serie 9000"^] pagina:

[cols="1,2"]
|===
| Titolo del documento | Descrizione 


 a| 
_Guida all'installazione dell'hardware della serie Nexus 9000_
 a| 
Fornisce informazioni dettagliate sui requisiti del sito, sui dettagli dell'hardware dello switch e sulle opzioni di installazione.



 a| 
_Cisco Nexus 9000 Series Software Configuration Guide_ (scegliere la guida per la release NX-OS installata sugli switch)
 a| 
Fornisce le informazioni di configurazione iniziale dello switch necessarie prima di poter configurare lo switch per il funzionamento ONTAP.



 a| 
_Guida all'aggiornamento e al downgrade del software per Cisco Nexus serie 9000 NX-OS_ (scegliere la guida per la release NX-OS installata sugli switch)
 a| 
Fornisce informazioni su come eseguire il downgrade dello switch al software dello switch supportato da ONTAP, se necessario.



 a| 
_Cisco Nexus serie 9000 NX-OS Command Reference Master Index_
 a| 
Fornisce collegamenti ai vari riferimenti ai comandi forniti da Cisco.



 a| 
_Riferimento MIB Cisco Nexus 9000_
 a| 
Descrive i file MIB (Management Information base) per i centralini Nexus 9000.



 a| 
_Guida ai messaggi del sistema NX-OS serie Nexus 9000_
 a| 
Descrive i messaggi di sistema per gli switch Cisco Nexus serie 9000, quelli che sono informativi e altri che possono aiutare a diagnosticare problemi con collegamenti, hardware interno o software di sistema.



 a| 
_Note sulla versione di Cisco Nexus 9000 Series NX-OS (scegliere le note per la release NX-OS installata sugli switch)_
 a| 
Descrive le funzioni, i bug e le limitazioni di Cisco Nexus serie 9000.



 a| 
Conformità alle normative e informazioni sulla sicurezza per Cisco Nexus serie 9000
 a| 
Fornisce informazioni legali, sulla conformità e sulla sicurezza degli switch Nexus serie 9000 a livello internazionale.

|===


=== Documentazione sui sistemi ONTAP

Per configurare un sistema ONTAP, sono necessari i seguenti documenti per la versione del sistema operativo in uso dal https://docs.netapp.com/ontap-9/index.jsp["Centro documentazione di ONTAP 9"^].

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
_Istruzioni di installazione e configurazione_ specifiche del controller
 a| 
Descrive come installare l'hardware NetApp.



 a| 
Documentazione ONTAP
 a| 
Fornisce informazioni dettagliate su tutti gli aspetti delle release di ONTAP.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornisce informazioni sulla compatibilità e sulla configurazione dell'hardware NetApp.

|===


=== Kit di guide e documentazione del cabinet

Per installare uno switch Cisco 9336-FX2 in un cabinet NetApp, consultare la seguente documentazione hardware.

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Cabinet di sistema 42U, guida dettagliata"^]
 a| 
Descrive le FRU associate all'armadio del sistema 42U e fornisce istruzioni per la manutenzione e la sostituzione delle FRU.



 a| 
link:install-switch-and-passthrough-panel.html["Installare uno switch Cisco 9336-FX2 in un cabinet NetApp"^]
 a| 
Descrive come installare uno switch Cisco Nexus 9336C-FX2 in un cabinet NetApp a quattro montanti.

|===