---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Se non si dispone già delle informazioni di configurazione e della documentazione necessarie, è necessario raccogliere tali informazioni prima di configurare il cluster e gli switch di rete di gestione. 
---
= Installare gli switch di archiviazione 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per installare gli switch di archiviazione Cisco Nexus 9336C-FX2 e 9336C-FX2-T.

.Prima di iniziare
Assicurati di avere quanto segue:

* Accesso a un server HTTP, FTP o TFTP nel sito di installazione per scaricare le versioni NX-OS e RCF (Reference Configuration File) applicabili.
* Versione NX-OS applicabile, scaricata da https://software.cisco.com/download/home["Download del software Cisco"^] pagina.
* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Completatolink:setup-worksheet-9336c-storage.html["fogli di lavoro sul cablaggio"] .
* RCF applicabili alla rete cluster NetApp e alla rete di gestione scaricabili dal sito di supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^] .  Tutti gli switch di rete cluster e di rete di gestione Cisco vengono forniti con la configurazione predefinita di fabbrica Cisco . Questi switch dispongono anche della versione corrente del software NX-OS, ma non hanno gli RCF caricati.
* Documentazione richiesta per lo switch. Vederelink:required-documentation-9336c-storage.html["Documentazione richiesta"] per maggiori informazioni.


.Passi
. Installare gli switch e i controller della rete del cluster e della rete di gestione.
+
[cols="1,2"]
|===
| Se stai installando il tuo... | Poi... 


 a| 
Cisco Nexus 9336C-FX2 in un cabinet di sistema NetApp
 a| 
Vederelink:install-switch-and-passthrough-panel-9336c-storage.html["Installare lo switch nell'armadio NetApp"] per istruzioni su come installare lo switch in un cabinet NetApp .



 a| 
Apparecchiature in un rack Telco
 a| 
Consultare le procedure fornite nelle guide all'installazione dell'hardware dello switch e nelle istruzioni di installazione e configurazione NetApp .

|===
. Cablare la rete del cluster e gli switch della rete di gestione ai controller utilizzando i fogli di lavoro di cablaggio compilati.
. Accendere la rete del cluster e gli switch e i controller della rete di gestione.


.Cosa succederà ora?
Facoltativamente, puoi link:install-switch-and-passthrough-panel-9336c-storage.html["installare uno switch Cisco Nexus 9336C-FX2 in un cabinet NetApp"]. Altrimenti vai a link:setup-switch-9336c-storage.html["configurare lo switch"].
