---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: 'Installa o aggiorna il file di configurazione (RCF) sugli switch di storage Cisco Nexus 9336C-FX2 e 9336C-FX2-T dopo la configurazione iniziale o quando aggiorni un RCF esistente.' 
---
= Installa o aggiorna l'RCF sugli switch di storage Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installa il file di configurazione di riferimento (RCF) sugli switch di storage Cisco Nexus 9336C-FX2 e 9336C-FX2-T dopo la configurazione iniziale oppure aggiorna la versione di RCF quando è disponibile una versione più recente.

Fare riferimento all'articolo della Knowledge Base link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch di interconnessione Cisco mantenendo la connettività remota"^] per ulteriori informazioni durante l'installazione o l'aggiornamento del proprio RCF.

.Configurazione RCF disponibile
Storage - (Storage RCF 1._xx_) è la configurazione RCF disponibile in cui tutte le porte sono configurate per connessioni storage NVMe 100GbE.

.Documentazione suggerita
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
+
Consultare la tabella di compatibilità degli switch per le versioni ONTAP e RCF supportate sul sito di supporto NetApp .  Si noti che possono esserci dipendenze tra la sintassi dei comandi nella RCF e la sintassi presente in versioni specifiche di NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switch Cisco Nexus serie 9000"^]
+
Per la documentazione completa sulle procedure di upgrade e downgrade degli switch Cisco , fare riferimento alle guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .



.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono s1 e s2.
* I nomi dei nodi sono cluster1-01 e cluster1-02.


Consultare la link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte corrette sulla propria piattaforma.


NOTE: Gli output dei comandi potrebbero variare a seconda delle diverse versioni di ONTAP.

.Comandi utilizzati
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 9000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

.Cosa succederà ora?
Dopo aver esaminato la procedura di installazione o aggiornamento RCF, è possibilelink:install-rcf-software-9336c-storage.html["installare l'RCF"] Olink:upgrade-rcf-software-9336c-storage.html["aggiorna il tuo RCF"] secondo necessità.
