---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'La sostituzione di uno switch Nexus 9336C-FX2 difettoso in una rete cluster è una procedura non distruttiva \(NDU\).' 
---
= Sostituisci gli switch di archiviazione Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire gli switch Nexus 9336C-FX2 e 9336C-FX2-T difettosi in una rete cluster. Si tratta di una procedura non distruttiva.

.Prima di iniziare
Prima di installare il software NX-OS e gli RCF sugli switch di archiviazione Cisco Nexus 9336C-FX2 e 9336C-FX2-T, assicurarsi che:

* Il sistema può supportare gli switch di archiviazione Cisco Nexus 9336C-FX2 e 9336C-FX2-T.
* Hai consultato la tabella di compatibilità degli switch nella pagina Cisco Ethernet Switch per le versioni ONTAP, NX-OS e RCF supportate.
* Hai fatto riferimento alle guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .
* Hai scaricato gli RCF applicabili.
* La configurazione di rete esistente presenta le seguenti caratteristiche:
+
** Nella pagina relativa agli switch Ethernet Cisco sono disponibili le versioni RCF e NX-OS più recenti sui tuoi switch.
** La connettività di gestione deve essere presente su entrambi gli switch.


* Lo switch sostitutivo Cisco Nexus 9336C-FX2 presenta le seguenti caratteristiche:
+
** La connettività della rete di gestione è funzionale.
** L'accesso alla console per l'interruttore sostitutivo è pronto.
** L'immagine appropriata del sistema operativo RCF e NX-OS viene caricata sullo switch.
** La configurazione iniziale dello switch è completa.




.Informazioni su questo compito
Questa procedura sostituisce il secondo switch storage Nexus 9336C-FX2 s2 con il nuovo switch 9336C-FX ns2. I due nodi sono cluster1-01 e cluster1-02.

Passaggi per completare:

* Confermare che l'interruttore da sostituire sia s2.
* Scollegare i cavi dallo switch s2.
* Ricollega i cavi allo switch ns2.
* Verificare tutte le configurazioni dei dispositivi sullo switch ns2.
+

NOTE: Possono esserci dipendenze tra la sintassi dei comandi nelle versioni RCF e NX-OS.



.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

. Controllare lo stato di integrità delle porte del nodo di archiviazione per assicurarsi che vi sia una connessione allo switch di archiviazione s1:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Verificare che lo switch di archiviazione s1 sia disponibile:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. Gestisci lo spettacolo `lldp neighbors` comando sullo switch funzionante per confermare che puoi vedere entrambi i nodi e tutti gli scaffali:
+
`show lldp neighbors`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Verificare le porte dello shelf di storage nel sistema storage:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. Rimuovere tutti i cavi collegati allo switch di storage s2.
. Ricollega tutti i cavi allo switch sostitutivo ns2.
. Ricontrollare lo stato di integrità delle porte del nodo di archiviazione:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Verificare che entrambi gli switch siano disponibili:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. Verificare le porte degli scaffali nel sistema di archiviazione:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
Dopo aver sostituito gli interruttori, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
