---
permalink: switch-cisco-9808/configure-install-upgrade-rcf-overview-9808.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808 
summary: 'Puoi installare o aggiornare il file di configurazione di riferimento (RCF) sugli switch Nexus 9808. Installi una versione supportata dell"RCF sugli switch come parte di una nuova installazione del sistema AFX 2K, della sostituzione del modulo supervisor o del ripristino dello switch alle impostazioni di fabbrica. Esegui l"aggiornamento a una versione supportata dell"RCF sugli switch per supportare nuovo hardware, una nuova versione di ONTAP o per allinearti a una nuova versione di NX-OS nella configurazione del sistema AFX 2K.' 
---
= Installa o aggiorna la panoramica RCF - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi installare o aggiornare il file di configurazione di riferimento (RCF) sugli switch Cisco Nexus 9808. Installi una versione supportata dell'RCF sugli switch come parte di una nuova installazione del sistema AFX 2K, della sostituzione di un modulo supervisor o del ripristino dello switch alle impostazioni di fabbrica. Aggiorni a una versione supportata dell'RCF sugli switch per supportare nuovo hardware, una nuova versione di ONTAP o per allinearti a una nuova versione di NX-OS nella configurazione del tuo sistema AFX.


NOTE: L'installazione o l'aggiornamento di RCF è indipendente dall'installazione o dall'aggiornamento di NX-OS. Se stai installando o aggiornando sia NX-OS che RCF, ti consigliamo di installare o aggiornare prima NX-OS.



[[understand-the-supported-rcf-versions]]
=== Comprendi le versioni RCF supportate

La versione di ONTAP in esecuzione sul tuo sistema AFX e la versione di NX-OS sui tuoi switch Cisco Nexus 9808 determinano le versioni di RCF supportate per i tuoi switch. Le versioni di RCF hanno configurazioni di velocità delle porte preimpostate che determinano quante porte dello switch sono in modalità breakout (4x100GbE) e quante in modalità non breakout.

[NOTE]
====
Per l'elenco aggiornato delle versioni RCF supportate, consulta link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet NetApp Cisco"^].

Le informazioni sulla porta dello switch si trovano anche nel link:https://hwu.netapp.com["Hardware Universe NetApp"^].

====

NOTE: Per i dettagli specifici sull'utilizzo di porte e VLAN, fare riferimento al banner e alla sezione delle note importanti nel proprio RCF. Consulta link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet NetApp Cisco"^] per maggiori informazioni.

Ad esempio, la tabella seguente mostra i gruppi preimpostati delle porte dello switch, le relative velocità delle porte e l'utilizzo in base alla versione 10.1 di RCF.

[cols="1,2"]
|===
| Gruppi di porte switch | Velocità e utilizzo delle porte 


 a| 
Ethernet1/1 a Ethernet1/18
 a| 
Modalità 400GbE per connessioni intra-cluster, HA e shelf di storage



 a| 
Ethernet1/19 a Ethernet1/35
 a| 
Modalità 4x100GbE per connessioni intra-cluster, HA e di storage



 a| 
Ethernet1/36
 a| 
Connessioni ISL intra-cluster da 400GbE

|===


[[change-port-speed-configuration]]
=== Modifica la configurazione della velocità della porta

Per gli switch con RCF 10.1 e versioni successive, puoi modificare la configurazione della velocità delle porte per regolare il numero di porte dello switch in modalità breakout (4x100GbE) e in modalità non-breakout (400GbE) quando devi adattare una diversa configurazione della velocità delle porte per il tuo sistema AFX. Qualsiasi modifica alle porte viene effettuata per ciascuna scheda di linea attualmente in uso.

Esegui questa modifica come parte della procedura di installazione o aggiornamento di RCF. Le procedure includono passaggi che rimandano a questa pagina.

Inserisci i comandi su entrambi gli switch.

[cols="1,2"]
|===
| Modifica la velocità delle porte | Passi 


 a| 
Trasforma le porte non breakout in porte breakout
 a| 
. Entra in modalità di configurazione nella CLI.
. Modifica la velocità delle porte e le modalità breakout sugli switch:
+
Per designare le porte breakout, usa il comando  `interface breakout module`.

+
Ad esempio, per designare le porte 19-22 in modalità 400GbE come porte breakout (4x100GbE), usa quanto segue:

+
`interface breakout module 1 port 19-22 map 100g-4x`

. Modifica l'elenco delle porte con le nuove porte che devono utilizzare il profilo di porta per la velocità di porta desiderata.
+
Ad esempio, per modificare l'elenco delle porte con le nuove porte, 19-22, per il profilo di velocità 100G, usa quanto segue:

+
`interface e1/19/1-4, e1/20/1-4, e1/21/1-4, e1/22/1-4`

. Imposta in modo fisso le porte breakout (4x100GbE) dello switch a 100GbE. Se non imposti la velocità in modo fisso, le porte non si attiveranno e rimarranno in uno stato di errore disabilitato.
+
`speed 100000`

+
`no negotiate auto`





 a| 
Riporta le porte breakout alle porte non breakout
 a| 
. Entra in modalità di configurazione nella CLI.
. Per riportare le porte breakout a porte non breakout, usa il comando  `no interface breakout` in modalità config.
+
Ad esempio, per riportare le porte 19-22 alla modalità 400GbE, usa quanto segue:

+
`no interface breakout module 1 port 19-22`



|===


[[suggested-documentation]]
=== Documentazione suggerita

Prima di installare o aggiornare l'RCF sugli switch, ti consigliamo di consultare la seguente documentazione:

* Consulta l'articolo della Knowledge Base di NetApp link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch di interconnessione Cisco mantenendo la connettività remota"^] per ulteriori informazioni quando installi o aggiorni il tuo RCF.
* Consultare la  https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe NetApp"^] per verificare le porte corrette sulla propria piattaforma.
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco (NSS)"^]
+
Consultare la tabella di compatibilità degli switch per le versioni ONTAP e RCF supportate sul sito di supporto NetApp .  Si noti che possono esserci dipendenze tra la sintassi dei comandi nella RCF e la sintassi presente in versioni specifiche di NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switch Cisco Nexus serie 9000"^]
+
Per la documentazione completa sulle procedure di upgrade e downgrade degli switch Cisco , fare riferimento alle guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .



.Cosa succederà ora?
Dopo aver esaminato la panoramica di installazione o aggiornamento di RCF, puoi link:configure-install-rcf-9808.html["installare l'RCF"] o link:configure-upgrade-rcf-9808.html["aggiornare l'RCF"] come necessario.
