---
permalink: switch-cisco-9808/maintain-replace-frus-9808.html 
sidebar: sidebar 
keywords: switches, hardware installation, Cisco Nexus, 9808 switches 
summary: 'Il tuo switch Cisco Nexus 9808 ha unità sostituibili sul campo (FRU) che puoi sostituire quando sono difettose.' 
---
= Sostituisci FRU - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il tuo switch Cisco Nexus 9808 ha unità sostituibili sul campo (FRU) che puoi sostituire quando sono difettose.

.Informazioni su questo compito
Lo switch Cisco Nexus 9808 dispone dei seguenti componenti sostituibili sul campo (FRU):

* *Filtri aria in schiuma per sportelli dello chassis* (2 in totale): Gli sportelli sono dotati di filtri aria preinstallati. Dovresti ispezionare il filtro aria ogni 3 mesi e sostituirlo se necessario.
* *Modulo Supervisor* (1 o 2 in totale, a seconda di come hai ordinato lo switch): Quando nello switch sono installati due moduli Supervisor, uno funge da modulo attivo e l'altro da modulo di standby. Quando il modulo Supervisor attivo viene rimosso, lo switch rende automaticamente attivo il modulo Supervisor di standby. Se nello switch è installato un solo modulo Supervisor, puoi installare un nuovo modulo Supervisor nello slot Supervisor vuoto durante il funzionamento.
* *Schede di linea* (8 in totale, ciascuna con 16 porte fisse da 400GbE): Lo switch funziona con una o più schede di linea installate nello chassis.
* *Vassoio ventola* (2 in totale)
* *Fabric module* (2 in totale)
* *Componenti dell'alimentatore* (2 in totale)
* *Modulo ventola* (6 in totale)
* *Moduli ricetrasmettitori OSFP/QSFP* (32 porte fisse 400GbE)


.Passi
. Vai al sito Cisco per il link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide.html["Guida all'installazione hardware dello switch Cisco Nexus 9808 in modalità NX-OS"^].
. Vai alla sezione link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-replace-chassis-components.html["Sostituisci i componenti dello chassis"^] per vedere le procedure FRU.
. Segui la procedura applicabile per sostituire il tuo FRU difettoso.
+
Consulta la link:https://hwu.netapp.com["Hardware Universe NetApp"^] per le informazioni sulla configurazione hardware e sulla compatibilità di NetApp.



.Cosa succederà ora?
Dopo aver completato la procedura FRU applicabile sul sito Cisco, puoi riprendere le normali operazioni.
