---
sidebar: sidebar 
permalink: switch-cisco-9808/reference-documentation-9808.html 
keywords: shared storage cluster switch 
summary: 'Per l"installazione e la configurazione dello switch Cisco Nexus 9808 come parte di un nuovo sistema AFX 2K o per la manutenzione di switch esistenti, puoi fare riferimento alla documentazione Cisco relativa allo switch e alla documentazione dei sistemi NetApp.' 
---
= Documentazione di riferimento - Cisco Nexus 9808
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la configurazione dello switch Cisco Nexus 9808 come parte di un nuovo sistema AFX 2K o per la manutenzione di switch esistenti, puoi fare riferimento alla documentazione Cisco relativa allo switch e alla documentazione dei sistemi NetApp.


NOTE: Per istruzioni dettagliate su come installare e configurare gli switch come parte di un nuovo sistema AFX 2K, consulta la link:install-configure-switches-in-afx-workflow-9808.html["Installa e configura gli switch in un workflow di sistema AFX"].



[[cisco-switch-documentation]]
== Documentazione degli switch Cisco

Per installare e configurare i tuoi switch Cisco Nexus 9808 come parte di un nuovo sistema AFX 2K, puoi consultare i seguenti documenti Cisco per familiarizzare con le note di rilascio dello switch, le informazioni sulla sicurezza, le opzioni di installazione, la configurazione software iniziale e i riferimenti ai comandi.

Dopo aver installato e configurato gli switch, puoi consultare la documentazione Cisco pertinente per la loro manutenzione.

Tutti questi documenti sono disponibili sulla pagina link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Supporto per gli switch Cisco Nexus serie 9000"^].

[cols="1,2,3"]
|===
| Tipo di attività | Titolo del documento Cisco | Descrizione 


 a| 
Installa e configura
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Note sulla versione NX-OS della serie Cisco Nexus 9000"^](seleziona le note per la versione NX-OS installata sui tuoi switch)
 a| 
Descrive le funzionalità, i bug e le limitazioni della serie Cisco Nexus 9000.



 a| 
Installa e configura
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Conformità normativa e informazioni sulla sicurezza per Cisco Nexus serie 9000"^]
 a| 
Fornisce informazioni sulla conformità alle agenzie internazionali, sulla sicurezza e sugli statuti per gli switch della serie Nexus 9000.



 a| 
Installa e configura
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-modular-overview-ph2.html?linkclickid=aisrch["Guida all'installazione hardware dello switch Cisco Nexus 9808 in modalità NX-OS"^]
 a| 
Fornisce informazioni dettagliate sui requisiti del sito, dettagli sull'hardware dello switch e opzioni di installazione.



 a| 
Installa e configura
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guide alla configurazione del software dello switch Cisco Nexus serie 9000"^](scegli la guida per la versione NX-OS installata sui tuoi switch)
 a| 
Fornisce le informazioni di configurazione iniziale dello switch necessarie prima di poterlo configurare per il funzionamento ONTAP .



 a| 
Installare, configurare e mantenere
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Riferimento ai comandi NX-OS della serie Cisco Nexus 9000"^]
 a| 
Fornisce collegamenti ai vari riferimenti ai comandi forniti da Cisco.



 a| 
Installa e configura
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guida all'aggiornamento e al downgrade del software NX-OS della serie Cisco Nexus 9000"^](scegli la guida per la versione NX-OS installata sui tuoi switch)
 a| 
Fornisce informazioni su come effettuare il downgrade dello switch al software dello switch supportato ONTAP , se necessario.



 a| 
Mantenere
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Riferimento ai messaggi del sistema Cisco Nexus serie NX-OS 9000"^]
 a| 
Descrive i messaggi di sistema per gli switch Cisco Nexus serie 9000, quelli informativi e altri che potrebbero aiutare a diagnosticare problemi con i collegamenti, l'hardware interno o il software di sistema.

|===


[[netapp-systems-documentation]]
== Documentazione dei sistemi NetApp

Per installare e configurare i tuoi switch Cisco Nexus 9808 come parte di un nuovo sistema AFX 2K, puoi consultare i seguenti documenti e risorse di sistema NetApp per familiarizzare con i sistemi AFX, le versioni ONTAP supportate, le configurazioni hardware supportate e i requisiti di installazione del sistema.

[cols="1,2,3"]
|===
| Tipo di attività | Titolo del documento ONTAP | Descrizione 


 a| 
Installa e configura
 a| 
link:https://docs.netapp.com/us-en/ontap-afx/index.html["Documentazione dei sistemi AFX"^]
 a| 
Descrive come installare l'hardware NetApp .



 a| 
Installa e configura
 a| 
link:https://docs.netapp.com/us-en/ontap-family/["Documentazione ONTAP"^]
 a| 
Fornisce informazioni dettagliate su tutti gli aspetti delle versioni ONTAP .



 a| 
Installa e configura
 a| 
link:https://hwu.netapp.com["Hardware Universe NetApp"^]
 a| 
Fornisce informazioni sulla configurazione hardware e sulla compatibilità NetApp .



 a| 
Installa e configura
 a| 
link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^]
 a| 
Fornisce maggiori informazioni sui requisiti di installazione del sistema storage.

|===