---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_migrate_from_a_switchless_cluster_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= Migrare da un cluster senza switch con storage DAT aggiungendo due nuovi switch condivisi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




==== Migrazione da un cluster senza switch con storage DAT

Quando si esegue la migrazione di un cluster senza switch a due nodi a un cluster con switch cluster Cisco Nexus 9336C-FX2, è necessario conoscere alcune informazioni di configurazione, le connessioni delle porte e i requisiti di cablaggio. La procedura da seguire dipende dalla presenza di due porte cluster-network dedicate su ciascun controller o di una singola porta cluster su ciascun controller. Il processo documentato funziona per tutti i nodi che utilizzano porte ottiche o Twinax, ma non è supportato su questo switch se i nodi utilizzano porte RJ45 10GB BASE-T integrate per le porte di rete del cluster.

La maggior parte dei sistemi richiede due porte cluster-network dedicate su ciascun controller. Vedere  https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"] per ulteriori informazioni.

Se si dispone di un ambiente cluster senza switch a due nodi, è possibile migrare a un ambiente cluster con switch a due nodi utilizzando gli switch Cisco Nexus 9336C-FX2 per consentire la scalabilità oltre due nodi nel cluster.

.Prima di iniziare
* Configurazione senza switch a due nodi:
+
** La configurazione senza switch a due nodi deve essere configurata e funzionante correttamente.
** I nodi devono eseguire ONTAP 9.8 e versioni successive.
** Tutte le porte del cluster devono trovarsi nello stato *up*.
** Tutte le interfacce logiche del cluster (LIFF) devono trovarsi nello stato *up* e sulle porte *home*.


* Configurazione dello switch Cisco Nexus 9336C-FX2:
+
** Entrambi gli switch devono disporre di connettività di rete di gestione.
** Gli switch del cluster devono essere accessibili dalla console.
** Le connessioni tra switch nodo-nodo e switch-to-switch Nexus 9336C-FX2 devono utilizzare cavi Twinax o in fibra.
** NetApp https://hwu.netapp.com["Hardware Universe"] contiene ulteriori informazioni sul cablaggio.
** I cavi ISL (Inter-Switch link) devono essere collegati alle porte 1/35 e 1/36 su entrambi gli switch 9336C-FX2.


* La personalizzazione iniziale degli switch 9336C-FX2 deve essere completata. In modo che:
+
** Gli switch 9336C-FX2 utilizzano la versione software più recente
** I file di configurazione di riferimento (RCF) sono stati applicati agli switch
** Qualsiasi personalizzazione del sito, ad esempio SMTP, SNMP e SSH, deve essere configurata sui nuovi switch.




.A proposito di questa attività
Gli esempi di questa procedura utilizzano la seguente nomenclatura di nodi e switch del cluster:

* I nomi degli switch 9336C-FX2 sono _cs1_ e _cs2_.
* I nomi delle SVM del cluster sono _node1_ e _node2_.
* I nomi delle LIF sono rispettivamente _node1_clus1_ e _node1_clus2_ sul nodo 1 e _node2_clus1_ e _node2_clus2_ sul nodo 2.
* Il prompt cluster1::*> indica il nome del cluster.
* Le porte del cluster utilizzate in questa procedura sono _e3a_ e _e3b_, in base al controller A400 AFF. Il https://hwu.netapp.com["Hardware Universe"] contiene le informazioni più recenti sulle porte cluster effettive per le piattaforme in uso.


.Fasi
. Se AutoSupport è attivato su questo cluster, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:  `system node autosupport invoke -node * -type all -message MAINT=xh`.
+
dove x è la durata della finestra di manutenzione in ore.




NOTE: Il messaggio AutoSupport informa il supporto tecnico di questa attività di manutenzione in modo che la creazione automatica del caso venga soppressa durante la finestra di manutenzione.

. [[step2]]impostare il livello di privilegio su Advanced (avanzato), immettendo y quando viene richiesto di continuare:
`set -privilege advanced`
+
Viene visualizzato il prompt Advanced (*>).

. Disattivare tutte le porte rivolte ai nodi (non le porte ISL) su entrambi i nuovi switch del cluster cs1 e cs2. Non è necessario disattivare le porte ISL.
+
L'esempio seguente mostra che le porte rivolte al nodo da 1 a 34 sono disattivate sullo switch cs1:



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e/1-34
cs1(config-if-range)# shutdown
----
. [[step4]]verificare che le porte ISL e fisiche dell'ISL tra i due switch 9336C-FX2 cs1 e cs2 siano installate sulle porte 1/35 e 1/36:
`show port-channel summary`
+
L'esempio seguente mostra che le porte ISL sono installate sullo switch cs1:



[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
L'esempio seguente mostra che le porte ISL sono installate sullo switch cs2:

[listing]
----
       cs2# show port-channel summary
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
. [[step5]]Visualizza l'elenco dei dispositivi vicini:
`show cdp neighbors`.
+
Questo comando fornisce informazioni sui dispositivi collegati al sistema. Nell'esempio riportato di seguito sono elencati i dispositivi adiacenti sullo switch cs1:



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
Nell'esempio riportato di seguito sono elencati i dispositivi adiacenti sullo switch cs2:

[listing]
----
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
. [[step6]]verificare che tutte le porte del cluster siano in funzione:
`network port show - ipspace Cluster`
+
Ogni porta deve visualizzare link e Healthy for Health Status:



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
. [[step7]]verificare che tutte le LIF del cluster siano operative:
`network interface show - vserver Cluster`
+
Ogni LIF del cluster dovrebbe visualizzare true per `Is Home` E avere uno stato Admin/Oper di up/up.



[listing]
----
cluster1::*> network interface show -vserver Cluster
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
. [[step8]]verificare che l'autorevert sia attivato su tutte le LIF del cluster:
`network interface show - vserver Cluster -fields auto-revert`


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
. [[step9]]scollegare il cavo dalla porta del cluster e3a sul nodo 1, quindi collegare e3a alla porta 1 sullo switch del cluster cs1, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
+
NetApp https://hwu.netapp.com["Hardware Universe"] contiene ulteriori informazioni sul cablaggio.

. Scollegare il cavo dalla porta del cluster e3a sul nodo 2, quindi collegare e3a alla porta 2 sullo switch del cluster cs1, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
. Abilitare tutte le porte rivolte ai nodi sullo switch cluster cs1.
+
L'esempio seguente mostra che le porte da 1/1 a 1/34 sono attivate sullo switch cs1:



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1-34
cs1(config-if-range)# no shutdown
----
. [[step12]]verificare che tutte le LIF del cluster siano *up*, operative e visualizzate come vere per `Is Home`:
`network interface show - vserver Cluster`
+
L'esempio seguente mostra che tutti i LIF sono *up* su node1 e node2 e questo `Is Home` i risultati sono *true*:



[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
. [[step13]]Visualizza informazioni sullo stato dei nodi nel cluster:
`cluster show`
+
Nell'esempio seguente vengono visualizzate informazioni sullo stato e sull'idoneità dei nodi nel cluster:



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. [[step14]]scollegare il cavo dalla porta del cluster e3b sul nodo 1, quindi collegare e3b alla porta 1 sullo switch del cluster cs2, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
. Scollegare il cavo dalla porta del cluster e3b sul nodo 2, quindi collegare e3b alla porta 2 sullo switch del cluster cs2, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
. Abilitare tutte le porte rivolte ai nodi sullo switch cluster cs2.
+
L'esempio seguente mostra che le porte da 1/1 a 1/34 sono attivate sullo switch cs2:



[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1-34
cs2(config-if-range)# no shutdown
----
. [[step17]]verificare che tutte le porte del cluster siano in funzione:
`network port show - ipspace Cluster`
+
L'esempio seguente mostra che tutte le porte del cluster sono su node1 e node2:



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
. [[step18]]verificare che tutte le interfacce visualizzino true per `Is Home`:
`network interface show - vserver Cluster`



NOTE: Il completamento di questa operazione potrebbe richiedere alcuni minuti.

L'esempio seguente mostra che tutte le LIF sono *up* su node1 e node2 e questo `Is Home` i risultati sono veri:

[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
. [[step19]]verificare che entrambi i nodi dispongano di una connessione a ciascuno switch:
`show cdp neighbors`
+
L'esempio seguente mostra i risultati appropriati per entrambi gli switch:



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
. [[step20]]Visualizza informazioni sui dispositivi di rete rilevati nel cluster:
`network device-discovery show -protocol cdp`


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
. [[step21]]verificare che la configurazione dello storage della coppia ha 1 (e della coppia ha 2) sia corretta e priva di errori:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step22]]verificare che le impostazioni siano disattivate:
`network options switchless-cluster show`



NOTE: Il completamento del comando potrebbe richiedere alcuni minuti. Attendi l'annuncio "3-minute lifetime to exceed" (3 minuti di scadenza).

Il `false` l'output dell'esempio seguente mostra che le impostazioni di configurazione sono disattivate:

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
. [[step23]]verificare lo stato dei membri del nodo nel cluster:
`cluster show`
+
L'esempio seguente mostra informazioni sullo stato e sull'idoneità dei nodi nel cluster:



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. [[step24]]assicurarsi che la rete del cluster disponga di connettività completa:
`cluster ping-cluster -node node-name`


[listing]
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
...
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
...
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step25]]Cambia di nuovo il livello di privilegio in admin:
`set -privilege admin`
. Attivare la funzione di raccolta dei log dello switch Ethernet per la raccolta dei file di log relativi allo switch, utilizzando i comandi seguenti:
+
** `system switch ethernet log setup-password`
** `system switch ethernet log enable-collection`




[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.

Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----


==== Configurare lo switch condiviso

Gli esempi di questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch condivisi sono _sh1_ e _sh2_.
* I nodi sono _node1_ e _node2_.



NOTE: La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 9000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.

.Fasi
. Verificare che la configurazione dello storage della coppia ha 1 (e della coppia ha 2) sia corretta e priva di errori:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step2]]verificare che le porte del nodo di storage siano funzionanti e funzionanti:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step3]]spostare le porte ha Pair 1, NSM224 PATH A nell'intervallo di porte sh1 11-22.
. Installare un cavo dalla coppia ha 1, nodo 1, percorso A all'intervallo di porte sh1 11-22. Ad esempio, il percorso Di Una porta di storage su un AFF A400 è e0c.
. Installare un cavo dalla coppia ha 1, nodo 2, percorso A all'intervallo di porte sh1 11-22.
. Verificare che le porte dei nodi siano funzionanti e funzionanti:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step7]]verificare che non vi siano problemi relativi allo switch di storage o al cablaggio del cluster:
`system health alert show -instance`


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step8]]spostare la coppia ha 1, le porte NSM224 percorso B nell'intervallo di porte sh2 11-22.
. Installare un cavo dalla coppia ha 1, nodo 1, percorso B alla gamma di porte sh2 11-22. Ad esempio, la porta di storage del percorso B su un sistema AFF A400 è e5b.
. Installare un cavo dalla coppia ha 1, nodo 2, percorso B alla gamma di porte sh2 11-22.
. Verificare che le porte dei nodi siano funzionanti e funzionanti:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step12]]verificare che la configurazione dello storage della coppia ha 1 sia corretta e priva di errori:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step13]]riconfigurare le porte di storage secondario (controller) inutilizzate sulla coppia ha 1 dallo storage alla rete. Se più di un NS224 è stato collegato direttamente, ci saranno porte che devono essere riconfigurate.


[listing]
----
storage port modify –node [node name] –port [port name] –mode network
----
Per inserire le porte di storage in un dominio di broadcast:

* `network port broadcast-domain create` (per creare un nuovo dominio, se necessario)
* `network port broadcast-domain add-ports` (per aggiungere porte a un dominio esistente)


. [[step14]]se è stata eliminata la creazione automatica del caso, riattivarla richiamando un messaggio AutoSupport:
`system node autosupport invoke -node * -type all -message MAINT=END`

