---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/components-9336c-shared.html 
keywords: shared storage cluster switch 
summary: A partire da ONTAP 9.9.1, è possibile utilizzare gli switch Cisco Nexus 9336C-FX2 per combinare funzionalità di storage e cluster in uno scenario di switch condiviso. 
---
= Componenti e numeri di parte per gli switch condivisi Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 9336C-FX2, assicurarsi di consultare l'elenco dei componenti e i codici articolo.

Nella tabella seguente sono elencati il codice articolo e la descrizione dello switch 9336C-FX2, delle ventole e degli alimentatori:

|===
| Numero di parte | Descrizione 


| X190200-CS-PE | N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28 


| X190200-CS-PI | N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28 


| X190002 | Kit accessori X190001/X190003 


| X-NXA-PAC-1100W-PE2 | Alimentatore N9K-9336C AC 1100W - Flusso d'aria di scarico lato sinistro 


| X-NXA-PAC-1100W-PI2 | Alimentatore CA N9K-9336C da 1100 W - Flusso d'aria di aspirazione lato sinistro 


| X-NXA-FAN-65CFM-PE | N9K-9336C 65CFM, flusso d'aria di scarico lato babordo 


| X-NXA-FAN-65CFM-PI | N9K-9336C 65CFM, flusso d'aria di aspirazione lato sinistro 
|===
.Cosa c'è dopo?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-9336c-shared.html["documentazione richiesta"].
