---
permalink: switch-cisco-9336c-fx2-shared/configure-switch-overview-9336c-shared.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: 'Panoramica dell"installazione e della configurazione degli switch condivisi Cisco Nexus 9336C-FX2' 
---
= Panoramica dell'installazione e della configurazione degli switch condivisi Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo switch condiviso Cisco Nexus 9336C-FX2 fa parte della piattaforma Cisco Nexus 9000 e può essere installato in un cabinet di sistema NetApp. Gli switch condivisi consentono di combinare funzionalità di cluster e storage in una configurazione di switch condivisa, supportando l'utilizzo di file di configurazione di riferimento di cluster e storage condivisi.



== Panoramica della configurazione iniziale

Per configurare inizialmente uno switch Cisco Nexus 9336C-FX2 su sistemi che eseguono ONTAP, attenersi alla seguente procedura:

. link:cable-9336c-shared.html["Completare il foglio di lavoro per il cablaggio"].
. link:install-9336c-shared.html["Installare lo switch"].
. link:setup-and-configure-9336c-shared.html["Configurare lo switch"].
. link:install-switch-and-passthrough-panel-9336c-shared.html["Installare lo switch in un armadio NetApp"].
. link:prepare-nxos-rcf-9336c-shared.html["Preparare l'installazione di NX-OS e RCF"].
. link:install-nxos-software-9336c-shared.html["Installare il software NX-OS"].
. link:install-nxos-rcf-9336c-shared.html["Installare il file di configurazione RCF"].
. link:configure-ssh.html["Abilitare SSH"].




== Ulteriori informazioni

Prima di iniziare l'installazione o la manutenzione, verificare quanto segue:

* link:configure-reqs-9336c-shared.html["Requisiti di configurazione"]
* link:components-9336c-shared.html["Componenti e numeri di parte"]
* link:required-documentation-9336c-shared.html["Documentazione richiesta"]

