---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/configure-reqs-9336c-shared.html 
keywords: shared storage cluster switch 
summary: A partire da ONTAP 9.9.1, è possibile utilizzare gli switch Cisco Nexus 9336C-FX2 per combinare funzionalità di storage e cluster in uno scenario di switch condiviso. 
---
= Requisiti di configurazione per gli switch condivisi Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 9336C-FX2, assicurarsi di rivedere la configurazione e i requisiti di rete.



== Supporto ONTAP

A partire da ONTAP 9.9.1, è possibile utilizzare gli switch Cisco Nexus 9336C-FX2 per combinare funzionalità di storage e cluster in una configurazione di switch condivisa.

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete supportati.



== Requisiti di configurazione

Per la configurazione, è necessario disporre del numero e del tipo appropriati di cavi e connettori per i propri switch.

A seconda del tipo di switch che si sta configurando inizialmente, è necessario connettersi alla porta della console dello switch tramite il cavo della console incluso; è inoltre necessario fornire informazioni di rete specifiche.



== Requisiti di rete

Per tutte le configurazioni dello switch sono necessarie le seguenti informazioni di rete.

* Subnet IP per il traffico di rete di gestione
* Nomi host e indirizzi IP per ciascuno dei controller del sistema di archiviazione e tutti gli switch applicabili
* La maggior parte dei controller dei sistemi di storage vengono gestiti tramite l'interfaccia e0M, collegandosi alla porta di servizio Ethernet (icona a forma di chiave inglese). Nei sistemi AFF A800 e AFF A700s , l'interfaccia e0M utilizza una porta Ethernet dedicata.
* Fare riferimento al https://hwu.netapp.com["Hardware Universe"] per le ultime informazioni. Vedere link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per maggiori informazioni sui requisiti di installazione degli switch.


Per maggiori informazioni sulla configurazione iniziale dello switch, consultare la seguente guida: https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Guida all'installazione e all'aggiornamento Cisco Nexus 9336C-FX2"] .

.Cosa c'è dopo?
Dopo aver esaminato i requisiti di configurazione, puoi confermare il tuo link:components-9336c-shared.html["componenti e numeri di parte"].
