---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Installare gli switch condivisi Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Seguire queste istruzioni per configurare gli switch condivisi Cisco Nexus 9336C-FX2.

.Prima di iniziare
Assicurati di avere quanto segue:

* Documentazione richiesta per lo switch condiviso, la documentazione del controller e la documentazione ONTAP .  Vederelink:required-documentation-9336c-shared.html["Requisiti di documentazione per gli switch condivisi Cisco Nexus 9336C-FX2"] E https://docs.netapp.com/us-en/ontap/index.html["Documentazione NetApp ONTAP"^] .
* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Schede di lavoro sui cablaggi completate. Vederelink:cable-9336c-shared.html["Completa il foglio di lavoro sul cablaggio Cisco Nexus 9336C-FX2"] .  Per maggiori informazioni sul cablaggio, fare riferimento a https://hwu.netapp.com["Hardware Universe"] .


.Passi
. Installare gli switch, i controller e gli scaffali di archiviazione NS224 NVMe.
+
Vedi illink:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Istruzioni per il montaggio"] per imparare come installare lo switch in un cabinet NetApp .

. Accendere gli switch, i controller e gli scaffali di archiviazione NVMe NS224.


.Cosa succederà ora?
Facoltativamente, puoi link:install-switch-and-passthrough-panel-9336c-shared.html["installare uno switch Cisco Nexus 9336C-FX2 in un cabinet NetApp"]. Altrimenti vai a link:setup-and-configure-9336c-shared.html["Configurare l'interruttore"].
