---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= Migrazione da un cluster switchless con storage collegato direttamente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile migrare da un cluster switchless con storage collegato direttamente aggiungendo due nuovi switch condivisi.

La procedura da utilizzare varia a seconda che si disponga di due porte di rete cluster dedicate su ciascun controller o di una singola porta cluster su ciascun controller.  Il processo documentato funziona per tutti i nodi che utilizzano porte ottiche o Twinax, ma non è supportato su questo switch se i nodi utilizzano porte RJ45 BASE-T da 10 Gb integrate per le porte della rete cluster.

La maggior parte dei sistemi richiede due porte di rete cluster dedicate su ciascun controller. Vedere https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"] per maggiori informazioni.

Se si dispone di un ambiente cluster switchless a due nodi esistente, è possibile migrare a un ambiente cluster switchato a due nodi utilizzando gli switch Cisco Nexus 9336C-FX2 per poter scalare oltre due nodi nel cluster.



== Requisiti di revisione

Assicurarsi che:

* Per la configurazione switchless a due nodi:
+
** La configurazione switchless a due nodi è correttamente configurata e funzionante.
** I nodi eseguono ONTAP 9.8 e versioni successive.
** Tutte le porte del cluster sono nello stato *attivo*.
** Tutte le interfacce logiche del cluster (LIF) sono nello stato *attivo* e sulle loro porte *home*.


* Per la configurazione dello switch Cisco Nexus 9336C-FX2:
+
** Entrambi gli switch dispongono di connettività di rete di gestione.
** È disponibile l'accesso alla console per gli switch del cluster.
** Le connessioni da nodo a nodo e da switch a switch del Nexus 9336C-FX2 utilizzano cavi Twinax o in fibra.
** NetApp https://hwu.netapp.com["Hardware Universe"] contiene maggiori informazioni sul cablaggio.
** I cavi Inter-Switch Link (ISL) sono collegati alle porte 1/35 e 1/36 su entrambi gli switch 9336C-FX2.


* La personalizzazione iniziale degli switch 9336C-FX2 è stata completata.  In modo che:
+
** Gli switch 9336C-FX2 eseguono l'ultima versione del software
** I file di configurazione di riferimento (RCF) sono stati applicati agli switch
** Sui nuovi switch è possibile configurare qualsiasi personalizzazione del sito, ad esempio SMTP, SNMP e SSH.






== Migrare gli switch

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di cluster switch e nodi:

* I nomi degli switch 9336C-FX2 sono _cs1_ e _cs2_.
* I nomi degli SVM del cluster sono _node1_ e _node2_.
* I nomi dei LIF sono _node1_clus1_ e _node1_clus2_ sul nodo 1, e _node2_clus1_ e _node2_clus2_ sul nodo 2, rispettivamente.
* Il prompt cluster1::*> indica il nome del cluster.
* Le porte cluster utilizzate in questa procedura sono _e3a_ e _e3b_, come per il controller AFF A400 .  IL https://hwu.netapp.com["Hardware Universe"] contiene le informazioni più recenti sulle porte cluster effettive per le tue piattaforme.




=== Passaggio 1: Migrazione da un cluster switchless con collegamento diretto

. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh` .
+
dove x è la durata della finestra di manutenzione in ore.




NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

. [[step2]]Modifica il livello di privilegio in avanzato, immettendo y quando richiesto per continuare:
+
`set -privilege advanced`

+
Viene visualizzato il prompt avanzato (*>).

. Disabilitare tutte le porte rivolte verso il nodo (non le porte ISL) su entrambi i nuovi switch del cluster cs1 e cs2.  Non è consentito disattivare le porte ISL.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1 a 34 rivolte al nodo sono disabilitate sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]]Verificare che l'ISL e le porte fisiche sull'ISL tra i due switch 9336C-FX2 cs1 e cs2 siano attivi sulle porte 1/35 e 1/36:
+
`show port-channel summary`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte ISL sono attive sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
L'esempio seguente mostra che le porte ISL sono attive sullo switch cs2:

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]]Visualizza l'elenco dei dispositivi vicini:
+
`show cdp neighbors`

+
Questo comando fornisce informazioni sui dispositivi collegati al sistema.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente elenca i dispositivi adiacenti sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
L'esempio seguente elenca i dispositivi adiacenti sullo switch cs2:

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[step6]]Verificare che tutte le porte del cluster siano attive:
+
`network port show - ipspace Cluster`

+
Ogni porta dovrebbe essere visualizzata come attiva per Collegamento e come integra per Stato di integrità.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[step7]]Verificare che tutti i cluster LIF siano attivi e operativi:
+
`network interface show - vserver Cluster`

+
Ogni cluster LIF dovrebbe visualizzare true per `Is Home` e avere uno stato Admin/Oper di up/up.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[step8]]Verificare che il ripristino automatico sia abilitato su tutti i LIF del cluster:
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]Scollegare il cavo dalla porta e3a del cluster sul nodo 1, quindi collegare e3a alla porta 1 sullo switch cs1 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
+
NetApp https://hwu.netapp.com["Hardware Universe"] contiene maggiori informazioni sul cablaggio. Vedere link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per maggiori informazioni sui requisiti di installazione degli switch.

. Scollegare il cavo dalla porta e3a del cluster sul nodo 2, quindi collegare e3a alla porta 2 sullo switch cs1 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
. Abilitare tutte le porte rivolte verso il nodo sullo switch del cluster cs1.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1/1 a 1/34 sono abilitate sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]Verificare che tutti i cluster LIF siano *attivi*, operativi e visualizzati come veri per `Is Home` :
+
`network interface show - vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutti i LIF sono *attivi* su node1 e node2 e che `Is Home` i risultati sono *veri*:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]Visualizza informazioni sullo stato dei nodi nel cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra informazioni sullo stato di integrità e sull'idoneità dei nodi nel cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]Scollegare il cavo dalla porta e3b del cluster sul nodo 1, quindi collegare e3b alla porta 1 sullo switch cs2 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
. Scollegare il cavo dalla porta e3b del cluster sul nodo 2, quindi collegare e3b alla porta 2 sullo switch cs2 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 9336C-FX2.
. Abilitare tutte le porte rivolte verso il nodo sullo switch cluster cs2.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1/1 a 1/34 sono abilitate sullo switch cs2:

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]Verificare che tutte le porte del cluster siano attive:
+
`network port show - ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutte le porte del cluster sono attive su node1 e node2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]Verificare che tutte le interfacce visualizzino true per `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: L'operazione potrebbe richiedere diversi minuti.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutti i LIF sono *attivi* su node1 e node2 e che `Is Home` i risultati sono veri:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]Verificare che entrambi i nodi abbiano una connessione a ciascun switch:
+
`show cdp neighbors`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra i risultati appropriati per entrambi gli switch:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]Visualizza informazioni sui dispositivi di rete rilevati nel tuo cluster:
+
`network device-discovery show -protocol cdp`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]Verificare che la configurazione di archiviazione della coppia HA 1 (e della coppia HA 2) sia corretta e priva di errori:
+
`system switch ethernet show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]Verificare che le impostazioni siano disabilitate:
+
`network options switchless-cluster show`

+

NOTE: Il completamento del comando potrebbe richiedere diversi minuti.  Attendi l'annuncio "Scadenza della durata di 3 minuti".

+
IL `false` l'output nell'esempio seguente mostra che le impostazioni di configurazione sono disabilitate:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]Verificare lo stato dei membri del nodo nel cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra informazioni sullo stato di integrità e sull'idoneità dei nodi nel cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step25]] Ripristina il livello di privilegio su amministratore:
+
`set -privilege admin`





=== Passaggio 2: configurare lo switch condiviso

Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch condivisi sono _sh1_ e _sh2_.
* I nodi sono _node1_ e _node2_.



NOTE: La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 9000. Salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

. Verificare che la configurazione di archiviazione della coppia HA 1 (e della coppia HA 2) sia corretta e priva di errori:
+
`system switch ethernet show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Verificare che le porte del nodo di archiviazione siano integre e operative:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]Spostare la coppia HA 1, porte del percorso A NSM224 sull'intervallo di porte sh1 11-22.
. Installare un cavo dalla coppia HA 1, nodo 1, percorso A alla porta sh1, intervallo 11-22.  Ad esempio, il percorso A della porta di archiviazione su un AFF A400 è e0c.
. Installare un cavo dalla coppia HA 1, nodo 2, percorso A alla porta sh1, intervallo 11-22.
. Verificare che le porte del nodo siano funzionanti e funzionanti:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verificare che non vi siano problemi di cablaggio o di switch di archiviazione nel cluster:
+
`system health alert show -instance`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Spostare la coppia HA 1, porte del percorso B NSM224 sull'intervallo di porte sh2 11-22.
. Installare un cavo dalla coppia HA 1, nodo 1, percorso B all'intervallo di porte sh2 11-22.  Ad esempio, la porta di archiviazione del percorso B su un AFF A400 è e5b.
. Installare un cavo dalla coppia HA 1, nodo 2, percorso B all'intervallo di porte sh2 11-22.
. Verificare che le porte del nodo siano funzionanti e funzionanti:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verificare che la configurazione di archiviazione della coppia HA 1 sia corretta e priva di errori:
+
`system switch ethernet show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Riconfigurare le porte di archiviazione secondaria (controller) non utilizzate sulla coppia HA 1 da archiviazione a rete.  Se è stato collegato direttamente più di un NS224, ci saranno delle porte che dovranno essere riconfigurate.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
Per posizionare le porte di archiviazione in un dominio broadcast:

+
** `network port broadcast-domain create`(per creare un nuovo dominio, se necessario)
** `network port broadcast-domain add-ports`(per aggiungere porte a un dominio esistente)


. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
Dopo aver migrato gli switch, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
