---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrare da una configurazione commutata con storage direct-attached
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile eseguire la migrazione da una configurazione commutata con storage direct-attached aggiungendo due nuovi switch condivisi.

.Switch supportati
Sono supportati i seguenti switch:

* Nexus 9336C-FX2
* Nexus 3232C


Le versioni di ONTAP e NX-OS supportate in questa procedura si trovano nella pagina Switch Ethernet Cisco. Vedere https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"].

.Porte di connessione
Gli switch utilizzano le seguenti porte per la connessione ai nodi:

* Nexus 9336C-FX2:
+
** Porte 1- 3: Modalità di interruzione (4x10G) Porte Intra-Cluster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Porte 4- 6: Modalità breakout (4x25G) Porte Intra-Cluster/ha, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Porte 7-34: Porte Intra-Cluster/ha 40/100GbE, int e1/7-34


* Nexus 3232C:
+
** Porte 1-30: 10/40/100 GbE


* Gli switch utilizzano le seguenti porte ISL (Inter-Switch link):
+
** Porte int e1/35-36: Nexus 9336C-FX2
** Porte e1/31-32: Nexus 3232C




Il https://hwu.netapp.com["Hardware Universe"] contiene informazioni sul cablaggio supportato per tutti gli switch del cluster.

.Di cosa hai bisogno
* Assicurarsi di aver completato le seguenti attività:
+
** Alcune porte degli switch Nexus 9336C-FX2 sono configurate per funzionare a 100 GbE.
** Connettività 100 GbE pianificata, migrata e documentata dai nodi agli switch Nexus 9336C-FX2.
** Migrazione senza interruzioni di altri switch cluster Cisco da un cluster ONTAP a switch di rete Cisco Nexus 9336C-FX2.


* La rete di switch esistente è configurata e funziona correttamente.
* Tutte le porte sono nello stato *up* per garantire operazioni senza interruzioni.
* Gli switch Nexus 9336C-FX2 sono configurati e funzionano con la versione corretta di NX-OS installato e il file di configurazione di riferimento (RCF) applicato.
* La configurazione di rete esistente presenta quanto segue:
+
** Un cluster NetApp ridondante e completamente funzionale che utilizza entrambi gli switch Cisco meno recenti.
** Connettività di gestione e accesso alla console sia agli switch Cisco meno recenti che ai nuovi switch.
** Tutte le LIF del cluster nello stato *up* con le LIF del cluster si trovano sulle porte home.
** Porte ISL abilitate e cablate tra gli altri switch Cisco e tra i nuovi switch.




.A proposito degli esempi
Gli esempi di questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Gli switch cluster Cisco Nexus 3232C esistenti sono _c1_ e _c2_.
* I nuovi switch Nexus 9336C-FX2 sono _sh1_ e _sh2_.
* I nodi sono _node1_ e _node2_.
* I LIF del cluster sono _node1_clus1_ e _node1_clus2_ sul nodo 1, e _node2_clus1_ e _node2_clus2_ rispettivamente sul nodo 2.
* L'interruttore c2 viene sostituito dall'interruttore sh2, quindi l'interruttore c1 viene sostituito dall'interruttore sh1.


.Fasi
. Se AutoSupport è attivato su questo cluster, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Dove x è la durata della finestra di manutenzione in ore.

. Controllare lo stato amministrativo e operativo di ciascuna porta del cluster.
. Verificare che tutte le porte del cluster siano funzionanti:
+
`network port show –role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]verificare che tutte le interfacce del cluster (LIFF) si trovino sulla porta home:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]verificare che il cluster visualizzi le informazioni per entrambi gli switch del cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]Disattiva il ripristino automatico sulle LIF del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]Spegni lo switch c2.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]verificare che le LIF del cluster siano migrate alle porte ospitate sullo switch del cluster sh1:
+
`network interface show -role cluster`

+
Questa operazione potrebbe richiedere alcuni secondi.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]sostituire lo switch c2 con il nuovo switch sh2 e cablare nuovamente il nuovo switch.
. Verificare che le porte siano di backup su sh2. *Notare* che i LIF sono ancora sullo switch c1.
. Spegnere lo switch c1.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]verificare che le LIF del cluster siano migrate alle porte ospitate sullo switch del cluster sh2. Questa operazione potrebbe richiedere alcuni secondi.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]sostituire lo switch c1 con il nuovo switch sh1 e cablare nuovamente il nuovo switch.
. Verificare che le porte siano di backup su sh1. *Notare* che i LIF sono ancora sullo switch c2.
. Abilitare il ripristino automatico sulle LIF del cluster:
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]verificare che il cluster funzioni correttamente:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.Quali sono le prossime novità?
Dopo aver migrato gli switch, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
