---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrazione da una configurazione commutata con storage collegato direttamente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile migrare da una configurazione commutata con storage collegato direttamente aggiungendo due nuovi switch condivisi.

.Switch supportati
Sono supportati i seguenti switch:

* Nexus 9336C-FX2
* Nexus 3232C


Le versioni ONTAP e NX-OS supportate in questa procedura sono disponibili nella pagina Switch Ethernet Cisco . Vedere https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"] .

.Porte di connessione
Gli switch utilizzano le seguenti porte per connettersi ai nodi:

* Nexus 9336C-FX2:
+
** Porte 1-3: Modalità breakout (4x10G) Porte intra-cluster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Porte 4-6: Modalità breakout (4x25G) Porte intra-cluster/HA, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Porte 7-34: porte intra-cluster/HA 40/100GbE, int e1/7-34


* Nexus 3232C:
+
** Porte 1-30: 10/40/100 GbE


* Gli switch utilizzano le seguenti porte Inter-Switch Link (ISL):
+
** Porte int e1/35-36: Nexus 9336C-FX2
** Porte e1/31-32: Nexus 3232C




IL https://hwu.netapp.com["Hardware Universe"] contiene informazioni sul cablaggio supportato per tutti gli switch cluster.

.Cosa ti servirà
* Assicurati di aver completato le seguenti attività:
+
** Configurate alcune porte sugli switch Nexus 9336C-FX2 per funzionare a 100 GbE.
** Connettività 100 GbE pianificata, migrata e documentata dai nodi agli switch Nexus 9336C-FX2.
** Migrazione senza interruzioni di altri switch cluster Cisco da un cluster ONTAP agli switch di rete Cisco Nexus 9336C-FX2.


* La rete di switch esistente è correttamente configurata e funzionante.
* Tutte le porte sono in stato *attivo* per garantire operazioni senza interruzioni.
* Gli switch Nexus 9336C-FX2 sono configurati e funzionano con la versione corretta di NX-OS installata e con il file di configurazione di riferimento (RCF) applicato.
* La configurazione di rete esistente è la seguente:
+
** Un cluster NetApp ridondante e completamente funzionale che utilizza entrambi gli switch Cisco più vecchi.
** Connettività di gestione e accesso alla console sia per i vecchi switch Cisco sia per quelli nuovi.
** Tutti i cluster LIF nello stato *up* con i cluster LIF sulle loro porte home.
** Porte ISL abilitate e cablate tra gli altri switch Cisco e tra i nuovi switch.




.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Gli switch cluster Cisco Nexus 3232C esistenti sono _c1_ e _c2_.
* I nuovi switch Nexus 9336C-FX2 sono _sh1_ e _sh2_.
* I nodi sono _node1_ e _node2_.
* I LIF del cluster sono _node1_clus1_ e _node1_clus2_ sul nodo 1, e _node2_clus1_ e _node2_clus2_ sul nodo 2, rispettivamente.
* Lo switch c2 viene sostituito prima dallo switch sh2 e poi lo switch c1 viene sostituito dallo switch sh1.


.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Dove x è la durata della finestra di manutenzione in ore.

. Controllare lo stato amministrativo e operativo di ogni porta del cluster.
. Verificare che tutte le porte del cluster siano attive e integre:
+
`network port show –role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]Verificare che tutte le interfacce cluster (LIF) siano sulla porta home:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]Verificare che il cluster visualizzi le informazioni per entrambi gli switch del cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]Disabilitare il ripristino automatico sui LIF del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]Spegnere lo switch c2.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]Verificare che i LIF del cluster siano migrati alle porte ospitate sullo switch sh1 del cluster:
+
`network interface show -role cluster`

+
Potrebbero volerci alcuni secondi.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]Sostituisci l'interruttore c2 con il nuovo interruttore sh2 e ricollega il nuovo interruttore.
. Verificare che le porte siano di nuovo attive su sh2.  *Nota* che i LIF sono ancora sullo switch c1.
. Spegnere l'interruttore c1.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]Verificare che i LIF del cluster siano migrati alle porte ospitate sullo switch sh2 del cluster. Potrebbero volerci alcuni secondi.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]Sostituire l'interruttore c1 con il nuovo interruttore sh1 e ricollegare il nuovo interruttore.
. Verificare che le porte siano di nuovo attive su sh1.  *Nota* che i LIF sono ancora sullo switch c2.
. Abilita il ripristino automatico sui LIF del cluster:
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]Verificare che il cluster sia integro:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.Cosa succederà ora?
Dopo aver migrato gli switch, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
