---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/prepare-nxos-rcf-9336c-shared.html 
keywords:  
summary:  
---
= Prepararsi all'installazione del software NX-OS e RCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di installare il software NX-OS e il file di configurazione di riferimento (RCF), seguire questa procedura.

.Documentazione suggerita
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Pagina dello switch Ethernet Cisco"^]
+
Consultare la tabella di compatibilità degli switch per le versioni ONTAP e NX-OS supportate.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Guide per l'aggiornamento e il downgrade del software"^]
+
Per la documentazione completa sulle procedure di upgrade e downgrade degli switch Cisco , fare riferimento alle guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .

* link:https://www.cisco.com/c/dam/en/us/td/docs/dcn/tools/nexus-9k3k-issu-matrix/index.html["Aggiornamento Cisco Nexus 9000 e 3000 e matrice ISSU"^]
+
Fornisce informazioni sull'aggiornamento/downgrade dirompente per il software Cisco NX-OS sugli switch Nexus serie 9000 in base alle versioni correnti e di destinazione.

+
Nella pagina, seleziona *Disruptive Upgrade* e seleziona la versione corrente e quella di destinazione dall'elenco a discesa.



.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono cs1 e cs2.
* I nomi dei nodi sono cluster1-01 e cluster1-02.
* I nomi LIF del cluster sono cluster1-01_clus1 e cluster1-01_clus2 per cluster1-01 e cluster1-02_clus1 e cluster1-02_clus2 per cluster1-02.
* IL `cluster1::*>` il prompt indica il nome del cluster.


.Informazioni su questo compito
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 9000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=x h`
+
dove x è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

. Modificare il livello di privilegio in avanzato, immettendo *y* quando richiesto per continuare:
+
[source, cli]
----
set -privilege advanced
----
+
Il prompt avanzato(`*>` ) appare.

. Visualizza quante interfacce di interconnessione cluster sono configurate in ciascun nodo per ogni switch di interconnessione cluster:
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e0a    cs1                       Eth1/2            N9K-C9336C
            e0b    cs2                       Eth1/2            N9K-C9336C
cluster1-01/cdp
            e0a    cs1                       Eth1/1            N9K-C9336C
            e0b    cs2                       Eth1/1            N9K-C9336C
.
.
----
====
. Verificare lo stato amministrativo o operativo di ciascuna interfaccia del cluster, di ciascuna porta di archiviazione del nodo e di ciascuna porta dello shelf di archiviazione.
+
.. Visualizza gli attributi della porta di rete:
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: cluster1-02
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: cluster1-01
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
.
.
----
====
.. Visualizza informazioni sui LIF:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical            Status     Network            Current       Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node          Port    Home
----------- ------------------ ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01   e0a     true
            cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01   e0b     true
            cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02   e0a     true
            cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02   e0b     true
.
.
----
====
.. Verificare che tutte le porte di storage del nodo siano attive e con stato integro:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. Verificare che tutte le porte dello scaffale di archiviazione siano attive e in buono stato:
+
[source, cli]
----
storage shelf port show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verificare che gli switch siano monitorati.
+
[source, cli]
----
system switch ethernet show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
s1
                            storage-network    10.228.143.216   N9K-C9336C-FX2
     Serial Number: FDOXXXXXXB
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(6)
    Version Source: CDP/ISDP


s2
                            storage-network    10.228.143.219   N9K-C9336C-FX2
     Serial Number: FDOXXXXXXC
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(2)
    Version Source: CDP/ISDP


cs1
                            cluster-network    10.228.184.39    N9K-C9336C-FX2
     Serial Number: FLMXXXXXXXJ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(6)
    Version Source: CDP/ISDP


cs2
                            cluster-network    10.228.184.40    N9K-C9336C-FX2
     Serial Number: FLMXXXXXXXG
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(2)
    Version Source: CDP/ISDP
----
====


. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source               Destination         Packet
Node   Date                       LIF                  LIF                 Loss
------ -------------------------- -------------------- ------------------- -----------
node1
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2    cluster1-02-clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2    cluster1-02_clus2   none
node2
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2    cluster1-01_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2    cluster1-01_clus2   none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]] Verificare che il comando di ripristino automatico sia abilitato su tutti i LIF del cluster:
+
[source, cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface           Auto-revert
--------- ------------------- ------------
Cluster
          cluster1-01_clus1   true
          cluster1-01_clus2   true
          cluster1-02_clus1   true
          cluster1-02_clus2   true
----
====


.Cosa succederà ora?
Dopo esserti preparato per installare il software NX-OS e RCF, puoi link:install-nxos-software-9336c-shared.html["installare il software NX-OS"].
