---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Configurare gli switch condivisi Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Seguire queste istruzioni per configurare gli switch condivisi Cisco Nexus 9336C-FX2.

.Prima di iniziare
Assicurati di avere quanto segue:

* Documentazione richiesta per lo switch condiviso, la documentazione del controller e la documentazione ONTAP .  Vederelink:required-documentation-9336c-shared.html["Requisiti di documentazione per gli switch condivisi Cisco Nexus 9336C-FX2"] E https://docs.netapp.com/us-en/ontap/index.html["Documentazione NetApp ONTAP"^] .
* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Schede di lavoro sui cablaggi completate. Vederelink:cable-9336c-shared.html["Completa il foglio di lavoro sul cablaggio Cisco Nexus 9336C-FX2"] .  Per maggiori informazioni sul cablaggio, fare riferimento a https://hwu.netapp.com["Hardware Universe"] .


.Passi
. [[step3]]Eseguire una configurazione iniziale degli switch.
+
Per la configurazione, è necessario disporre del numero e del tipo appropriati di cavi e connettori per i propri switch.

+
A seconda del tipo di switch che si sta configurando inizialmente, è necessario connettersi alla porta della console dello switch tramite il cavo della console incluso; è inoltre necessario fornire informazioni di rete specifiche.

. Avviare lo switch.
+
Fornire le risposte appropriate alle seguenti domande sulla configurazione iniziale al primo avvio dello switch.

+
La politica di sicurezza del tuo sito definisce le risposte e i servizi da abilitare.

+
.. Interrompere il provisioning automatico e continuare con la configurazione normale?  (sì/no)
+
Rispondi con *sì*.  L'impostazione predefinita è no.

.. Vuoi applicare uno standard di password sicura?  (sì/no)
+
Rispondi con *sì*.  L'impostazione predefinita è sì.

.. Inserisci la password per l'amministratore.
+
La password predefinita è admin; è necessario crearne una nuova, più complessa.

+
Una password debole può essere rifiutata.

.. Desideri accedere alla finestra di dialogo di configurazione di base?  (sì/no)
+
Rispondere con *sì* alla configurazione iniziale dello switch.

.. Vuoi creare un altro account di accesso?  (sì/no)
+
La risposta dipende dalle policy del tuo sito relative agli amministratori alternativi.  L'impostazione predefinita è no.

.. Configurare la stringa di comunità SNMP di sola lettura?  (sì/no)
+
Rispondi con *no*.  L'impostazione predefinita è no.

.. Configurare la stringa di comunità SNMP di lettura-scrittura?  (sì/no)
+
Rispondi con *no*.  L'impostazione predefinita è no.

.. Inserisci il nome dello switch.
+
Il nome dello switch è limitato a 63 caratteri alfanumerici.

.. Continuare con la configurazione della gestione fuori banda (mgmt0)?  (sì/no)
+
Rispondere con *sì* (impostazione predefinita) a tale richiesta.  Al prompt mgmt0 IPv4 address:, inserisci il tuo indirizzo IP: ip_address

.. Configurare il gateway predefinito?  (sì/no)
+
Rispondi con *sì*.  All'indirizzo IPv4 del prompt default-gateway:, immettere default_gateway.

.. Configurare le opzioni IP avanzate?  (sì/no)
+
Rispondi con *no*.  L'impostazione predefinita è no.

.. Abilitare il servizio telnet?  (sì/no)
+
Rispondi con *no*.  L'impostazione predefinita è no.

.. Abilitare il servizio SSH?  (sì/no)
+
Rispondi con *sì*.  L'impostazione predefinita è sì.

+

NOTE: Si consiglia di utilizzare SSH quando si utilizza Ethernet Switch Health Monitor (CSHM) per le sue funzionalità di raccolta dei log.  Per una maggiore sicurezza si consiglia anche l'uso di SSHv2.

.. [[step14]]Inserisci il tipo di chiave SSH che vuoi generare (dsa/rsa/rsa1).  L'impostazione predefinita è rsa.
.. Inserire il numero di bit della chiave (1024-2048).
.. Configurare il server NTP?  (sì/no)
+
Rispondi con *no*.  L'impostazione predefinita è no.

.. Configurare il livello di interfaccia predefinito (L3/L2):
+
Rispondi con *L2*.  Il valore predefinito è L2.

.. Configura lo stato predefinito dell'interfaccia della porta dello switch (shut/noshut):
+
Rispondi con *noshut*.  L'impostazione predefinita è noshut.

.. Configurare il profilo del sistema CoPP (rigoroso/moderato/indulgente/denso):
+
Rispondi con *rigoroso*.  L'impostazione predefinita è rigorosa.

.. Vuoi modificare la configurazione?  (sì/no)
+
A questo punto dovresti vedere la nuova configurazione.  Rivedi e apporta tutte le modifiche necessarie alla configurazione appena inserita.  Se sei soddisfatto della configurazione, rispondi no al prompt.  Rispondi *sì* se desideri modificare le impostazioni di configurazione.

.. Utilizzare questa configurazione e salvarla?  (sì/no)
+
Rispondere con *sì* per salvare la configurazione.  In questo modo vengono aggiornate automaticamente le immagini di kickstart e di sistema.



. Verificare le scelte di configurazione effettuate nella schermata che appare al termine dell'installazione e assicurarsi di salvare la configurazione.
+

NOTE: Se non si salva la configurazione in questa fase, nessuna delle modifiche sarà effettiva al successivo riavvio dello switch.

. Controllare la versione sugli switch di rete del cluster e, se necessario, scaricare la versione del software supportata da NetApp sugli switch dal https://software.cisco.com/download/home["Scarica il software Cisco"^] pagina.


.Cosa succederà ora?
Dopo aver configurato gli switch, puoi link:prepare-nxos-rcf-9336c-shared.html["prepararsi a installare NX-OS e RCF"].
