---
permalink: switch-cisco-9364d-gx2a/configure-smart-call-9364d.html 
sidebar: sidebar 
keywords: cisco smart call,small call home 
summary: Per utilizzare Smart Call Home, è necessario configurare uno switch di rete cluster per comunicare tramite e-mail con il sistema Smart Call Home. Inoltre, è possibile configurare facoltativamente lo switch di rete del cluster per sfruttare la funzionalità di supporto Smart Call Home integrata di Cisco. 
---
= Configura Smart Call Home - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare Smart Call Home, è necessario configurare uno switch di rete cluster per comunicare tramite e-mail con il sistema Smart Call Home. Inoltre, è possibile configurare facoltativamente lo switch di rete del cluster per sfruttare la funzionalità di supporto Smart Call Home integrata di Cisco.

Smart Call Home di Cisco monitora i componenti hardware e software della tua rete. Quando si verifica una configurazione di sistema critica, genera una notifica via email e invia un avviso a tutti i destinatari configurati nel tuo profilo di destinazione.

[NOTE]
====
ONTAP supporta il monitoraggio dello stato di salute degli switch Ethernet (CSHM) per monitorare gli switch del cluster AFX, nonché la possibilità di raccogliere i log diagnostici degli switch.

Smart Call Home di Cisco è un'opzione che offre supporto proattivo e ti aiuta a risolvere eventuali problemi che potrebbero sorgere con gli switch.

====
Prima di poter utilizzare Smart Call Home, è necessario tenere presente i seguenti requisiti:

* Deve essere presente un server di posta elettronica.
* Lo switch deve disporre di connettività IP al server di posta elettronica.
* È necessario configurare il nome del contatto (contatto del server SNMP), il numero di telefono e le informazioni sull'indirizzo.  Ciò è necessario per determinare l'origine dei messaggi ricevuti.
* Un ID CCO deve essere associato a un contratto di servizio Cisco SMARTnet appropriato per la tua azienda.
* Per registrare il dispositivo, è necessario che sia attivo il servizio Cisco SMARTnet.


IL http://www.cisco.com/c/en/us/products/switches/index.html["Sito di supporto Cisco"^] contiene informazioni sui comandi per configurare Smart Call Home.

La funzione Smart Call Home può essere configurata durante l'installazione e la configurazione di un nuovo sistema oppure in un secondo momento.
