---
permalink: switch-cisco-9364d-gx2a/configure-review-cabling-config-requirements-9364d.html 
sidebar: sidebar 
keywords: 9364d-gx2a cabling setup, 9364d-gx2a switches configuration, nx-os 
summary: Se stai installando nuovi switch Cisco Nexus 9364D-GX2A come parte di una nuova installazione di sistema AFX 1K o AFX 2K, sostituendo uno switch o ripristinando uno switch alle impostazioni di fabbrica, devi esaminare i seguenti requisiti di cablaggio e configurazione. 
---
= Verifica i requisiti di cablaggio e configurazione - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se stai installando switch Cisco Nexus 9364D-GX2A come parte di una nuova installazione di un sistema AFX 1K o AFX 2K, stai sostituendo uno switch o stai ripristinando uno switch alle impostazioni di fabbrica, devi esaminare i seguenti requisiti di cablaggio e configurazione.



[[hard-code-the-speed-on-breakout-ports]]
== Imposta la velocità in modo fisso sulle porte breakout

Devi impostare manualmente le porte breakout dello switch (4x100GbE) su 100GbE. Se non imposti manualmente la velocità, le porte non si attiveranno e saranno in uno stato di errore disabilitato.

Ad esempio, per impostare la velocità 100GbE sulle porte breakout da 1 a 13, esegui quanto segue in modalità di configurazione. L'esempio mostra i comandi applicati al primo switch (cs1). Ripeti questi comandi per il secondo switch.

[listing, subs="+quotes"]
----
(cs1)(config)# *interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7/1-4, e1/8/1-4, e1/9/1-4, e1/10/1-4, e1/11/1-4, e1/12/1-4, e1/13/1-4*
(cs1)(config-if)# *speed 100000*
(cs1)(config-if)# *no negotiate auto*
(cs1)(config-if)# *exit*
(cs1)(config)# *exit*
(cs1)# *copy running-config startup-config*
----
.Cosa succederà ora?
Dopo aver soddisfatto i requisiti di cablaggio e configurazione, puoi link:configure-install-nxos-9364d.html["installa NX-OS"].
