---
permalink: switch-cisco-9364d-gx2a/configure-verify-ssh-9364d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: 'Se stai configurando gli switch come parte di una nuova installazione di un sistema AFX 1K o AFX 2K, di una sostituzione di uno switch o di un ripristino delle impostazioni di fabbrica, per utilizzare la funzionalità di raccolta dei log del health monitor degli switch Ethernet (CSHM), devi verificare che SSH sia abilitato sugli switch.' 
---
= Verifica SSH per la raccolta dei log - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se stai configurando gli switch come parte di una nuova installazione di un sistema AFX 1K o AFX 2K, di una sostituzione di uno switch o di un ripristino delle impostazioni di fabbrica, per utilizzare la funzionalità di raccolta dei log del health monitor degli switch Ethernet (CSHM), devi verificare che SSH sia abilitato sugli switch.

.Prima di iniziare
È necessario connettersi allo switch tramite la console seriale.

.Passi
. Verificare che SSH sia abilitato:
+
[listing, subs="+quotes"]
----
(switch) *show ssh server*
ssh version 2 is enabled
----
. Verificare che le chiavi SSH siano abilitate:
+
`show ssh key`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ssh key*

rsa Keys generated:Thu May 15 15:09:55 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCQJPZk7OGhg0j1t0NWKylnI8R8zDpuMpU6KKAjPOCShTFpibeYQqxOPTCAKACkut8dduZmc3bY9DIOle0cKYQ8PgS2mG9ovQ0RJ56RUNhVNPdJuhXM4ckHoiVJxIAbHkbcw8rzawbkT6cNBUiZY3MrOMh0e0CnMRhh9we
MOo/vQ==


bitcount:1024
fingerprint:
SHA256:TMUXFgyRC3EcIZEVbQ/P0elDByBCJizPJ1XKMkIXfPI
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Thu May 15 15:12:09 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADquZcNSDA/eLAaItXyxVZxsSJSE3u4et9B6+RLq162zTe/3A6JTCyBrkfrMhQt9QMQ7XrMqJGxLSinXhyUClBxwQD/ZbkZueZHiFuYg5hKN97wUYvts+EwpG2mSVonxKKp
atmtgu48BqKfZTc4LZYL5vgdh5uuktJ0Z8mYHt3xKPXsvw==


bitcount:521
fingerprint:
SHA256:K8LDx6L7sJjLFn8iubUhjt66uk8TYmXwnQKWVD04C1o
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====


.Cosa succederà ora?
* Dopo che hai verificato che SSH è abilitato per la raccolta dei log, link:../switch-cshm/cshm-overview.html["configura il monitoraggio dello stato di salute dello switch Ethernet"].
+
** Dopo che hai configurato il monitoraggio dello stato di salute dello switch Ethernet, se vuoi sfruttare la funzionalità di supporto Smart Call Home di Cisco, devi link:configure-smart-call-9364d.html["configurare Smart Call Home"].


* Se hai configurato lo switch nell'ambito di una nuova installazione di sistema AFX 1K o AFX 2K, devi link:install-complete-afx-setup-9364d.html["completa la configurazione del sistema AFX"].

