---
permalink: switch-cisco-9364d-gx2a/configure-complete-initial-setup-9364d.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9364d-gx2a 
summary: Dopo aver acceso gli switch Cisco Nexus 9364D-GX2A come parte di una nuova installazione di un sistema AFX 1K o AFX 2K o di una sostituzione di uno switch, oppure dopo aver ripristinato le impostazioni di fabbrica di uno switch, ti viene richiesto di completare la configurazione iniziale degli switch utilizzando la procedura guidata di configurazione. Puoi consultare le seguenti domande della procedura guidata di configurazione e le risposte consigliate per aiutarti a completare la configurazione iniziale degli switch. 
---
= Completa la configurazione iniziale dello switch - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver acceso gli switch Cisco Nexus 9364D-GX2A come parte di una nuova installazione di un sistema AFX 1K o AFX 2K o di una sostituzione di uno switch, oppure dopo aver ripristinato le impostazioni di fabbrica di uno switch, ti viene richiesto di completare la configurazione iniziale degli switch utilizzando la procedura guidata di configurazione. Puoi consultare le seguenti domande della procedura guidata di configurazione e le risposte consigliate per aiutarti a completare la configurazione iniziale degli switch.

.Prima di iniziare
Assicurati di avere le informazioni di rete e di configurazione per ogni switch e le licenze applicabili.

.Informazioni su questo compito
* Devi completare la configurazione iniziale su ogni switch.
* Se necessario, puoi consultare la documentazione della tua versione di NX-OS link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/104x/configuration/fundamentals/cisco-nexus-9000-series-nx-os-fundamentals-configuration-guide-release-104x.html["Guida alla configurazione dei concetti fondamentali di Cisco Nexus 9000 Series NX-OS"^] per informazioni sulla configurazione degli switch, che si trova nel capitolo "Using the Cisco NX-OS Setup Utility". Puoi anche trovare informazioni sulle impostazioni del terminale nel capitolo "Configuring Terminal Settings and Sessions".


.Passi
. Collega il tuo laptop alla porta seriale della console degli switch.
+
.. Impostare la porta della console seriale sul laptop a 9,600 baud con N-8-1.


. Imposta la password per l'utente admin, come richiesto.
. Completa la configurazione iniziale dello switch rispondendo alle seguenti domande.
+

NOTE: La politica di sicurezza del tuo sito definisce le risposte e i servizi da abilitare.

+
[cols="1,2"]
|===
| Richiesta | Risposta 


 a| 
Interrompere il provisioning automatico e continuare con la configurazione normale?  (sì/no)
 a| 
Rispondi con *sì*.  L'impostazione predefinita è no.



 a| 
Vuoi applicare uno standard di password sicura?  (sì/no)
 a| 
Rispondi con *sì*.  L'impostazione predefinita è sì.



 a| 
Inserisci la password per l'amministratore.
 a| 
La password predefinita è "`admin`"; è necessario crearne una nuova, più complessa.  Una password debole può essere rifiutata.



 a| 
Desideri accedere alla finestra di dialogo di configurazione di base?  (sì/no)
 a| 
Rispondere con *sì* alla configurazione iniziale dello switch.



 a| 
Vuoi creare un altro account di accesso?  (sì/no)
 a| 
La risposta dipende dalle policy del tuo sito relative agli amministratori alternativi.  L'impostazione predefinita è *no*.



 a| 
Configurare la stringa di comunità SNMP di sola lettura?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Configurare la stringa di comunità SNMP di lettura-scrittura?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Inserisci il nome dello switch.
 a| 
Immettere il nome dello switch, che è limitato a 63 caratteri alfanumerici.



 a| 
Continuare con la configurazione della gestione fuori banda (mgmt0)?  (sì/no)
 a| 
Rispondere con *sì* (impostazione predefinita) a tale richiesta.  Al prompt mgmt0 IPv4 address:, inserisci il tuo indirizzo IP: ip_address.



 a| 
Configurare il gateway predefinito?  (sì/no)
 a| 
Rispondi con *sì*.  All'indirizzo IPv4 del prompt default-gateway:, immettere default_gateway.



 a| 
Configurare le opzioni IP avanzate?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Abilitare il servizio telnet?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Servizio SSH abilitato?  (sì/no)
 a| 
Rispondi con *sì*.  L'impostazione predefinita è sì.


NOTE: Si consiglia di utilizzare SSH quando si utilizza Ethernet Switch Health Monitor (CSHM) per le sue funzionalità di raccolta dei log.  Per una maggiore sicurezza si consiglia anche l'uso di SSHv2.



 a| 
Inserisci il tipo di chiave SSH che vuoi generare (dsa/rsa/rsa1).
 a| 
Il valore predefinito è *rsa*.



 a| 
Inserire il numero di bit della chiave (1024-2048).
 a| 
Inserisci il numero di bit della chiave da 1024 a 2048.



 a| 
Configurare il server NTP?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Configurare il livello di interfaccia predefinito (L3/L2)
 a| 
Rispondi con *L2*.  Il valore predefinito è L2.



 a| 
Configura lo stato predefinito dell'interfaccia della porta dello switch (shut/noshut)
 a| 
Rispondi con *noshut*.  L'impostazione predefinita è noshut.



 a| 
Configurare il profilo del sistema CoPP (rigoroso/moderato/indulgente/denso)
 a| 
Rispondi con *rigoroso*.  L'impostazione predefinita è rigorosa.



 a| 
Vuoi modificare la configurazione?  (sì/no)
 a| 
A questo punto dovresti vedere la nuova configurazione.  Rivedi e apporta tutte le modifiche necessarie alla configurazione appena inserita.  Se sei soddisfatto della configurazione, rispondi *no* al prompt.  Rispondi *sì* se desideri modificare le impostazioni di configurazione.



 a| 
Utilizzare questa configurazione e salvarla?  (sì/no)
 a| 
Rispondere con *sì* per salvare la configurazione.  In questo modo vengono aggiornate automaticamente le immagini di kickstart e di sistema.


NOTE: Se non si salva la configurazione in questa fase, nessuna delle modifiche sarà effettiva al successivo riavvio dello switch.

|===
. Verificare le scelte di configurazione effettuate nella schermata che appare al termine dell'installazione e assicurarsi di salvare la configurazione.


.Cosa succederà ora?
Dopo che hai completato la configurazione iniziale dello switch, link:configure-review-cabling-config-requirements-9364d.html["controlla i requisiti di cablaggio e configurazione"].
