---
permalink: switch-cisco-9364d-gx2a/install-rcf-software-9364d-cluster.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 'È possibile installare l"RCF dopo aver configurato per la prima volta lo switch Nexus 9364d-gx2a.' 
---
= Installare il file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato per la prima volta lo switch Nexus 9364D-GX2A, installare il file di configurazione di riferimento (RCF).

.Prima di iniziare
Verificare le seguenti installazioni e connessioni:

* Una connessione della console allo switch.  La connessione alla console è facoltativa se si ha accesso remoto allo switch.
* Gli switch cs1 e cs2 vengono accesi e la configurazione iniziale dello switch è completata (l'indirizzo IP di gestione e SSH sono configurati).
* La versione NX-OS desiderata è stata installata.
* Le connessioni ISL tra gli switch sono connesse.
* Le porte del cluster del nodo ONTAP non sono connesse.




== Fase 1: installare l'RCF sugli switch

. Accedi per cambiare cs1 tramite SSH o tramite una console seriale.
. Copiare l'RCF nel bootflash dello switch cs1 utilizzando uno dei seguenti protocolli di trasferimento: FTP, TFTP, SFTP o SCP.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Riferimento ai comandi NX-OS della serie Cisco Nexus 9000"^] guide.

+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra come TFTP viene utilizzato per copiare un RCF nel bootflash sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9364D-GX2A-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Applicare l'RCF precedentemente scaricato al bootflash.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Riferimento ai comandi NX-OS della serie Cisco Nexus 9000"^] guide.

+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra il file RCF `NX9364D-GX2A-RCF-v10.0-Shared.txt` in fase di installazione sullo switch cs1:

[listing]
----
cs1# copy NX9364D-GX2A-RCF-v10.0-Shared.txt running-config echo-commands
----
====
. Esaminare l'output del banner dal `show banner motd` comando. Per garantire la corretta configurazione e il corretto funzionamento dello switch, è necessario leggere e seguire queste istruzioni.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9364D-GX2A
* Filename : NX9364D-GX2A-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-62: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-62}/1-4
* Ports 63-64: Intra-Cluster ISL Ports, int e1/63-64
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
*
******************************************************************************
----
====
. Verificare che il file RCF sia la versione più recente corretta:
+
`show running-config`

+
Quando controlli l'output per verificare di avere l'RCF corretto, assicurati che le seguenti informazioni siano corrette:

+
** Lo striscione RCF
** Le impostazioni del nodo e della porta
** Personalizzazioni
+
L'output varia in base alla configurazione del sito.  Controllare le impostazioni della porta e fare riferimento alle note di rilascio per eventuali modifiche specifiche all'RCF installato.



. Salva i dettagli di configurazione di base nel `write_erase.cfg` file sul bootflash.
+
[NOTE]
====
Assicurati di configurare quanto segue:

** Nome utente e password
** Indirizzo IP di gestione
** Gateway predefinito
** Cambia nome


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`

+
Vedi l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch di interconnessione Cisco mantenendo la connettività remota"^] per ulteriori dettagli.

. Verificare che il `write_erase.cfg` il file è popolato come previsto:
+
`*show file bootflash:write_erase.cfg*`

. Emettere il `write erase` comando per cancellare la configurazione salvata corrente:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copiare la configurazione di base salvata in precedenza nella configurazione di avvio.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Riavviare lo switch:
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Ripetere i passaggi da 1 a 10 sullo switch cs2.
. Collegare le porte di tutti i nodi del cluster ONTAP agli switch cs1 e cs2.




== Passaggio 2: verificare le connessioni dello switch

. Verificare che le porte dello switch collegate alle porte del cluster siano attive:
+
`show interface brief`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
----
====
. Verificare che i nodi del cluster si trovino nelle VLAN del cluster corrette utilizzando i seguenti comandi:
+
`show vlan brief`

+
`show interface trunk`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/63, Eth1/64
                                                Eth1/65, Eth1/66, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
                                                Eth1/2/1, Eth1/2/2, Eth1/2/3
                                                Eth1/2/4, Eth1/3/1, Eth1/3/2
                                                Eth1/3/3, Eth1/3/4, Eth1/4/1
                                                Eth1/4/2, Eth1/4/3, Eth1/4/4
                                                Eth1/5/1, Eth1/5/2, Eth1/5/3
                                                Eth1/5/4, Eth1/6/1, Eth1/6/2
                                                Eth1/6/3, Eth1/6/4, Eth1/7/1
                                                Eth1/7/2, Eth1/7/3, Eth1/7/4
                                                Eth1/8/1, Eth1/8/2, Eth1/8/3
                                                Eth1/8/4, Eth1/9/1, Eth1/9/2
                                                Eth1/9/3, Eth1/9/4, Eth1/10/1
                                                Eth1/10/2, Eth1/10/3, Eth1/10/4
                                                Eth1/11/1, Eth1/11/2, Eth1/11/3
                                                Eth1/11/4, Eth1/12/1, Eth1/12/2
                                                Eth1/12/3, Eth1/12/4, Eth1/13/1
                                                Eth1/13/2, Eth1/13/3, Eth1/13/4
                                                Eth1/14/1, Eth1/14/2, Eth1/14/3
                                                Eth1/14/4, Eth1/15/1, Eth1/15/2
                                                Eth1/15/3, Eth1/15/4, Eth1/16/1
                                                Eth1/16/2, Eth1/16/3, Eth1/16/4
                                                Eth1/17/1, Eth1/17/2, Eth1/17/3
                                                Eth1/17/4, Eth1/18/1, Eth1/18/2
                                                Eth1/18/3, Eth1/18/4, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
                                                Eth1/28/2, Eth1/28/3, Eth1/28/4
                                                Eth1/29/1, Eth1/29/2, Eth1/29/3
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4, Eth1/31/1
                                                Eth1/31/2, Eth1/31/3, Eth1/31/4
                                                Eth1/32/1, Eth1/32/2, Eth1/32/3
                                                Eth1/32/4, Eth1/33/1, Eth1/33/2
                                                Eth1/33/3, Eth1/33/4, Eth1/34/1
                                                Eth1/34/2, Eth1/34/3, Eth1/34/4
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4, Eth1/36/1, Eth1/36/2
                                                Eth1/36/3, Eth1/36/4, Eth1/37/1
                                                Eth1/37/2, Eth1/37/3, Eth1/37/4
                                                Eth1/38/1, Eth1/38/2, Eth1/38/3
                                                Eth1/38/4, Eth1/39/1, Eth1/39/2
                                                Eth1/39/3, Eth1/39/4, Eth1/40/1
                                                Eth1/40/2, Eth1/40/3, Eth1/40/4
                                                Eth1/41/1, Eth1/41/2, Eth1/41/3
                                                Eth1/41/4, Eth1/42/1, Eth1/42/2
                                                Eth1/42/3, Eth1/42/4, Eth1/43/1
                                                Eth1/43/2, Eth1/43/3, Eth1/43/4
                                                Eth1/44/1, Eth1/44/2, Eth1/44/3
                                                Eth1/44/4, Eth1/45/1, Eth1/45/2
                                                Eth1/45/3, Eth1/45/4, Eth1/46/1
                                                Eth1/46/2, Eth1/46/3, Eth1/46/4
                                                Eth1/47/1, Eth1/47/2, Eth1/47/3
                                                Eth1/47/4, Eth1/48/1, Eth1/48/2
                                                Eth1/48/3, Eth1/48/4, Eth1/49/1
                                                Eth1/49/2, Eth1/49/3, Eth1/49/4
                                                Eth1/50/1, Eth1/50/2, Eth1/50/3
                                                Eth1/50/4, Eth1/51/1, Eth1/51/2
                                                Eth1/51/3, Eth1/51/4, Eth1/52/1
                                                Eth1/52/2, Eth1/52/3, Eth1/52/4
                                                Eth1/53/1, Eth1/53/2, Eth1/53/3
                                                Eth1/53/4, Eth1/54/1, Eth1/54/2
                                                Eth1/54/3, Eth1/54/4, Eth1/55/1
                                                Eth1/55/2, Eth1/55/3, Eth1/55/4
                                                Eth1/56/1, Eth1/56/2, Eth1/56/3
                                                Eth1/56/4, Eth1/57/1, Eth1/57/2
                                                Eth1/57/3, Eth1/57/4, Eth1/58/1
                                                Eth1/58/2, Eth1/58/3, Eth1/58/4
                                                Eth1/59/1, Eth1/59/2, Eth1/59/3
                                                Eth1/59/4, Eth1/60/1, Eth1/60/2
                                                Eth1/60/3, Eth1/60/4, Eth1/61/1
                                                Eth1/61/2, Eth1/61/3, Eth1/61/4
                                                Eth1/62/1, Eth1/62/2, Eth1/62/3
                                                Eth1/62/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4

cs1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/62/2     none
Eth1/62/3     none
Eth1/62/4     none
Eth1/63       none
Eth1/64       none
Po1           1
----
====
+

NOTE: Per informazioni specifiche sull'utilizzo di porte e VLAN, fare riferimento alla sezione banner e note importanti nel RCF.

. Verificare che l'ISL tra cs1 e cs2 sia funzionante:
+
[source, cli]
----
show port-channel summary
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/63(P)   Eth1/64(P)
999   Po999(SD)   Eth      NONE      --
cs1#
----
====




== Passaggio 3: configura il tuo cluster ONTAP

NetApp consiglia di utilizzare System Manager per configurare nuovi cluster.

System Manager fornisce un flusso di lavoro semplice e facile per l'impostazione e la configurazione del cluster, tra cui l'assegnazione di un indirizzo IP di gestione del nodo, l'inizializzazione del cluster, la creazione di un livello locale, la configurazione dei protocolli e il provisioning dello storage iniziale.

Vai a https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurare ONTAP su un nuovo cluster con System Manager"] per le istruzioni di installazione.

.Cosa succederà ora?
Dopo aver installato l'RCF, link:configure-ssh-keys.html["verificare la configurazione SSH"].
