---
permalink: switch-cisco-9364d-gx2a/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: install, upgarde, cluster, switch, cisco 9364d-gx2a 
summary: 'È possibile installare l"RCF dopo aver configurato per la prima volta lo switch Nexus 9364d-gx2a. Puoi usare questa procedura anche per aggiornare il tuo RCF.' 
---
= Panoramica sull'installazione o l'aggiornamento del file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato per la prima volta lo switch Nexus 9364D-GX2A, installare il file di configurazione di riferimento (RCF). È possibile aggiornare la versione RCF quando sullo switch è installata una versione esistente del file RCF.

Vedi l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch di interconnessione Cisco mantenendo la connettività remota"^] per ulteriori informazioni sull'installazione o l'aggiornamento del tuo RCF.

.Configurazione RCF disponibile
* *Cluster-HA-Storage* - Supporta il traffico cluster/HA/storage condiviso sulle porte (NX9364D-GX2A-RCF-v10.0-Shared.txt).


Per informazioni specifiche sull'utilizzo di porte e VLAN, fare riferimento alla sezione banner e note importanti nel RCF.

.Documentazione suggerita
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco (NSS)"^]
+
Consultare la tabella di compatibilità degli switch per le versioni ONTAP e RCF supportate sul sito di supporto NetApp .  Si noti che possono esserci dipendenze tra la sintassi dei comandi nella RCF e la sintassi presente in versioni specifiche di NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Switch Cisco Nexus serie 3=9000"^]
+
Per la documentazione completa sulle procedure di upgrade e downgrade degli switch Cisco , fare riferimento alle guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .



.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono cs1 e cs2.
* I nomi dei nodi sono node1-01, node1-02, node1-03 e node1-04.
* I nomi LIF del cluster sono node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 e node1-04_clus2.
* IL `cluster1::*>` il prompt indica il nome del cluster.


Vedi il https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte cluster corrette sulle tue piattaforme.


NOTE: Gli output dei comandi potrebbero variare a seconda delle diverse versioni di ONTAP.

.Comandi utilizzati
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 9000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

.Cosa succederà ora?
Dopo aver esaminato la procedura di installazione o aggiornamento RCF, è possibilelink:install-rcf-software-9364d-cluster.html["installare l'RCF"] Olink:upgrade-rcf-software-9364d-cluster.html["aggiorna il tuo RCF"] come richiesto.
