---
permalink: switch-cisco-9364d-gx2a/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: install, upgarde, cluster, switch, cisco 9364d-gx2a 
summary: 'È possibile installare l"RCF dopo aver configurato per la prima volta lo switch Nexus 9364d-gx2a. Puoi usare questa procedura anche per aggiornare il tuo RCF.' 
---
= Panoramica sull'installazione o l'aggiornamento del file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installi il file RCF dopo aver configurato per la prima volta lo switch Nexus 9364D-GX2A. Aggiorni la versione del file RCF quando hai già una versione esistente del file RCF installata sullo switch.

Fare riferimento all'articolo della Knowledge Base link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch di interconnessione Cisco mantenendo la connettività remota"^] per ulteriori informazioni durante l'installazione o l'aggiornamento del proprio RCF.

.Configurazione RCF disponibile
* *Cluster-HA-Storage AFX* - Tutte le porte sono configurate in modalità breakout 4x100GbE che supporta universalmente cluster di nodi AFX, HA, porte di storage e porte di storage shelf NX224.  ISL 400GbE tra switch.  (_Cluster-HA-Storage AFX RCF_vxx.x_).


Per i dettagli specifici sull'utilizzo di porte e VLAN, fare riferimento al banner e alla sezione delle note importanti nel proprio RCF. Consultare link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] per ulteriori informazioni.

.Documentazione suggerita
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco (NSS)"^]
+
Consultare la tabella di compatibilità degli switch per le versioni ONTAP e RCF supportate sul sito di supporto NetApp .  Si noti che possono esserci dipendenze tra la sintassi dei comandi nella RCF e la sintassi presente in versioni specifiche di NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Switch Cisco Nexus serie 9000"^]
+
Per la documentazione completa sulle procedure di upgrade e downgrade degli switch Cisco , fare riferimento alle guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .



.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono cs1 e cs2.
* I nomi dei nodi sono node1-01, node1-02, node1-03 e node1-04.
* I nomi LIF del cluster sono node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 e node1-04_clus2.
* IL `cluster1::*>` il prompt indica il nome del cluster.


Consultare la link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte del cluster corrette sulle proprie piattaforme.


NOTE: Gli output dei comandi potrebbero variare a seconda delle diverse versioni di ONTAP.

.Comandi utilizzati
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 9000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

.Cosa succederà ora?
Dopo aver esaminato la procedura di installazione o aggiornamento RCF, è possibilelink:install-rcf-software-9364d-cluster.html["installare l'RCF"] Olink:upgrade-rcf-software-9364d-cluster.html["aggiorna il tuo RCF"] come richiesto.
