---
sidebar: sidebar 
permalink: switch-cisco-9364d-gx2a/reset-switch-9364d.html 
keywords: reset switch factory defaults 
summary: Ripristinare le impostazioni predefinite di fabbrica dello switch 9364D-GX2A. 
---
= Ripristinare l'interruttore 9364D-GX2A alle impostazioni predefinite di fabbrica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ripristinare le impostazioni predefinite di fabbrica dello switch 9364D-GX2A, è necessario cancellare le impostazioni dello switch 9364D-GX2A.

.A proposito di questa attività
* È necessario essere collegati allo switch mediante la console seriale.
* Questa attività ripristina la configurazione della rete di gestione.


.Fasi
. Cancella la configurazione esistente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Ricaricare il software dello switch:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Il sistema si riavvia e accede alla procedura guidata di configurazione.  Durante l'avvio, se viene visualizzato il messaggio "Interrompere il provisioning automatico e continuare con la configurazione normale?"  (sì/no)[n]”, dovresti rispondere *sì* per procedere.


