= Confermare il monitoraggio degli switch Ethernet collegati
:allow-uri-read: 




== Confermare il monitoraggio degli switch Ethernet collegati

Per confermare che gli switch Ethernet collegati siano monitorati, eseguire:

[source, cli]
----
system switch ethernet show
----
Se il `Model` la colonna visualizza *ALTRO* o `IS Monitored` Se il campo visualizza *false*, ONTAP non può monitorare lo switch.  Un valore *OTHER* indica in genere che ONTAP non supporta tale switch per il monitoraggio dello stato.

IL `IS Monitored` il campo è impostato su *false* per il motivo specificato nel `Reason` campo.

[NOTE]
====
Se uno switch non è elencato nell'output del comando, è probabile che ONTAP non lo abbia rilevato.  Verificare che l'interruttore sia cablato correttamente.  Se necessario, è possibile aggiungere manualmente lo switch.  Vederelink:monitor-manage.html["Gestire il monitoraggio degli switch Ethernet"] per ulteriori dettagli.

====


== Conferma che il firmware e le versioni RCF siano aggiornati

Assicurarsi che lo switch esegua il firmware supportato più recente e che sia stato applicato un file di configurazione di riferimento (RCF) compatibile.  Ulteriori informazioni sono disponibili sulhttps://mysupport.netapp.com/site/downloads["Pagina dei download del supporto NetApp"^] .

Per impostazione predefinita, il monitoraggio dello stato utilizza SNMPv2c con la stringa di comunità *cshm1!*, ma è possibile configurare anche SNMPv3.

Se è necessario modificare la stringa della community SNMPv2c predefinita, assicurarsi che sullo switch sia stata configurata la stringa della community SNMPv2c desiderata.

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: Vederelink:config-snmpv3.html["Facoltativo: configurare SNMPv3"] per i dettagli sulla configurazione di SNMPv3 per l'uso.



== Conferma la connessione alla rete di gestione

Verificare che la porta di gestione dello switch sia connessa alla rete di gestione.

Per consentire a ONTAP di eseguire query SNMP e raccogliere registri, è necessaria una corretta connessione alla porta di gestione.
