= Creare una voce di switch in modo che ONTAP possa monitorarla
:allow-uri-read: 




== Creare una voce di switch in modo che ONTAP possa monitorarla

Utilizzare il `system switch ethernet create` comando per configurare e abilitare manualmente il monitoraggio per uno switch Ethernet specificato.  Questa operazione è utile se ONTAP non aggiunge automaticamente lo switch oppure se in precedenza lo switch è stato rimosso e si desidera aggiungerlo di nuovo.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Un esempio tipico è l'aggiunta di uno switch denominato [DeviceName], con indirizzo IP 1.2.3.4 e credenziali SNMPv2c impostate su *cshm1!*.  Utilizzo `-type storage-network` invece di `-type cluster-network` se si sta configurando uno switch di archiviazione.



== Disattiva il monitoraggio senza eliminare lo switch

Se si desidera mettere in pausa o interrompere il monitoraggio di un determinato switch, ma conservarlo comunque per il monitoraggio futuro, modificarne `is-monitoring-enabled-admim` parametro invece di eliminarlo.

Per esempio:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Ciò consente di preservare i dettagli e la configurazione dello switch senza generare nuovi avvisi o nuove rilevazioni.



== Rimuovi un interruttore di cui non hai più bisogno

Utilizzo `system switch ethernet delete` per eliminare uno switch che è stato disconnesso o non è più necessario:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Per impostazione predefinita, questo comando riesce solo se ONTAP non rileva attualmente lo switch tramite CDP o LLDP.  Per rimuovere uno switch scoperto, utilizzare `-force` parametro:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Quando `-force` viene utilizzato, lo switch potrebbe essere aggiunto di nuovo automaticamente se ONTAP lo rileva di nuovo.
