= Nuovo supporto switch
:allow-uri-read: 




== Nuovo supporto switch

[cols="25h,~,~"]
|===
| Switch | Descrizione | Inizio disponibile 


 a| 
Switch Cisco a 32 porte 400GbE (X190300-CS-PI e X190300-PE)
 a| 
Supporto per switch Intra-Cluster/HA/Storage Cisco 9332D-GX2B.
 a| 
ONTAP 9.17.1



 a| 
Switch Cisco a 64 porte 400GbE (X190310-CS-PI)
 a| 
Supporto per switch Intra-Cluster/HA/Storage Cisco 9364D-GX2A.
 a| 
ONTAP 9.17.1



 a| 
Switch di cluster e storage Cisco Nexus 9336C-FX2-T a 12 porte 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Supporta configurazioni di cluster 10/25/40/100GbE e configurazioni di storage 100GbE (switch-attached storage).
 a| 
ONTAP 9.10.1



 a| 
Switch di cluster e storage Cisco Nexus 9336C-FX2-T a 12 porte 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Supporta configurazioni di cluster 10/25/40/100GbE e configurazioni di storage 100GbE (switch-attached storage).
 a| 
ONTAP 9.10.1



 a| 
Switch NVIDIA 100GbE a 16 porte (X190006-PE e X190006-PI)
 a| 
Supporto di switch per cluster Interconnect NVIDIA SN2100 e switch storage, incluso il supporto per le configurazioni IP MetroCluster.
 a| 
ONTAP 9.10.1



 a| 
Switch Cisco 100GbE a 36 porte (X190200-CS-PE e X190200-CS-PI)
 a| 
Supporta un'infrastruttura condivisa (cluster, ha e storage collegato a switch) sulla stessa coppia di switch Cisco Nexus 9336C-FX2, incluso il supporto per le configurazioni IP MetroCluster.
 a| 
ONTAP 9.9.1



 a| 
Switch Cisco 100GbE a 36 porte (X190200-CS-PE e X190200-CS-PI), (X190210-FE-PE e X190210-FE-PI)
 a| 
Supporto di switch cluster Interconnect Cisco Nexus 9336C-FX2 e switch storage per sistemi storage AFF e ASA, nonché per la connettività dei dati front-end.
 a| 
ONTAP 9.8



 a| 
Switch Broadcom BES-53248 (X190005 e X190005R)
 a| 
Switch per cluster Interconnect Broadcom BES-53248 per il supporto di controller AFF/FAS con porte 10/25GbE e 40/100GbE.
 a| 
ONTAP 9.8



 a| 
Switch Cisco 100GbE a 36 porte (X190200) e switch Cisco 100GbE a 32 porte (X190100 e X190100R)
 a| 
Supporto dello storage switch Cisco Nexus 3232C per la connessione di NS224 shelf di dischi NVMe sistemi storage AFF e ASA:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===