---
permalink: switch-cisco-9332d-gx2b/configure-review-cabling-config-requirements-9332d.html 
sidebar: sidebar 
keywords: 9332d-gx2b cabling setup, 9332d-gx2b switches configuration, nx-os 
summary: Verifica i requisiti di cablaggio e configurazione per gli switch Cisco Nexus 9332D-GX2B prima di installarli come parte di un sistema AFX 1K o AFX 2K. 
---
= Esamina i requisiti di cablaggio e configurazione per lo switch Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esamina i requisiti di cablaggio e configurazione per gli switch Cisco Nexus 9332D-GX2B prima di installarli come parte di un nuovo sistema AFX 1K o AFX 2K, di sostituire uno switch o di ripristinare uno switch alle impostazioni di fabbrica.



[[hard-code-the-speed-on-breakout-ports]]
== Imposta la velocità in modo fisso sulle porte breakout

Devi impostare manualmente le porte breakout dello switch (4x100GbE) su 100GbE. Se non imposti manualmente la velocità, le porte non si attiveranno e saranno in uno stato di errore disabilitato.

Ad esempio, per impostare la velocità 100GbE sulle porte breakout da 1 a 14, fai così in modalità di configurazione. L'esempio mostra i comandi applicati al primo switch (cs1). Ripeti questi comandi per il secondo switch.

[listing, subs="+quotes"]
----
(cs1)(config)# *interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7/1-4, e1/8/1-4, e1/9/1-4, e1/10/1-4, e1/11/1-4, e1/12/1-4, e1/13/1-4, e1/14/1-4*
(cs1)(config-if)# *speed 100000*
(cs1)(config-if)# *no negotiate auto*
(cs1)(config-if)# *exit*
(cs1)(config)# *exit*
(cs1)# *copy running-config startup-config*
----
.Cosa succederà ora?
Dopo che hai soddisfatto i requisiti di cablaggio e configurazione, puoi link:configure-install-nxos-9332d.html["installa NX-OS"].
