---
sidebar: sidebar 
permalink: switch-cisco-9332d-gx2b/configure-reqs-9332d-cluster.html 
keywords: shared storage cluster switch 
summary: A partire da ONTAP 9.9.1, è possibile utilizzare gli switch Cisco Nexus 9332D-GX2B per combinare funzionalità di storage e cluster in uno scenario di switch condiviso. 
---
= Requisiti di rete per gli switch Cisco Nexus 9332D-GX2B
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 9332D-GX2B, assicurarsi di esaminare i requisiti di cablaggio e di rete.



== Requisiti di rete

Per tutte le configurazioni dello switch sono necessarie le seguenti informazioni di rete.

* Subnet IP per il traffico di rete di gestione
* Nomi host e indirizzi IP per ciascuno dei controller del sistema di archiviazione e tutti gli switch applicabili
* La maggior parte dei controller dei sistemi di storage vengono gestiti tramite l'interfaccia e0M, collegandosi alla porta di servizio Ethernet (icona a forma di chiave inglese).
* Fare riferimento al https://hwu.netapp.com["Hardware Universe"^] per le ultime informazioni. Vedere link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per maggiori informazioni sui requisiti di installazione degli switch.




== Requisiti di cablaggio

* Hai il numero e il tipo di cavi e connettori per i tuoi switch appropriati. Vedi il https://hwu.netapp.com["Hardware Universe"^] .
* A seconda del tipo di switch che si sta configurando inizialmente, è necessario collegarsi alla porta della console dello switch tramite il cavo della console incluso.

