---
permalink: switch-cisco-9332d-gx2b/install-complete-afx-setup-9332d.html 
sidebar: sidebar 
keywords: switches, complete system setup, Cisco Nexus, 9332D-GX2B switches, AFX 
summary: Completa la configurazione del sistema AFX 1K o AFX 2K dopo aver terminato la configurazione dello switch Cisco Nexus 9332D-GX2B. 
---
= Completa la configurazione del sistema AFX per lo switch Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato la configurazione dello switch Cisco Nexus 9332D-GX2B, accendi gli alloggiamenti di storage e i controller, verifica la connettività dello switch e completa la configurazione del sistema AFX 1K o AFX 2K.

.Prima di iniziare
* Devi aver completato le procedure di configurazione dello switch in link:configure-switch-workflow-9332d.html["configura il workflow dello switch"].
* Ogni switch deve essere collegato a una console oppure devi avere accesso remoto a ciascuno switch.


.Passi
. Completa le procedure di accensione e configurazione del tuo sistema AFX 1K o AFX 2K:
+
** Per un sistema AFX 1K, vai alla link:https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-hardware.html["Accendi il tuo sistema di archiviazione AFX 1K"^] procedura.
** Per un sistema AFX 2K, vai alla link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/power-on-hardware.html["Accendi il tuo sistema storage AFX 2K"^] procedura.




.Cosa succederà ora?
Dopo aver acceso le unità di archiviazione e i controller e aver completato la configurazione del sistema AFX 1K o AFX 2K, sei pronto per usare il tuo sistema AFX.
