---
permalink: switch-cisco-9332d-gx2b/install-rcf-software-9332d-cluster.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 'È possibile installare l"RCF dopo aver configurato per la prima volta lo switch Nexus 9332D-GX2B.' 
---
= Installazione del file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato per la prima volta lo switch Nexus 9332D-GX2B, installare il file di configurazione di riferimento (RCF).

.Prima di iniziare
Verificare le seguenti installazioni e connessioni:

* Collegamento della console allo switch. Il collegamento alla console è opzionale se si dispone dell'accesso remoto allo switch.
* Lo switch CS1 e lo switch CS2 sono accesi e la configurazione iniziale dello switch è completa (l'indirizzo IP di gestione e SSH è impostato).
* È stata installata la versione NX-OS desiderata.
* Le connessioni ISL tra gli switch sono collegate.




== Fase 1: Installare l'RCF sugli interruttori

. Accedere allo switch CS1 usando SSH o usando una console seriale.
. Copiare l'RCF nella memoria di avvio dello switch CS1 utilizzando uno dei seguenti protocolli di trasferimento: FTP, TFTP, SFTP o SCP.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata in https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 Series NX-OS Command Reference"^] guide.

+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra l'utilizzo di TFTP per copiare un RCF nel bootflash dello switch CS1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9332D-GX2B-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Applicare l'RCF precedentemente scaricato al bootflash.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata in https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 Series NX-OS Command Reference"^] guide.

+
Questo esempio mostra il file RCF `NX9332D-GX2B-RCF-v10.0-Shared.txt` in fase di installazione sullo switch cs1:

+
[listing, subs="+quotes"]
----
cs1# *copy NX9332D-GX2B-RCF-v10.0-Shared.txt running-config echo-commands*
----
. Esaminare l'output dello striscione da `show banner motd` comando. Leggere e seguire queste istruzioni per garantire la corretta configurazione e il corretto funzionamento dello switch.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9332D-GX2B
* Filename : NX9332D-GX2B-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-30: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-30}/1-4
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
******************************************************************************
----
====
. Verificare che il file RCF sia la versione più recente corretta:
+
`show running-config`

+
Quando si controlla l'output per verificare che l'RCF sia corretto, assicurarsi che le seguenti informazioni siano corrette:

+
** Il banner RCF
** Le impostazioni di nodo e porta
** Personalizzazioni
+
L'output varia in base alla configurazione del sito. Controllare le impostazioni della porta e fare riferimento alle note di rilascio per eventuali modifiche specifiche all'RCF installato.



. Salva i dettagli di configurazione di base nel `write_erase.cfg` file sul bootflash.
+
[NOTE]
====
Assicurati di configurare quanto segue:

** Nome utente e password
** Indirizzo IP di gestione
** Gateway predefinito
** Cambia nome


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`

+
Vedi l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch Cisco Interconnect mantenendo la connettività remota"^] per ulteriori dettagli.

. Verificare che il `write_erase.cfg` il file è popolato come previsto:
+
`*show file bootflash:write_erase.cfg*`

. Emettere il `write erase` comando per cancellare la configurazione salvata corrente:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copiare la configurazione di base salvata in precedenza nella configurazione di avvio.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Riavviare lo switch:
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Ripetere i passaggi da 1 a 10 sullo switch cs2.
. Collegare le porte di tutti i nodi del cluster ONTAP agli switch cs1 e cs2.




== Fase 2: Verificare i collegamenti dello switch

. Verificare che le porte dello switch collegate alle porte del cluster siano attive:
+
`show interface brief`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
----
====
. Verificare che i nodi del cluster si trovino nelle VLAN del cluster corrette utilizzando i seguenti comandi:
+
`show vlan brief`

+
`show interface trunk`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
                                                Eth1/2/1, Eth1/2/2, Eth1/2/3
                                                Eth1/2/4, Eth1/3/1, Eth1/3/2
                                                Eth1/3/3, Eth1/3/4, Eth1/4/1
                                                Eth1/4/2, Eth1/4/3, Eth1/4/4
                                                Eth1/5/1, Eth1/5/2, Eth1/5/3
                                                Eth1/5/4, Eth1/6/1, Eth1/6/2
                                                Eth1/6/3, Eth1/6/4, Eth1/7/1
                                                Eth1/7/2, Eth1/7/3, Eth1/7/4
                                                Eth1/8/1, Eth1/8/2, Eth1/8/3
                                                Eth1/8/4, Eth1/9/1, Eth1/9/2
                                                Eth1/9/3, Eth1/9/4, Eth1/10/1
                                                Eth1/10/2, Eth1/10/3, Eth1/10/4
                                                Eth1/11/1, Eth1/11/2, Eth1/11/3
                                                Eth1/11/4, Eth1/12/1, Eth1/12/2
                                                Eth1/12/3, Eth1/12/4, Eth1/13/1
                                                Eth1/13/2, Eth1/13/3, Eth1/13/4
                                                Eth1/14/1, Eth1/14/2, Eth1/14/3
                                                Eth1/14/4, Eth1/15/1, Eth1/15/2
                                                Eth1/15/3, Eth1/15/4, Eth1/16/1
                                                Eth1/16/2, Eth1/16/3, Eth1/16/4
                                                Eth1/17/1, Eth1/17/2, Eth1/17/3
                                                Eth1/17/4, Eth1/18/1, Eth1/18/2
                                                Eth1/18/3, Eth1/18/4, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
                                                Eth1/28/2, Eth1/28/3, Eth1/28/4
                                                Eth1/29/1, Eth1/29/2, Eth1/29/3
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4

cs1# *show interface trunk*
--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31       none
Eth1/32       none
Po1           1
----
====
+

NOTE: Per informazioni dettagliate sull'utilizzo di porte e VLAN specifiche, fare riferimento alla sezione banner e note importanti nell'RCF.

. Verificare che l'ISL tra cs1 e cs2 funzioni correttamente:
+
[source, cli]
----
show port-channel summary
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
cs1#
----
====




== Fase 3: Configurare il cluster ONTAP

NetApp consiglia di utilizzare System Manager per configurare nuovi cluster.

System Manager offre un workflow semplice e facile per la configurazione e la configurazione del cluster, che include l'assegnazione di un indirizzo IP di gestione dei nodi, l'inizializzazione del cluster, la creazione di un Tier locale, la configurazione dei protocolli e il provisioning dello storage iniziale.

Passare a. https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurare ONTAP su un nuovo cluster con Gestione di sistema"] per le istruzioni di installazione.

.Quali sono le prossime novità?
Dopo aver installato l'RCF,link:configure-ssh-keys.html["verificare la configurazione SSH"] .
