---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/components-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: A partire da ONTAP 9.9.1, è possibile utilizzare gli switch Cisco Nexus 9336C-FX2 per combinare funzionalità di storage e cluster in uno scenario di switch condiviso. 
---
= Componenti e numeri parte di switch cluster Cisco Nexus 9336C-FX2 e 9336C-FX2-T.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione degli switch Cisco Nexus 9336C-FX2 e 9336C-FX2-T, rivedere l'elenco dei componenti e dei numeri parte.



== Dettagli del numero di parte

La tabella seguente elenca il numero di parte e la descrizione per gli interruttori 9336C-FX2 e 9336C-FX2-T, le ventole e gli alimentatori:

[cols="1,2"]
|===
| Codice del ricambio | Descrizione 


 a| 
X190200-CS-PE
 a| 
Interruttore quadro strumenti, N9336C 36Pt PTSX 10/25/40/100g



 a| 
X190200-CS-PI
 a| 
Interruttore quadro strumenti, N9336C 36Pt PSIN 10/25/40/100g



 a| 
X190212-CS-PE
 a| 
Interruttore quadro strumenti, N9336C 12pt (9336C-FX2-T) PTSX 10/25/40/100g



 a| 
X190212-CS-PI
 a| 
Interruttore quadro strumenti, N9336C 12pt (9336C-FX2-T) PSIN 10/25/40/100g



 a| 
SW-N9K-FX2-24P-UPG
 a| 
SW, licenza POD Cisco 9336CFX2 a 24 porte



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT 10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT 10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit di accessori X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C AC 1100 W PSU - flusso d'aria di scarico laterale



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C AC 1100 W PSU - flusso d'aria di aspirazione lato porta



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM, flusso d'aria di scarico lato porta



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM, flusso d'aria di aspirazione lato porta

|===


== Licenze Cisco Smart solo per porte 9336C-FX2-T

Per attivare più di 12 porte sullo switch cluster Cisco Nexus 9336C-FX-T, è necessario acquistare una licenza Cisco Smart. Le licenze Cisco Smart vengono gestite tramite gli account Cisco Smart.

. Se necessario, creare un nuovo account Smart. Per ulteriori informazioni, vedere https://id.cisco.com/signin/register["Creare un nuovo account Smart"^].
. Richiedere l'accesso a un account Smart esistente. Per ulteriori informazioni, vedere https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30["Richiedere l'accesso a un account Smart esistente"^].



NOTE: Una volta acquistata la licenza Smart, installare l'RCF appropriato per abilitare e configurare tutte le 36 porte disponibili per l'uso.

.Cosa c'è dopo?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-9336c-cluster.html["documentazione richiesta"].
