---
permalink: switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: 'Panoramica dell"installazione e della configurazione degli switch cluster Cisco Nexus 9336C-FX2' 
---
= Panoramica dell'installazione e della configurazione degli switch cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo switch cluster Cisco Nexus 9336C-FX2 fa parte della piattaforma Cisco Nexus 9000 e può essere installato in un cabinet di sistema NetApp. Gli switch del cluster consentono di creare cluster ONTAP con più di due nodi.



== Panoramica della configurazione iniziale

Per configurare inizialmente uno switch Cisco Nexus 9336C-FX2 su sistemi che eseguono ONTAP, attenersi alla seguente procedura:

. link:setup-worksheet-9336c-cluster.html["Completare il foglio di lavoro per il cablaggio di Cisco Nexus 9336C-FX2"].
+
Il foglio di lavoro di esempio relativo ai cavi fornisce esempi di assegnazione delle porte consigliate dagli switch ai controller. Il foglio di lavoro vuoto fornisce un modello che è possibile utilizzare per la configurazione del cluster.

. link:install-switch-9336c-cluster.html["Installare lo switch"].
+
Configurare l'hardware dello switch.

. link:setup-switch-9336c-cluster.html["Configurare lo switch del cluster 9336C-FX2"].
+
Configurare lo switch Cisco Nexus 9336C-FX2.

. link:install-switch-and-passthrough-panel-9336c-cluster.html["Installare uno switch Cisco Nexus 9336C-FX2 in un cabinet NetApp"].
+
A seconda della configurazione, è possibile installare lo switch Cisco Nexus 9336C-FX2 e il pannello pass-through in un cabinet NetApp con le staffe standard incluse con lo switch.

. link:install-nxos-overview-9336c-cluster.html["Preparare l'installazione del software NX-OS e di RCF"].
+
Seguire le procedure preliminari per l'installazione del software Cisco NX-OS e dei file di configurazione di riferimento (RCF).

. link:install-nxos-software-9336c-cluster.html["Installare o aggiornare il software NX-OS"].
+
Installa o aggiorna il software NX-OS sullo switch del cluster Nexus 9336C-FX2.

. link:install-nxos-rcf-9336c-cluster.html["Installare o aggiornare l'RCF"].
+
Installare o aggiornare l'RCF dopo aver configurato per la prima volta lo switch Nexus 9336C-FX2. È inoltre possibile utilizzare questa procedura per aggiornare la versione di RCF.

. link:configure-ssh.html["Attivare SSH sugli switch del cluster Nexus 9336C-FX2"].
+
Se si utilizzano le funzioni CSHM (Ethernet Switch Health Monitor) e di raccolta dei registri, attivare SSH sugli switch.





== Ulteriori informazioni

Prima di iniziare l'installazione o la manutenzione, verificare quanto segue:

* link:configure-reqs-9336c-cluster.html["Requisiti di configurazione"]
* link:components-9336c-cluster.html["Componenti e numeri di parte"]
* link:required-documentation-9336c-cluster.html["Documentazione richiesta"]
* link:smart-call-9336c-cluster.html["Requisiti Smart Call Home"]

