---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Panoramica della configurazione software per gli switch cluster Cisco Nexus 9336C-FX2 
---
= Workflow di installazione del software per switch cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare e configurare il software per uno switch Cisco Nexus 9336C-FX2 e per installare o aggiornare il file di configurazione di riferimento (RCF), attenersi alla seguente procedura:

. link:install-nxos-overview-9336c-cluster.html["Preparare l'installazione del software NX-OS e RCF"].
. link:install-nxos-software-9336c-cluster.html["Installare il software NX-OS"].
. link:install-nxos-rcf-9336c-cluster.html["Installare o aggiornare il file di configurazione di riferimento (RCF)"].
+
Installare l'RCF dopo aver configurato lo switch Nexus 9336C-FX2 per la prima volta. È inoltre possibile utilizzare questa procedura per aggiornare la versione di RCF.

+
.Configurazioni RCF disponibili
Nella tabella seguente sono descritti gli RCF disponibili per diverse configurazioni. Scegliere l'RCF applicabile alla propria configurazione.

+
Per informazioni dettagliate sull'utilizzo di porte e VLAN specifiche, fare riferimento alla sezione banner e note importanti nell'RCF.

+
[cols="1,2"]
|===
| Nome RCF | Descrizione 


 a| 
2 cluster-ha-breakout
 a| 
Supporta due cluster ONTAP con almeno otto nodi, compresi i nodi che utilizzano porte ha e cluster condivisi.



 a| 
4 cluster-ha-breakout
 a| 
Supporta quattro cluster ONTAP con almeno quattro nodi, inclusi i nodi che utilizzano porte ha e cluster condivisi.



 a| 
1-Cluster-ha
 a| 
Tutte le porte sono configurate per 40 GbE/100GbE GbE. Supporta il traffico ha/cluster condiviso sulle porte. Richiesto per i sistemi AFF A320, AFF A250 e FAS500f. Inoltre, tutte le porte possono essere utilizzate come porte cluster dedicate.



 a| 
1 cluster-ha-breakout
 a| 
Le porte sono configurate per breakout 4x10GbE, breakout 4x25GbE (RCF 1,6+ su switch 100GbE) e 40/100GbE. Supporta il traffico ha/cluster condiviso sulle porte per i nodi che utilizzano porte ha/cluster condivisi: Sistemi AFF A320, AFF A250 e FAS500f. Inoltre, tutte le porte possono essere utilizzate come porte cluster dedicate.



 a| 
Storage ha-cluster
 a| 
Le porte sono configurate per 40/100GbE per Cluster+ha, breakout 4x10 GbE per il cluster e breakout 4x25GbE per Cluster+ha e 100GbE per ogni coppia ha storage.



 a| 
Cluster
 a| 
Due versioni di RCF con diverse allocazioni di 4 porte 10 GbE (breakout) e porte 40/100GbE. Tutti i nodi FAS/AFF sono supportati, ad eccezione dei sistemi AFF A320, AFF A250 e FAS500f.



 a| 
Storage
 a| 
Tutte le porte sono configurate per connessioni storage NVMe da 100GbE GB.

|===

