---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Panoramica della configurazione software per gli switch cluster Cisco Nexus 9336C-FX2 
---
= Workflow di installazione del software per switch cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare e configurare il software per uno switch Cisco Nexus 9336C-FX2 e per installare o aggiornare il file di configurazione di riferimento (RCF), attenersi alla seguente procedura:

. link:install-nxos-overview-9336c-cluster.html["Preparare l'installazione del software NX-OS e di RCF"].
+
Il software Cisco NX-OS e i file di configurazione di riferimento (RCF) devono essere installati sugli switch cluster Cisco Nexus 9336C-FX2.

. link:install-nxos-software-9336c-cluster.html["Installare o aggiornare il software NX-OS"].
+
Scarica e installa o aggiorna il software NX-OS sullo switch cluster Cisco Nexus 9336C-FX2.

. link:install-nxos-rcf-9336c-cluster.html["Installare o aggiornare l'RCF"].
+
Installare o aggiornare l'RCF dopo aver configurato per la prima volta lo switch Cisco Nexus 9336C-FX2. È inoltre possibile utilizzare questa procedura per aggiornare la versione di RCF.

. link:configure-ssh.html["Abilitare SSH"].
+
Se si utilizzano le funzioni CSHM (Ethernet Switch Health Monitor) e di raccolta dei registri, attivare SSH sugli switch.


