---
permalink: switch-cisco-9336c-fx2/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: 'SSH è un requisito per l"utilizzo delle funzionalità di monitoraggio dello stato di salute dello switch del cluster (CSHM) e di raccolta dei log. Per abilitare SSH sugli switch del cluster Cisco 9336c-FX2, si generano prima le chiavi SSH e quindi si abilita SSH.' 
---
= Installare o aggiornare la panoramica del file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato per la prima volta lo switch Nexus 9336C-FX2, installare il file di configurazione di riferimento (RCF). La versione RCF viene aggiornata quando sullo switch è installata una versione esistente del file RCF.

Per ulteriori informazioni sull'installazione o l'aggiornamento di RCF, consultare l'articolo della Knowledge baselink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch Cisco Interconnect mantenendo la connettività remota"^].

.Configurazioni RCF disponibili
Nella tabella seguente sono descritti gli RCF disponibili per diverse configurazioni. Scegliere l'RCF applicabile alla propria configurazione.

Per informazioni dettagliate sull'utilizzo di porte e VLAN specifiche, fare riferimento alla sezione banner e note importanti nell'RCF.

[cols="1,2"]
|===
| Nome RCF | Descrizione 


 a| 
2 cluster-ha-breakout
 a| 
Supporta due cluster ONTAP con almeno otto nodi, compresi i nodi che utilizzano porte ha e cluster condivisi.



 a| 
4 cluster-ha-breakout
 a| 
Supporta quattro cluster ONTAP con almeno quattro nodi, inclusi i nodi che utilizzano porte ha e cluster condivisi.



 a| 
1-Cluster-ha
 a| 
Tutte le porte sono configurate per 40 GbE/100GbE GbE. Supporta il traffico ha/cluster condiviso sulle porte. Richiesto per i sistemi AFF A320, AFF A250 e FAS500f. Inoltre, tutte le porte possono essere utilizzate come porte cluster dedicate.



 a| 
1 cluster-ha-breakout
 a| 
Le porte sono configurate per breakout 4x10GbE, breakout 4x25GbE (RCF 1,6+ su switch 100GbE) e 40/100GbE. Supporta il traffico ha/cluster condiviso sulle porte per i nodi che utilizzano porte ha/cluster condivisi: Sistemi AFF A320, AFF A250 e FAS500f. Inoltre, tutte le porte possono essere utilizzate come porte cluster dedicate.



 a| 
Storage ha-cluster
 a| 
Le porte sono configurate per 40/100GbE GbE per Cluster+ha, 4x10GbE breakout per il cluster e 4x25GbE breakout per Cluster+ha e 100GbE GbE per ogni coppia ha storage.



 a| 
Cluster
 a| 
Due versioni di RCF con diverse allocazioni di 4 porte 10 GbE (breakout) e porte 40/100GbE. Tutti i nodi FAS/AFF sono supportati, ad eccezione dei sistemi AFF A320, AFF A250 e FAS500f.



 a| 
Storage
 a| 
Tutte le porte sono configurate per connessioni storage NVMe da 100GbE GB.

|===
.Documentazione consigliata
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco (NSS)"^]
+
Consultare la tabella di compatibilità degli switch per le versioni ONTAP e RCF supportate sul sito di supporto NetApp. Si noti che possono esistere dipendenze di comando tra la sintassi di comando nell'RCF e la sintassi trovata nelle versioni specifiche di NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Switch Cisco Nexus serie 3000"^]
+
Per la documentazione completa sulle procedure di aggiornamento e di downgrade degli switch Cisco, consultare le guide appropriate per il software e l'aggiornamento disponibili sul sito Web di Cisco.



.A proposito degli esempi
Gli esempi di questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono *CS1* e *CS2*.
* I nomi dei nodi sono *cluster1-01*, *cluster1-02*, *cluster1-03* e *cluster1-04*.
* I nomi LIF del cluster sono *cluster1-01_clus1*, *cluster1-01_clus2*, *cluster1-03_clus2*, *cluster1-03_clus1*, *cluster1-02_clus2*, *cluster1-02_clus1*, *cluster1-04_clus1* e *cluster1-04_clus2*.
* Il `cluster1::*>` prompt indica il nome del cluster.


Gli esempi di questa procedura utilizzano quattro nodi. Questi nodi utilizzano due porte di interconnessione cluster 10GbE *e0a* e *e0b*. Consultare https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte cluster corrette sulle piattaforme.


NOTE: Gli output dei comandi possono variare a seconda delle diverse versioni di ONTAP.

Per informazioni dettagliate sulle configurazioni RCF disponibili, vedere link:configure-software-overview-9336c-cluster.html["Workflow di installazione del software"].

.Comandi utilizzati
La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 9000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.

.Quali sono le prossime novità?
link:install-rcf-software-9336c-cluster.html["Installare RCF"] o link:upgrade-rcf-software-9336c-cluster.html["Aggiornare il file RCF"].
