---
permalink: switch-cisco-9336c-fx2/replace-storage-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'La sostituzione di uno switch Nexus 9336C-FX2 difettoso in una rete cluster è una procedura non distruttiva \(NDU\).' 
---
= Sostituire uno switch di archiviazione Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si sostituiscono gli switch di archiviazione Cisco Nexus 9336C-FX2, è necessario conoscere alcune informazioni sulla configurazione, sui collegamenti delle porte e sui requisiti di cablaggio.

.Cosa ti servirà
Prima di installare il software NX-OS e gli RCF su uno switch di archiviazione Cisco Nexus 9336C-FX2, è necessario verificare che siano presenti le seguenti condizioni:

* Il sistema può supportare gli switch di archiviazione Cisco Nexus 9336C-FX2.
* È necessario aver consultato la tabella di compatibilità degli switch nella pagina Cisco Ethernet Switch per le versioni ONTAP, NX-OS e RCF supportate.
* È necessario aver consultato le guide software e di aggiornamento appropriate disponibili sul sito Web Cisco .  Switch Cisco Nexus serie 3000
* È necessario aver scaricato gli RCF applicabili.
* La configurazione di rete esistente deve avere le seguenti caratteristiche:
+
** Nella pagina relativa agli switch Ethernet Cisco sono disponibili le versioni RCF e NX-OS più recenti sui tuoi switch.
** La connettività di gestione deve essere presente su entrambi gli switch.


* Lo switch sostitutivo Cisco Nexus 9336C-FX2 deve avere le seguenti caratteristiche:
+
** La connettività della rete di gestione deve essere funzionale.
** Deve essere presente l'accesso alla console per l'interruttore sostitutivo.
** Sullo switch deve essere caricata l'immagine appropriata del sistema operativo RCF e NX-OS.
** La configurazione iniziale dello switch deve essere completa.




.Informazioni su questo compito
Questa procedura sostituisce il secondo switch di archiviazione Nexus 9336C-FX2 S2 con il nuovo switch 9336C-FX NS2.  I due nodi sono node1 e node2.

Passaggi per completare:

* Verificare che l'interruttore da sostituire sia S2.
* Scollegare i cavi dall'interruttore S2.
* Ricollegare i cavi allo switch NS2.
* Verificare tutte le configurazioni dei dispositivi sullo switch NS2.
+

NOTE: Possono esserci dipendenze tra la sintassi dei comandi nelle versioni RCF e NX-OS.



.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

. Controllare lo stato di integrità delle porte del nodo di archiviazione per assicurarsi che vi sia una connessione allo switch di archiviazione S1:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. Verificare che lo switch di archiviazione S1 sia disponibile:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. Gestisci lo spettacolo `lldp neighbors` comando sullo switch funzionante per confermare che puoi vedere entrambi i nodi e tutti gli scaffali:
+
`show lldp neighbors`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Verificare le porte degli scaffali nel sistema di archiviazione:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. Rimuovere tutti i cavi collegati all'interruttore di archiviazione S2.
. Ricollegare tutti i cavi allo switch sostitutivo NS2.
. Ricontrollare lo stato di integrità delle porte del nodo di archiviazione:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. Verificare che entrambi gli switch siano disponibili:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. Verificare le porte degli scaffali nel sistema di archiviazione:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


