---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/required-documentation-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: 'Per l"installazione e la manutenzione dello switch Cisco Nexus 9336C-FX2, assicurarsi di consultare la documentazione specifica dello switch e del controller per configurare gli switch Cisco 9336-FX2 e il cluster ONTAP .' 
---
= Requisiti di documentazione per gli switch Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione degli switch Cisco Nexus 9336C-FX2 e 9336C-FX2-T, assicurarsi di consultare la documentazione specifica dello switch e del controller per configurare gli switch Cisco 9336-FX2 e il cluster ONTAP .



== Documentazione dello switch

Per configurare gli switch Cisco Nexus 9336C-FX2 e 9336C-FX2-T, è necessaria la seguente documentazione dal https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Supporto per gli switch Cisco Nexus serie 9000"^] pagina:

[cols="1,2"]
|===
| Titolo del documento | Descrizione 


 a| 
_Guida all'installazione dell'hardware della serie Nexus 9000_
 a| 
Fornisce informazioni dettagliate sui requisiti del sito, dettagli sull'hardware dello switch e opzioni di installazione.



 a| 
_Guide alla configurazione del software dello switch Cisco Nexus serie 9000_ (scegli la guida per la versione NX-OS installata sugli switch)
 a| 
Fornisce le informazioni di configurazione iniziale dello switch necessarie prima di poterlo configurare per il funzionamento ONTAP .



 a| 
_Guida all'aggiornamento e al downgrade del software Cisco Nexus serie NX-OS_ (scegli la guida per la versione NX-OS installata sui tuoi switch)
 a| 
Fornisce informazioni su come effettuare il downgrade dello switch al software dello switch supportato ONTAP , se necessario.



 a| 
_Indice principale di riferimento dei comandi NX-OS della serie Cisco Nexus 9000_
 a| 
Fornisce collegamenti ai vari riferimenti ai comandi forniti da Cisco.



 a| 
_Riferimento MIB Cisco Nexus 9000_
 a| 
Descrive i file MIB (Management Information Base) per gli switch Nexus 9000.



 a| 
_Riferimento ai messaggi di sistema NX-OS della serie Nexus 9000_
 a| 
Descrive i messaggi di sistema per gli switch Cisco Nexus serie 9000, quelli informativi e altri che potrebbero aiutare a diagnosticare problemi con i collegamenti, l'hardware interno o il software di sistema.



 a| 
_Note sulla versione NX-OS della serie Cisco Nexus 9000 (selezionare le note per la versione NX-OS installata sugli switch)_
 a| 
Descrive le funzionalità, i bug e le limitazioni della serie Cisco Nexus 9000.



 a| 
Conformità normativa e informazioni sulla sicurezza per Cisco Nexus serie 9000
 a| 
Fornisce informazioni sulla conformità alle agenzie internazionali, sulla sicurezza e sugli statuti per gli switch della serie Nexus 9000.

|===


== Documentazione dei sistemi ONTAP

Per configurare un sistema ONTAP , sono necessari i seguenti documenti per la versione del sistema operativo da https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
Istruzioni di installazione e configurazione specifiche del controller
 a| 
Descrive come installare l'hardware NetApp .



 a| 
Documentazione ONTAP
 a| 
Fornisce informazioni dettagliate su tutti gli aspetti delle versioni ONTAP .



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornisce informazioni sulla configurazione hardware e sulla compatibilità NetApp .

|===


== Documentazione del kit ferroviario e dell'armadio

Per installare uno switch Cisco 9336-FX2 in un cabinet NetApp , consultare la seguente documentazione hardware.

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armadio di sistema 42U, guida profonda"^]
 a| 
Descrive le FRU associate al cabinet del sistema 42U e fornisce istruzioni per la manutenzione e la sostituzione delle FRU.



 a| 
link:install-switch-and-passthrough-panel-9336c-cluster.html["Installare uno switch Cisco 9336-FX2 in un cabinet NetApp"^]
 a| 
Descrive come installare gli switch Cisco Nexus 9336C-FX2 e 9336C-FX2-T in un cabinet NetApp a quattro montanti.

|===