---
permalink: switch-cisco-9336c-fx2/reset-switch-9336c.html 
sidebar: sidebar 
keywords: 9336C-FX2 reset switch to factory defaults, 9336C-FX2 switches configuration, efos 
summary: Prima di configurare lo switch Cisco Nexus 9336C-FX2, leggere le seguenti informazioni. 
---
= Ripristinare i valori predefiniti di fabbrica degli switch cluster 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 


[role="lead"]
Per ripristinare le impostazioni predefinite di fabbrica degli switch cluster 9336C-FX2 e 9336C-FX2-T, è necessario cancellare le impostazioni degli switch 9336C-FX2 e 9336C-FX2-T.

.Informazioni su questo compito
* È necessario connettersi allo switch tramite la console seriale.
* Questa attività reimposta la configurazione della rete di gestione.


.Passi
. Cancella la configurazione esistente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Ricaricare il software dello switch:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Il sistema si riavvia e accede alla procedura guidata di configurazione. Durante l'avvio, se viene visualizzato il messaggio "Interrompere il provisioning automatico e continuare con la configurazione normale?" (sì/no)[n]”, dovresti rispondere *sì* per procedere.



.Cosa c'è dopo?
Dopo aver ripristinato gli switch, puoilink:configure-switch-overview-9336c-cluster.html["riconfigurare"] secondo necessità.
