---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: È possibile utilizzare questa procedura per installare il file di configurazione applicabile per il monitoraggio dello stato degli switch cluster degli switch cluster Nexus 92300YC. 
---
= Installare il file di configurazione del monitor dello stato degli interruttori sul quadro strumenti (SHM)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per installare il file di configurazione applicabile per il monitoraggio dello stato degli switch del cluster (SHM) degli switch del cluster Nexus 9336C-FX2.

.Di cosa hai bisogno
Prima di impostare l'unità SHM per gli switch del cluster 9336C-FX2, verificare che il cluster ONTAP sia attivo e in funzione.


NOTE: Si dovrebbe anche abilitare SSH per utilizzare tutte le funzioni disponibili in SHM.

.Fasi
. Scaricare il file zip di configurazione del cluster SHM in base alla versione della release ONTAP corrispondente. Questo file è disponibile in https://mysupport.netapp.com/NOW/cgi-bin/software/["Download del software NetApp"^] pagina.
+
.. Nella pagina di download del software, selezionare *Switch Health Monitor Configuration Files*
.. Selezionare piattaforma = *ONTAP* e selezionare *Vai!*
.. Nella pagina file di configurazione di Switch Health Monitor per ONTAP, selezionare *Visualizza e scarica*
.. Nella pagina file di configurazione di Switch Health Monitor per ONTAP > Descrizione, selezionare *Download* per il modello di switch cluster applicabile, ad esempio: *Cisco Nexus 9336C-FX2*
.. Nella pagina Contratto di licenza con l'utente finale, selezionare *Accetta*
.. Nella pagina file di configurazione di Switch Health Monitor per ONTAP > Download, selezionare il file di configurazione appropriato, ad esempio, *Cisco_Nexus_9336C-FX2.zip*


. Caricare il file zip applicabile sul server Web interno in cui l'indirizzo IP è X.X.X.X.
+
Per un indirizzo IP interno del server Web 192.168.2.20 e supponendo che esista una directory /usr/download, è possibile caricare il file zip sul server Web utilizzando SCP:

+
[listing]
----
% scp Cisco_Nexus_9336C-FX2.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. Accedere all'impostazione della modalità avanzata da uno dei sistemi ONTAP nel cluster:
+
`set-privilege advanced`

+
[listing]
----
cluster1::> set -privilege advanced
----
. Eseguire il comando di configurazione dello switch Health monitor `system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file`:
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. Verificare che l'output del comando contenga la stringa di testo "Downloaded package processed successfully" (pacchetto scaricato elaborato correttamente). In caso di errore, contattare il supporto NetApp.
. Eseguire il comando `system cluster-switch show` Sul sistema ONTAP e assicurarsi che gli switch del cluster vengano rilevati con il campo monitorato impostato su "vero".
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: Se in qualsiasi momento si torna a una versione precedente di ONTAP, sarà necessario installare nuovamente il file di configurazione di SHM per abilitare l'SHM degli switch del cluster 9336C-FX2.


