---
permalink: switch-cisco-9336c-fx2/setup-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Seguire questa procedura per impostare e configurare lo switch Cisco Nexus 9336C-FX2. 
---
= Configurare gli switch cluster 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per configurare gli switch Cisco Nexus 9336C-FX2 e 9336C-FX2-T.

.Prima di iniziare
Assicurati di avere quanto segue:

* Accesso a un server HTTP, FTP o TFTP nel sito di installazione per scaricare le versioni NX-OS e RCF (Reference Configuration File) applicabili.
* Versione NX-OS applicabile, scaricata da https://software.cisco.com/download/home["Scarica il software Cisco"^] pagina.
* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Completatolink:setup-worksheet-9336c-cluster.html["fogli di lavoro sul cablaggio"] .
* RCF applicabili alla rete cluster NetApp e alla rete di gestione scaricabili dal sito di supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^] .  Tutti gli switch di rete cluster e di rete di gestione Cisco vengono forniti con la configurazione predefinita di fabbrica Cisco . Questi switch dispongono anche della versione corrente del software NX-OS, ma non hanno gli RCF caricati.
* link:required-documentation-9336c-cluster.html["Documentazione richiesta per switch e ONTAP"].


.Passi
. Eseguire una configurazione iniziale degli switch di rete del cluster.
+
Fornire risposte pertinenti alle seguenti domande sulla configurazione iniziale al primo avvio dello switch.  La politica di sicurezza del tuo sito definisce le risposte e i servizi da abilitare.

+
[cols="1,2"]
|===
| Richiesta | Risposta 


 a| 
Interrompere il provisioning automatico e continuare con la configurazione normale?  (sì/no)
 a| 
Rispondi con *sì*.  L'impostazione predefinita è no.



 a| 
Vuoi applicare uno standard di password sicura?  (sì/no)
 a| 
Rispondi con *sì*.  L'impostazione predefinita è sì.



 a| 
Inserisci la password per l'amministratore.
 a| 
La password predefinita è "`admin`"; è necessario crearne una nuova, più complessa.  Una password debole può essere rifiutata.



 a| 
Desideri accedere alla finestra di dialogo di configurazione di base?  (sì/no)
 a| 
Rispondere con *sì* alla configurazione iniziale dello switch.



 a| 
Vuoi creare un altro account di accesso?  (sì/no)
 a| 
La risposta dipende dalle policy del tuo sito relative agli amministratori alternativi.  L'impostazione predefinita è *no*.



 a| 
Configurare la stringa di comunità SNMP di sola lettura?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Configurare la stringa di comunità SNMP di lettura-scrittura?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Inserisci il nome dello switch.
 a| 
Immettere il nome dello switch, che è limitato a 63 caratteri alfanumerici.



 a| 
Continuare con la configurazione della gestione fuori banda (mgmt0)?  (sì/no)
 a| 
Rispondere con *sì* (impostazione predefinita) a tale richiesta.  Al prompt mgmt0 IPv4 address:, inserisci il tuo indirizzo IP: ip_address.



 a| 
Configurare il gateway predefinito?  (sì/no)
 a| 
Rispondi con *sì*.  All'indirizzo IPv4 del prompt default-gateway:, immettere default_gateway.



 a| 
Configurare le opzioni IP avanzate?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Abilitare il servizio telnet?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Servizio SSH abilitato?  (sì/no)
 a| 
Rispondi con *sì*.  L'impostazione predefinita è sì.


NOTE: Si consiglia di utilizzare SSH quando si utilizza Ethernet Switch Health Monitor (CSHM) per le sue funzionalità di raccolta dei log.  Per una maggiore sicurezza si consiglia anche l'uso di SSHv2.



 a| 
Inserisci il tipo di chiave SSH che vuoi generare (dsa/rsa/rsa1).
 a| 
Il valore predefinito è *rsa*.



 a| 
Inserire il numero di bit della chiave (1024-2048).
 a| 
Inserisci il numero di bit della chiave da 1024 a 2048.



 a| 
Configurare il server NTP?  (sì/no)
 a| 
Rispondi con *no*.  L'impostazione predefinita è no.



 a| 
Configurare il livello di interfaccia predefinito (L3/L2)
 a| 
Rispondi con *L2*.  Il valore predefinito è L2.



 a| 
Configura lo stato predefinito dell'interfaccia della porta dello switch (shut/noshut)
 a| 
Rispondi con *noshut*.  L'impostazione predefinita è noshut.



 a| 
Configurare il profilo del sistema CoPP (rigoroso/moderato/indulgente/denso)
 a| 
Rispondi con *rigoroso*.  L'impostazione predefinita è rigorosa.



 a| 
Vuoi modificare la configurazione?  (sì/no)
 a| 
A questo punto dovresti vedere la nuova configurazione.  Rivedi e apporta tutte le modifiche necessarie alla configurazione appena inserita.  Se sei soddisfatto della configurazione, rispondi *no* al prompt.  Rispondi *sì* se desideri modificare le impostazioni di configurazione.



 a| 
Utilizzare questa configurazione e salvarla?  (sì/no)
 a| 
Rispondere con *sì* per salvare la configurazione.  In questo modo vengono aggiornate automaticamente le immagini di kickstart e di sistema.


NOTE: Se non si salva la configurazione in questa fase, nessuna delle modifiche sarà effettiva al successivo riavvio dello switch.

|===
. Verificare le scelte di configurazione effettuate nella schermata che appare al termine dell'installazione e assicurarsi di salvare la configurazione.
. Controllare la versione sugli switch di rete del cluster e, se necessario, scaricare la versione del software supportata da NetApp sugli switch dal https://software.cisco.com/download/home["Scarica il software Cisco"^] pagina.


.Cosa succederà ora?
Dopo aver configurato gli switch, puoi link:install-nxos-overview-9336c-cluster.html["prepararsi a installare il software NX-OS e RCF"].
