---
permalink: switch-cisco-9336c-fx2/smart-call-9336c-cluster.html 
sidebar: sidebar 
keywords: cisco smart call,small call home 
summary: Esamina i requisiti e le opzioni di configurazione di Smart Call Home per gli switch cluster Cisco Nexus 9336C-FX2. 
---
= Esamina i requisiti di Smart Call Home per gli switch cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esamina i requisiti per configurare Smart Call Home sugli switch di cluster Cisco Nexus 9336C-FX2 per abilitare le notifiche email automatiche per eventi critici del sistema.

Smart Call Home di Cisco monitora i componenti hardware e software della tua rete. Quando si verifica una configurazione di sistema critica, genera una notifica via email e invia un avviso a tutti i destinatari configurati nel tuo profilo di destinazione.

[NOTE]
====
ONTAP supporta il monitoraggio dello stato di salute degli switch Ethernet (CSHM) per monitorare gli switch del cluster AFX, nonché la possibilità di raccogliere i log diagnostici degli switch.

Smart Call Home di Cisco è un'opzione che offre supporto proattivo e ti aiuta a risolvere eventuali problemi che potrebbero sorgere con gli switch.

====
Prima di poter utilizzare Smart Call Home, è necessario tenere presente i seguenti requisiti:

* Deve essere presente un server di posta elettronica.
* Lo switch deve disporre di connettività IP al server di posta elettronica.
* È necessario configurare il nome del contatto (contatto del server SNMP), il numero di telefono e le informazioni sull'indirizzo.  Ciò è necessario per determinare l'origine dei messaggi ricevuti.
* Un ID CCO deve essere associato a un contratto di servizio Cisco SMARTnet appropriato per la tua azienda.
* Per registrare il dispositivo, è necessario che sia attivo il servizio Cisco SMARTnet.


IL http://www.cisco.com/c/en/us/products/switches/index.html["Sito di supporto Cisco"^] contiene informazioni sui comandi per configurare Smart Call Home.

La funzione Smart Call Home può essere configurata durante l'installazione e la configurazione di un nuovo sistema oppure in un secondo momento.
