---
permalink: switch-bes-53248/complete-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches, upgrade completion, upgrade bes-53248 switch 
summary: Prima di configurare gli switch del cluster BES-53248, esaminare una panoramica del processo e della nomenclatura. 
---
= Completare l'aggiornamento dello switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per completare l'aggiornamento degli switch cluster BES-54328, se applicabile.

. link:configure-ssh.html["Abilitare SSH sugli switch cluster BES-53248"].
+
Se si utilizzano le funzioni di monitoraggio dello stato di salute dello switch del cluster (CSHM) e di raccolta dei log, attivare SSH sugli switch.

. link:configure-log-collection.html["Attivare la funzione di raccolta dei log"].
+
Utilizzare questa funzione per raccogliere i file di log relativi allo switch in ONTAP.

. link:CSHM_snmpv3.html["Configurare SNMPv3 per il monitoraggio"].
+
Se si utilizza la funzione Cluster Switch Health Monitor (CSHM), configurare SNMPv3, che supporta il monitoraggio dello stato degli switch Ethernet (CSHM).


