---
permalink: switch-bes-53248/components-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: 'Per l"installazione e la manutenzione dell"interruttore BES-53248, assicurarsi di rivedere l"elenco dei componenti e i codici articolo.' 
---
= Componenti e numeri di parte per gli switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dell'interruttore BES-53248, assicurarsi di rivedere l'elenco dei componenti e i codici articolo.

Nella tabella seguente sono elencati il ​​codice articolo, la descrizione e le versioni minime EFOS e ONTAP per i componenti dello switch cluster BES-53248, inclusi i dettagli del kit di guide per montaggio su rack.


NOTE: Per i codici articolo *X190005-B* e *X190005R-B* è richiesta una versione EFOS minima *3.10.0.3*.

[cols="20,40,20,20"]
|===
| Numero di parte | Descrizione | Versione minima EFOS | Versione minima ONTAP 


 a| 
X190005-B
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25GB, PTSX (PTSX = scarico lato sinistro)
 a| 
3.10.0.3
 a| 
9,8



 a| 
X190005R-B
 a| 
BES-53248-B/IX8, CLSW, 16PT10/25GB, PSIN (PSIN = ingresso lato porta)
 a| 
3.10.0.3
 a| 
9,8



 a| 
X190005
 a| 
BES-53248, CLSW, 16Pt10/25GB, PTSX, BRDCM SUPP
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X190005R
 a| 
BES-53248, CLSW, 16Pt10/25GB, PSIN, BRDCM SUPP
 a| 
3.4.4.6
 a| 
9.5P8



 a| 
X-RAIL-4POST-190005
 a| 
Kit di montaggio su rack Ozeki 4 montanti 19"
 a| 
N / A
 a| 
N / A

|===

IMPORTANT: Per quanto riguarda i tipi di macchina, tenere presente le seguenti informazioni:

[cols="50,50"]
|===
| Tipo di macchina | Versione minima EFOS 


 a| 
BES-53248A1
| 3.4.4.6 


 a| 
BES-53248A2
| 3.10.0.3 


 a| 
BES-53248A3
| 3.10.0.3 
|===
Puoi determinare il tipo specifico della tua macchina utilizzando il comando: `show version`

.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show version*

Switch: cs1

System Description............................. EFOS, 3.10.0.3, Linux 5.4.2-b4581018, 2016.05.00.07
Machine Type................................... *_BES-53248A3_*
Machine Model.................................. BES-53248
Serial Number.................................. QTWCU225xxxxx
Part Number.................................... 1IX8BZxxxxx
Maintenance Level.............................. a3a
Manufacturer................................... QTMC
Burned In MAC Address.......................... C0:18:50:F4:3x:xx
Software Version............................... 3.10.0.3
Operating System............................... Linux 5.4.2-b4581018
Network Processing Device...................... BCM56873_A0
.
.
.
----
====
.Cosa c'è dopo?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-bes53248.html["documentazione richiesta"].
