---
permalink: switch-bes-53248/configure-software-overview-bes53248.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Esaminare la panoramica del software. 
---
= Workflow di installazione del software per switch BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare e configurare il software per uno switch cluster BES-53248, attenersi alla seguente procedura:

. link:configure-efos-software.html["Installare il software EFOS"].
+
Scaricare e installare il software Ethernet Fabric OS (EFOS) sullo switch cluster BES-53248.

. link:configure-licenses.html["Installare le licenze per gli switch cluster BES-53248"].
+
Facoltativamente, aggiungere nuove porte acquistando e installando ulteriori licenze. Il modello di base dello switch è concesso in licenza per 16 porte 10GbE o 25GbE e due porte 100GbE.

. link:configure-install-rcf.html["Installazione del file di configurazione di riferimento (RCF)"].
+
Installare o aggiornare l'RCF sullo switch del cluster BES-53248, quindi verificare le porte per una licenza aggiuntiva dopo l'applicazione dell'RCF.

. link:configure-ssh.html["Abilitare SSH sugli switch cluster BES-53248"].
+
Se si utilizzano le funzioni CSHM (Ethernet Switch Health Monitor) e di raccolta dei registri, attivare SSH sugli switch.

. link:reset-switch-bes-53248.html["Ripristinare l'interruttore alle impostazioni predefinite di fabbrica"].
+
Cancellare le impostazioni dello switch del cluster BES-53248.


