---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Per installare il software Ethernet Fabric OS (EFOS) sullo switch cluster BES-53248, procedere come segue.' 
---
= Installare il software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare il software Ethernet Fabric OS (EFOS) sullo switch cluster BES-53248, procedere come segue.

Il software EFOS include una serie di funzionalità di rete avanzate e protocolli per lo sviluppo di sistemi di infrastruttura Ethernet e IP. Questa architettura software è adatta a qualsiasi dispositivo organizzativo di rete che utilizzi applicazioni che richiedono un'ispezione completa dei pacchetti o la separazione.



== Preparazione per l'installazione

.Prima di iniziare
* Questa procedura è adatta solo per installazioni nuove.
* Scaricare il software Broadcom EFOS applicabile per gli switch del cluster da https://www.broadcom.com/support/bes-switch["Supporto per switch Ethernet Broadcom"^] sito.
* Assicurarsi che link:configure-install-initial.html["Lo switch del cluster BES-53248 è configurato"].




== Installare il software

Per installare il software EFOS, utilizzare uno dei seguenti metodi:

* <<Metodo 1: Installare EFOS>>. Utilizzare per la maggior parte dei casi.
* <<Metodo 2: Installare EFOS in modalità ONIE>>. Utilizzare se una versione di EFOS è conforme a FIPS e l'altra non è conforme a FIPS.




=== Metodo 1: Installare EFOS

Per installare il software EFOS, procedere come segue.

.Fasi
. Accedere alla porta seriale della console dello switch o connettersi con SSH.
. Utilizzare `ping` Per verificare la connettività al server che ospita EFOS, le licenze e il file RCF.
+
.Mostra esempio
[%collapsible]
====
Questo esempio verifica che lo switch sia connesso al server all'indirizzo IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Scaricare il file immagine sullo switch.
+
Consultare la tabella seguente per informazioni sui protocolli di copia supportati:

+
|===


| *Protocollo* | *Prerequisito* 


 a| 
TFTP (Trivial file Transfer Protocol)
 a| 
Nessuno



 a| 
SFTP (SSH file Transfer Protocol)
 a| 
Il pacchetto software deve supportare una gestione sicura



 a| 
FTP
 a| 
Password obbligatoria



 a| 
XMODEM
 a| 
Nessuno



 a| 
YMODEM
 a| 
Nessuno



 a| 
ZMODEM
 a| 
Nessuno



 a| 
Protocollo SCP (Secure Copy Protocol)
 a| 
Il pacchetto software deve supportare una gestione sicura



 a| 
HTTP
 a| 
Trasferimenti di file basati su CLI supportati su piattaforme selezionate quando è disponibile un'utilità WGET nativa



 a| 
HTTPS
 a| 
Trasferimenti di file basati su CLI supportati su piattaforme selezionate quando è disponibile un'utilità WGET nativa

|===
+
Copiare il file immagine nell'immagine attiva significa che quando si riavvia, l'immagine stabilisce la versione EFOS in esecuzione. L'immagine precedente rimane disponibile come backup.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Visualizzare le immagini di avvio per la configurazione attiva e di backup:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Riavviare lo switch:
+
`reload`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Effettuare nuovamente l'accesso e verificare la nuova versione del software EFOS:
+
`show version`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Completare l'installazione.
Per riconfigurare l'interruttore, procedere come segue:
+
.. link:configure-licenses.html["Installare le licenze"]
.. link:configure-install-rcf.html["Installare il file RCF"]
.. link:configure-ssh.html["Abilitare SSH"]
.. link:CSHM_log_collection.html["Abilitare la raccolta dei log"]
.. link:CSHM_snmpv3.html["Configurare SNMPv3 per il monitoraggio"]


. Ripetere i passaggi da 1 a 7 sullo switch partner.




=== Metodo 2: Installare EFOS in modalità ONIE

Se una versione di EFOS è conforme a FIPS e l'altra non è conforme a FIPS, eseguire le seguenti operazioni. Questa procedura può essere utilizzata per installare l'immagine EFOS 3.7.x.x non conforme a FIPS o FIPS da ONIE in caso di mancato avvio dello switch.

.Fasi
. Collegare a una console collegata alla porta seriale dello switch.
. Avviare lo switch in modalità di installazione ONIE.
+
Durante l'avvio, selezionare ONIE quando viene visualizzato il prompt.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Dopo aver selezionato *ONIE*, lo switch si carica e presenta diverse opzioni. Selezionare *Installa sistema operativo*.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Lo switch si avvia in modalità di installazione ONIE.

. Interrompere il rilevamento ONIE e configurare l'interfaccia Ethernet.
+
Quando viene visualizzato il seguente messaggio, premere *Invio* per richiamare la console ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: Il rilevamento ONIE continua e i messaggi vengono stampati sulla console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configurare l'interfaccia Ethernet della porta di gestione dello switch e aggiungere il routing utilizzando `ifconfig eth0 <ipAddress> netmask <netmask> up` e. `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verificare che il server che ospita il file di installazione ONIE sia raggiungibile:
+
`ping`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installare il nuovo software dello switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Il software installa e riavvia lo switch. Lasciare che lo switch si riavvii normalmente nella nuova versione di EFOS.

. Accedere e verificare che il nuovo software dello switch sia installato:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Completare l'installazione.
Lo switch viene riavviato senza alcuna configurazione applicata e viene ripristinato i valori predefiniti. Per riconfigurare l'interruttore, procedere come segue:
+
.. link:configure-install-initial.html["Configurare lo switch"]
.. link:configure-licenses.html["Installare le licenze"]
.. link:configure-install-rcf.html["Installare il file RCF"]
.. link:configure-ssh.html["Abilitare SSH"]
.. link:CSHM_log_collection.html["Abilitare la raccolta dei log"]
.. link:CSHM_snmpv3.html["Configurare SNMPv3 per il monitoraggio"]


. Ripetere i passaggi da 1 a 8 sullo switch partner.


.Cosa c'è dopo?
link:configure-licenses.html["Installare le licenze"] .
