---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: 'SSH è un requisito per l"utilizzo delle funzionalità di monitoraggio dello stato di salute dello switch del cluster (CSHM) e di raccolta dei log. Per attivare SSH sugli switch cluster BES-53248, generare prima le chiavi SSH e quindi attivare SSH.' 
---
= Abilitare SSH sugli switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizzano le funzioni Ethernet Switch Health Monitor (CSHM) e di raccolta dei log, è necessario generare le chiavi SSH e quindi abilitare SSH sugli switch del cluster.

.Fasi
. Verificare che SSH sia disattivato:
+
`show ip ssh`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
Se SSH non è disabilitato, disabilitarlo come segue:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server disable*
(switch)# *ip scp server disable*
----
====
+

WARNING: Assicuratevi di disabilitare SSH prima di modificare le chiavi, altrimenti verrà segnalato un avviso sullo switch.

. Generare le chiavi SSH:
+
`crypto key generate`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*

(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
(switch)# *write mem*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Crittografare le chiavi SSH (solo per *FIPS-mode*):
+

CAUTION: In modalità FIPS, le chiavi devono essere crittografate con una passphrase per la protezione. In assenza di una chiave crittografata, l'applicazione non si avvia. Le chiavi vengono create e crittografate utilizzando i seguenti comandi:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# end
(switch)# write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Riavviare lo switch:
+
`reload`

. Verificare che SSH sia attivato:
+
`show ip ssh`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.Quali sono le prossime novità?
link:../switch-cshm/config-overview.html["Configurare il monitoraggio dello stato dello switch"]
