---
permalink: switch-bes-53248/configure-health-monitor.html 
sidebar: sidebar 
keywords: CSHM,initial setup,configuration file,cshm,enable SSH 
summary: 'È possibile installare il file di configurazione di Cluster Switch Health Monitor (CSHM), che monitora gli switch del cluster BES-53248.' 
---
= Installare il file di configurazione di Cluster Switch Health Monitor (CSHM)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare il file di configurazione di Cluster Switch Health Monitor (CSHM), che monitora gli switch del cluster BES-53248.

Nelle versioni ONTAP 9.5P7 e precedenti e 9.6P2 e precedenti, è necessario scaricare il file CSHM separatamente. Nelle versioni ONTAP 9.5P8 e successive, 9.6P3 e successive, 9.7 e successive, il file CSHM viene fornito con ONTAP.

.Prima di iniziare
Assicurarsi che il cluster ONTAP sia attivo e in esecuzione.

Per installare il file di configurazione di Cluster Switch Health Monitor (CSHM), procedere come segue.

.Fasi
. Scaricare il file zip di CSHM in base alla versione della release di ONTAP corrispondente. Questo file è disponibile nella pagina: https://mysupport.netapp.com/NOW/cgi-bin/software/["Download del software NetApp"^]
+
.. Nella pagina di download del software, selezionare *Switch Health Monitor Configuration Files*.
.. Selezionare piattaforma = *ONTAP* e fare clic su *Go!*.
.. Nella pagina Cambia file di configurazione del monitor dello stato di salute per ONTAP, fare clic su *Visualizza e scarica*.
.. Nella pagina file di configurazione del monitor dello stato dello switch per ONTAP - Descrizione, fare clic su *Scarica* per il modello di switch cluster applicabile; ad esempio: *BES-53248 supportato da Broadcom*.
.. Nella pagina Contratto di licenza con l'utente finale, fare clic su *Accetta*.
.. Nella ONTAP pagina Download - file di configurazione del monitor dello stato dello switch, selezionare il file di configurazione appropriato, ad esempio *Broadcom_BES-53248.zip*.


. Caricare il file zip applicabile sul server Web interno in cui l'indirizzo IP è X.X.X.X.
+
Per un indirizzo IP interno del server Web 192.168.2.20 e supponendo che esista una directory /usr/download, è possibile caricare il file zip sul server Web utilizzando `scp`:

+
[listing, subs="+quotes"]
----
% *scp Broadcom_BES-53248.zip admin@192.168.2.20:/usr/download/Broadcom_BES-53248.zip*
----
. Accedere all'impostazione della modalità avanzata da uno dei sistemi ONTAP nel cluster, utilizzando il comando `set -privilege advanced`:
+
[listing, subs="+quotes"]
----
cluster1::> *set -privilege advanced*
----
. Eseguire il comando switch Health monitor configure:


[role="tabbed-block"]
====
.Per ONTAP 9.8 e versioni successive
--
`system switch ethernet configure-health-monitor -node * -package-url \http://server/file-location`

[listing]
----
cluster1::> switch ethernet configure-health-monitor -node * -package-url
http://192.168.2.20/usr/download/Broadcom_BES-53248.zip
----
--
.Per ONTAP 9.4 e versioni successive
--
`system cluster-switch configure-health-monitor -node * -package-url \http://server/file-location`

[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url
http://192.168.2.20/usr/download/Broadcom_BES-53248.zip
----
--
====
. [[step5]]verificare che l'output del comando contenga la stringa di testo: `downloaded package processed successfully`. In caso di errore, contattare il supporto NetApp.
. Eseguire il comando sul sistema ONTAP e verificare che gli switch del cluster vengano rilevati con il campo monitorato impostato su "vero":


[role="tabbed-block"]
====
.Per ONTAP 9.8 e versioni successive
--
`system switch ethernet show`

--
.Per ONTAP 9.4 e versioni successive
--
`system cluster-switch show`

--
====

NOTE: Se in qualsiasi momento si ripristina una versione precedente di ONTAP, è necessario installare nuovamente il file di configurazione CSHM per abilitare il monitoraggio dello stato degli switch cluster BES-53248.

.Quali sono le prossime novità?
Per utilizzare tutte le funzioni disponibili in CSHM, attivare SSH come descritto in link:configure-ssh.html["Abilitare SSH sugli switch cluster BES-53248"].
