---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: Il modello base di switch cluster BES-53248 è concesso in licenza per 16 porte 10GbE o 25GbE e due porte 100GbE. È possibile aggiungere nuove porte acquistando più licenze. 
---
= Installare le licenze per gli switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il modello base di switch cluster BES-53248 è concesso in licenza per 16 porte 10GbE o 25GbE e due porte 100GbE. È possibile aggiungere nuove porte acquistando ulteriori licenze.


CAUTION: Per EFOS 3,12 e versioni successive, seguire la procedura di installazione descritta in link:efos-install-rcf-license-file.html["Installare il file di configurazione di riferimento (RCF) e il file di licenza"].



== Esaminare le licenze disponibili

Sullo switch cluster BES-53248 sono disponibili le seguenti licenze:

[cols="1,2,3"]
|===
| Tipo di licenza | Dettagli della licenza | Versione del firmware supportata 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Broadcom 8PT-10G25G + chiave di licenza 2PT-40G100G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Chiave di licenza Broadcom 8 porte 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Chiave di licenza Broadcom a 6 porte 40G100G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive

|===


== Licenze legacy

La seguente tabella elenca le licenze legacy disponibili per l'utilizzo sullo switch cluster BES-53248:

[cols="1,2,3"]
|===
| Tipo di licenza | Dettagli della licenza | Versione del firmware supportata 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25,2P40-100, chiave di licenza, X190005/R.
 a| 
EFOS 3.4.3.3 e versioni successive



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25,4P40-100, chiave di licenza, X190005/R.
 a| 
EFOS 3.4.3.3 e versioni successive



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-25,6P40-100, chiave di licenza, X190005/R.
 a| 
EFOS 3.4.3.3 e versioni successive



 a| 
SW-BES54248-40-100G-LIC
 a| 
Chiave di licenza Broadcom 6Port 40G100G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Chiave di licenza Broadcom 8Port 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Chiave di licenza Broadcom 16 Port 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Chiave di licenza Broadcom 24Port 10G25G, X190005/R.
 a| 
EFOS 3.4.4.6 e versioni successive

|===

NOTE: Non è richiesta una licenza per la configurazione di base.



== Installare i file di licenza

Per installare le licenze per gli switch cluster BES-53248, procedere come segue.

.Fasi
. Collegare lo switch del cluster alla rete di gestione.
. Utilizzare `ping` Per verificare la connettività al server che ospita EFOS, le licenze e il file RCF.
+
.Mostra esempio
[%collapsible]
====
Questo esempio verifica che lo switch sia connesso al server all'indirizzo IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Verificare l'utilizzo corrente della licenza sullo switch cs2:
+
`show license`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. Installare il file di licenza.
+
Ripetere questo passaggio per caricare più licenze e utilizzare numeri di indice delle chiavi diversi.

+
.Mostra esempio
[%collapsible]
====
Nell'esempio seguente viene utilizzato SFTP per copiare un file di licenza in un indice delle chiavi 1.

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. Visualizzare tutte le informazioni sulla licenza corrente e annotare lo stato della licenza prima del riavvio dello switch cs2:
+
`show license`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. Visualizza tutte le porte concesse in licenza:
+
`show port all | exclude Detach`

+
Le porte dei file di licenza aggiuntivi non vengono visualizzate fino a quando lo switch non viene riavviato.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. Riavviare lo switch:
+
`reload`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. Verificare che la nuova licenza sia attiva e notare che la licenza è stata applicata:
+
`show license`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. Verificare che tutte le nuove porte siano disponibili:
+
`show port all | exclude Detach`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: Quando si installano licenze aggiuntive, è necessario configurare manualmente le nuove interfacce. Non riapplicare un RCF a uno switch di produzione funzionante.



== Risolvere i problemi di installazione

Quando si verificano problemi durante l'installazione di una licenza, eseguire i seguenti comandi di debug prima di eseguire `copy` di nuovo comando.

Comandi di debug da utilizzare: `debug transfer` e. `debug license`

.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
Quando si esegue `copy` con il `debug transfer` e. `debug license` opzioni attivate, viene restituito l'output del log.

.Mostra esempio
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
Verificare quanto segue nell'output di debug:

* Verificare che il numero di serie corrisponda a: `Serial number QTFCU38290012 matched.`
* Verificare che il modello dello switch corrisponda a: `Model BES-53248 matched.`
* Verificare che l'indice di licenza specificato non sia stato utilizzato in precedenza. Se è già utilizzato un indice di licenza, viene visualizzato il seguente errore: `License file /mnt/download//license.dat.1 already exists.`
* Una licenza porta non è una licenza funzione. Pertanto, è prevista la seguente dichiarazione: `Feature not found in license file with index = 1.`


Utilizzare `copy` comando per eseguire il backup delle licenze delle porte sul server:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: Se è necessario eseguire il downgrade del software dello switch dalla versione 3.4.4.6, le licenze vengono rimosse. Questo è il comportamento previsto.

È necessario installare una licenza precedente appropriata prima di tornare a una versione precedente del software.



== Attivare le nuove porte con licenza

Per attivare le nuove porte con licenza, è necessario modificare l'ultima versione di RCF e rimuovere i commenti relativi ai dettagli della porta.

La licenza predefinita attiva le porte da 0/1 a 0/16 e da 0/55 a 0/56, mentre le nuove porte con licenza si trovano tra le porte da 0/17 a 0/54, a seconda del tipo e del numero di licenze disponibili. Ad esempio, per attivare la licenza SW-BES54248-40-100G-LIC, è necessario rimuovere i commenti dalla seguente sezione dell'RCF:

.Mostra esempio
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: Per le porte ad alta velocità comprese tra 0/49 e 0/54, rimuovere il commento da ciascuna porta, ma rimuovere solo una linea *speed* nell'RCF per ciascuna di queste porte: *Speed 100G full-duplex* o *speed 40G full-duplex* come mostrato nell'esempio. Per le porte a bassa velocità comprese tra 0/17 e 0/48, rimuovere i commenti dall'intera sezione a 8 porte quando è stata attivata una licenza appropriata.

.Quali sono le prossime novità?
link:configure-install-rcf.html["Installazione del file di configurazione di riferimento (RCF)"] oppure link:upgrade-rcf.html["Aggiornare l'RCF"].
