---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: È possibile utilizzare la tabella di assegnazione delle porte dello switch del cluster BES-53248 come guida per configurare il cluster. 
---
= Requisiti di configurazione per gli switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch BES-53248, assicurarsi di rivedere i requisiti di supporto e configurazione EFOS e ONTAP .



== Supporto EFOS e ONTAP

Vedi il https://hwu.netapp.com/Switch/Index["Hardware Universe NetApp"^] E https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Matrice di compatibilità degli switch Broadcom"^] per informazioni sulla compatibilità EFOS e ONTAP con gli switch BES-53248.  Il supporto EFOS e ONTAP può variare in base al tipo di macchina specifico dello switch BES-53248.  Per i dettagli di tutti i tipi di macchine di commutazione BES-52348, vederelink:components-bes53248.html["Componenti e numeri di parte per gli switch cluster BES-53248"] .



== Requisiti di configurazione

Per configurare un cluster, è necessario disporre del numero e del tipo appropriati di cavi e connettori per gli switch del cluster.  A seconda del tipo di switch cluster che si sta configurando inizialmente, è necessario connettersi alla porta della console dello switch tramite il cavo della console incluso.



=== Assegnazioni delle porte dello switch del cluster

È possibile utilizzare la tabella delle assegnazioni delle porte dello switch del cluster BES-53248 supportata da Broadcom come guida per la configurazione del cluster.

[cols="1,2"]
|===
| Porte di commutazione | Utilizzo delle porte 


 a| 
01-16
 a| 
Nodi porta cluster 10/25GbE, configurazione di base



 a| 
17-48
 a| 
Nodi di porta cluster 10/25GbE, con licenze



 a| 
49-54
 a| 
Nodi porta cluster 40/100GbE, con licenze, aggiunti da destra a sinistra



 a| 
55-56
 a| 
Porte Inter-Switch Link (ISL) del cluster 100GbE, configurazione di base

|===
Vedi il https://hwu.netapp.com/Switch/Index["Hardware Universe"] per maggiori informazioni sulle porte dello switch.



=== Vincolo di velocità del gruppo di porte

* Negli switch cluster BES-53248, le 48 porte 10/25GbE (SFP28/SFP+) sono combinate in 12 gruppi da 4 porte come segue: Porte 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 e 45-48.
* La velocità della porta SFP28/SFP+ deve essere la stessa (10 GbE o 25 GbE) su tutte le porte del gruppo a 4 porte.




=== Requisiti aggiuntivi

* Se acquisti licenze aggiuntive, vedilink:configure-licenses.html["Attiva le nuove porte di licenza"] per i dettagli su come attivarli.
* Se SSH è attivo, è necessario riattivarlo manualmente dopo aver eseguito il comando `erase startup-config` e riavviare lo switch.


.Cosa c'è dopo?
Dopo aver esaminato i requisiti di configurazione, puoi confermare il tuo link:components-bes53248.html["componenti e numeri di parte"].
