---
permalink: switch-bes-53248/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation,BES-53248 Broadcom setup,BES-53248 switches configuration,EFOS 
summary: 'La funzionalità di raccolta dei registri del monitoraggio dello stato di salute dello switch Ethernet (CSHM) viene utilizzata per raccogliere i registri dagli switch di rete di cluster o di storage in ONTAP.' 
---
= Raccolta di log di monitoraggio dello stato dello switch Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il monitoraggio dello stato dello switch Ethernet (CSHM) è responsabile di garantire lo stato operativo degli switch di rete Cluster e Storage e di raccogliere i registri degli switch a scopo di debug.  Questa procedura ti guida attraverso il processo di impostazione e avvio della raccolta di registri dettagliati di *Supporto* dallo switch e avvia una raccolta oraria di dati *Periodici* raccolti da AutoSupport.

.Prima di iniziare
* Per abilitare la funzionalità di raccolta dei log, è necessario eseguire ONTAP versione 9.10.1P15, 9.11.1P12 o 9.12.1 o successiva ed EFOS 3.8.0.2 o successiva.
* Per lo switch deve essere abilitato il monitoraggio dello stato di integrità.  Verificare ciò assicurandosi che `Is Monitored:` il campo è impostato su *true* nell'output del `system switch ethernet show` comando.


.Passi
. Per impostare la raccolta dei log, eseguire il seguente comando per ogni switch.  Ti verrà richiesto di immettere il nome dello switch, il nome utente e la password per la raccolta dei registri.
+
`system switch ethernet log setup-password`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. Per avviare la raccolta dei log, eseguire il comando seguente, sostituendo DEVICE con l'opzione utilizzata nel comando precedente.  In questo modo vengono avviati entrambi i tipi di raccolta dei registri: i registri dettagliati di *Supporto* e una raccolta oraria di dati *Periodici*.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
Attendi 10 minuti e poi verifica che la raccolta dei log sia completata:

+
`system switch ethernet log show`

+

CAUTION: Se uno di questi comandi restituisce un errore o se la raccolta dei log non viene completata, contattare l'assistenza NetApp .



.Risoluzione dei problemi
Se si verifica uno dei seguenti stati di errore segnalati dalla funzionalità di raccolta dei log (visibili nell'output di `system switch ethernet log show` ), provare i passaggi di debug corrispondenti:

|===


| *Stato di errore nella raccolta dei log* | *Risoluzione* 


 a| 
*Chiavi RSA non presenti*
 a| 
Rigenera le chiavi SSH ONTAP . Contattare l'assistenza NetApp .



 a| 
*errore di cambio password*
 a| 
Verificare le credenziali, testare la connettività SSH e rigenerare le chiavi SSH ONTAP .  Per istruzioni, consultare la documentazione dello switch o contattare l'assistenza NetApp .



 a| 
*Chiavi ECDSA non presenti per FIPS*
 a| 
Se la modalità FIPS è abilitata, è necessario generare le chiavi ECDSA sullo switch prima di riprovare.



 a| 
*trovato registro preesistente*
 a| 
Rimuovere il file di raccolta dei registri precedente sullo switch.



 a| 
*errore di cambio registro dump*
 a| 
Assicurarsi che l'utente che effettua lo switch disponga delle autorizzazioni per la raccolta dei log.  Fare riferimento ai prerequisiti sopra indicati.

|===