---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 'La sostituzione di uno switch cluster BES-53248 difettoso supportato da Broadcom in una rete cluster è una procedura non distruttiva \(NDU\).' 
---
= Sostituisci uno switch cluster BES-53248 supportato da Broadcom
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sostituire uno switch cluster BES-53248 difettoso supportato da Broadcom in una rete cluster, seguire questi passaggi. Si tratta di una procedura non distruttiva (NDU).

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi degli switch BES-53248 esistenti sono `cs1` E `cs2` .
* Il nome del nuovo switch BES-53248 è `newcs2` .
* I nomi dei nodi sono `node1` E `node2` .
* Le porte del cluster su ciascun nodo sono denominate `e0a` E `e0b` .
* I nomi LIF del cluster sono `node1_clus1` E `node1_clus2` per il nodo 1 e `node2_clus1` E `node2_clus2` per il nodo 2.
* La richiesta di modifiche a tutti i nodi del cluster è `cluster1::>`


.Informazioni sulla topologia
Questa procedura si basa sulla seguente topologia di rete cluster:

.Mostra topologia di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
====
.Passi
. Rivedere illink:replace-switch-reqs.html["Requisiti di sostituzione"] .
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
dove _x_ è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

. Installare il file di configurazione di riferimento (RCF) e l'immagine appropriati sullo switch, newcs2, ed effettuare le necessarie preparazioni del sito.
+
Se necessario, verificare, scaricare e installare le versioni appropriate del software RCF ed EFOS per il nuovo switch.  Se hai verificato che il nuovo switch è configurato correttamente e non necessita di aggiornamenti del software RCF ed EFOS, continua con il passaggio 2.

+
.. È possibile scaricare il software Broadcom EFOS applicabile per gli switch del cluster da https://www.broadcom.com/support/bes-switch["Supporto per switch Ethernet Broadcom"^] sito.  Seguire i passaggi indicati nella pagina Download per scaricare il file EFOS per la versione del software ONTAP che si sta installando.
.. L'RCF appropriato è disponibile presso https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Switch cluster Broadcom"^] pagina.  Seguire i passaggi indicati nella pagina Download per scaricare il file RCF corretto per la versione del software ONTAP che si sta installando.


. Sul nuovo switch, accedi come `admin` e chiudere tutte le porte che saranno connesse alle interfacce del cluster di nodi (porte da 1 a 16).
+

NOTE: Se hai acquistato licenze aggiuntive per porte aggiuntive, chiudi anche queste porte.

+
Se lo switch che si sta sostituendo non è funzionante ed è spento, i LIF sui nodi del cluster dovrebbero aver già eseguito il failover sull'altra porta del cluster per ciascun nodo.

+

NOTE: Non è richiesta alcuna password per entrare `enable` modalità.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
====
. Verificare che tutti i cluster LIF abbiano `auto-revert` abilitato:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.Mostra topologia di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true
----
====
. Disattivare le porte ISL 0/55 e 0/56 sullo switch BES-53248 cs1:
+
.Mostra topologia di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
====
. Rimuovere tutti i cavi dallo switch BES-53248 cs2, quindi collegarli alle stesse porte sullo switch BES-53248 newcs2.
. Attivare le porte ISL 0/55 e 0/56 tra gli switch cs1 e newcs2, quindi verificare lo stato operativo del canale porta.
+
Lo stato del collegamento per il canale porta 1/1 dovrebbe essere *attivo* e tutte le porte membro dovrebbero essere impostate su True sotto l'intestazione Porta attiva.

+
.Mostra esempio
[%collapsible]
====
Questo esempio abilita le porte ISL 0/55 e 0/56 e visualizza lo stato del collegamento per il canale porta 1/1 sullo switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Sul nuovo switch newcs2, riattivare tutte le porte connesse alle interfacce del cluster di nodi (porte da 1 a 16).
+

NOTE: Se hai acquistato licenze aggiuntive per porte aggiuntive, chiudi anche queste porte.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
====
. Verificare che la porta e0b sia *attiva*:
+
`network port show -ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
L'output dovrebbe essere simile al seguente:

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
====
. Sullo stesso nodo utilizzato nel passaggio precedente, attendi che il cluster LIF node1_clus2 sul nodo 1 venga ripristinato automaticamente.
+
.Mostra esempio
[%collapsible]
====
In questo esempio, LIF node1_clus2 su node1 viene ripristinato correttamente se `Is Home` È `true` e la porta è e0b.

Il seguente comando visualizza informazioni sui LIF su entrambi i nodi.  L'attivazione del primo nodo ha esito positivo se `Is Home` È `true` per entrambe le interfacce del cluster e mostrano le assegnazioni delle porte corrette, in questo esempio `e0a` E `e0b` sul nodo 1.

[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
====
. Visualizza informazioni sui nodi in un cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra che lo stato di salute del nodo per `node1` E `node2` in questo cluster è `true` :

[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
====
. Confermare la seguente configurazione di rete del cluster:
+
`network port show`

+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. Verificare che la rete del cluster sia integra:
+
`show isdp neighbors`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
Dopo aver sostituito gli interruttori, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
