---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 'L"aggiornamento degli switch del cluster BES-53248 inizia con la preparazione del controller per l"aggiornamento, l"installazione del software EFOS, delle licenze e del file di configurazione di riferimento (RCF). Dopo l"installazione, è possibile ripristinare la configurazione del controller in un ambiente di aggiornamento senza interruzioni e senza interruzioni.' 
---
= Aggiornare lo switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiornare lo switch cluster BES-53248, procedere come segue.

Questa procedura si applica a un cluster funzionante e consente un aggiornamento senza interruzioni (NDU) e un ambiente senza interruzioni (NDO).



== Verifica dei requisiti

Prima di installare il software EFOS, le licenze e il file RCF su uno switch cluster NetApp BES-53248 esistente, assicurarsi che:

* Il cluster è un cluster completamente funzionante (nessun messaggio di log degli errori o altri problemi).
* Il cluster non contiene schede di interfaccia di rete (NIC) del cluster difettose.
* Tutte le porte collegate su entrambi gli switch del cluster sono funzionali.
* Tutte le porte del cluster sono installate.
* Tutte le LIF del cluster sono amministrativamente e funzionalmente up-up e sulle loro porte home.
* Le prime due LIF del cluster su ciascun nodo sono configurate su NIC separate e collegate a porte switch del cluster separate.
* ONTAP `cluster ping-cluster -node node1` il comando advanced privilege indica che `larger than PMTU communication` ha successo su tutti i percorsi.



NOTE: Potrebbero esserci dipendenze tra la sintassi dei comandi nelle versioni RCF ed EFOS.


NOTE: Per informazioni sulla compatibilità dello switch, consultare la tabella di compatibilità sul https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Switch di cluster Broadcom"^] Per le versioni supportate di EFOS, RCF e ONTAP.



== Preparare il controller

Seguire questa procedura per preparare il controller per un aggiornamento dello switch del cluster BES-53248.

.Fasi
. Collegare lo switch del cluster alla rete di gestione.
. Utilizzare il comando ping per verificare la connettività al server che ospita EFOS, le licenze e RCF.
+
In caso di problemi, utilizzare una rete non instradata e configurare la porta del servizio utilizzando l'indirizzo IP 192.168.x o 172.19.x. È possibile riconfigurare la porta del servizio in un secondo momento con l'indirizzo IP di gestione della produzione.

+
.Mostra esempio
[%collapsible]
====
Questo esempio verifica che lo switch sia connesso al server all'indirizzo IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Verificare che le porte del cluster siano integre e che il collegamento sia disponibile utilizzando il comando:
+
`network port show -ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra il tipo di output con tutte le porte dotate di `Link` valore di up e a. `Health Status` di salute:

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Verificare che le LIF del cluster siano amministrativamente e funzionalmente aggiornate e risiedano sulle proprie porte home, utilizzando il comando:
+
`network interface show -vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
In questo esempio, il `-vserver` Parameter (parametro): Visualizza le informazioni relative alle LIF associate alle porte del cluster. `Status Admin/Oper` deve essere in su e. `Is Home` deve essere vero:

[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====




== Installare il software

Seguire queste istruzioni per installare il software.

. link:configure-efos-software.html["Installare il software EFOS"]. Scaricare e installare il software Ethernet Fabric OS (EFOS) sullo switch cluster BES-53248.
. link:configure-licenses.html["Installare le licenze per gli switch cluster BES-53248"]. Facoltativamente, aggiungere nuove porte acquistando e installando ulteriori licenze. Il modello di base dello switch è concesso in licenza per 16 porte 10GbE o 25GbE e due porte 100GbE.
. link:configure-install-rcf.html["Installazione del file di configurazione di riferimento (RCF)"]. Installare o aggiornare l'RCF sullo switch del cluster BES-53248, quindi verificare le porte per una licenza aggiuntiva dopo l'applicazione dell'RCF.
. link:configure-health-monitor.html["Installare il file di configurazione di Cluster Switch Health Monitor (CSHM)"]. Installare il file di configurazione applicabile per il monitoraggio dello stato dello switch del cluster.
. link:configure-ssh.html["Abilitare SSH sugli switch cluster BES-53248"]. Se si utilizzano le funzioni di monitoraggio dello stato di salute dello switch del cluster (CSHM) e di raccolta dei log, attivare SSH sugli switch.
. link:configure-log-collection.html["Attivare la funzione di raccolta dei log"]. Utilizzare questa funzione per raccogliere i file di log relativi allo switch in ONTAP.

