---
permalink: switch-bes-53248/replace-switch-reqs.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 'La sostituzione di uno switch cluster BES-53248 difettoso supportato da Broadcom in una rete cluster è una procedura non distruttiva \(NDU\).' 
---
= Requisiti di sostituzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire l'interruttore, assicurarsi che le seguenti condizioni siano soddisfatte nell'ambiente attuale e sull'interruttore sostitutivo.



== Cluster esistente e infrastruttura di rete

Assicurarsi che:

* Il cluster esistente è stato verificato come completamente funzionale, con almeno uno switch del cluster completamente connesso.
* Tutte le porte del cluster sono *attive*.
* Tutte le interfacce logiche del cluster (LIF) sono amministrativamente e operativamente *attive* e sulle loro porte home.
* L' ONTAP `cluster ping-cluster -node node1` il comando deve indicare che le impostazioni, `basic connectivity` E `larger than PMTU communication` , hanno successo su tutti i percorsi.




== Interruttore cluster sostitutivo BES-53248

Assicurarsi che:

* La connettività della rete di gestione sullo switch sostitutivo è funzionante.
* L'accesso alla console per l'interruttore sostitutivo è pronto.
* Le connessioni dei nodi sono le porte da 0/1 a 0/16 con licenza predefinita.
* Tutte le porte Inter-Switch Link (ISL) sono disabilitate sulle porte 0/55 e 0/56.
* Il file di configurazione di riferimento desiderato (RCF) e l'immagine dello switch del sistema operativo EFOS vengono caricati sullo switch.
* La personalizzazione iniziale dello switch è completa, come dettagliato inlink:configure-install-initial.html["Configurare lo switch cluster BES-53248"] .


Tutte le personalizzazioni precedenti del sito, come STP, SNMP e SSH, vengono copiate sul nuovo switch.



== Abilita la registrazione della console

NetApp consiglia vivamente di abilitare la registrazione della console sui dispositivi utilizzati e di adottare le seguenti misure quando si sostituisce lo switch:

* Lasciare AutoSupport abilitato durante la manutenzione.
* Attivare un AutoSupport di manutenzione prima e dopo la manutenzione per disattivare la creazione di casi per tutta la durata della manutenzione.  Vedi questo articolo della Knowledge Base https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Come sopprimere la creazione automatica dei casi durante le finestre di manutenzione programmata"^] per ulteriori dettagli.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI.  Per istruzioni su come abilitare la registrazione della sessione, consultare la sezione "Registrazione dell'output della sessione" in questo articolo della Knowledge Base https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^] .




== Per maggiori informazioni

* https://mysupport.netapp.com/["Sito di supporto NetApp"^]
* https://hwu.netapp.com/Home/Index["Hardware Universe NetApp"^]

