---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Per impostare la configurazione Cluster-Mode è necessaria la documentazione specifica dello switch e del controller. 
---
= Requisiti di documentazione per gli switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch BES-53248, assicurarsi di consultare la documentazione specifica dello switch e del controller.



== Documentazione Broadcom

Per configurare lo switch cluster BES-53248, sono necessari i seguenti documenti, disponibili sul sito di supporto Broadcom: https://www.broadcom.com/support/bes-switch["Linea di prodotti Broadcom Ethernet Switch"^]

[cols="1,2"]
|===
| Titolo del documento | Descrizione 


 a| 
_Guida dell'amministratore di EFOS v3.4.3_
 a| 
Fornisce esempi di come utilizzare lo switch BES-53248 in una rete tipica.



 a| 
_Riferimento ai comandi CLI EFOS v3.4.3_
 a| 
Descrive i comandi dell'interfaccia della riga di comando (CLI) utilizzati per visualizzare e configurare il software BES-53248.



 a| 
_Guida introduttiva a EFOS v3.4.3_
 a| 
Fornisce informazioni dettagliate sullo switch BES-53248.



 a| 
_Guida di riferimento SNMP EFOS v3.4.3_
 a| 
Fornisce esempi di come utilizzare lo switch BES-53248 in una rete tipica.



 a| 
_Parametri e valori di ridimensionamento EFOS v3.4.3_
 a| 
Descrive i parametri di ridimensionamento predefiniti con cui il software EFOS viene distribuito e convalidato sulle piattaforme supportate.



 a| 
_Specifiche funzionali EFOS v3.4.3_
 a| 
Descrive le specifiche del software EFOS sulle piattaforme supportate.



 a| 
Note sulla versione EFOS v3.4.3
 a| 
Fornisce informazioni specifiche sulla versione del software BES-53248.



 a| 
_Matrice di compatibilità della rete di cluster e della rete di gestione_
 a| 
Fornisce informazioni sulla compatibilità di rete.  La matrice è disponibile sul sito di download dello switch BES-53248 all'indirizzo https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Switch cluster Broadcom"^] .

|===


== Documentazione dei sistemi ONTAP e articoli della Knowledge Base

Per configurare un sistema ONTAP , sono necessari i seguenti documenti dal sito di supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^] o il sito della Knowledgebase (KB) all'indirizzo https://kb.netapp.com/["kb.netapp.com"^] .

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
https://hwu.netapp.com/Home/Index["Hardware Universe NetApp"^]
 a| 
Descrive i requisiti di alimentazione e di sito per tutto l'hardware NetApp , compresi gli armadi di sistema, e fornisce informazioni sui connettori e sulle opzioni di cavi pertinenti da utilizzare, insieme ai relativi codici articolo.



 a| 
Istruzioni di installazione e configurazione specifiche del controller
 a| 
Descrive come installare l'hardware NetApp .



 a| 
ONTAP 9
 a| 
Fornisce informazioni dettagliate su tutti gli aspetti della versione ONTAP 9.



 a| 
_Come aggiungere licenze di porta aggiuntive per lo switch BES-53248 supportato da Broadcom_
 a| 
Fornisce informazioni dettagliate sull'aggiunta di licenze di porta.  Vai al https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Articolo della Knowledge Base"^] .

|===