---
permalink: switch-bes-53248/reset-switch-bes-53248.html 
sidebar: sidebar 
keywords: BES-53248 reset switch to factory defaults, BES-53248 switches configuration, efos 
summary: Prima di configurare lo switch Broadcom BES-53248, leggere le seguenti informazioni. 
---
= Ripristinare lo switch del cluster BES-53248 ai valori predefiniti di fabbrica
:allow-uri-read: 


[role="lead"]
Per ripristinare le impostazioni predefinite di fabbrica dello switch cluster BES-53248, è necessario cancellare le impostazioni dello switch BES-53248.

.Informazioni su questo compito
* È necessario connettersi allo switch tramite la console seriale.
* Questa attività reimposta la configurazione della rete di gestione.


.Passi
. Passare al prompt dei comandi con privilegi elevati.
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)#
----
. Cancella la configurazione di avvio.
+
`erase startup-config`

+
[listing, subs="+quotes"]
----
(cs2)# *erase startup-config*

Are you sure you want to clear the configuration? (y/n) *y*
----
. Riavviare lo switch.
+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
----



NOTE: Se il sistema chiede se salvare la configurazione non salvata o modificata prima di ricaricare lo switch, selezionare *No*.

. [[step4]] Attendi che lo switch si ricarichi, quindi accedi allo switch.
+
L'utente predefinito è "admin" e non è impostata alcuna password.  Viene visualizzato un messaggio simile al seguente:

+
[listing]
----
(Routing)>
----

