---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Per aggiornare il software Ethernet Fabric OS (EFOS) sullo switch cluster BES-53248, seguire questi passaggi.' 
---
= Aggiorna il software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiornare il software EFOS sullo switch cluster BES-53248, seguire questi passaggi.

Il software EFOS include una serie di funzionalità e protocolli di rete avanzati per lo sviluppo di sistemi infrastrutturali Ethernet e IP.  Questa architettura software è adatta a qualsiasi dispositivo organizzativo di rete che utilizzi applicazioni che richiedono un'ispezione o una separazione completa dei pacchetti.



== Preparati per l'aggiornamento

.Prima di iniziare
* Scarica il software Broadcom EFOS applicabile per i tuoi switch cluster da https://www.broadcom.com/support/bes-switch["Supporto per switch Ethernet Broadcom"^] sito.
* Rivedere le seguenti note relative alle versioni EFOS.


[]
====
*Nota quanto segue:*

* Quando si esegue l'aggiornamento da EFOS 3.4.xx a EFOS 3.7.xx o versione successiva, lo switch deve eseguire EFOS 3.4.4.6 (o versione successiva 3.4.xx).  Se si utilizza una versione precedente a questa, aggiornare prima lo switch a EFOS 3.4.4.6 (o versione successiva 3.4.xx), quindi aggiornare lo switch a EFOS 3.7.xx o versione successiva.
* La configurazione per EFOS 3.4.xx e 3.7.xx o versioni successive è diversa.  Per modificare la versione EFOS da 3.4.xx a 3.7.xx o successiva, o viceversa, è necessario ripristinare le impostazioni predefinite di fabbrica e (ri)applicare i file RCF per la versione EFOS corrispondente.  Questa procedura richiede l'accesso tramite la porta della console seriale.
* A partire dalla versione EFOS 3.7.xx o successiva, è disponibile una versione non conforme a FIPS e una conforme a FIPS.  Quando si passa da una versione non conforme a FIPS a una conforme a FIPS o viceversa, si applicano passaggi diversi.  La modifica di EFOS da una versione non conforme a FIPS a una conforme a FIPS o viceversa ripristinerà le impostazioni predefinite di fabbrica dello switch.  Questa procedura richiede l'accesso tramite la porta della console seriale.


====
|===


| *Procedura* | *Versione EFOS corrente* | *Nuova versione EFOS* | *Passi di alto livello* 


 a| 
Passaggi per aggiornare EFOS tra due versioni (non) conformi a FIPS
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Aggiorna la nuova immagine EFOS utilizzando<<Metodo 1: Aggiorna EFOS>> .  Le informazioni sulla configurazione e sulla licenza vengono conservate.



 a| 
3.4.4.6 (o versione successiva 3.4.xx)
 a| 
3.7.xx o versione successiva non conforme a FIPS
 a| 
Aggiorna EFOS utilizzando<<Metodo 1: Aggiorna EFOS>> .  Ripristinare le impostazioni predefinite di fabbrica dello switch e applicare il file RCF per EFOS 3.7.xx o versioni successive.



.2+| 3.7.xx o versione successiva non conforme a FIPS  a| 
3.4.4.6 (o versione successiva 3.4.xx)
 a| 
Eseguire il downgrade di EFOS utilizzando<<Metodo 1: Aggiorna EFOS>> .  Ripristinare l'interruttore alle impostazioni predefinite di fabbrica e applicare il file RCF per EFOS 3.4.xx



 a| 
3.7.xx o versione successiva non conforme a FIPS
 a| 
Aggiorna la nuova immagine EFOS utilizzando<<Metodo 1: Aggiorna EFOS>> .  Le informazioni sulla configurazione e sulla licenza vengono conservate.



 a| 
3.7.xx o versione successiva conforme a FIPS
 a| 
3.7.xx o versione successiva conforme a FIPS
 a| 
Aggiorna la nuova immagine EFOS utilizzando<<Metodo 1: Aggiorna EFOS>> .  Le informazioni sulla configurazione e sulla licenza vengono conservate.



 a| 
Passaggi per l'aggiornamento a/da una versione EFOS conforme a FIPS
 a| 
Non conforme a FIPS
 a| 
Conforme a FIPS
 a| 
Aggiornamento dell'immagine EFOS utilizzando<<Metodo 2: Aggiornare EFOS utilizzando l'installazione del sistema operativo ONIE>> .  La configurazione dello switch e le informazioni sulla licenza andranno perse.



 a| 
Conforme a FIPS
 a| 
Non conforme a FIPS

|===
[IMPORTANT]
====
Per verificare se la tua versione di EFOS è conforme o non conforme a FIPS, usa `show fips status` comando.  Negli esempi seguenti, *IP_switch_a1* utilizza EFOS conforme a FIPS e *IP_switch_a2* utilizza EFOS non conforme a FIPS.

* Sullo switch IP_switch_a1 (EFOS conforme a FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* Sullo switch IP_switch_a2 (EFOS non conforme a FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Aggiorna il software

Utilizzare uno dei seguenti metodi:

* <<Metodo 1: Aggiorna EFOS>>. Da utilizzare nella maggior parte dei casi (vedere la tabella sopra).
* <<Metodo 2: Aggiornare EFOS utilizzando l'installazione del sistema operativo ONIE>>. Utilizzare se una versione di EFOS è conforme a FIPS e l'altra non lo è.



NOTE: Aggiornare EFOS su uno switch alla volta per garantire il funzionamento continuo della rete cluster.



=== Metodo 1: Aggiorna EFOS

Per aggiornare il software EFOS, procedere come segue.


IMPORTANT: Si noti che dopo l'aggiornamento degli switch cluster BES-53248 da EFOS 3.3.xx o 3.4.xx a EFOS 3.7.0.4 o 3.8.0.2, i collegamenti inter-switch (ISL) e i canali delle porte vengono contrassegnati nello stato *Down*.  Si tratta di un comportamento previsto ed è possibile continuare l'aggiornamento in tutta sicurezza, a meno che non si riscontrino problemi con i LIF di ripristino automatico.  Consultare l'articolo della Knowledge Base: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248 Cluster Switch NDU non è riuscito ad aggiornare a EFOS 3.7.0.4 e versioni successive"^] per ulteriori dettagli.

.Passi
. Collegare lo switch cluster BES-53248 alla rete di gestione.
. Utilizzare il `ping` comando per verificare la connettività al server che ospita EFOS, le licenze e il file RCF.
+
Questo esempio verifica che lo switch sia connesso al server all'indirizzo IP 172.19.2.1:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Disabilitare il ripristino automatico sui LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Visualizza le immagini di avvio per la configurazione attiva e di backup:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. Scarica il file immagine sullo switch.
+
Copiando il file immagine nell'immagine di backup, al riavvio tale immagine stabilisce la versione EFOS in esecuzione, completando l'aggiornamento.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Visualizza le immagini di avvio per la configurazione attiva e di backup:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.10.0.3            3.7.0.4       3.10.0.3
----
====
. Avviare il sistema dalla configurazione di backup:
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. Visualizza le immagini di avvio per la configurazione attiva e di backup:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. Salvare la configurazione in esecuzione nella configurazione di avvio:
+
`write memory`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. Riavviare lo switch:
+
`reload`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Effettua nuovamente l'accesso e verifica la nuova versione del software EFOS:
+
`show version`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Ripetere i passaggi da 5 a 11 sullo switch cs1.
. Abilita il ripristino automatico sui LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verificare che i LIF del cluster siano tornati alla loro porta home:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Per ulteriori dettagli, vederelink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Ripristinare un LIF alla sua porta di origine"] .





=== Metodo 2: Aggiornare EFOS utilizzando l'installazione del sistema operativo ONIE

È possibile eseguire i seguenti passaggi se una versione di EFOS è conforme a FIPS e l'altra non lo è.  Questi passaggi possono essere utilizzati per aggiornare l'immagine EFOS 3.7.xx non FIPS o conforme a FIPS da ONIE se lo switch non riesce ad avviarsi.


NOTE: Questa funzionalità è disponibile solo per EFOS 3.7.xx o versioni successive non conformi a FIPS.


CAUTION: Se si aggiorna EFOS tramite l'installazione del sistema operativo ONIE, la configurazione viene ripristinata ai valori predefiniti di fabbrica e le licenze vengono eliminate.  Per ripristinare il normale funzionamento dello switch, è necessario configurare lo switch e installare le licenze e un RCF supportato.

.Passi
. Disabilitare il ripristino automatico sui LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Avviare lo switch in modalità di installazione ONIE.
+
Durante l'avvio, seleziona ONIE quando vedi il prompt:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Dopo aver selezionato *ONIE*, l'interruttore si carica e ti presenta diverse scelte.  Selezionare *Installa sistema operativo*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Lo switch si avvia in modalità di installazione ONIE.

. Interrompere la scoperta ONIE e configurare l'interfaccia Ethernet.
+
Quando viene visualizzato il seguente messaggio, premere *Invio* per richiamare la console ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: La scoperta ONIE continua e i messaggi vengono stampati sulla console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configurare l'interfaccia Ethernet e aggiungere il percorso utilizzando `ifconfig eth0 <ipAddress> netmask <netmask> up` E `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verificare che il server che ospita il file di installazione ONIE sia raggiungibile:
+
`ping`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installa il nuovo software dello switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Il software installa e poi riavvia lo switch.  Lasciare che lo switch si riavvii normalmente nella nuova versione EFOS.

. Verificare che il nuovo software dello switch sia installato:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Completare l'installazione.  Lo switch si riavvia senza alcuna configurazione applicata e ripristina le impostazioni predefinite di fabbrica.  Per riconfigurare lo switch, completare i seguenti passaggi:
+
.. link:configure-licenses.html["Installa le licenze"]
.. link:configure-install-rcf.html["Installare l'RCF"]
.. link:configure-ssh.html["Abilita SSH"]
.. link:CSHM_log_collection.html["Abilita la raccolta dei log"]
.. link:CSHM_snmpv3.html["Configurare SNMPv3 per il monitoraggio"]


. Ripetere i passaggi da 2 a 8 sullo switch cs1.
. Abilita il ripristino automatico sui LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verificare che i LIF del cluster siano tornati alla loro porta home:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Per ulteriori dettagli, vederelink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Ripristinare un LIF alla sua porta di origine"] .


