---
permalink: switch-bes-53248/upgrade-switch-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: Prima di configurare gli switch del cluster BES-53248, esaminare una panoramica del processo e della nomenclatura. 
---
= Panoramica del processo di aggiornamento per gli switch cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per aggiornare il software EFOS e i file di configurazione di riferimento (RCF) sugli switch cluster Broadcom BES-54328, se pertinente.

. link:upgrade-efos-software.html["Aggiornare la versione EFOS"]
+
Scaricare e installare il software Ethernet Fabric OS (EFOS) sullo switch cluster BES-53248.

. link:upgrade-rcf.html["Aggiornare la versione RCF"]
+
Aggiornare l'RCF sullo switch del cluster BES-53248, quindi verificare la presenza di una licenza aggiuntiva nelle porte dopo l'applicazione dell'RCF.

. link:replace-verify.html["Verificare la rete del cluster ONTAP dopo l'aggiornamento"]
+
Verificare lo stato della rete cluster ONTAP dopo un aggiornamento del software EFOS o RCF per gli switch del cluster BES-53248.


