---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Per aggiornare il software EFOS (Ethernet Fabric OS) sullo switch del cluster BES-53248, procedere come segue.' 
---
= Aggiornare il software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiornare il software EFOS sullo switch del cluster BES-53248, procedere come segue.

Il software EFOS include una serie di funzionalità di rete avanzate e protocolli per lo sviluppo di sistemi di infrastruttura Ethernet e IP. Questa architettura software è adatta a qualsiasi dispositivo organizzativo di rete che utilizzi applicazioni che richiedono un'ispezione completa dei pacchetti o la separazione.



== Preparatevi per l'aggiornamento

.Prima di iniziare
* Scaricare il software Broadcom EFOS applicabile per gli switch del cluster da https://www.broadcom.com/support/bes-switch["Supporto per switch Ethernet Broadcom"^] sito.
* Leggere le seguenti note relative alle versioni di EFOS.


[]
====
*Nota:*

* Quando si esegue l'aggiornamento da EFOS 3.4.x.x a EFOS 3.7.x.x o versioni successive, lo switch deve eseguire EFOS 3.4.4.6 (o versioni successive 3.4.x.x). Se si esegue una release precedente, aggiornare prima lo switch a EFOS 3.4.4.6 (o versione successiva 3.4.x.x), quindi aggiornare lo switch a EFOS 3.7.x.x o versione successiva.
* La configurazione per EFOS 3.4.x.x e 3.7.x.x o versioni successive è diversa. Se si modifica la versione di EFOS da 3.4.x.x a 3.7.x.x o successiva o viceversa, è necessario ripristinare le impostazioni predefinite dello switch e applicare nuovamente i file RCF per la versione di EFOS corrispondente. Questa procedura richiede l'accesso tramite la porta seriale della console.
* A partire dalla versione EFOS 3.7.x.x o successiva, è disponibile una versione non conforme a FIPS e una conforme a FIPS. Quando si passa da una versione non conforme a FIPS a una versione conforme a FIPS o viceversa, si applicano diversi passaggi. Se si cambia EFOS da una versione non conforme a FIPS a una conforme a FIPS o viceversa, si ripristinano le impostazioni predefinite dello switch. Questa procedura richiede l'accesso tramite la porta seriale della console.


====
|===


| *Procedura* | *Versione EFOS corrente* | *Nuova versione EFOS* | *Fasi di alto livello* 


 a| 
Procedura per l'aggiornamento di EFOS tra due versioni (non) conformi a FIPS
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Aggiornare la nuova immagine EFOS utilizzando <<Metodo 1: Aggiornamento EFOS>>.
Le informazioni di configurazione e licenza vengono conservate.



 a| 
3.4.4.6 (o versione successiva 3.4.x.x)
 a| 
3.7.x.x o versioni successive non conformi a FIPS
 a| 
Aggiorna EFOS utilizzando <<Metodo 1: Aggiornamento EFOS>>.
Ripristinare le impostazioni predefinite dello switch e applicare il file RCF per EFOS 3.7.x.x o versioni successive.



.2+| 3.7.x.x o versioni successive non conformi a FIPS  a| 
3.4.4.6 (o versione successiva 3.4.x.x)
 a| 
Eseguire il downgrade di EFOS con <<Metodo 1: Aggiornamento EFOS>>.
Ripristinare le impostazioni predefinite dello switch e applicare il file RCF per EFOS 3.4.x.x.



 a| 
3.7.x.x o versioni successive non conformi a FIPS
 a| 
Aggiornare la nuova immagine EFOS utilizzando <<Metodo 1: Aggiornamento EFOS>>. Le informazioni di configurazione e licenza vengono conservate.



 a| 
3.7.x.x o successivo conforme a FIPS
 a| 
3.7.x.x o successivo conforme a FIPS
 a| 
Aggiornare la nuova immagine EFOS utilizzando <<Metodo 1: Aggiornamento EFOS>>.
Le informazioni di configurazione e licenza vengono conservate.



 a| 
Procedura per l'aggiornamento a/da una versione EFOS conforme a FIPS
 a| 
Non conforme a FIPS
 a| 
Conforme a FIPS
 a| 
Aggiornamento dell'immagine EFOS utilizzando <<Metodo 2: Aggiornare EFOS utilizzando l'installazione del sistema operativo ONIE>>. La configurazione dello switch e le informazioni sulla licenza andranno perse.



 a| 
Conforme a FIPS
 a| 
Non conforme a FIPS

|===
[IMPORTANT]
====
Per verificare se la versione di EFOS in uso è conforme a FIPS o non conforme a FIPS, utilizzare `show fips status` comando. Negli esempi seguenti, *IP_switch_a1* utilizza EFOS conforme a FIPS e *IP_switch_a2* utilizza EFOS non conforme a FIPS.

* Sullo switch IP_switch_A1 (EFOS conforme a FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* Sullo switch IP_switch_A2 (EFOS non conforme a FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Aggiornare il software

Utilizzare uno dei seguenti metodi:

* <<Metodo 1: Aggiornamento EFOS>>. Utilizzare per la maggior parte dei casi (vedere la tabella precedente).
* <<Metodo 2: Aggiornare EFOS utilizzando l'installazione del sistema operativo ONIE>>. Utilizzare se una versione di EFOS è conforme a FIPS e l'altra non è conforme a FIPS.



NOTE: Aggiornare EFOS su uno switch alla volta per garantire il funzionamento continuo della rete cluster.



=== Metodo 1: Aggiornamento EFOS

Per aggiornare il software EFOS, procedere come segue.


IMPORTANT: Si noti che dopo l'aggiornamento degli switch cluster BES-53248 da EFOS 3.3.x.x o 3.4.x.x a EFOS 3.7.0.4 o 3.8.0.2, i collegamenti Inter-Switch (ISL) e il canale della porta sono contrassegnati nello stato *down*. Consulta questo articolo della Knowledge base: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248 Cluster Switch NDU non ha eseguito l'aggiornamento a EFOS 3.7.0.4 e versioni successive"^] per ulteriori dettagli.

.Fasi
. Collegare lo switch del cluster BES-53248 alla rete di gestione.
. Utilizzare `ping` Per verificare la connettività al server che ospita EFOS, le licenze e il file RCF.
+
Questo esempio verifica che lo switch sia connesso al server all'indirizzo IP 172.19.2.1:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Disattiva l'autorevert sulle LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Visualizzare le immagini di avvio per la configurazione attiva e di backup:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4

----
====
. Backup dell'immagine attiva corrente su cs2:
+
[source, cli]
----
copy active backup
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy active backup*
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :
 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4
(cs2)#
----
====
. Verificare la versione in esecuzione del software EFOS:
+
`show version`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.7.0.4, Linux 4.4.117-ceeeb99d, 2016.05.00.05
Machine Type................................... BES-53248A1
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.7.0.4
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
+

NOTE: Se sono state installate licenze, verificare il relativo stato.

. Scaricare il file immagine sullo switch.
+
Copiare il file immagine nell'immagine attiva significa che quando si riavvia, l'immagine stabilisce la versione EFOS in esecuzione. L'immagine precedente rimane disponibile come backup.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Visualizzare le immagini di avvio per la configurazione attiva e di backup:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Riavviare lo switch:
+
`reload`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Effettuare nuovamente l'accesso e verificare la nuova versione del software EFOS:
+
`show version`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Ripetere i passi da 5 a 10 sull'interruttore CS1.
. Abilitare il ripristino automatico sulle LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verificare che le LIF del cluster siano tornate alla porta home:
+
[source, cli]
----
network interface show -role Cluster
----
+
Per ulteriori dettagli, vedere link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Ripristinare la porta home di un LIF"].





=== Metodo 2: Aggiornare EFOS utilizzando l'installazione del sistema operativo ONIE

Se una versione di EFOS è conforme a FIPS e l'altra non è conforme a FIPS, eseguire le seguenti operazioni. Questi passaggi possono essere utilizzati per aggiornare l'immagine EFOS 3,7.x.x non conforme a FIPS o FIPS da ONIE in caso di mancato avvio dello switch.


NOTE: Questa funzionalità è disponibile solo per EFOS 3.7.x.x o versioni successive non conformi a FIPS.


CAUTION: Se si aggiorna EFOS utilizzando l'installazione ONIE OS, la configurazione viene ripristinata ai valori predefiniti e le licenze vengono eliminate. È necessario impostare lo switch e installare le licenze e un RCF supportato per riportare lo switch al normale funzionamento.

.Fasi
. Disattiva l'autorevert sulle LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Avviare lo switch in modalità di installazione ONIE.
+
Durante l'avvio, selezionare ONIE quando viene visualizzato il prompt:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Dopo aver selezionato *ONIE*, lo switch si carica e presenta diverse opzioni. Selezionare *Installa sistema operativo*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Lo switch si avvia in modalità di installazione ONIE.

. Interrompere il rilevamento ONIE e configurare l'interfaccia Ethernet.
+
Quando viene visualizzato il seguente messaggio, premere *Invio* per richiamare la console ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: Il rilevamento ONIE continua e i messaggi vengono stampati sulla console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configurare l'interfaccia Ethernet e aggiungere il percorso utilizzando `ifconfig eth0 <ipAddress> netmask <netmask> up` e. `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verificare che il server che ospita il file di installazione ONIE sia raggiungibile:
+
`ping`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Installare il nuovo software dello switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
Il software installa e riavvia lo switch. Lasciare che lo switch si riavvii normalmente nella nuova versione di EFOS.

. Verificare che il nuovo software dello switch sia installato:
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Completare l'installazione. Lo switch viene riavviato senza alcuna configurazione applicata e viene ripristinato i valori predefiniti. Completare i seguenti passaggi per riconfigurare l'interruttore:
+
.. link:configure-licenses.html["Installare le licenze"]
.. link:configure-install-rcf.html["Installare RCF"]
.. link:configure-ssh.html["Abilitare SSH"]
.. link:CSHM_log_collection.html["Abilitare la raccolta dei log"]
.. link:CSHM_snmpv3.html["Configurare SNMPv3 per il monitoraggio"]


. Ripetere i passi da 2 a 8 sull'interruttore CS1.
. Abilitare il ripristino automatico sulle LIF del cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verificare che le LIF del cluster siano tornate alla porta home:
+
[source, cli]
----
network interface show -role Cluster
----
+
Per ulteriori dettagli, vedere link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Ripristinare la porta home di un LIF"].


