---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Prima di configurare gli switch Cisco Nexus 3132q-v, rivedere una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Gli switch Cisco Nexus 3132Q-V possono essere utilizzati come switch cluster nel cluster AFF o FAS . Gli switch cluster consentono di creare cluster ONTAP con più di due nodi.

[NOTE]
====
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

====
Per maggiori informazioni, vedere:

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Pagina di descrizione NetApp CN1601 e CN1610"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Pagina di descrizione dello switch Ethernet Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Requisiti CN1610

Sono supportati i seguenti switch cluster:

* NetApp CN1610
* Cisco Nexus 3132Q-V


Gli switch del cluster supportano le seguenti connessioni di nodo:

* NetApp CN1610: porte da 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3132Q-V: porte e1/1-30 (40/100 GbE)


Gli switch del cluster utilizzano le seguenti porte di collegamento inter-switch (ISL):

* NetApp CN1610: porte da 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3132Q-V: porte e1/31-32 (40/100 GbE)
+
ILlink:https://hwu.netapp.com/["Hardware Universe"^] contiene informazioni sul cablaggio supportato per gli switch Nexus 3132Q-V:

* I nodi con connessioni cluster da 10 GbE richiedono cavi breakout in fibra ottica da QSFP a SFP+ o cavi breakout in rame da QSFP a SFP+
* I nodi con connessioni cluster 40/100 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra ottica o cavi di collegamento diretto in rame QSFP/QSFP28


Il cablaggio ISL appropriato è il seguente:

* Inizio: per CN1610 a CN1610 (SFP+ a SFP+), quattro cavi SFP+ in fibra ottica o rame a collegamento diretto
* Interim: per CN1610 a Nexus 3132Q-V (breakout da QSFP a quattro SFP+), un cavo breakout in fibra ottica o rame da QSFP a SFP+
* Finale: per Nexus 3132Q-V a Nexus 3132Q-V (da QSFP28 a QSFP28), due cavi QSFP28 in fibra ottica o rame a collegamento diretto


I cavi twinax NetApp non sono compatibili con gli switch Cisco Nexus 3132Q-V.

Se la configurazione CN1610 attuale utilizza cavi twinax NetApp per connessioni cluster-nodo-switch o connessioni ISL e si desidera continuare a utilizzare twinax nel proprio ambiente, è necessario procurarsi cavi twinax Cisco .  In alternativa, è possibile utilizzare cavi in ​​fibra ottica sia per le connessioni ISL sia per le connessioni cluster-nodo-switch.

.Informazioni sugli esempi utilizzati
Gli esempi in questa procedura descrivono la sostituzione degli switch CN1610 con gli switch Cisco Nexus 3132Q-V.  È possibile utilizzare questi passaggi (con modifiche) anche per altri switch Cisco meno recenti.

La procedura utilizza anche la seguente nomenclatura di switch e nodi:

* Gli output dei comandi potrebbero variare a seconda delle diverse versioni di ONTAP.
* Gli switch CN1610 da sostituire sono *CL1* e *CL2*.
* Gli switch Nexus 3132Q-V che sostituiranno gli switch CN1610 sono *C1* e *C2*.
* *n1_clus1* è la prima interfaccia logica del cluster (LIF) connessa allo switch del cluster 1 (CL1 o C1) per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo *n1*.
* *n1_clus3* è il secondo LIF connesso allo switch cluster 2 (CL2 o C2) per il nodo *n1*.
* *n1_clus4* è il secondo LIF connesso allo switch cluster 1 (CL1 o C1) per il nodo *n1*.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili sul https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download del file di configurazione di riferimento dello switch di rete Cisco® Cluster"^] pagina.
* I nodi sono *n1*, *n2*, *n3* e *n4*.


Gli esempi in questa procedura utilizzano quattro nodi:

* Due nodi utilizzano quattro porte di interconnessione cluster da 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Gli altri due nodi utilizzano due porte di interconnessione cluster da 40 GbE: *e4a* e *e4e*.
+
ILlink:https://hwu.netapp.com/["Hardware Universe"^] elenca le porte cluster effettive sulle tue piattaforme.



.Cosa succederà ora?
link:cn5596-prepare-to-migrate.html["Prepararsi alla migrazione"].
