---
permalink: switch-cisco-3132q-v/configure-reqs-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 'Per l"installazione e la manutenzione dello switch Cisco Nexus 3132Q-V, assicurati di consultare i requisiti di rete e di configurazione' 
---
= Requisiti di configurazione per gli switch Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 3132Q-V, assicurati di consultare i requisiti di rete e di configurazione.



[[configuration-requirements]]
== Requisiti di configurazione

Per configurare il tuo cluster, ti servono il numero e il tipo appropriati di cavi e connettori per i tuoi switch. A seconda del tipo di switch che stai configurando inizialmente, devi collegarti alla porta console dello switch con il cavo console incluso; devi anche fornire informazioni di rete specifiche.



[[network-requirements]]
== Requisiti di rete

Ti servono le seguenti informazioni di rete per tutte le configurazioni degli switch:

* Sottorete IP per traffico di rete di gestione.
* Nomi host e indirizzi IP per ciascun controller del sistema storage e per tutti gli switch applicabili.
* La maggior parte dei controller dei sistemi storage viene gestita tramite l'interfaccia e0M collegandosi alla porta di servizio Ethernet (icona a forma di chiave inglese). Nei sistemi AFF A800 e AFF A700, l'interfaccia e0M utilizza una porta Ethernet dedicata.


.Informazioni correlate
* Consultare il link:https://hwu.netapp.com["Hardware Universe"^] per le informazioni più recenti.
* Consultare link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per ulteriori informazioni sui requisiti di installazione dello switch.


.Cosa c'è dopo?
Dopo aver esaminato i requisiti di configurazione, puoi esaminare il link:required-documentation-3132q.html["documentazione richiesta"].
