---
permalink: switch-cisco-3132q-v/configure-reqs-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 'Per l"installazione e la manutenzione dello switch Cisco Nexus 3132Q-V, assicurarsi di rivedere i requisiti di rete e configurazione' 
---
= Requisiti di configurazione per gli switch Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 3132Q-V, assicurarsi di rivedere i requisiti di rete e di configurazione.



== Requisiti di configurazione

Per configurare il cluster, è necessario disporre del numero e del tipo appropriati di cavi e connettori per i propri switch.  A seconda del tipo di switch che si sta configurando inizialmente, è necessario connettersi alla porta della console dello switch tramite il cavo della console incluso; è inoltre necessario fornire informazioni di rete specifiche.



== Requisiti di rete

Per tutte le configurazioni dello switch sono necessarie le seguenti informazioni di rete:

* Subnet IP per il traffico di rete di gestione.
* Nomi host e indirizzi IP per ciascuno dei controller del sistema di archiviazione e tutti gli switch applicabili.
* La maggior parte dei controller dei sistemi di storage vengono gestiti tramite l'interfaccia e0M, collegandosi alla porta di servizio Ethernet (icona a forma di chiave inglese). Nei sistemi AFF A800 e AFF A700 , l'interfaccia e0M utilizza una porta Ethernet dedicata.


Fare riferimento al https://hwu.netapp.com["Hardware Universe"^] per le ultime informazioni. Vedere link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per maggiori informazioni sui requisiti di installazione degli switch.

.Cosa c'è dopo?
Dopo aver esaminato i requisiti di configurazione, è possibile rivedere il link:required-documentation-3132q.html["documentazione richiesta"].
