---
permalink: switch-cisco-3132q-v/install-switch-3132qv.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 3132q-v 
summary: Installa gli switch cluster Cisco Nexus 3132Q-V per prepararli al funzionamento in rete. 
---
= Installa gli switch cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installa gli switch cluster Cisco Nexus 3132Q-V per prepararli al funzionamento in rete.

.Prima di iniziare
Assicurati di avere quanto segue:

* Accesso a un server HTTP, FTP o TFTP nel sito di installazione per scaricare le versioni NX-OS e RCF (Reference Configuration File) applicabili.
* Versione NX-OS applicabile, scaricata da https://software.cisco.com/download/home["Download del software Cisco"^] pagina.
* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Completato link:setup_worksheet_3132q.html["fogli di lavoro sul cablaggio"].
* RCF applicabili alla rete cluster NetApp e alla rete di gestione scaricabili dal sito di supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^] .  Tutti gli switch di rete cluster e di rete di gestione Cisco vengono forniti con la configurazione predefinita di fabbrica Cisco . Questi switch dispongono anche della versione corrente del software NX-OS, ma non hanno gli RCF caricati.
* link:required-documentation-3132q.html["Documentazione richiesta per switch e ONTAP"].


.Passi
. Installare gli switch e i controller della rete del cluster e della rete di gestione.
+
[cols="1,2"]
|===
| Se stai installando... | Poi... 


 a| 
Cisco Nexus 9336C-FX2 in un cabinet di sistema NetApp
 a| 
Per le istruzioni su come installare lo switch in un armadio NetApp, fare riferimento alla guida _Installing a Cisco Nexus 3132Q-V cluster switch and pass-through panel in a NetApp cabinet_.



 a| 
Apparecchiature in un rack Telco
 a| 
Fare riferimento alle procedure fornite nelle guide di installazione dell'hardware dello switch e alle istruzioni di installazione e configurazione NetApp.

|===
. Cablare la rete del cluster e gli switch della rete di gestione ai controller utilizzando i fogli di lavoro di cablaggio compilati.
. Accendere la rete del cluster e gli switch e i controller della rete di gestione.


.Cosa succederà ora?
Facoltativamente, puoi link:install-cisco-nexus-3132qv.html["installa uno switch Cisco Nexus 3132Q-V in un armadio NetApp"]. Altrimenti, puoi link:cabling-considerations-3132q-v.html["rivedi il cablaggio e la configurazione"] requisiti.
