---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Prima di configurare gli switch Cisco Nexus 3132q-v, esaminare una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Se si dispone di un cluster senza switch a due nodi, rivedere la procedura seguente per i requisiti applicabili per la migrazione a un cluster con switch a due nodi.

[NOTE]
====
La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 3000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.

====
Per ulteriori informazioni, consulta:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.Connessioni porta e nodo
Assicurarsi di comprendere i requisiti di connessione di porte e nodi e di cablaggio quando si esegue la migrazione a un cluster con switch a due nodi con switch cluster Cisco Nexus 3132Q-V.

* Gli switch del cluster utilizzano le porte ISL (Inter-Switch link) e1/31-32.
* Il link:https://hwu.netapp.com/["Hardware Universe"^] Contiene informazioni sul cablaggio supportato per gli switch Nexus 3132Q-V:
+
** I nodi con connessioni cluster da 10 GbE richiedono moduli ottici QSFP con cavi in fibra breakout o cavi di breakout in rame da QSFP a SFP+.
** I nodi con connessioni cluster 40 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra o cavi direct-attach QSFP/QSFP28 in rame.
** Gli switch del cluster utilizzano il cablaggio ISL appropriato: 2 cavi QSFP28 a collegamento diretto in fibra o rame.


* Su Nexus 3132Q-V, è possibile utilizzare le porte QSFP come modalità Ethernet da 40 GB o Ethernet 4x10 GB.
+
Per impostazione predefinita, sono presenti 32 porte nella modalità Ethernet da 40 GB. Queste porte Ethernet da 40 GB sono numerate con una convenzione di denominazione a 2 tuple. Ad esempio, la seconda porta Ethernet da 40 GB è numerata come 1/2. Il processo di modifica della configurazione da Ethernet 40 GB a Ethernet 10 GB è denominato _breakout_ e il processo di modifica della configurazione da Ethernet 10 GB a Ethernet 40 GB è denominato _breakin_. Quando si suddivide una porta Ethernet da 40 GB in porte Ethernet da 10 GB, le porte risultanti vengono numerate utilizzando una convenzione di denominazione di 3 tuple. Ad esempio, le porte di breakout della seconda porta Ethernet da 40 GB sono numerate come 1/2/1, 1/2/2, 1/2/3 e 1/2/4.

* Sul lato sinistro di Nexus 3132Q-V si trova un set di quattro porte SFP+ multiplate alla prima porta QSFP.
+
Per impostazione predefinita, RCF è strutturato in modo da utilizzare la prima porta QSFP.

+
È possibile attivare quattro porte SFP+ invece di una porta QSFP per Nexus 3132Q-V utilizzando `hardware profile front portmode sfp-plus` comando. Allo stesso modo, è possibile reimpostare Nexus 3132Q-V per utilizzare una porta QSFP invece di quattro porte SFP+ utilizzando `hardware profile front portmode qsfp` comando.

* Assicurarsi di aver configurato alcune porte su Nexus 3132Q-V in modo che funzionino a 10 GbE o 40 GbE.
+
È possibile suddividere le prime sei porte in modalità 4x10 GbE utilizzando `interface breakout module 1 port 1-6 map 10g-4x` comando. Allo stesso modo, è possibile raggruppare le prime sei porte QSFP+ dalla configurazione breakout utilizzando `no interface breakout module 1 port 1-6 map 10g-4x` comando.

* Il numero di porte 10 GbE e 40 GbE è definito nei file di configurazione di riferimento (RCF) disponibili all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento di Cisco ® Cluster Network Switch"^] .


.Prima di iniziare
* Configurazioni correttamente configurate e funzionanti.
* Nodi che eseguono ONTAP 9.4 o versioni successive.
* Tutte le porte del cluster in `up` stato.
* Lo switch cluster Cisco Nexus 3132Q-V è supportato.
* La configurazione di rete del cluster esistente dispone di:
+
** L'infrastruttura cluster Nexus 3132 ridondante e pienamente funzionante su entrambi gli switch.
** Le ultime versioni di RCF e NX-OS sugli switch.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]contiene informazioni sulle versioni ONTAP e NX-OS supportate in questa procedura.

** Connettività di gestione su entrambi gli switch.
** Accesso da console a entrambi gli switch.
** Tutte le interfacce logiche del cluster (LIF) in `up` senza essere migrati.
** Personalizzazione iniziale dello switch.
** Tutte le porte ISL abilitate e cablate.




Inoltre, devi pianificare, migrare e leggere la documentazione richiesta sulla connettività 10 GbE e 40 GbE dai nodi agli switch cluster Nexus 3132Q-V.

.Informazioni sugli esempi utilizzati
Gli esempi di questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Switch in cluster Nexus 3132Q-V, C1 e C2.
* I nodi sono n1 e n2.


[NOTE]
====
Negli esempi di questa procedura vengono utilizzati due nodi, ciascuno dei quali utilizza due porte di interconnessione cluster 40 GbE *e4a* e *E4E*. link:https://hwu.netapp.com/["Hardware Universe"^]Dispone di dettagli sulle porte cluster sulle piattaforme.

====
Questa procedura descrive i seguenti scenari:

* *n1_clus1* è la prima interfaccia logica del cluster (LIF) ad essere collegata allo switch del cluster C1 per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF ad essere collegato al cluster switch C2 per il nodo *n1*.
* *n2_clus1* è il primo cluster LIF ad essere collegato al cluster switch C1 per il nodo *n2*.
* *n2_clus2* è il secondo cluster LIF da collegare al cluster switch C2 per il nodo *n2*.
* Il numero di porte 10 GbE e 40 GbE è definito nei file di configurazione di riferimento (RCF) disponibili all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento di Cisco ® Cluster Network Switch"^] .


[NOTE]
====
La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 3000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.

====
* Il cluster inizia con due nodi connessi e funzionanti in un'impostazione di cluster senza switch a due nodi.
* La prima porta del cluster viene spostata in C1.
* La seconda porta del cluster viene spostata in C2.
* L'opzione cluster senza switch a due nodi è disattivata.


.Quali sono le prossime novità?
link:migrate-switchless-prepare-to-migrate.html["Preparazione per la migrazione"].
