---
permalink: switch-cisco-3132q-v/migrate-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Puoi usare gli switch Cisco Nexus 3132q-v come switch di cluster nel tuo cluster AFF o FAS. 
---
= Configura le porte per la migrazione da cluster senza switch a cluster con switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Segui questi passaggi per configurare le porte per la migrazione da cluster senza switch a due nodi a cluster con switch a due nodi.

.Passi
. Sugli switch Nexus 3132Q-V C1 e C2, disabilita tutte le porte rivolte verso i nodi C1 e C2, ma non disabilitare le porte ISL.
+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra la disabilitazione delle porte da 1 a 30 sugli switch cluster Nexus 3132Q-V C1 e C2 utilizzando una configurazione supportata in RCF `NX3132_RCF_v1.1_24p10g_26p40g.txt`:

[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. Collega le porte 1/31 e 1/32 su C1 alle stesse porte su C2 usando cablaggi supportati.
. Verifica che le porte ISL siano operative su C1 e C2:
+
`show port-channel summary`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Visualizza l'elenco dei dispositivi vicini allo switch:
+
`show cdp neighbors`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
====
. Visualizza la connettività delle porte del cluster su ciascun nodo:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra una configurazione di cluster senza switch a due nodi.

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. Migra l'interfaccia clus1 alla porta fisica che ospita clus2:
+
`network interface migrate`

+
Esegui questo comando da ciascun nodo locale.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e
----
====
. Verifica la migrazione delle interfacce del cluster:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Arresta le porte del cluster clus1 LIF su entrambi i nodi:
+
`network port modify`

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Aspetta qualche secondo prima di eseguire il comando show per vedere i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step10]]Scollega il cavo da e4a sul nodo n1.
+
Puoi fare riferimento alla configurazione corrente e collegare la prima porta 40 GbE sullo switch C1 (porta 1/7 in questo esempio) a e4a su n1 utilizzando il cablaggio supportato su Nexus 3132Q-V.

+

NOTE: Quando ricolleghi i cavi a un nuovo Cisco cluster switch, i cavi utilizzati devono essere in fibra o cavi supportati da Cisco.

. Scollega il cavo da e4a sul nodo n2.
+
Puoi fare riferimento alla configurazione corrente e collegare e4a alla prossima porta 40 GbE disponibile su C1, porta 1/8, utilizzando il cablaggio supportato.

. Abilita tutte le porte rivolte verso i nodi su C1.
+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra l'abilitazione delle porte da 1 a 30 sugli switch di cluster Nexus 3132Q-V C1 e C2 utilizzando la configurazione supportata in RCF `NX3132_RCF_v1.1_24p10g_26p40g.txt`:

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. Abilita la prima porta del cluster, e4a, su ciascun nodo:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. Verifica che i cluster siano attivi su entrambi i nodi:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
. Per ciascun nodo, ripristina tutte le LIF di interconnessione del cluster migrate:
+
`network interface revert`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra le LIF migrate che vengono riportate alle loro porte di origine.

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
====
. Verifica che tutte le porte di interconnessione del cluster siano ora tornate alle rispettive porte principali:
+
`network interface show`

+
La `Is Home` colonna dovrebbe visualizzare un valore di `true` per tutte le porte elencate nella `Current Port` colonna. Se il valore visualizzato è `false`, la porta non è stata ripristinata.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Visualizza la connettività delle porte del cluster su ciascun nodo:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
====
. Sulla console di ciascun nodo, migra clus2 alla porta e4a:
+
`network interface migrate`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a
----
====
. Arresta le porte del cluster clus2 LIF su entrambi i nodi:
+
`network port modify`

+
Il seguente esempio mostra le porte specificate che vengono disattivate su entrambi i nodi:

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. Verifica lo stato LIF del cluster:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. Scollega il cavo da e4e sul nodo n1.
+
Puoi fare riferimento alla configurazione corrente e collegare la prima porta 40 GbE sulla switch C2 (porta 1/7 in questo esempio) a e4e su n1 utilizzando il cablaggio supportato su Nexus 3132Q-V.

. Scollega il cavo da e4e sul nodo n2.
+
Puoi fare riferimento alla configurazione corrente e collegare e4e alla prossima porta 40 GbE disponibile su C2, porta 1/8, utilizzando il cablaggio supportato.

. Abilita tutte le porte rivolte verso i nodi su C2.
+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra l'abilitazione delle porte da 1 a 30 sugli switch di cluster Nexus 3132Q-V C1 e C2 utilizzando una configurazione supportata in RCF `NX3132_RCF_v1.1_24p10g_26p40g.txt`:

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. Abilita la seconda porta del cluster, e4e, su ciascun nodo:
+
`network port modify`

+
Il seguente esempio mostra l'attivazione delle porte specificate:

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. Per ciascun nodo, ripristina tutte le LIF di interconnessione del cluster migrate:
+
`network interface revert`

+
Il seguente esempio mostra le LIF migrate che vengono riportate alle loro porte di origine.

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. Verifica che tutte le porte di interconnessione del cluster siano ora tornate alle rispettive porte principali:
+
`network interface show`

+
La `Is Home` colonna dovrebbe visualizzare un valore di `true` per tutte le porte elencate nella `Current Port` colonna. Se il valore visualizzato è `false`, la porta non è stata ripristinata.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. Verifica che tutte le porte di interconnessione del cluster siano nello stato  `up`.
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====


.Cosa succederà ora?
Dopo che hai configurato le porte dello switch, puoi link:migrate-switchless-complete-migration.html["completa la tua migrazione"].
