---
permalink: switch-cisco-3132q-v/migrate-switchless-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Preparati a migrare da un cluster senza switch a switch di cluster Cisco Nexus 3132Q-V. 
---
= Preparati a migrare da un cluster senza switch agli switch di cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepara il tuo cluster senza switch a due nodi per la migrazione a un cluster con switch utilizzando gli switch cluster Cisco Nexus 3132Q-V.

.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

+
[NOTE]
====
Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

====
. Determinare lo stato amministrativo o operativo per ciascuna interfaccia del cluster:
+
.. Visualizza gli attributi della porta di rete:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
.. Visualizza le informazioni sulle interfacce logiche:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====


. Verifica che i file RCF e l'immagine appropriati siano installati sui nuovi switch 3132Q-V in base alle tue esigenze e apporta tutte le personalizzazioni essenziali del sito, come utenti e password, indirizzi di rete e così via.
+
Devi preparare entrambi gli switch in questa fase. Se devi aggiornare il software RCF e l'immagine, devi seguire questi passaggi:

+
.. Vai su link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] NetApp Support Site.
.. Annota il tuo switch e le versioni software richieste nella tabella presente in quella pagina.
.. Scarica la versione appropriata di RCF.
.. Seleziona *CONTINUA* nella pagina *Descrizione*, accetta il contratto di licenza e poi segui le istruzioni nella pagina *Download* per scaricare l'RCF.
.. Scarica la versione appropriata del software dell'immagine.


. Seleziona *CONTINUA* nella pagina *Descrizione*, accetta il contratto di licenza e poi segui le istruzioni nella pagina *Download* per scaricare l'RCF.


.Cosa succederà ora?
Dopo che hai preparato gli switch per la migrazione, puoi link:migrate-switchless-configure-ports.html["configura le tue porte"].
