---
permalink: switch-cisco-3132q-v/migrate-from-cisco-nexus-5596-to-cisco-nexus-3232c.html 
sidebar: sidebar 
keywords: replace, cisco nexus 5596 cluster switch, 3132q-v 
summary: Per sostituire uno switch di cluster Nexus 5596 esistente con uno switch di cluster Nexus 3132Q-V, è necessario eseguire una sequenza specifica di attività. 
---
= Eseguire la migrazione di uno switch cluster Cisco Nexus 5596 a uno switch cluster Cisco Nexus 3132Q-V.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per sostituire uno switch del cluster Nexus 5596 esistente con uno switch del cluster Nexus 3132Q-V.



== Verifica dei requisiti

Esaminare i requisiti di Cisco Nexus 5596 in link:switch-requirements.html["Requisiti per la sostituzione degli switch cluster Cisco Nexus 3132Q-V."].

Per ulteriori informazioni, consulta:

* http://support.netapp.com/NOW/download/software/cm_switches/["Pagina di descrizione dello switch Ethernet Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Sostituire lo switch

.A proposito degli esempi
Gli esempi di questa procedura descrivono la sostituzione degli switch Nexus 5596 con gli switch Nexus 3132Q-V. È possibile utilizzare questa procedura (con modifiche) per sostituire altri switch Cisco meno recenti.

La procedura utilizza la seguente nomenclatura di switch e nodi:

* Gli output dei comandi possono variare a seconda delle diverse versioni di ONTAP.
* Gli switch Nexus 5596 da sostituire sono CL1 e CL2.
* Gli switch Nexus 3132Q-V in sostituzione degli switch Nexus 5596 sono C1 e C2.
* n1_clus1 è la prima interfaccia logica del cluster (LIF) collegata allo switch del cluster 1 (CL1 o C1) per il nodo n1.
* n1_clus2 è il primo LIF del cluster collegato allo switch del cluster 2 (CL2 o C2) per il nodo n1.
* n1_clus3 è il secondo LIF collegato allo switch del cluster 2 (CL2 o C2) per il nodo n1.
* n1_clus4 è il secondo LIF collegato allo switch del cluster 1 (CL1 o C1) per il nodo n1.
* I nodi sono n1, n2, n3 e n4.
* Gli esempi di questa procedura utilizzano quattro nodi: Due nodi utilizzano quattro porte di interconnessione del cluster da 10 GbE: E0a, e0b, e0c e e0d. Gli altri due nodi utilizzano due porte di interconnessione cluster da 40/100 GbE: E4a, e4e. Il link:https://hwu.netapp.com/["Hardware Universe"^] elenca le porte del cluster effettive sulle piattaforme.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili su https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download del file di configurazione di riferimento di Cisco® Cluster Network Switch"^] pagina.
+

NOTE: La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 3000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.



.A proposito di questa attività
Questa procedura descrive i seguenti scenari:

* Il cluster inizia con due nodi collegati e funzionanti in 2 switch di cluster Nexus 5596.
* Lo switch del cluster CL2 deve essere sostituito da C2 (<<step1_replace5596_3232q,Fasi 1>> - <<step19_replace5596_3232q,19>>)
+
** Il traffico su tutte le porte del cluster e le LIF su tutti i nodi connessi a CL2 viene migrato sulle prime porte del cluster e sulle LIF connesse a CL1.
** Scollegare il cablaggio da tutte le porte del cluster su tutti i nodi collegati a CL2, quindi utilizzare il cablaggio break-out supportato per ricollegare le porte al nuovo switch del cluster C2.
** Scollegare i cavi tra le porte ISL tra CL1 e CL2, quindi utilizzare i cavi di breakout supportati per ricollegare le porte da CL1 a C2.
** Il traffico su tutte le porte del cluster e le LIF collegate a C2 su tutti i nodi viene invertito.


* Lo switch del cluster CL2 deve essere sostituito da C2
+
** Il traffico su tutte le porte cluster o LIF su tutti i nodi connessi a CL1 viene migrato sulle porte del secondo cluster o LIF connesse a C2.
** Scollegare il cablaggio da tutte le porte del cluster su tutti i nodi collegati a CL1 e ricollegarlo, utilizzando il cablaggio di breakout supportato, al nuovo switch del cluster C1.
** Scollegare il cablaggio tra le porte ISL tra CL1 e C2 e ricollegarlo utilizzando i cavi supportati, da C1 a C2.
** Il traffico su tutte le porte cluster o LIF collegate a C1 su tutti i nodi viene invertito.


* Sono stati aggiunti due nodi FAS9000 al cluster con esempi che mostrano i dettagli del cluster.




=== Fase 1: Preparazione per la sostituzione

Per sostituire uno switch di cluster Nexus 5596 esistente con uno switch di cluster Nexus 3132Q-V, è necessario eseguire una sequenza specifica di attività.

. Se AutoSupport è attivato su questo cluster, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
_x_ è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio informa il supporto tecnico di questa attività di manutenzione in modo che la creazione automatica del caso venga soppressa durante la finestra di manutenzione.

. Visualizzare le informazioni relative ai dispositivi nella configurazione:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra quante interfacce di interconnessione del cluster sono state configurate in ciascun nodo per ogni switch di interconnessione del cluster:

[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1      N5K-C5596UP
            e0b    CL2                 Ethernet1/1      N5K-C5596UP
            e0c    CL2                 Ethernet1/2      N5K-C5596UP
            e0d    CL1                 Ethernet1/2      N5K-C5596UP
n2         /cdp
            e0a    CL1                 Ethernet1/3      N5K-C5596UP
            e0b    CL2                 Ethernet1/3      N5K-C5596UP
            e0c    CL2                 Ethernet1/4      N5K-C5596UP
            e0d    CL1                 Ethernet1/4      N5K-C5596UP
8 entries were displayed.
----
====
. Determinare lo stato amministrativo o operativo di ciascuna interfaccia del cluster:
+
.. Visualizzare gli attributi della porta di rete:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
Nell'esempio seguente vengono visualizzati gli attributi della porta di rete su un sistema:

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
.. Visualizza informazioni sulle interfacce logiche: +
`network interface show`
+
.Mostra esempio
[%collapsible]
====
Nell'esempio riportato di seguito vengono visualizzate le informazioni generali su tutti i file LIF presenti nel sistema:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
.. Visualizzare le informazioni sugli switch del cluster rilevati: +
`system cluster-switch show`
+
.Mostra esempio
[%collapsible]
====
Nell'esempio riportato di seguito vengono visualizzati gli switch del cluster noti al cluster e i relativi indirizzi IP di gestione:

[listing]
----
cluster::*> system cluster-switch show

Switch                        Type               Address         Model
----------------------------- ------------------ --------------- ---------------
CL1                           cluster-network    10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

2 entries were displayed.
----
====


. Impostare `-auto-revert` parametro a. `false` Su cluster LIF clus1 e clus2 su entrambi i nodi:
+
`network interface modify`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
. Verificare che l'RCF e l'immagine appropriati siano installati sui nuovi switch 3132Q-V in base alle proprie esigenze ed eseguire le personalizzazioni essenziali del sito, ad esempio utenti e password, indirizzi di rete e così via.
+
È necessario preparare entrambi gli switch in questa fase. Se è necessario aggiornare l'RCF e l'immagine, attenersi alla seguente procedura:

+
.. Accedere alla link:http://support.netapp.com/NOW/download/software/cm_switches/["Switch Ethernet Cisco"^] Sul sito di supporto NetApp.
.. Annotare lo switch e le versioni software richieste nella tabella riportata in tale pagina.
.. Scaricare la versione appropriata di RCF.
.. Fare clic su *CONTINUA* nella pagina *Descrizione*, accettare il contratto di licenza, quindi seguire le istruzioni nella pagina *Download* per scaricare RCF.
.. Scaricare la versione appropriata del software dell'immagine.
+
Vedere la pagina __ONTAP 8.x o versione successiva file di configurazione di riferimento per switch di rete di gestione e cluster__Download, quindi fare clic sulla versione appropriata.

+
Per trovare la versione corretta, consultare la _pagina di download dello switch di rete cluster ONTAP 8.x o versione successiva_.



. Migrare i LIF associati al secondo switch Nexus 5596 da sostituire:
+
`network interface migrate`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra n1 e n2, ma la migrazione LIF deve essere eseguita su tutti i nodi:

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 –
destination-node n1 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 –
destination-node n1 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 –
destination-node n2 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 –
destination-node n2 -destination-port e0d
----
====
. Verificare lo stato del cluster:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra il risultato del precedente `network interface migrate` comando:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Spegnere le porte di interconnessione del cluster fisicamente collegate allo switch CL2:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
I seguenti comandi disattivano le porte specificate su n1 e n2, ma le porte devono essere chiuse su tutti i nodi:

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin false
cluster::*> network port modify -node n1 -port e0c -up-admin false
cluster::*> network port modify -node n2 -port e0b -up-admin false
cluster::*> network port modify -node n2 -port e0c -up-admin false
----
====
. Eseguire il ping delle interfacce del cluster remoto ed eseguire un controllo del server RPC:
+
`cluster ping-cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come eseguire il ping delle interfacce del cluster remoto:

[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check
----
====
. Spegnere le porte ISL da 41 a 48 sullo switch Nexus 5596 attivo CL1:
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come spegnere le porte ISL da 41 a 48 sullo switch Nexus 5596 CL1:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/41-48
(CL1)(config-if-range)# shutdown
(CL1)(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
====
+
Se si sostituisce Nexus 5010 o 5020, specificare i numeri di porta appropriati per ISL.

. Creare un ISL temporaneo tra CL1 e C2.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra un ISL temporaneo impostato tra CL1 e C2:

[listing]
----
C2# configure
C2(config)# interface port-channel 2
C2(config-if)# switchport mode trunk
C2(config-if)# spanning-tree port type network
C2(config-if)# mtu 9216
C2(config-if)# interface breakout module 1 port 24 map 10g-4x
C2(config)# interface e1/24/1-4
C2(config-if-range)# switchport mode trunk
C2(config-if-range)# mtu 9216
C2(config-if-range)# channel-group 2 mode active
C2(config-if-range)# exit
C2(config-if)# exit
----
====




=== Fase 2: Configurare le porte

. Su tutti i nodi, rimuovere tutti i cavi collegati allo switch Nexus 5596 CL2.
+
Con il cablaggio supportato, ricollegare le porte scollegate su tutti i nodi allo switch Nexus 3132Q-V C2.

. Rimuovere tutti i cavi dallo switch Nexus 5596 CL2.
+
Collegare i cavi di breakout Cisco QSFP a SFP+ appropriati collegando la porta 1/24 del nuovo switch Cisco 3132Q-V, C2, alle porte da 45 a 48 di Nexus 5596, CL1.

. Verificare che le interfacce eth1/45-48 siano già presenti `channel-group 1 mode active` nella configurazione in esecuzione.
. Portare le porte ISL da 45 a 48 sullo switch Nexus 5596 CL1 attivo.
+
.Mostra esempio
[%collapsible]
====
Nell'esempio seguente vengono mostrate le porte ISL da 45 a 48:

[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/45-48
(CL1)(config-if-range)# no shutdown
(CL1)(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. Verificare che gli ISL siano `up` Sullo switch Nexus 5596 CL1:
+
`show port-channel summary`

+
.Mostra esempio
[%collapsible]
====
Le porte da eth1/45 a eth1/48 devono indicare (P), ovvero le porte ISL `up` nel port-channel:

[listing]
----
Example
CL1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/41(D)   Eth1/42(D)   Eth1/43(D)
                                    Eth1/44(D)   Eth1/45(P)   Eth1/46(P)
                                    Eth1/47(P)   Eth1/48(P)
----
====
. Verificare che gli ISL siano `up` Sullo switch C2 3132Q-V:
+
`show port-channel summary`

+
.Mostra esempio
[%collapsible]
====
Le porte eth1/24/1, eth1/24/2, eth1/24/3 e eth1/24/4 devono indicare (P), ovvero le porte ISL `up` nel port-channel:

[listing]
----
C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(D)   Eth1/32(D)
2     Po2(SU)      Eth    LACP      Eth1/24/1(P)  Eth1/24/2(P)  Eth1/24/3(P)
                                    Eth1/24/4(P)
----
====
. Su tutti i nodi, richiamare tutte le porte di interconnessione del cluster collegate allo switch 3132Q-V C2:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte specificate che vengono avviate sui nodi n1 e n2:

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
----
====
. Su tutti i nodi, ripristinare tutte le LIF di interconnessione cluster migrate collegate a C2:
+
`network interface revert`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le LIF del cluster migrate vengono ripristinate alle porte home sui nodi n1 e n2:

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
----
====
. Verificare che tutte le porte di interconnessione del cluster siano ora ripristinate nella propria abitazione:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
Nell'esempio seguente viene mostrato che i LIF su clus2 tornavano alle porte home e che i LIF vengono ripristinati correttamente se le porte nella colonna Current Port (porta corrente) hanno uno stato di `true` in `Is Home` colonna. Se il `Is Home` il valore è `false`, La LIF non è stata ripristinata.

[listing]
----
cluster::*> network interface show -role cluster
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Verificare che le porte del cluster siano connesse:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra il risultato del precedente `network port modify` verificare che tutte le interconnessioni del cluster siano `up`:

[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. Eseguire il ping delle interfacce del cluster remoto ed eseguire un controllo del server RPC:
+
`cluster ping-cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come eseguire il ping delle interfacce del cluster remoto:

[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
====
. Su ciascun nodo del cluster, migrare le interfacce associate al primo switch Nexus 5596, CL1, da sostituire:
+
`network interface migrate`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte o i LIF migrati sui nodi n1 e n2:

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1 -
destination-node n1 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n1_clus4 -source-node n1 -
destination-node n1 -destination-port e0c
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2 -
destination-node n2 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n2_clus4 -source-node n2 -
destination-node n2 -destination-port e0c
----
====
. Verificare lo stato del cluster:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le LIF del cluster richieste sono state migrate alle porte del cluster appropriate ospitate sullo switch del cluster C2:

[listing]
----
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0b     false
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0c     false
            n2_clus1   up/up      10.10.0.5/24       n2            e0b     false
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0c     false
8 entries were displayed.

----- ------- ----
----
====
. Su tutti i nodi, chiudere le porte del nodo collegate a CL1:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le porte specificate che vengono chiuse sui nodi n1 e n2:

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin false
cluster::*> network port modify -node n1 -port e0d -up-admin false
cluster::*> network port modify -node n2 -port e0a -up-admin false
cluster::*> network port modify -node n2 -port e0d -up-admin false
----
====
. Spegnere le porte ISL 24, 31 e 32 sullo switch 3132Q-V C2 attivo:
+
`shutdown`

+
.Mostra esempio
[%collapsible]
====
Nell'esempio seguente viene illustrato come chiudere gli ISL 24, 31 e 32:

[listing]
----
C2# configure
C2(Config)# interface e1/24/1-4
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# interface 1/31-32
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config-if)# exit
C2#
----
====
. Su tutti i nodi, rimuovere tutti i cavi collegati allo switch Nexus 5596 CL1.
+
Con il cablaggio supportato, ricollegare le porte scollegate su tutti i nodi allo switch Nexus 3132Q-V C1.

. Rimuovere il cavo di breakout QSFP dalle porte C2 E1/24 Nexus 3132Q-V.
+
Collegare le porte e1/31 e e1/32 su C1 alle porte e1/31 e e1/32 su C2 utilizzando cavi Cisco QSFP in fibra ottica o a collegamento diretto supportati.

. Ripristinare la configurazione sulla porta 24 e rimuovere il canale 2 della porta temporanea su C2:
+
[listing]
----
C2# configure
C2(config)# no interface breakout module 1 port 24 map 10g-4x
C2(config)# no interface port-channel 2
C2(config-if)# int e1/24
C2(config-if)# description 40GbE Node Port
C2(config-if)# spanning-tree port type edge
C2(config-if)# spanning-tree bpduguard enable
C2(config-if)# mtu 9216
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
. Porta ISL 31 e 32 su C2, lo switch 3132Q-V attivo: `no shutdown`
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come attivare gli ISL 31 e 32 sullo switch 3132Q-V C2:

[listing]
----
C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====




=== Fase 3: Verificare la configurazione

. Verificare che le connessioni ISL siano `up` Sullo switch C2 3132Q-V:
+
`show port-channel summary`

+
.Mostra esempio
[%collapsible]
====
Le porte eth1/31 e eth1/32 devono indicare `(P)`, Vale a dire che entrambe le porte ISL sono `up` nel port-channel:

[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Su tutti i nodi, richiamare tutte le porte di interconnessione del cluster collegate al nuovo switch 3132Q-V C1:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra tutte le porte di interconnessione del cluster che vengono avviate per n1 e n2 sullo switch 3132Q-V C1:

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin true
cluster::*> network port modify -node n1 -port e0d -up-admin true
cluster::*> network port modify -node n2 -port e0a -up-admin true
cluster::*> network port modify -node n2 -port e0d -up-admin true
----
====
. Verificare lo stato della porta del nodo del cluster:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente verifica che tutte le porte di interconnessione del cluster su tutti i nodi del nuovo switch 3132Q-V C1 siano `up`:

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. Su tutti i nodi, ripristinare le specifiche LIF del cluster alle porte home:
+
`network interface revert`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra le specifiche LIF del cluster ripristinate alle porte home sui nodi n1 e n2:

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n1_clus4
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus4
----
====
. Verificare che l'interfaccia sia home:
+
`network interface show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra lo stato delle interfacce di interconnessione del cluster `up` e. `Is home` per n1 e n2:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Eseguire il ping delle interfacce del cluster remoto, quindi eseguire un controllo del server di chiamata per la procedura remota:
+
`cluster ping-cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come eseguire il ping delle interfacce del cluster remoto:

[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
====
. Espandere il cluster aggiungendo nodi agli switch del cluster Nexus 3132Q-V.
. Visualizzare le informazioni relative ai dispositivi nella configurazione:
+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`
+
.Mostra esempio
[%collapsible]
====
Gli esempi seguenti mostrano i nodi n3 e n4 con porte cluster da 40 GbE collegate alle porte e1/7 e e1/8, rispettivamente sugli switch cluster Nexus 3132Q-V e su entrambi i nodi collegati al cluster. Le porte di interconnessione del cluster da 40 GbE utilizzate sono e4a e e4e.

[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3132Q-V
            e0b    C2                 Ethernet1/1/1    N3K-C3132Q-V
            e0c    C2                 Ethernet1/1/2    N3K-C3132Q-V
            e0d    C1                 Ethernet1/1/2    N3K-C3132Q-V
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3132Q-V
            e0b    C2                 Ethernet1/1/3    N3K-C3132Q-V
            e0c    C2                 Ethernet1/1/4    N3K-C3132Q-V
            e0d    C1                 Ethernet1/1/4    N3K-C3132Q-V
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3132Q-V
            e4e    C2                 Ethernet1/7      N3K-C3132Q-V
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3132Q-V
            e4e    C2                 Ethernet1/8      N3K-C3132Q-V
12 entries were displayed.
----
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL1                           cluster-network   10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

4 entries were displayed.

----
====


. Rimuovere Nexus 5596 sostituito se non viene rimosso automaticamente:
+
`system cluster-switch delete`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come rimuovere Nexus 5596:

[listing]
----
cluster::> system cluster-switch delete –device CL1
cluster::> system cluster-switch delete –device CL2
----
====
. Configurare i cluster clus1 e clus2 per il ripristino automatico su ciascun nodo e confermare.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
. Verificare che siano monitorati gli switch del cluster corretti:
+
`system cluster-switch show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Se è stata eliminata la creazione automatica del caso, riattivarla richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Quali sono le prossime novità?
link:../switch-cshm/config-overview.html["Configurare il monitoraggio dello stato dello switch"]
