---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Prima di configurare gli switch Cisco Nexus 3132q-v, rivedere una panoramica del processo e della nomenclatura. 
---
= Requisiti di migrazione
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Se si dispone di un cluster switchless a due nodi, consultare questa procedura per i requisiti applicabili alla migrazione a un cluster switched a due nodi.

[NOTE]
====
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

====
Per maggiori informazioni, vedere:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.Connessioni di porte e nodi
Quando si esegue la migrazione a un cluster commutato a due nodi con switch cluster Cisco Nexus 3132Q-V, assicurarsi di comprendere i requisiti di collegamento delle porte e dei nodi e di cablaggio.

* Gli switch cluster utilizzano le porte Inter-Switch Link (ISL) e1/31-32.
* ILlink:https://hwu.netapp.com/["Hardware Universe"^] contiene informazioni sul cablaggio supportato per gli switch Nexus 3132Q-V:
+
** I nodi con connessioni cluster 10 GbE richiedono moduli ottici QSFP con cavi in fibra ottica breakout o cavi breakout in rame da QSFP a SFP+.
** I nodi con connessioni cluster da 40 GbE richiedono moduli ottici QSFP/QSFP28 supportati con cavi in fibra o cavi di collegamento diretto in rame QSFP/QSFP28.
** Gli switch cluster utilizzano il cablaggio ISL appropriato: 2 cavi QSFP28 in fibra o rame a collegamento diretto.


* Su Nexus 3132Q-V, è possibile utilizzare le porte QSFP in modalità Ethernet 40 Gb o Ethernet 4x10 Gb.
+
Per impostazione predefinita, nella modalità Ethernet da 40 Gb sono presenti 32 porte.  Queste porte Ethernet da 40 Gb sono numerate secondo una convenzione di denominazione a 2 tuple.  Ad esempio, la seconda porta Ethernet da 40 Gb è numerata come 1/2.  Il processo di modifica della configurazione da 40 Gb Ethernet a 10 Gb Ethernet è chiamato _breakout_, mentre il processo di modifica della configurazione da 10 Gb Ethernet a 40 Gb Ethernet è chiamato _breakin_.  Quando si scompone una porta Ethernet da 40 Gb in porte Ethernet da 10 Gb, le porte risultanti vengono numerate utilizzando una convenzione di denominazione a 3 tuple.  Ad esempio, le porte breakout della seconda porta Ethernet da 40 Gb sono numerate come 1/2/1, 1/2/2, 1/2/3 e 1/2/4.

* Sul lato sinistro del Nexus 3132Q-V è presente un set di quattro porte SFP+ multiplexate sulla prima porta QSFP.
+
Per impostazione predefinita, l'RCF è strutturato per utilizzare la prima porta QSFP.

+
È possibile rendere attive quattro porte SFP+ anziché una porta QSFP per Nexus 3132Q-V utilizzando `hardware profile front portmode sfp-plus` comando.  Allo stesso modo, è possibile reimpostare Nexus 3132Q-V per utilizzare una porta QSFP invece di quattro porte SFP+ utilizzando `hardware profile front portmode qsfp` comando.

* Assicurati di aver configurato alcune porte sul Nexus 3132Q-V per funzionare a 10 GbE o 40 GbE.
+
È possibile suddividere le prime sei porte in modalità 4x10 GbE utilizzando `interface breakout module 1 port 1-6 map 10g-4x` comando.  Allo stesso modo, è possibile raggruppare le prime sei porte QSFP+ dalla configurazione breakout utilizzando `no interface breakout module 1 port 1-6 map 10g-4x` comando.

* Il numero di porte 10 GbE e 40 GbE è definito nei file di configurazione di riferimento (RCF) disponibili all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco ® Cluster"^] .


.Prima di iniziare
* Configurazioni correttamente impostate e funzionanti.
* Nodi che eseguono ONTAP 9.4 o versioni successive.
* Tutte le porte del cluster nel `up` stato.
* È supportato lo switch cluster Cisco Nexus 3132Q-V.
* La configurazione di rete del cluster esistente presenta:
+
** L'infrastruttura del cluster Nexus 3132 è ridondante e completamente funzionale su entrambi gli switch.
** Le ultime versioni RCF e NX-OS sui tuoi switch.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]contiene informazioni sulle versioni ONTAP e NX-OS supportate in questa procedura.

** Connettività di gestione su entrambi gli switch.
** Accesso alla console per entrambi gli switch.
** Tutte le interfacce logiche del cluster (LIF) nel `up` stato senza essere migrato.
** Personalizzazione iniziale dello switch.
** Tutte le porte ISL sono abilitate e cablate.




Inoltre, è necessario pianificare, migrare e leggere la documentazione richiesta sulla connettività 10 GbE e 40 GbE dai nodi agli switch cluster Nexus 3132Q-V.

.Informazioni sugli esempi utilizzati
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Switch cluster Nexus 3132Q-V, C1 e C2.
* I nodi sono n1 e n2.


[NOTE]
====
Gli esempi in questa procedura utilizzano due nodi, ciascuno con due porte di interconnessione cluster da 40 GbE *e4a* e *e4e*.  ILlink:https://hwu.netapp.com/["Hardware Universe"^] contiene dettagli sulle porte del cluster sulle tue piattaforme.

====
Questa procedura copre i seguenti scenari:

* *n1_clus1* è la prima interfaccia logica del cluster (LIF) da connettere allo switch del cluster C1 per il nodo *n1*.
* *n1_clus2* è il primo cluster LIF ad essere connesso allo switch del cluster C2 per il nodo *n1*.
* *n2_clus1* è il primo cluster LIF ad essere connesso allo switch del cluster C1 per il nodo *n2*.
* *n2_clus2* è il secondo cluster LIF da connettere allo switch cluster C2 per il nodo *n2*.
* Il numero di porte 10 GbE e 40 GbE è definito nei file di configurazione di riferimento (RCF) disponibili all'indirizzolink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download del file di configurazione di riferimento dello switch di rete Cisco ® Cluster"^] .


[NOTE]
====
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

====
* Il cluster inizia con due nodi connessi e funzionanti in un ambiente di cluster switchless a due nodi.
* La prima porta del cluster viene spostata su C1.
* La seconda porta del cluster viene spostata su C2.
* L'opzione cluster switchless a due nodi è disabilitata.


.Cosa succederà ora?
Dopo aver esaminato i requisiti di migrazione, puoilink:migrate-switchless-prepare-to-migrate.html["preparati a migrare i tuoi switch"] .
