---
permalink: switch-cisco-3132q-v/smart-call-home-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Per utilizzare la funzione Smart Call Home, consultare le seguenti linee guida. 
---
= Requisiti di Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare Smart Call Home, è necessario configurare uno switch di rete cluster per comunicare tramite e-mail con il sistema Smart Call Home. Inoltre, è possibile configurare facoltativamente lo switch di rete del cluster per sfruttare la funzionalità di supporto Smart Call Home integrata di Cisco.

Smart Call Home monitora i componenti hardware e software della tua rete. Quando si verifica una configurazione critica del sistema, viene generata una notifica tramite e-mail e viene inviato un avviso a tutti i destinatari configurati nel profilo di destinazione.

Smart Call Home monitora i componenti hardware e software della tua rete. Quando si verifica una configurazione critica del sistema, viene generata una notifica tramite e-mail e viene inviato un avviso a tutti i destinatari configurati nel profilo di destinazione.

Prima di poter utilizzare Smart Call Home, è necessario tenere presente i seguenti requisiti:

* Deve essere presente un server di posta elettronica.
* Lo switch deve disporre di connettività IP al server di posta elettronica.
* È necessario configurare il nome del contatto (contatto del server SNMP), il numero di telefono e le informazioni sull'indirizzo.  Ciò è necessario per determinare l'origine dei messaggi ricevuti.
* Un ID CCO deve essere associato a un contratto di servizio Cisco SMARTnet appropriato per la tua azienda.
* Per registrare il dispositivo, è necessario che sia attivo il servizio Cisco SMARTnet.


IL http://www.cisco.com/c/en/us/products/switches/index.html["Sito di supporto Cisco"^] contiene informazioni sui comandi per configurare Smart Call Home.
