---
sidebar: sidebar 
permalink: switch-cisco-3232c-storage/configure-reqs-3232c-storage.html 
keywords: shared storage cluster switch 
summary: 'Prima dell"installazione o dell"aggiornamento, verifica i requisiti di configurazione degli switch di storage Cisco Nexus 3232C.' 
---
= Esamina i requisiti di configurazione per gli switch di storage Cisco Nexus 3232C
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima dell'installazione o dell'aggiornamento, verifica i requisiti di configurazione degli switch di storage Cisco Nexus 3232C.



[[configuration-requirements]]
== Requisiti di configurazione

È necessario disporre del numero e del tipo appropriati di cavi e connettori per i propri switch. A seconda del tipo di switch che si sta configurando inizialmente, è necessario collegarsi alla porta console dello switch con il cavo console incluso; è inoltre necessario fornire informazioni di rete specifiche.



[[network-requirements]]
== Requisiti di rete

Ti servono le seguenti informazioni di rete per tutte le configurazioni degli switch:

* Subnet IP per il traffico di rete di gestione
* Nomi host e indirizzi IP per ciascuno dei controller del sistema di archiviazione e tutti gli switch applicabili
* La maggior parte dei controller dei sistemi storage viene gestita tramite l'interfaccia e0M collegandosi alla porta di servizio Ethernet (icona a forma di chiave inglese). Nei sistemi AFF A800 e AFF A700, l'interfaccia e0M utilizza una porta Ethernet dedicata.


Consulta la  https://hwu.netapp.com["Hardware Universe"^] per le informazioni più recenti. Vedi link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per ulteriori informazioni sui requisiti di installazione dello switch.

.Cosa c'è dopo?
Dopo aver confermato i requisiti di configurazione, puoi rivedere il link:required-documentation-3232c-storage.html["documentazione richiesta"].
