---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'SSH è un requisito quando si utilizzano le funzionalità Cluster Switch Health Monitor \(CSHM\) e di raccolta dei registri. Per abilitare SSH sugli switch del cluster Cisco 3232c, è necessario prima generare le chiavi SSH e poi abilitare SSH.' 
---
= Installare il file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato per la prima volta gli switch Nexus 3232C, installare il file di configurazione di riferimento (RCF).

.Prima di iniziare
Verificare le seguenti installazioni e connessioni:

* Un backup attuale della configurazione dello switch.
* Un cluster completamente funzionante (nessun errore nei log o problemi simili).
* L'attuale RCF.
* Una connessione console allo switch, necessaria durante l'installazione dell'RCF.


.Informazioni su questo compito
La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .

Completare la procedura in link:prepare-install-cisco-nexus-3232c-storage.html["Prepararsi all'installazione di NX-OS e RCF"], e quindi seguire i passaggi seguenti.



== Fase 1: installare l'RCF sugli switch

. Accedi allo switch s2 utilizzando SSH o utilizzando una console seriale.
. Copia l'RCF nella bootflash dello switch s2 utilizzando uno dei seguenti protocolli di trasferimento: FTP, TFTP, SFTP o SCP. Per ulteriori informazioni sui comandi Cisco, consulta la guida appropriata nella  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Riferimento ai comandi NX-OS della serie Cisco Nexus 3000"^].
+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra TFTP utilizzato per copiare un RCF nel bootflash sullo switch s2:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Applicare l'RCF precedentemente scaricato al bootflash.
+
Per ulteriori informazioni sui comandi Cisco , consultare la guida appropriata nel https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Riferimento ai comandi NX-OS della serie Cisco Nexus 3000"^] .

+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra il file RCF `NX9336C-FX2-RCF-v1.13-1-Storage.txt` installato sullo switch s2:

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
Assicuratevi di leggere attentamente le sezioni *Installation notes*, *Important Notes* e *banner* del vostro RCF. È necessario leggere e seguire queste istruzioni per verificare la corretta configurazione e il corretto funzionamento dello switch.

====
. Esaminare l'output del banner dal `show banner motd` comando.  È necessario leggere e seguire le istruzioni riportate nella sezione *Note importanti* per garantire la corretta configurazione e il corretto funzionamento dello switch.
. Verificare che la RCF sia la versione più recente corretta:
+
`show running-config`

+
Quando controlli l'output per verificare di avere l'RCF corretto, assicurati che le seguenti informazioni siano corrette:

+
** Lo striscione RCF
** Le impostazioni del nodo e della porta
** Personalizzazioni
+
L'output varia in base alla configurazione del sito.  Controllare le impostazioni della porta e fare riferimento alle note di rilascio per eventuali modifiche specifiche all'RCF installato.



. Riapplicare eventuali personalizzazioni precedenti alla configurazione dello switch.
. Dopo aver verificato che le versioni RCF e le impostazioni degli switch siano corrette, copiare il file `running-config` file al `startup-config` file.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. Riavvia switch s2:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Ripetere i passaggi da 1 a 8 sullo switch s1.
. Collegare le porte di storage del nodo e le porte di storage shelf di tutti i nodi nel cluster ONTAP agli switch s1 e s2.




== Passaggio 2: verificare le connessioni dello switch

. Verificare che le porte dello switch siano *up*.
+
`show interface brief`

. Verificare che le porte di storage del nodo e le porte dello storage shelf siano nelle VLAN corrette utilizzando i seguenti comandi:
+
`show vlan brief`

+
`show interface trunk`





== Passaggio 3: configura il tuo cluster ONTAP

NetApp consiglia di utilizzare System Manager per configurare nuovi cluster.

System Manager fornisce un flusso di lavoro semplice e facile per l'impostazione e la configurazione del cluster, tra cui l'assegnazione di un indirizzo IP di gestione del nodo, l'inizializzazione del cluster, la creazione di un livello locale, la configurazione dei protocolli e il provisioning dello storage iniziale.

Fare riferimento a https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurare ONTAP su un nuovo cluster con System Manager"] per le istruzioni di installazione.

.Cosa succederà ora?
Dopo aver installato l'RCF, puoi link:configure-ssh-keys.html["verificare la configurazione SSH"].
