---
permalink: switch-cisco-3232c-storage/prepare-install-cisco-nexus-3232c-storage.html 
sidebar: sidebar 
keywords: nx-os software, install, cisco nexus storage switches, 3232c, rcfs 
summary: 'Prepara gli switch di storage Cisco Nexus 3232C prima di installare il software NX-OS e il file di configurazione di riferimento (RCF).' 
---
= Prepara l'installazione del software NX-OS e di RCF sugli switch di storage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepara gli switch di storage Cisco Nexus 3232C prima di installare il software NX-OS e il file di configurazione (RCF). NX-OS e l'RCF devono essere installati prima che lo switch possa operare in una rete di storage ONTAP.

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono s1 e s2.
* I nomi dei nodi sono cluster1-01 e cluster1-02.


Vedere link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte di rete corrette sulle proprie piattaforme. Consultare link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per ulteriori informazioni sui requisiti di installazione degli switch.

.Informazioni su questo compito
La procedura richiede l'utilizzo sia dei comandi ONTAP che dei comandi degli switch Cisco Nexus 3000 Series; vengono utilizzati i comandi ONTAP, salvo diversa indicazione.

.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimi la creazione automatica dei casi richiamando un messaggio AutoSupport:
`system node autosupport invoke -node * -type all -message MAINT=x h`
+
dove _x_ è la durata della finestra di manutenzione in ore.

+
[NOTE]
====
Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

====
. Modificare il livello di privilegio in avanzato, immettendo *y* quando richiesto per continuare:
+
`set -privilege advanced`

+
Il prompt avanzato(`*>` ) appare.

. Visualizza quante interfacce sono configurate in ciascun nodo per ciascun switch:
+
`network device-discovery show -protocol cdp`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e5a    s1                        Eth1/2            N3K-C3232C
            e3b    s2                        Eth1/2            N3K-C3232C
cluster1-01/cdp
            e5a    s1                        Eth1/1            N3K-C3232C
            e3b    s2                        Eth1/1            N3K-C3232C
.
.
----
====
. Verificare lo stato amministrativo o operativo di ciascuna porta di storage del nodo e di ciascuna porta di storage dello shelf.
+
.. Visualizza gli attributi della porta di storage del nodo:
+
`storage port show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. Visualizza gli attributi della porta dello shelf di storage: +
`storage shelf port show`
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verificare che il monitoraggio dello stato dello switch (CSHM) sia abilitato per gli switch in modo che siano monitorati:
+
`system switch ethernet show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch             Type               Address          Model
  ------------------ ------------------ ---------------- ---------------
  s1                 storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                 storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.Cosa succederà ora?
Dopo aver preparato l'installazione del software NX-OS e RCF, puoi link:install-nx-os-software-3232c-storage.html["installare il software NX-OS"].
