---
permalink: switch-cisco-3232c-storage/required-documentation-3232c-storage.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Esamina la documentazione necessaria per installare e mantenere gli switch di storage Cisco Nexus 3232C. 
---
= Esamina i requisiti di documentazione per gli switch di storage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esamina la documentazione relativa agli switch e ai controller necessaria per configurare gli switch di storage Cisco Nexus 3232C e configurarli in una rete di storage ONTAP.



[[switch-documentation]]
== Documentazione dello switch

Per configurare gli switch Cisco Nexus 3232C, è necessaria la seguente documentazione da link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Supporto per gli switch Cisco Nexus 3000 Series"^].

[cols="1,2"]
|===
| Titolo del documento | Descrizione 


 a| 
_Guida all'installazione hardware della serie Nexus 3000_
 a| 
Fornisce informazioni dettagliate sui requisiti del sito, dettagli sull'hardware dello switch e opzioni di installazione.



 a| 
Guide alla configurazione del software per gli switch Cisco Nexus 3000 Series (scegli la guida per la release di NX-OS installata sui tuoi switch)
 a| 
Fornisce le informazioni di configurazione iniziale dello switch necessarie prima di poterlo configurare per il funzionamento ONTAP .



 a| 
_Guida all'aggiornamento e al downgrade del software NX-OS per la serie Cisco Nexus 3000_ (scegli la guida relativa alla versione di NX-OS installata sui tuoi switch)
 a| 
Fornisce informazioni su come effettuare il downgrade dello switch al software dello switch supportato ONTAP , se necessario.



 a| 
_Indice principale dei comandi NX-OS Cisco Nexus 3000 Series Command Reference_
 a| 
Fornisce collegamenti ai vari riferimenti ai comandi forniti da Cisco.



 a| 
_Riferimento MIB Cisco Nexus 3000_
 a| 
Descrive i file Management Information Base (MIB) per gli switch Nexus 3000.



 a| 
_Riferimento ai messaggi di sistema NX-OS della serie Nexus 3000_
 a| 
Descrive i messaggi di sistema degli switch Cisco Nexus serie 3000, quelli informativi e altri che possono aiutare a diagnosticare problemi con i collegamenti, l'hardware interno o il software di sistema.



 a| 
_Note di rilascio di Cisco Nexus 3000 Series NX-OS (scegli le note per la versione di NX-OS installata sui tuoi switch)_
 a| 
Descrive le funzionalità, i bug e le limitazioni della serie Cisco Nexus 3000.



 a| 
Informazioni normative, di conformità e di sicurezza per Cisco Nexus 6000, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series e Cisco Nexus 2000 Series
 a| 
Fornisce informazioni sulla conformità alle normative internazionali, sulla sicurezza e sugli obblighi di legge relativi agli switch della serie Nexus 3000.

|===


[[ontap-systems-documentation]]
== Documentazione dei sistemi ONTAP

Per configurare un sistema ONTAP, sono necessari i seguenti documenti per la versione del sistema operativo.

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
Istruzioni di installazione e configurazione specifiche del controller
 a| 
Descrive come installare l'hardware NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Fornisce informazioni dettagliate su tutti gli aspetti delle versioni ONTAP .



 a| 
link:https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornisce informazioni sulla configurazione hardware e sulla compatibilità NetApp .

|===


[[rail-kit-and-cabinet-documentation]]
== Documentazione del kit ferroviario e dell'armadio

Per installare uno switch Cisco 3232C in un cabinet NetApp, consulta la seguente documentazione hardware.

[cols="1,2"]
|===
| Nome | Descrizione 


 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armadio di sistema 42U, guida profonda"^]
 a| 
Descrive le FRU associate al cabinet del sistema 42U e fornisce istruzioni per la manutenzione e la sostituzione delle FRU.



 a| 
link:install-cisco-nexus-3232c-storage.html["Installa uno switch Cisco Nexus 3232C in un NetApp Cabinet"^]
 a| 
Descrive come installare uno switch Cisco Nexus 3232C in un armadio NetApp a quattro montanti.

|===