---
permalink: switch-cisco-3232c-storage/reset-switch-3232c-storage.html 
sidebar: sidebar 
keywords: 3232C reset switch to factory defaults, 3232C switches configuration, efos 
summary: Ripristina lo switch di storage Cisco Nexus 3232C alle impostazioni di fabbrica cancellando la configurazione corrente dello switch. 
---
= Ripristina le impostazioni di fabbrica dello switch di storage Cisco Nexus 3232C
:allow-uri-read: 


[role="lead"]
Reimposta lo switch di storage Cisco Nexus 3232C alle impostazioni di fabbrica cancellando la configurazione corrente dello switch e ripristinando le impostazioni originali dello switch.

.Informazioni su questo compito
* È necessario connettersi allo switch tramite la console seriale.
* Questa attività reimposta la configurazione della rete di gestione.


.Passi
. Cancella la configurazione esistente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(s2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Ricaricare il software dello switch:
+
`reload`

+
[listing, subs="+quotes"]
----
(s2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
Il sistema si riavvia e accede alla procedura guidata di configurazione. Durante l'avvio, se viene visualizzato il messaggio "Interrompere il provisioning automatico e continuare con la configurazione normale?" (sì/no)[n]”, dovresti rispondere *sì* per procedere.



.Cosa c'è dopo?
Dopo aver reimpostato l'interruttore, puoi link:configure-software-overview-3232c-storage.html["riconfigurare"] configurarlo in base alle tue esigenze.
