---
permalink: switch-cisco-3232c-storage/upgrade-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: 'Il software Cisco NX-OS e i file di configurazione di riferimento (RCF) possono essere aggiornati sugli switch di archiviazione Cisco Nexus 3232C.' 
---
= Aggiorna uno switch di archiviazione Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiornare il software Cisco NX-OS e i file di configurazione di riferimento (RCF) sugli switch Cisco Nexus 3232C, seguire questi passaggi.



== Requisiti di revisione

.Prima di iniziare
Prima di aggiornare il software NX-OS e gli RCF sullo switch di archiviazione, assicurarsi che siano soddisfatte le seguenti condizioni:

* Lo switch è perfettamente funzionante (non dovrebbero esserci errori nei log o problemi simili).
* Se si installa solo NX-OS e si mantiene la versione RCF corrente, sono state selezionate o impostate le variabili di avvio desiderate nell'RCF in modo da riflettere le immagini di avvio desiderate.
+
Se è necessario modificare le variabili di avvio per riflettere le immagini di avvio correnti, è necessario farlo prima di riapplicare l'RCF, in modo che ai riavvii futuri venga istanziata la versione corretta.

* Hai fatto riferimento alle guide software e di upgrade appropriate disponibili nella pagina link:http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Switch Cisco Nexus serie 3000"^] per la documentazione completa sulle procedure di upgrade e downgrade dello storage Cisco.
* Il numero di porte 10 GbE e 40/100 GbE è definito nei file di configurazione di riferimento (RCF) disponibili nella pagina link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco®"^].




== Sostituire l'interruttore

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due storage switch sono s1 e s2.
* I nodi sono cluster1-01 e cluster1-02.


Gli esempi in questa procedura utilizzano due nodi: cluster1-01 con due porte di storage e cluster1-02 con due porte di storage. Consultare la link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte di storage corrette sulle piattaforme. Consultare link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per ulteriori informazioni sui requisiti di installazione degli switch.


NOTE: La procedura richiede l'uso sia dei comandi ONTAP sia dei comandi degli switch Cisco Nexus serie 3000; salvo diversa indicazione, vengono utilizzati i comandi ONTAP .  Gli output dei comandi potrebbero variare a seconda delle diverse versioni di ONTAP.



=== Passaggio 1: verificare lo stato di integrità degli switch e delle porte

. Se AutoSupport è abilitato, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

. Verificare che gli switch di archiviazione siano disponibili:
+
`system switch ethernet show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                  Type               Address          Model
----------------------- ------------------ ---------------- ---------------
s1
                        storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

s2
                        storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. Verificare che le porte del nodo siano funzionanti e funzionanti:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
.
.
----
====
. Verificare che non vi siano problemi con l'interruttore di archiviazione o con il cablaggio:
+
`system health alert show -instance`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====




=== Passaggio 2: copia l'RCF sullo switch Cisco s2

. Copia l'RCF sullo switch s2 nel bootflash dello switch utilizzando uno dei seguenti protocolli di trasferimento: FTP, HTTP, TFTP, SFTP o SCP.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata nel link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^].

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra l'utilizzo di HTTP per copiare un RCF nel bootflash sullo switch s2:

[listing, subs="+quotes"]
----
s2# *copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management*
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:-   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
s2#
----
====
. Applicare l'RCF precedentemente scaricato al bootflash:
+
`copy bootflash:`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra il file RCF `Nexus_3232C_RCF_v1.6-Storage.txt` installato sullo switch s2:

[listing, subs="+quotes"]
----
s2# *copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands*
----
====
. Verificare che il file RCF sia la versione più recente corretta:
+
`show running-config`

+
Quando controlli l'output per verificare di avere l'RCF corretto, assicurati che le seguenti informazioni siano corrette:

+
** Lo striscione RCF
** Le impostazioni del nodo e della porta
** Personalizzazioni
+
L'output varia in base alla configurazione del sito.  Controllare le impostazioni della porta e fare riferimento alle note di rilascio per eventuali modifiche specifiche all'RCF installato.

+
[NOTE]
====
Nel banner di output dal `show banner motd` comando, è necessario leggere e seguire le istruzioni nella sezione *NOTE IMPORTANTI* per assicurarsi che la configurazione e il funzionamento dello switch siano corretti.

====
+
.Mostra esempio
[%collapsible]
====
[listing]
----
s2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
s2#
----
====
+

NOTE: Quando si applica RCF per la prima volta, è previsto il messaggio *ERROR: Failed to write VSH commands*, che può essere ignorato.



. Dopo aver verificato che le versioni del software e le impostazioni dello switch siano corrette, copia il `running-config` file nel `startup-config` file sullo switch s2.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata nel link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^].

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra il `running-config` file copiato correttamente nel `startup-config` file:

[listing]
----
s2# copy running-config startup-config
[########################################] 100% Copy complete.
----
====




=== Passaggio 3: copia l'immagine NX-OS sullo switch Cisco s2 e riavvia

. Copia l'immagine NX-OS sullo switch s2.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Installare l'immagine di sistema in modo che la nuova versione venga caricata al successivo riavvio dello switch S2.
+
Lo switch verrà riavviato tra 10 secondi con la nuova immagine, come mostrato nel seguente output:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*
input string too long
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
s2#
----
====
. Salvare la configurazione.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata nel link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Riferimenti ai comandi NX-OS della serie Cisco Nexus 3000"^].

+
Ti verrà richiesto di riavviare il sistema.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy running-config startup-config*
[########################################] 100% Copy complete.
s2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
====
. Verificare che sullo switch sia presente il nuovo numero di versione NX-OS:
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

s2#
----
====




=== Passaggio 4: ricontrollare lo stato di integrità degli switch e delle porte

. Ricontrollare che gli switch di archiviazione siano disponibili dopo il riavvio:
+
`system switch ethernet show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
s1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

s2
                            storage-network    172.17.227.6    NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP
----
====
. Verificare che le porte dello switch siano funzionanti e integre dopo il riavvio:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. Ricontrollare che non vi siano problemi di cablaggio o di switch di archiviazione nel cluster:
+
`system health alert show -instance`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Ripetere la procedura per aggiornare il software NX-OS e RCF sullo switch s1.
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
Dopo aver aggiornato il tuo switch, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
