---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: È possibile utilizzare questa procedura per aggiornare la versione RCF. 
---
= Aggiorna il tuo file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare la versione RCF quando è installata una versione esistente del file RCF sugli switch operativi.

.Prima di iniziare
Assicurati di avere quanto segue:

* Un backup attuale della configurazione dello switch.
* Un cluster completamente funzionante (nessun errore nei log o problemi simili).
* L'attuale RCF.
* Se si aggiorna la versione RCF, è necessaria una configurazione di avvio in RCF che rifletta le immagini di avvio desiderate.
+
Se è necessario modificare la configurazione di avvio per riflettere le immagini di avvio correnti, è necessario farlo prima di riapplicare l'RCF, in modo che la versione corretta sia inclusa nei riavvii futuri.




CAUTION: Prima di installare una nuova versione del software dello switch e degli RCF, è necessario cancellare le impostazioni dello switch ed eseguire la configurazione di base.  Prima di cancellare le impostazioni dello switch, è necessario essere connessi allo switch tramite la console seriale oppure aver conservato le informazioni di configurazione di base.



== Passaggio 1: Prepararsi all'aggiornamento

. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Dove _x_ è la durata della finestra di manutenzione in ore.

. Modificare il livello di privilegio in avanzato, immettendo *y* quando richiesto per continuare:
+
`set -privilege advanced`

+
Viene visualizzato il prompt avanzato (*>).

. Visualizza le porte su ciascun nodo connesse agli switch:
+
[source, cli]
----
network device-discovery show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====
. Verificare lo stato amministrativo o operativo di ciascuna porta di storage del nodo e di ciascuna porta di storage dello shelf.
+
.. Verificare che tutte le porte di storage del nodo siano attive e con stato integro:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. Verificare che tutte le porte dello scaffale di archiviazione siano attive e in buono stato:
+
[source, cli]
----
storage shelf port show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verificare che gli switch siano monitorati.
+
[source, cli]
----
system switch ethernet show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== Fase 2: Aggiorna l'RCF

. Accedi allo switch s2 utilizzando SSH o utilizzando una console seriale.
. Disattivare le porte collegate a tutte le porte dei nodi.
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-32*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: Assicurati di chiudere *tutte* le porte connesse per evitare problemi di connessione di rete. Vedi l'articolo della Knowledge Base https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nodo fuori quorum durante la migrazione del cluster LIF durante l'aggiornamento del sistema operativo dello switch"^] per ulteriori dettagli.

. Se non lo hai già fatto, salva una copia della configurazione corrente dello switch copiando l'output del seguente comando in un file di testo:
+
`show running-config`

+
.. Registrare eventuali aggiunte personalizzate tra l'attuale `running-config` e il file RCF in uso (ad esempio una configurazione SNMP per la tua organizzazione).
.. Per NX-OS 10.2 e versioni successive, utilizzare `show diff running-config` comando per confrontare con il file RCF salvato nel bootflash. In caso contrario, utilizzare uno strumento di confronto o diff di terze parti.


. Salva i dettagli di configurazione di base nel `write_erase.cfg` file sul bootflash.
+
[NOTE]
====
Assicurati di configurare quanto segue:

** Nome utente e password
** Indirizzo IP di gestione
** Gateway predefinito
** Cambia nome


====
+
`s2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`s2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`s2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
Vedi l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Come cancellare la configurazione su uno switch di interconnessione Cisco mantenendo la connettività remota"^] per ulteriori dettagli.

. Verificare che il `write_erase.cfg` il file è popolato come previsto:
+
`*show file bootflash:write_erase.cfg*`

. Emettere il `write erase` comando per cancellare la configurazione salvata corrente:
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copiare la configurazione di base salvata in precedenza nella configurazione di avvio.
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. Riavviare lo switch:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Una volta che l'indirizzo IP di gestione è nuovamente raggiungibile, accedere allo switch tramite SSH.
+
Potrebbe essere necessario aggiornare le voci del file host relative alle chiavi SSH.

. Copia l'RCF nel bootflash dello switch s2 utilizzando uno dei seguenti protocolli di trasferimento: FTP, TFTP, SFTP o SCP.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata nella  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html#CommandReferences["Documentazione Cisco Nexus 3000 Series NX-OS"^].

+
.Mostra esempio
[%collapsible]
====
Questo esempio mostra TFTP utilizzato per copiare un RCF nel bootflash sullo switch s2:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Applicare l'RCF precedentemente scaricato al bootflash.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata nella  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentazione della serie Cisco Nexus 3000"^].

+
Questo esempio mostra il file RCF `NX3232C-RCF-v1.13-1-Storage.txt` installato sullo switch s2:

+
[listing, subs="+quotes"]
----
s2# *copy NX3232C-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
Assicuratevi di leggere attentamente le sezioni *Note di installazione*, *Note importanti* e *banner* del vostro RCF. Per garantire la corretta configurazione e il corretto funzionamento dello switch, è necessario leggere e seguire queste istruzioni.

====
. Verificare che il file RCF sia la versione più recente corretta:
+
`show running-config`

+
Quando controlli l'output per verificare di avere l'RCF corretto, assicurati che le seguenti informazioni siano corrette:

+
** Lo striscione RCF
** Le impostazioni del nodo e della porta
** Personalizzazioni
+
L'output varia in base alla configurazione del sito.  Controllare le impostazioni della porta e fare riferimento alle note di rilascio per eventuali modifiche specifiche all'RCF installato.



. Riapplicare eventuali personalizzazioni precedenti alla configurazione dello switch.
. Dopo aver verificato che le versioni RCF, le aggiunte personalizzate e le impostazioni degli switch siano corrette, copiare il file `running-config` file al `startup-config` file.
+
Per ulteriori informazioni sui comandi Cisco, consultare la guida appropriata nella  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentazione Cisco Nexus 9000 Series"^].

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Riavviare lo switch s2. È possibile ignorare gli avvisi "`cluster switch health monitor`" e gli eventi "`cluster ports down`" segnalati sui nodi durante il riavvio dello switch.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Verificare lo stato amministrativo o operativo di ciascuna porta di storage del nodo e di ciascuna porta di storage dello shelf.
+
.. Verificare che tutte le porte di archiviazione siano attive e integre:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. Verificare che tutte le porte dello scaffale di archiviazione siano attive e in buono stato:
+
[source, cli]
----
storage shelf port show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verificare che gli switch siano monitorati:
+
[source, cli]
----
system switch ethernet show
----
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. Ripeti i passaggi da 1 a 16 sullo switch s1.




== Passaggio 3: verificare la rete di archiviazione

Completare i seguenti passaggi su ogni switch di archiviazione per verificare che la rete di archiviazione funzioni correttamente dopo l'aggiornamento RCF.

. Verificare che le porte dello switch siano *up*.
+
[source, cli]
----
show interface brief
----
. Verificare che le porte di storage del nodo previste siano ancora connesse:
+
[source, cli]
----
show cdp neighbors
----
. Verificare che le porte previste dello shelf di storage siano ancora connesse:
+
[source, cli]
----
show lldp neighbors
----
. Verificare che le porte di storage del nodo e le porte dello storage shelf siano nelle VLAN corrette utilizzando i seguenti comandi:
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.Cosa succederà ora?
Dopo aver aggiornato il tuo RCF, puoilink:configure-ssh-keys.html["verificare la configurazione SSH"] .
