---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: 'Installa il software FASTPATH sugli switch di cluster NetApp CN1610, iniziando l"aggiornamento dal secondo switch (cs2).' 
---
= Installa il software FASTPATH sugli switch di cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installa il software FASTPATH sugli switch di cluster NetApp CN1610, iniziando l'aggiornamento dal secondo switch, _cs2_.



[[review-requirements]]
== Requisiti di revisione

.Prima di iniziare
Assicurati di avere quanto segue:

* Un backup attuale della configurazione dello switch.
* Un cluster perfettamente funzionante (nessun errore nei log e nessuna scheda di interfaccia di rete (NIC) del cluster difettosa o problemi simili).
* Connessioni di porta perfettamente funzionanti sullo switch del cluster.
* Tutte le porte del cluster sono state configurate.
* Tutte le interfacce logiche del cluster (LIF) sono configurate (non devono essere state migrate).
* Un percorso di comunicazione riuscito: il comando ONTAP (privilegio: avanzato) `cluster ping-cluster -node node1` deve indicare che `larger than PMTU communication` ha avuto successo su tutti i percorsi.
* Una versione supportata di FASTPATH e ONTAP.
+
Assicurati di consultare la tabella di compatibilità degli switch sulla pagina  http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp Switch CN1601 e CN1610"^] per le versioni supportate di FASTPATH e ONTAP.





[[install-fastpath]]
== Installa FASTPATH

La seguente procedura utilizza la sintassi di Clustered Data ONTAP 8.2. Di conseguenza, i nomi dei Vserver del cluster, dei LIF e l'output della CLI sono diversi da quelli di Data ONTAP 8.3.

Possono esserci dipendenze tra la sintassi dei comandi nelle versioni RCF e FASTPATH.

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I due NetApp switch sono cs1 e cs2.
* I due cluster LIF sono clus1 e clus2.
* I Vserver sono vs1 e vs2.
* Il  `cluster::*>` prompt indica il nome del cluster.
* Le porte del cluster su ciascun nodo sono denominate e1a ed e2a.
+
Il link:https://hwu.netapp.com/["Hardware Universe"^] contiene maggiori informazioni sulle porte del cluster effettivamente supportate sulla tua piattaforma.

* I collegamenti Inter-Switch (ISL) supportati sono le porte 0/13 fino a 0/16.
* Le connessioni nodo supportate sono le porte da 0/1 a 0/12.




[[step-1-migrate-cluster]]
=== Passaggio 1: Migra il cluster

. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

. Accedi allo switch come admin. Di default non c'è password. Al `(cs2) #` prompt, inserisci il comando `enable`. Anche in questo caso, di default non c'è password. Questo ti dà accesso alla modalità Privileged EXEC, che ti permette di configurare l'interfaccia di rete.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. Sulla console di ciascun nodo, migra clus2 sulla porta e1a:
+
`network interface migrate`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. Sulla console di ciascun nodo, verifica che la migrazione sia avvenuta:
+
`network interface show`

+
Il seguente esempio mostra che clus2 è stato migrato alla porta e1a su entrambi i nodi:

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




[[step-2-install-fastpath-software]]
=== Passaggio 2: Installa il software FASTPATH

. Arresta la porta cluster e2a su entrambi i nodi:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra la porta e2a che viene disattivata su entrambi i nodi:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifica che la porta e2a sia chiusa su entrambi i nodi:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Spegni le porte Inter-Switch Link (ISL) su cs1, lo switch NetApp attivo:
+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Esegui il backup dell'immagine attiva corrente su cs2.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Scarica il file immagine sullo switch.
+
Copiare il file immagine nell'immagine attiva significa che, al riavvio, tale immagine stabilisce la versione di FASTPATH in esecuzione. L'immagine precedente rimane disponibile come backup.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Verifica la versione in esecuzione del software FASTPATH.
+
`show version`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Visualizza le immagini di avvio per la configurazione attiva e di backup.
+
`show bootvar`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Riavviare lo switch.
+
`reload`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




[[step-3-validate-installation]]
=== Passaggio 3: Convalida dell'installazione

. Accedi di nuovo e verifica la nuova versione del software FASTPATH.
+
`show version`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Attiva le porte ISL su cs1, lo switch attivo.
+
`configure`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Verifica che gli ISL siano operativi:
+
`show port-channel 3/1`

+
Il campo Stato collegamento dovrebbe indicare  `Up`.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Copia il  `running-config` file nel  `startup-config` file quando sei soddisfatto delle versioni del software e delle impostazioni dello switch.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Abilita la seconda porta del cluster, e2a, su ciascun nodo:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Ripristina il clus2 associato alla porta e2a:
+
`network interface revert`

+
Il LIF potrebbe ripristinarsi automaticamente, a seconda della versione del software ONTAP.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Verifica che il LIF sia ora home (`true` su entrambi i nodi:
+
`network interface show -_role cluster_`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Visualizza lo stato dei nodi:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Ripeti i passaggi precedenti per installare il software FASTPATH sull'altro switch, cs1.
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


