---
permalink: switch-netapp-cn1610/migrate-switched-netapp-cn1610.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: Esegui la migrazione da un cluster senza switch a un ambiente cluster con switch utilizzando gli switch cluster NetApp CN1610. 
---
= Esegui la migrazione da un cluster senza switch a un ambiente cluster NetApp CN1610 con switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esegui la migrazione da un ambiente cluster senza switch a due nodi a un ambiente cluster con switch utilizzando gli switch cluster NetApp CN1610. Questa migrazione ti permette di scalare il cluster oltre i due nodi.



[[review-requirements]]
== Requisiti di revisione

.Prima di iniziare
Assicurati di avere quanto segue:

Per una configurazione senza switch a due nodi, assicurati che:

* La configurazione switchless a due nodi è correttamente configurata e funzionante.
* I nodi eseguono ONTAP 8.2 o versioni successive.
* Tutte le porte del cluster sono nello  `up` stato.
* Tutte le interfacce logiche del cluster (LIF) sono nello  `up` stato e sulle rispettive porte home.


Per la configurazione dello switch cluster CN1610:

* L'infrastruttura dello switch cluster CN1610 è pienamente funzionante su entrambi gli switch.
* Entrambi gli switch dispongono di connettività di rete di gestione.
* È disponibile l'accesso alla console per gli switch del cluster.
* I collegamenti tra nodi e tra switch CN1610 utilizzano cavi twinax o in fibra.
+
Il link:https://hwu.netapp.com/["Hardware Universe"^] contiene maggiori informazioni sul cablaggio.

* I cavi Inter-Switch Link (ISL) sono collegati alle porte da 13 a 16 su entrambi gli switch CN1610.
* La personalizzazione iniziale di entrambi gli switch CN1610 è completata.
+
Qualsiasi personalizzazione precedente del sito, come SMTP, SNMP e SSH, dovrebbe essere copiata sui nuovi switch.



.Informazioni correlate
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Impostazione e configurazione degli switch CN1601 e CN1610"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Articolo 1010449 della Knowledge Base NetApp : Come sopprimere la creazione automatica di casi durante le finestre di manutenzione programmata"^]




[[migrate-the-switches]]
== Migrare gli switch

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di cluster switch e nodi:

* I nomi degli switch CN1610 sono cs1 e cs2.
* I nomi dei LIF sono clus1 e clus2.
* I nomi dei nodi sono node1 e node2.
* Il  `cluster::*>` prompt indica il nome del cluster.
* Le porte del cluster utilizzate in questa procedura sono e1a ed e2a.
+
Il link:https://hwu.netapp.com/["Hardware Universe"^] contiene le informazioni più aggiornate sulle porte cluster effettive per le vostre piattaforme.





[[step-1-prepare-for-migration]]
=== Fase 1: Prepararsi alla migrazione

. Cambia il livello di privilegio in avanzato, inserendo `y` quando viene richiesto di continuare:
+
`set -privilege advanced`

+
Viene visualizzato il prompt avanzato (*>).

. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

+
.Mostra esempio
[%collapsible]
====
Il seguente comando sopprime la creazione automatica dei casi per due ore:

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====




[[step-2-configure-ports]]
=== Passaggio 2: configurare le porte

. Disabilita tutte le porte rivolte verso i nodi (non le porte ISL) su entrambi i nuovi switch del cluster cs1 e cs2.
+
Non è consentito disattivare le porte ISL.

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che le porte rivolte verso il nodo da 1 a 12 sono disabilitate sullo switch cs1:

[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
Il seguente esempio mostra che le porte rivolte verso il nodo da 1 a 12 sono disabilitate sullo switch cs2:

[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. Verifica che l'ISL e le porte fisiche sull'ISL tra i due switch di cluster CN1610 cs1 e cs2 siano  `up`:
+
`show port-channel`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte ISL sono  `up` sullo switch cs1:

[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
L'esempio seguente mostra che le porte ISL sono  `up` sullo switch cs2:

[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Visualizza l'elenco dei dispositivi vicini:
+
`show isdp neighbors`

+
Questo comando fornisce informazioni sui dispositivi collegati al sistema.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente elenca i dispositivi adiacenti sullo switch cs1:

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
L'esempio seguente elenca i dispositivi adiacenti sullo switch cs2:

[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. Visualizza l'elenco delle porte del cluster:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra le porte del cluster disponibili:

[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
====
. Verifica che ciascuna porta del cluster sia connessa alla porta corrispondente sul nodo partner del cluster:
+
`run * cdpd show-neighbors`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che le porte del cluster e1a ed e2a sono collegate alla stessa porta sul nodo partner del cluster:

[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
====
. Verifica che tutti i LIF del cluster siano  `up` e operativi:
+
`network interface show -vserver Cluster`

+
Ogni cluster LIF dovrebbe mostrare  `true` nella colonna "`Is Home`".

+
.Mostra esempio
[%collapsible]
====
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
====
+

NOTE: Le seguenti modifiche e i comandi di migrazione nei passaggi da 10 a 13 devono essere eseguiti dal nodo locale.

. Verifica che tutte le porte del cluster siano  `up`:
+
`network port show -ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Imposta il  `-auto-revert` parametro su  `false` cluster LIF clus1 e clus2 su entrambi i nodi:
+
`network interface modify`

+
.Mostra esempio
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
+

NOTE: Per le versioni 8.3 e successive, usa il seguente comando: `network interface modify -vserver Cluster -lif * -auto-revert false`

. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] Migra clus1 sulla porta e2a dalla console di ciascun nodo:
+
`network interface migrate`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra il processo di migrazione di clus1 alla porta e2a su node1 e node2:

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
====
+

NOTE: Per le versioni 8.3 e successive, usa il seguente comando: `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`

. Verifica che la migrazione sia avvenuta:
+
`network interface show -vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio verifica che clus1 sia stato migrato sulla porta e2a su node1 e node2:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. Spegni la porta cluster e1a su entrambi i nodi:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come spegnere la porta e1a su node1 e node2:

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
====
. Verifica lo stato della porta:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che la porta e1a è `down` su node1 e node2:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Scollega il cavo dalla porta cluster e1a su node1, quindi collega e1a alla porta 1 sullo switch di cluster cs1, utilizzando il cablaggio appropriato supportato dagli switch CN1610.
+
Il link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] contiene maggiori informazioni sul cablaggio.

. Scollega il cavo dalla porta cluster e1a su nodo2, quindi collega e1a alla porta 2 sullo switch cluster cs1, utilizzando il cablaggio appropriato supportato dagli switch CN1610.
. Abilita tutte le porte rivolte verso i nodi sullo switch del cluster cs1.
+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che le porte da 1 a 12 sono abilitate sullo switch cs1:

[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
====
. Abilita la prima porta del cluster e1a su ciascun nodo:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra come abilitare la porta e1a su node1 e node2:

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
====
. Verifica che tutte le porte del cluster siano  `up`:
+
`network port show -ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che tutte le porte del cluster sono  `up` su node1 e node2:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Riporta clus1 (che era stato precedentemente migrato) su e1a su entrambi i nodi:
+
`network interface revert`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra come ripristinare clus1 sulla porta e1a su node1 e node2:

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
====
+

NOTE: Per le versioni 8.3 e successive, usa il seguente comando: `network interface revert -vserver Cluster -lif <nodename_clus<N>>`

. Verifica che tutti i cluster LIF siano  `up`, operativi e visualizzati come  `true` nella colonna "Is Home":
+
`network interface show -vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutti i LIF sono  `up` su node1 e node2 e che i risultati della colonna "Is Home" sono  `true`:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. Visualizza informazioni sullo stato dei nodi nel cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra informazioni sullo stato di integrità e sull'idoneità dei nodi nel cluster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Migra clus2 sulla porta e1a dalla console di ciascun nodo:
+
`network interface migrate`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra la procedura per la migrazione di clus2 alla porta e1a su node1 e node2:

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
====
+

NOTE: Per le versioni 8.3 e successive, usa il seguente comando: `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`

. Verifica che la migrazione sia avvenuta:
+
`network interface show -vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio verifica che clus2 sia stato migrato sulla porta e1a su node1 e node2:

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
====
. Arresta la porta cluster e2a su entrambi i nodi:
+
`network port modify`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra come disattivare la porta e2a su node1 e node2:

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifica lo stato della porta:
+
`network port show`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che la porta e2a è  `down` su node1 e node2:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Scollega il cavo dalla porta del cluster e2a su node1, poi collega e2a alla porta 1 sullo switch del cluster cs2, usando il cablaggio appropriato supportato dagli switch CN1610.
. Scollega il cavo dalla porta cluster e2a sul nodo2, poi collega e2a alla porta 2 sullo switch cluster cs2, usando il cablaggio appropriato supportato dagli switch CN1610.
. Abilita tutte le porte rivolte verso i nodi sullo switch del cluster cs2.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1 a 12 sono abilitate sullo switch cs2:

[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. Abilita la seconda porta del cluster e2a su ogni nodo.
+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra come abilitare la porta e2a su node1 e node2:

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====
. Verifica che tutte le porte del cluster siano  `up`:
+
`network port show -ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra che tutte le porte del cluster sono  `up` su node1 e node2:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. Ripristina clus2 (che era stato precedentemente migrato) su e2a su entrambi i nodi:
+
`network interface revert`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra come ripristinare clus2 sulla porta e2a su node1 e node2:

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
+

NOTE: Per la versione 8.3 e successive, i comandi sono:
`cluster::*> network interface revert -vserver Cluster -lif node1_clus2` e
`cluster::*> network interface revert -vserver Cluster -lif node2_clus2`





[[step-3-complete-the-configuration]]
=== Passaggio 3: Completa la configurazione

. Verifica che tutte le interfacce visualizzino  `true` nella colonna "Is Home":
+
`network interface show -vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutti i LIF sono  `up` su node1 e node2 e che i risultati della colonna "Is Home" sono  `true`:

[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] Verifica che entrambi i nodi abbiano due connessioni a ciascuno switch:
+
`show isdp neighbors`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra i risultati appropriati per entrambi gli switch:

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. Visualizza le informazioni sui dispositivi nella tua configurazione:
+
`network device discovery show`

. Disabilita le impostazioni di configurazione senza switch a due nodi su entrambi i nodi utilizzando il comando con privilegi avanzati:
+
`network options detect-switchless modify`

+
.Mostra esempio
[%collapsible]
====
Il seguente esempio mostra come disabilitare le impostazioni di configurazione senza switch:

[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
====
+

NOTE: Per le versioni 9.2 e successive, salta questo passaggio perché la configurazione viene convertita automaticamente.

. Verificare che le impostazioni siano disabilitate:
+
`network options detect-switchless-cluster show`

+
.Mostra esempio
[%collapsible]
====
IL `false` l'output nell'esempio seguente mostra che le impostazioni di configurazione sono disabilitate:

[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
====
+

NOTE: Per la versione 9.2 e successive, aspetta che  `Enable Switchless Cluster` sia impostato su false. Questo può richiedere fino a tre minuti.

. Configura i cluster clus1 e clus2 per il ripristino automatico su ciascun nodo e conferma.
+
.Mostra esempio
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
+

NOTE: Per la versione 8.3 e successive, usa il seguente comando: `network interface modify -vserver Cluster -lif * -auto-revert true` per abilitare il ripristino automatico su tutti i nodi del cluster.

. Verificare lo stato dei membri del nodo nel cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra informazioni sullo stato di integrità e sull'idoneità dei nodi nel cluster:

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. Ripristinare il livello di privilegio su amministratore:
+
`set -privilege admin`


