---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Se si dispone di un cluster switchless a due nodi, è possibile migrare, senza interruzioni, a un cluster switch a due nodi che include switch di rete cluster NetApp CN1610. 
---
= Opzioni di migrazione per un cluster commutato a due nodi con switch cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di un cluster switchless a due nodi, è possibile migrare, senza interruzioni, a un cluster switch a due nodi che include switch di rete cluster NetApp CN1610.  La procedura da utilizzare varia a seconda che si disponga di due porte di rete cluster dedicate su ciascun controller o di una singola porta cluster su ciascun controller.

La maggior parte dei sistemi richiede due porte di rete cluster dedicate su ciascun controller.

I nodi FAS22xx consentono una singola porta cluster su ciascun controller.

Sono disponibili due opzioni di migrazione:

* link:migrate-switched-netapp-cn1610.html["Migrazione da un cluster switchless a un ambiente cluster NetApp CN1610 commutato"]
* link:migrate-fas22xx-systems.html["Migrazione da un cluster switchless (sistemi FAS22xx con una singola connessione cluster-rete)"]

