---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Esamina le opzioni di migrazione per passare da un cluster senza switch a un cluster con switch utilizzando gli switch di cluster NetApp CN1610. 
---
= Esamina le opzioni di migrazione per gli switch cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esamina le opzioni di migrazione per il passaggio da un cluster senza switch a un cluster con switch utilizzando gli switch di cluster NetApp CN1610. La procedura dipende dal fatto che tu abbia due porte di rete cluster dedicate o una singola porta cluster su ciascun controller.

La maggior parte dei sistemi richiede due porte di rete cluster dedicate su ciascun controller.

I nodi FAS22xx consentono una singola porta cluster su ciascun controller.

Sono disponibili due opzioni di migrazione:

* link:migrate-switched-netapp-cn1610.html["Esegui la migrazione da un cluster senza switch a un ambiente cluster NetApp CN1610 con switch"]
* link:migrate-fas22xx-systems.html["Migra da un cluster senza switch (sistemi FAS22xx con una singola connessione di rete cluster)"]

