---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Se hai un cluster senza switch a due nodi, puoi migrare, senza interruzioni, a un cluster a due nodi con switch che include gli switch di rete cluster NetApp CN1610. 
---
= Opzioni di migrazione per un cluster a due nodi con switch di cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se hai un cluster senza switch a due nodi, puoi migrare, senza interruzioni, a un cluster a due nodi con switch che include gli switch di rete cluster CN1610 NetApp. La procedura che usi dipende dal fatto che su ciascun controller ci siano due porte di rete cluster dedicate oppure una singola porta cluster su ciascun controller.

La maggior parte dei sistemi richiede due porte di rete cluster dedicate su ciascun controller.

I nodi FAS22xx consentono una singola porta cluster su ciascun controller.

Sono disponibili due opzioni di migrazione:

* link:migrate-switched-netapp-cn1610.html["Esegui la migrazione da un cluster senza switch a un ambiente cluster NetApp CN1610 con switch"]
* link:migrate-fas22xx-systems.html["Migra da un cluster senza switch (sistemi FAS22xx con una singola connessione di rete cluster)"]

