---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: È necessario installare il software FASTPATH e i file di configurazione di riferimento RCF su uno switch di cluster NetApp CN1610. 
---
= Preparati a installare il software FASTPATH e gli RCF su uno NetApp cluster switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Devi installare il software FASTPATH e i file di configurazione di riferimento (RCF) su uno switch di cluster NetApp CN1610.

.Prima di iniziare
* Il cluster deve essere un cluster perfettamente funzionante.
* Non devono esserci schede di interfaccia di rete (NIC) del cluster difettose e tutte le porte collegate sullo switch del cluster devono essere funzionanti.
* Tutte le porte del cluster devono essere attive.
* Tutte le interfacce logiche del cluster (LIF) devono essere attive e non devono essere state migrate.
* Il comando ONTAP (privilegio: avanzato) `cluster ping-cluster -node node1` deve indicare che `larger than PMTU communication` ha avuto successo su tutti i percorsi.
* Devi consultare la tabella di compatibilità degli switch nella pagina  http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp Switch CN1601 e CN1610"^] per le versioni supportate di FASTPATH, RCF e ONTAP.
+
Possono esserci dipendenze tra la sintassi dei comandi nelle versioni RCF e FASTPATH.




NOTE: Nella versione 1.2 di RCF, il supporto per Telnet è stato esplicitamente disabilitato per motivi di sicurezza. Per evitare problemi di connettività durante l'installazione di RCF 1.2, devi verificare che Secure Shell (SSH) sia abilitato. Il https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp® Guida dell'amministratore dello switch CN1610"^] contiene ulteriori informazioni su SSH.

.Informazioni su questo compito
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Le procedure in questo documento utilizzano la sintassi di Clustered Data ONTAP 8.2. Di conseguenza, il Vserver del cluster, i nomi delle LIF e l'output della CLI saranno diversi rispetto a quelli di Data ONTAP 8.3.
* I due NetApp switch sono cs1 e cs2.
* I due cluster LIF sono clus1 e clus2.
* I Vserver sono vs1 e vs2.
* Il  `cluster::*>` prompt indica il nome del cluster.
* Le porte del cluster su ciascun nodo sono denominate e1a ed e2a.
+
La https://hwu.netapp.com/["Hardware Universe"^] contiene maggiori informazioni sulle porte del cluster effettivamente supportate sulla tua piattaforma.

* I collegamenti inter-switch (ISL) supportati per lo NetApp cluster switch sono le porte da 0/13 a 0/16.
* Le connessioni dei nodi supportate per lo NetApp cluster switch sono le porte da 0/1 a 0/12.


Questa procedura si compone di due parti:

* link:install-fastpath-software.html["Installa il software FASTPATH"]Descrive come installare il software FASTPATH.
* link:install-rcf-file.html["Installa un RCF su uno switch CN1610"]Spiega come installare gli RCF.

