---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: 'È necessario installare il software FASTPATH ​​e i file di configurazione di riferimento (RCF) su uno switch cluster NetApp CN1610.' 
---
= Prepararsi all'installazione del software FASTPATH ​​e degli RCF su uno switch cluster NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare il software FASTPATH ​​e i file di configurazione di riferimento (RCF) su uno switch cluster NetApp CN1610.

.Prima di iniziare
* Il cluster deve essere un cluster completamente funzionante.
* Non devono essere presenti schede di interfaccia di rete (NIC) del cluster difettose e tutte le porte collegate allo switch del cluster devono essere funzionanti.
* Tutte le porte del cluster devono essere attive.
* Tutte le interfacce logiche del cluster (LIF) devono essere attive e non devono essere state migrate.
* L' ONTAP (privilegio: avanzato) `cluster ping-cluster -node node1` il comando deve indicare che `larger than PMTU communication` ha successo su tutti i percorsi.
* È necessario consultare la tabella di compatibilità degli switch sul http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switch NetApp CN1601 e CN1610"^] pagina per le versioni FASTPATH, RCF e ONTAP supportate.
+
Possono esserci dipendenze tra i comandi della sintassi nelle versioni RCF e FASTPATH.




NOTE: Nella versione 1.2 di RCF, il supporto per Telnet è stato esplicitamente disabilitato per motivi di sicurezza.  Per evitare problemi di connettività durante l'installazione di RCF 1.2, è necessario verificare che Secure Shell (SSH) sia abilitato.  IL https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guida dell'amministratore dello switch NetApp® CN1610"^] contiene maggiori informazioni su SSH.

.Informazioni su questo compito
Gli esempi in questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* Le procedure descritte in questo documento utilizzano la sintassi clustered Data ONTAP 8.2.  Di conseguenza, il cluster Vserver, i nomi LIF e l'output CLI saranno diversi da quelli in Data ONTAP 8.3.
* I due switch NetApp sono cs1 e cs2.
* I due cluster LIF sono clus1 e clus2.
* I Vserver sono vs1 e vs2.
* IL `cluster::*>` il prompt indica il nome del cluster.
* Le porte del cluster su ciascun nodo sono denominate e1a ed e2a.
+
IL https://hwu.netapp.com/["Hardware Universe"^] contiene maggiori informazioni sulle porte cluster effettivamente supportate sulla tua piattaforma.

* I collegamenti Inter-Switch (ISL) supportati per lo switch cluster NetApp sono le porte da 0/13 a 0/16.
* Le connessioni dei nodi supportate per lo switch cluster NetApp sono le porte da 0/1 a 0/12.


Questa procedura è composta da due parti:

* link:install-fastpath-software.html["Installa il software FASTPATH"]descrive come installare il software FASTPATH.
* link:install-rcf-file.html["Installare un RCF su uno switch CN1610"]descrive come installare gli RCF.

