---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: Sostituisci uno switch di cluster NetApp CN1610 difettoso. Questa è una procedura senza interruzioni. 
---
= Sostituisci uno switch di cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sostituisci uno switch di cluster CN1610 NetApp difettoso in una rete di cluster senza interrompere il funzionamento del cluster. Questa procedura non distruttiva (NDU) prevede la preparazione di uno switch sostitutivo e la migrazione delle connessioni dallo switch guasto.



[[review-requirements]]
== Requisiti di revisione

.Prima di iniziare
Prima di procedere alla sostituzione dello switch, devono essere soddisfatte le seguenti condizioni nell'ambiente attuale e sullo switch sostitutivo per l'infrastruttura di cluster e di rete esistente:

* Il cluster esistente deve essere verificato come completamente funzionante, con almeno uno switch del cluster completamente connesso.
* Tutte le porte del cluster devono essere *attive*.
* Tutte le interfacce logiche del cluster (LIF) devono essere attive e non devono essere state migrate.
* Il comando  `ping-cluster -node node1`ONTAP cluster deve indicare che la connettività di base e la comunicazione di dimensioni superiori a PMTU hanno esito positivo su tutti i percorsi.




[[enable-console-logging]]
== Abilita la registrazione della console

NetApp consiglia vivamente di abilitare la registrazione della console sui dispositivi utilizzati e di adottare le seguenti misure quando si sostituisce lo switch:

* Lasciare AutoSupport abilitato durante la manutenzione.
* Avvia una manutenzione AutoSupport prima e dopo la manutenzione per disabilitare la creazione di casi per tutta la durata della manutenzione. Consulta questo articolo della Knowledge Base link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Come sopprimere la creazione automatica dei casi durante le finestre di manutenzione programmata"^] per ulteriori dettagli.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI.  Per istruzioni su come abilitare la registrazione della sessione, consultare la sezione "Registrazione dell'output della sessione" in questo articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^] .




[[replace-the-switch]]
== Sostituire l'interruttore

.Informazioni su questo compito
È necessario eseguire il comando per migrare un cluster LIF dal nodo in cui è ospitato il cluster LIF.

Gli esempi in questa procedura utilizzano la seguente nomenclatura di cluster switch e nodi:

* I nomi dei due switch cluster CN1610 sono  `cs1` e  `cs2`.
* Il nome dello switch CN1610 da sostituire (lo switch difettoso) è  `old_cs1`.
* Il nome del nuovo switch CN1610 (lo switch di ricambio) è  `new_cs1`.
* Il nome dello switch partner che non viene sostituito è `cs2`.


.Passi
. Verifica che il file di configurazione di avvio corrisponda al file di configurazione in esecuzione. Devi salvare questi file localmente per poterli utilizzare durante la sostituzione.
+
I comandi di configurazione nel seguente esempio sono per FASTPATH 1.2.0.7:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. Crea una copia del file di configurazione in esecuzione.
+
Il comando nel seguente esempio è per FASTPATH 1.2.0.7:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: Puoi usare qualsiasi nome file tranne  `CN1610_CS_RCF_v1.2.scr`. Il nome del file deve avere l'estensione *.scr*.

. [[step3]]Salva il file di configurazione in esecuzione dello switch su un host esterno in preparazione alla sostituzione.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. Verificare che le versioni dello switch e di ONTAP corrispondano nella matrice di compatibilità. Consulta link:https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp Switch CN1601 e CN1610"^] per i dettagli.
. Dal link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["Pagina di download del software"^] sito di supporto NetApp, selezionare NetApp Cluster Switches per scaricare le versioni appropriate di RCF e FASTPATH.
. Configura un server TFTP (Trivial File Transfer Protocol) con FASTPATH, RCF e il file di configurazione salvato `.scr` da utilizzare con il nuovo switch.
. Collega la porta seriale (il connettore RJ-45 etichettato "IOIOI" sul lato destro dello switch) a un host disponibile con emulazione di terminale.
. Sul computer host, imposta le impostazioni di connessione del terminale seriale:
+
.. 9600 baud
.. 8 bit di dati
.. 1 bit di stop
.. parità: nessuna
.. controllo di flusso: nessuno


. Collegare la porta di gestione (la porta RJ-45 sul lato sinistro dello switch) alla stessa rete in cui si trova il server TFTP.
. Preparati a connetterti alla rete con il server TFTP.
+
Se usi il protocollo DHCP (Dynamic Host Configuration Protocol), non devi configurare un indirizzo IP per lo switch in questo momento. La porta di servizio è impostata per usare DHCP per impostazione predefinita. La porta di gestione della rete è impostata su nessuno per le impostazioni del protocollo IPv4 e IPv6. Se la tua porta wrench è collegata a una rete con un server DHCP, allora le impostazioni del server vengono configurate automaticamente.

+
Per impostare un indirizzo IP statico, dovresti usare i comandi serviceport protocol, network protocol e serviceport ip.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. In alternativa, se il server TFTP si trova su un laptop, collega lo switch CN1610 al laptop tramite un cavo Ethernet standard e poi configura la sua porta di rete sulla stessa rete con un indirizzo IP alternativo.
+
Puoi usare il comando  `ping` per verificare l'indirizzo. Se non riesci a stabilire la connettività, dovresti usare una rete non instradata e configurare la porta di servizio usando IP 192.168.x o 172.16.x. Puoi riconfigurare la porta di servizio con l'indirizzo IP di gestione della produzione in un secondo momento.

. Facoltativamente, verifica e installa le versioni appropriate del software RCF e FASTPATH per il nuovo switch. Se hai verificato che il nuovo switch è configurato correttamente e non richiede aggiornamenti del software RCF e FASTPATH, puoi passare al punto 13.
+
.. Verifica le nuove impostazioni dello switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. Scarica il file RCF sul nuovo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. Verifica che il file RCF sia stato scaricato sullo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. Applica l'RCF allo switch CN1610.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. Salva il file di configurazione in esecuzione in modo che diventi il file di configurazione di avvio quando riavvii lo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Scarica l'immagine sullo switch CN1610.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. Avvia la nuova immagine di boot attiva riavviando lo switch.
+
Lo switch deve essere riavviato affinché il comando del passaggio 6 rifletta la nuova immagine. Esistono due possibili schermate di risposta che potresti vedere dopo aver immesso il comando reload.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. Copia il file di configurazione salvato dal vecchio switch al nuovo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. Applica la configurazione salvata in precedenza al nuovo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Salva il file di configurazione in esecuzione nel file di configurazione di avvio.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. Se AutoSupport è abilitato su questo cluster, sopprimi la creazione automatica dei casi richiamando un messaggio AutoSupport:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ è la durata della finestra di manutenzione in ore.

+
[NOTE]
====
Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

====
. Sul nuovo switch new_cs1, accedi come utente admin e disattiva tutte le porte che sono collegate alle interfacce del cluster dei nodi (porte da 1 a 12).
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. Migra i LIF del cluster dalle porte collegate allo switch old_cs1.
+
Devi migrare ogni cluster LIF dall'interfaccia di gestione del nodo corrente.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. Verifica che tutte le LIF del cluster siano state spostate sulla porta del cluster appropriata su ciascun nodo.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. Disattiva le porte del cluster collegate allo switch che hai sostituito.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. Verifica lo stato di salute del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Verifica che le porte siano disattivate.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. Sullo switch cs2, disattiva le porte ISL dalla 13 alla 16.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. Verifica se l'amministratore dello storage è pronto per la sostituzione dello switch.
. Scollega tutti i cavi dallo switch old_cs1 e poi collegali alle stesse porte sul nuovo switch new_cs1.
. Sullo switch cs2, attiva le porte ISL dalla 13 alla 16.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. Attiva le porte sul nuovo switch associate ai nodi del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. Su un singolo nodo, attiva la porta del nodo del cluster che è collegata allo switch sostituito e poi verifica che il collegamento sia attivo.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. Ripristina le LIF del cluster associate alla porta nel passaggio 25 sullo stesso nodo.
+
In questo esempio, i LIF su nodo1 vengono ripristinati correttamente se la colonna "Is Home" è vera.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. Se il cluster LIF del primo nodo è attivo e viene ripristinato alla sua porta home, ripeti i passaggi 25 e 26 per attivare le porte del cluster e ripristinare i cluster LIF sugli altri nodi del cluster.
. Visualizza le informazioni sui nodi del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Conferma che il file di configurazione di avvio e il file di configurazione in esecuzione siano corretti sullo switch sostituito. Questo file di configurazione deve corrispondere all'output del passaggio 1.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


