---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: È possibile sostituire senza interruzioni uno switch del cluster NetApp CN1610 difettoso eseguendo una sequenza specifica di attività. 
---
= Sostituire uno switch cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per sostituire uno switch NetApp CN1610 difettoso in una rete cluster. Si tratta di una procedura senza interruzioni (NDU).



== Verifica dei requisiti

.Di cosa hai bisogno
Prima di eseguire la sostituzione dello switch, devono sussistere le seguenti condizioni prima di eseguire la sostituzione dello switch nell'ambiente corrente e sullo switch sostitutivo per l'infrastruttura di rete e del cluster esistente:

* Il cluster esistente deve essere verificato come completamente funzionale, con almeno uno switch del cluster completamente connesso.
* Tutte le porte del cluster devono essere *up*.
* Tutte le interfacce logiche del cluster (LIF) devono essere aggiornate e non devono essere state migrate.
* Il cluster ONTAP `ping-cluster -node node1` Il comando deve indicare che la connettività di base e le comunicazioni di dimensioni superiori a quelle di PMTU hanno esito positivo su tutti i percorsi.




== Attivare la registrazione della console

NetApp consiglia vivamente di attivare la registrazione della console sui dispositivi in uso e di eseguire le seguenti operazioni quando si sostituisce lo switch:

* Lasciare attivato AutoSupport durante la manutenzione.
* Attivare un AutoSupport di manutenzione prima e dopo la manutenzione per disattivare la creazione del caso per tutta la durata della manutenzione. Consultare questo articolo della Knowledge base https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Come eliminare la creazione automatica dei casi durante le finestre di manutenzione programmata"^] per ulteriori dettagli.
* Attivare la registrazione della sessione per qualsiasi sessione CLI. Per istruzioni su come attivare la registrazione della sessione, consultare la sezione "registrazione dell'output della sessione" in questo articolo della Knowledge base https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare Putty per una connettività ottimale ai sistemi ONTAP"^].




== Sostituire lo switch

.A proposito di questa attività
È necessario eseguire il comando per la migrazione di un LIF del cluster dal nodo in cui è ospitato il LIF del cluster.

Gli esempi di questa procedura utilizzano la seguente nomenclatura di nodi e switch del cluster:

* I nomi dei due switch del cluster CN1610 sono `cs1` e. `cs2`.
* Il nome dello switch CN1610 da sostituire (switch difettoso) è `old_cs1`.
* Il nome del nuovo switch CN1610 (switch sostitutivo) è `new_cs1`.
* Il nome dello switch partner che non viene sostituito è `cs2`.


.Fasi
. Verificare che il file di configurazione di avvio corrisponda al file di configurazione in esecuzione. È necessario salvare questi file localmente per utilizzarli durante la sostituzione.
+
I comandi di configurazione nell'esempio seguente sono per FASTPATH 1.2.0.7:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. Creare una copia del file di configurazione in esecuzione.
+
Il comando nell'esempio seguente è per FASTPATH 1.2.0.7:

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: È possibile utilizzare qualsiasi nome di file, ad eccezione di `CN1610_CS_RCF_v1.2.scr`. Il nome del file deve avere l'estensione *.scr*.

. [[fase 3]]salvare il file di configurazione in esecuzione dello switch su un host esterno in preparazione della sostituzione.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. Verificare che le versioni dello switch e di ONTAP corrispondano nella matrice di compatibilità. Vedere https://mysupport.netapp.com/site/info/netapp-cluster-switch["Switch NetApp CN1601 e CN1610"^] per ulteriori informazioni.
. Dal https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["Pagina Download software"^] Sul NetApp Support Site, selezionare NetApp Cluster Switch per scaricare le versioni RCF e FASTPATH appropriate.
. Configurare un server TFTP (Trivial file Transfer Protocol) con FASTPATH, RCF e la configurazione salvata `.scr` file da utilizzare con il nuovo switch.
. Collegare la porta seriale (il connettore RJ-45 denominato "IOI" sul lato destro dello switch) a un host disponibile con emulazione terminale.
. Sull'host, impostare le impostazioni di connessione del terminale seriale:
+
.. 9600 baud
.. 8 bit di dati
.. 1 bit di stop
.. parità: nessuna
.. controllo di flusso: nessuno


. Collegare la porta di gestione (la porta RJ-45 sul lato sinistro dello switch) alla stessa rete in cui si trova il server TFTP.
. Preparare la connessione alla rete con il server TFTP.
+
Se si utilizza il protocollo DHCP (Dynamic host Configuration Protocol), non è necessario configurare un indirizzo IP per lo switch. Per impostazione predefinita, la porta del servizio utilizza DHCP. La porta di gestione della rete è impostata su NONE per le impostazioni dei protocolli IPv4 e IPv6. Se la porta chiave è connessa a una rete che dispone di un server DHCP, le impostazioni del server vengono configurate automaticamente.

+
Per impostare un indirizzo IP statico, utilizzare il protocollo serviceport, il protocollo di rete e i comandi ip serviceport.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. Se il server TFTP si trova su un computer portatile, collegare lo switch CN1610 al computer portatile utilizzando un cavo Ethernet standard, quindi configurare la porta di rete nella stessa rete con un indirizzo IP alternativo.
+
È possibile utilizzare `ping` per verificare l'indirizzo. Se non si riesce a stabilire la connettività, utilizzare una rete non instradata e configurare la porta di servizio utilizzando IP 192.168.x o 172.16.x. È possibile riconfigurare la porta del servizio in un secondo momento con l'indirizzo IP di gestione della produzione.

. Facoltativamente, verificare e installare le versioni appropriate del software RCF e FASTPATH per il nuovo switch. Se il nuovo switch è stato configurato correttamente e non richiede aggiornamenti del software RCF e FASTPATH, passare al punto 13.
+
.. Verificare le nuove impostazioni dello switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. Scaricare l'RCF sul nuovo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. Verificare che l'RCF sia stato scaricato sullo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. Applicare l'RCF allo switch CN1610.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. Salvare il file di configurazione in esecuzione in modo che diventi il file di configurazione di avvio quando si riavvia lo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Scaricare l'immagine sullo switch CN1610.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. Eseguire la nuova immagine di boot attiva riavviando lo switch.
+
Lo switch deve essere riavviato perché il comando nel passaggio 6 rifletta la nuova immagine. Sono disponibili due viste per una risposta che potrebbero essere visualizzate dopo l'immissione del comando reload.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. Copiare il file di configurazione salvato dal vecchio switch al nuovo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. Applicare la configurazione salvata in precedenza al nuovo switch.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. Salvare il file di configurazione in esecuzione nel file di configurazione di avvio.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. Se AutoSupport è attivato su questo cluster, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ è la durata della finestra di manutenzione in ore.

+
[NOTE]
====
Il messaggio AutoSupport informa il supporto tecnico di questa attività di manutenzione in modo che la creazione automatica del caso venga soppressa durante la finestra di manutenzione.

====
. Sul nuovo switch new_cs1, accedere come utente amministratore e chiudere tutte le porte collegate alle interfacce del cluster di nodi (porte da 1 a 12).
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. Eseguire la migrazione delle LIF del cluster dalle porte collegate allo switch Old_cs1.
+
È necessario migrare ciascun LIF del cluster dall'interfaccia di gestione del nodo corrente.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. Verificare che tutte le LIF del cluster siano state spostate nella porta del cluster appropriata su ciascun nodo.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. Spegnere le porte del cluster collegate allo switch sostituito.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. Verificare lo stato del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Verificare che le porte non siano attive.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. Sullo switch cs2, spegnere le porte ISL da 13 a 16.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. Verificare che l'amministratore dello storage sia pronto per la sostituzione dello switch.
. Rimuovere tutti i cavi dallo switch Old_cs1, quindi collegare i cavi alle stesse porte dello switch New_cs1.
. Sullo switch cs2, richiamare le porte ISL da 13 a 16.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. Visualizzare le porte del nuovo switch associate ai nodi del cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. Su un singolo nodo, richiamare la porta del nodo del cluster collegata allo switch sostituito, quindi confermare che il collegamento è attivo.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. Ripristinare le LIF del cluster associate alla porta nella fase 25 sullo stesso nodo.
+
In questo esempio, i LIF su node1 vengono ripristinati correttamente se la colonna "is Home" è vera.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. Se la LIF del cluster del primo nodo è attiva e viene ripristinata alla porta home, ripetere i passaggi 25 e 26 per visualizzare le porte del cluster e ripristinare le LIF del cluster sugli altri nodi del cluster.
. Visualizza le informazioni sui nodi nel cluster.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. Verificare che il file di configurazione di avvio e il file di configurazione in esecuzione siano corretti sullo switch sostituito. Questo file di configurazione deve corrispondere all'output del passaggio 1.
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. Se è stata eliminata la creazione automatica del caso, riattivarla richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


