---
permalink: switch-netapp-cn1610/required-documentation-cn1610.html 
sidebar: sidebar 
keywords: cn1610, switch, netapp 
summary: Esamina la documentazione necessaria per installare e mantenere gli switch cluster NetApp CN1610. 
---
= Esamina i requisiti di documentazione per gli switch cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esamina la documentazione relativa agli switch e ai controller necessaria per configurare gli switch cluster NetApp CN1610 e inserirli in un cluster ONTAP.

[cols="1,2"]
|===
| Titolo del documento | Descrizione 


 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117853["Guida all'installazione 1G"^]
 a| 
Panoramica delle caratteristiche hardware e software dello switch CN1601 e della procedura di installazione.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117824["Guida all'installazione 10G"^]
 a| 
Una panoramica delle caratteristiche hardware e software dello switch CN1610 e una descrizione delle funzionalità per installare lo switch e accedere alla CLI.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Guida all'installazione e alla configurazione degli switch CN1601 e CN1610"^]
 a| 
Dettaglia come configurare l'hardware e il software dello switch per il tuo ambiente cluster.



 a| 
Guida dell'amministratore dello switch CN1601
 a| 
Fornisce esempi di come utilizzare lo switch CN1601 in una rete tipica.

* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117844["Guida dell'amministratore"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2811865["Guida dell'amministratore, versione 1.1.x.x"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117874["Guida dell'amministratore, versione 1.2.x.x"^]




 a| 
Riferimento ai comandi CLI dello switch di rete CN1610
 a| 
Fornisce informazioni dettagliate sui comandi dell'interfaccia a riga di comando (CLI) che usi per configurare il software CN1601.

* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117834["Riferimento comandi"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2811863["Manuale di riferimento dei comandi, versione 1.1.x.x"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117863["Manuale di riferimento dei comandi, versione 1.2.x.x"^]


|===