---
permalink: switch-netapp-cn1610/required-documentation-cn1610.html 
sidebar: sidebar 
keywords: cn1610, switch, netapp 
summary: 'Per l"installazione e la manutenzione dello switch NetApp CN1610, assicurarsi di consultare tutta la documentazione consigliata.' 
---
= Requisiti di documentazione per gli switch NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NetApp CN1610, assicurarsi di consultare tutta la documentazione consigliata.

[cols="1,2"]
|===
| Titolo del documento | Descrizione 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMP1117853["Guida all'installazione 1G"^]
 a| 
Panoramica delle caratteristiche hardware e software dello switch CN1601 e del processo di installazione.



 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMP1117824["Guida all'installazione 10G"^]
 a| 
Panoramica delle funzionalità hardware e software dello switch CN1610 e descrizione delle funzionalità per installare lo switch e accedere alla CLI.



 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Guida all'installazione e alla configurazione degli switch CN1601 e CN1610"^]
 a| 
Spiega in dettaglio come configurare l'hardware e il software dello switch per il tuo ambiente cluster.



 a| 
Guida dell'amministratore dello switch CN1601
 a| 
Fornisce esempi di come utilizzare lo switch CN1601 in una rete tipica.

* https://library.netapp.com/ecm/ecm_download_file/ECMP1117844["Guida dell'amministratore"^]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2811865["Guida dell'amministratore, versione 1.1.xx"^]
* https://library.netapp.com/ecm/ecm_download_file/ECMP1117874["Guida dell'amministratore, versione 1.2.xx"^]




 a| 
Riferimento ai comandi CLI dello switch di rete CN1610
 a| 
Fornisce informazioni dettagliate sui comandi dell'interfaccia della riga di comando (CLI) utilizzati per configurare il software CN1601.

* https://library.netapp.com/ecm/ecm_download_file/ECMP1117834["Riferimento ai comandi"^]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2811863["Riferimento ai comandi, versione 1.1.xx"^]
* https://library.netapp.com/ecm/ecm_download_file/ECMP1117863["Riferimento ai comandi, versione 1.2.xx"^]


|===