---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Prima di configurare gli switch NetApp CN1610, rivedere la panoramica della procedura. 
---
= Panoramica dell'installazione e della configurazione degli switch NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il CN1610 è uno switch Layer 2 gestito ad alta larghezza di banda che fornisce 16 porte Small Form-Factor Pluggable Plus (SFP+) da 10 Gigabit.

Lo switch include alimentatori ridondanti e vassoi per ventole che supportano la sostituzione a caldo per un'elevata disponibilità.  Questo switch 1U può essere installato in un cabinet di sistema NetApp 42U standard da 19 pollici o in un cabinet di terze parti.

Lo switch supporta la gestione locale tramite la porta della console o la gestione remota tramite Telnet o SSH tramite una connessione di rete.  Il CN1610 include una porta di gestione RJ45 Ethernet da 1 Gigabit dedicata per la gestione degli switch fuori banda.  È possibile gestire lo switch immettendo comandi nell'interfaccia della riga di comando (CLI) oppure utilizzando un sistema di gestione della rete (NMS) basato su SNMP.
