---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Scopri lo switch di cluster CN1610 NetApp e il suo ruolo nel networking dei cluster ONTAP. 
---
= Scopri i switch di cluster CN1610 NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il NetApp CN1610 è uno switch cluster Layer 2 gestito a elevata larghezza di banda che offre 16 porte SFP+ da 10 Gigabit. Consulta questa pagina per scoprire le funzionalità dello switch e il suo ruolo nel networking dei cluster ONTAP.

Lo switch include alimentatori ridondanti e alloggiamenti per ventole che supportano la sostituzione a caldo per un'elevata disponibilità. Questo switch 1U può essere installato in un armadio rack standard da 19 pollici 42U NetApp o in un armadio di terze parti.

Lo switch supporta la gestione locale tramite la porta console o la gestione remota tramite Telnet o SSH attraverso una connessione di rete. Il CN1610 include una porta di gestione RJ45 Ethernet da 1 Gigabit dedicata per la gestione out-of-band dello switch. Puoi gestire lo switch inserendo comandi nell'interfaccia a riga di comando (CLI) o utilizzando un sistema di gestione di rete (NMS) basato su SNMP.
