---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: 'Prima di configurare gli switch NetApp CN1610, dai un"occhiata alla panoramica della procedura.' 
---
= Panoramica sull'installazione e la configurazione degli switch NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il CN1610 è uno switch Layer 2 gestito ad alta larghezza di banda che offre 16 porte Small Form-Factor Pluggable Plus (SFP+) da 10 Gigabit.

Lo switch include alimentatori ridondanti e alloggiamenti per ventole che supportano la sostituzione a caldo per un'elevata disponibilità. Questo switch 1U può essere installato in un armadio rack standard da 19 pollici 42U NetApp o in un armadio di terze parti.

Lo switch supporta la gestione locale tramite la porta console o la gestione remota tramite Telnet o SSH attraverso una connessione di rete. Il CN1610 include una porta di gestione RJ45 Ethernet da 1 Gigabit dedicata per la gestione out-of-band dello switch. Puoi gestire lo switch inserendo comandi nell'interfaccia a riga di comando (CLI) o utilizzando un sistema di gestione di rete (NMS) basato su SNMP.
