---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: Scopri di più su cluster, storage e switch condivisi. 
---
= Scopri gli switch del tuo sistema ONTAP
:allow-uri-read: 


[role="lead"]
NetApp offre sistemi AFX, cluster, storage e switch condivisi che garantiscono comunicazioni interne con la possibilità di spostare dati e interfacce di rete all'interno del cluster senza interruzioni.

Gli switch "front-end" forniscono connettività allo storage host, mentre gli switch cluster "back-end" forniscono connessioni tra due o più controller NetApp .


NOTE: Sono supportati solo gli switch back-end convalidati NetApp(ordinati da NetApp).


CAUTION: Se stai aggiornando gli switch, NetApp consiglia di completare prima l'aggiornamento del software ONTAP, quindi di eseguire l'aggiornamento del software degli switch.



[[afx-systems-switches]]
== Interruttori di sistema AFX

Gli switch di sistema AFX consentono di creare switch di rete veloci, efficienti dal punto di vista energetico e salvaspazio. Le loro dimensioni ridotte e l'elevata densità di porte li rendono ideali per la gestione di grandi reti. Le porte supportano diverse velocità e possono essere suddivise in più connessioni. Gli switch di sistema AFX supportati da NetApp includono:

* Cisco Nexus 9808
* Cisco Nexus 9332D-GX2B
* Cisco Nexus 9364D-GX2A




[[cluster-switches]]
== Interruttori a grappolo

Gli switch cluster consentono di creare cluster ONTAP con più di due nodi. Gli switch cluster supportati da NetApp includono:

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




[[storage-switches]]
== Interruttori di archiviazione

Gli switch di archiviazione consentono di instradare i dati tra server e array di archiviazione in una rete SAN (Storage Area Network).  Gli switch di archiviazione supportati da NetApp includono:

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




[[shared-switches]]
== Switch condivisi

Gli switch condivisi consentono di combinare funzionalità di cluster e storage in una configurazione di switch condivisa, supportando l'uso di RCF di cluster e storage condivisi.  Lo switch condiviso supportato da NetApp è:

* Cisco Nexus 9336C-FX2




[[end-of-availability-switches]]
== Interruttori di fine disponibilità

Per un elenco degli switch di rete non più disponibili per l'acquisto, ma ancora supportati, consultare link:../eoa/index.html["Interruttori di fine disponibilità"].
