---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Scopri gli switch cluster Cisco Nexus 92300YC e il loro ruolo nel networking dei cluster ONTAP. 
---
= Scopri lo switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il Cisco Nexus 92300YC è uno switch di cluster per ambienti ONTAP con più di due nodi. Verifica le funzionalità e i casi d'uso di questo switch prima di implementarlo nel tuo cluster.

Puoi installare lo switch Cisco Nexus 92300YC (X190003/R) in un NetApp system cabinet o in un armadio di terze parti con le staffe standard incluse con lo switch.

La tabella seguente elenca il codice articolo e la descrizione per lo switch 92300YC, le ventole e gli alimentatori:

[cols="1,2"]
|===
| Numero di parte | Descrizione 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = scarico lato porte)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = aspirazione lato porte)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventola, flusso d'aria in ingresso dal lato porta Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventola, flusso d'aria di scarico lato porta Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentatore Cisco 650W - presa d'aria lato porta



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentatore, Cisco 650W - scarico lato porta

|===
Dettagli sul flusso d'aria dello switch Cisco Nexus 92300YC:

* Flusso d'aria di scarico lato porta (aria standard): l'aria fredda entra nello chassis attraverso i moduli ventola e alimentatore nel corridoio freddo ed esce attraverso l'estremità porta dello chassis nel corridoio caldo. Flusso d'aria di scarico lato porta con colorazione blu.
* Flusso d'aria in ingresso dal lato porta (aria inversa): l'aria fredda entra nello chassis attraverso l'estremità delle porte nel corridoio freddo ed esce attraverso i moduli ventola e alimentazione nel corridoio caldo. Flusso d'aria in ingresso dal lato porta con colorazione bordeaux.


.Documentazione disponibile
La tabella seguente elenca la documentazione disponibile per gli switch Cisco Nexus 92300YC.

|===


| Titolo | Descrizione 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["Configura gli switch di cluster Cisco® Nexus 92300YC"^]
 a| 
Descrive come configurare e impostare gli switch cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_Installa NX-OS e i file di configurazione di riferimento (RCF)_"^]
 a| 
Descrive come installare NX-OS e i file di configurazione di riferimento (RCF) sullo switch di cluster Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["Configura un nuovo switch Cisco Nexus 92300YC."^]
 a| 
Descrive come migrare da ambienti che utilizzano switch Cisco meno recenti ad ambienti che utilizzano switch Cisco 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc.html["_Migra da uno switch Cisco obsoleto a uno switch Cisco Nexus 92300YC_"^]
 a| 
Descrive la procedura per sostituire uno switch Cisco obsoleto con uno switch cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_Migra da un cluster senza switch a due nodi_"^]
 a| 
Descrive come migrare da un ambiente cluster senza switch a due nodi a un ambiente cluster a due nodi con switch utilizzando gli switch cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_Sostituisci uno switch cluster Cisco Nexus 92300YC_"^]
 a| 
Descrive la procedura per sostituire uno switch Cisco Nexus 92300YC difettoso in un cluster e scaricare il sistema operativo dello switch e il file di configurazione di riferimento.

|===