---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati.  È possibile utilizzare switch di gestione aggiuntivi, che sono facoltativi. 
---
= Panoramica dello switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati.  È possibile utilizzare switch di gestione aggiuntivi, che sono facoltativi.

È possibile installare lo switch Cisco Nexus 92300YC (X190003/R) in un cabinet di sistema NetApp o in un cabinet di terze parti utilizzando le staffe standard incluse con lo switch.

Nella tabella seguente sono elencati il codice articolo e la descrizione dello switch 92300YC, delle ventole e degli alimentatori:

[cols="1,2"]
|===
| Numero di parte | Descrizione 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = scarico lato porta)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = presa lato porta)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventola, flusso d'aria di aspirazione lato porta Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventola, flusso d'aria di scarico lato porta Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentatore, Cisco 650W - presa lato porta



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentatore, Cisco 650W - scarico lato sinistro

|===
Dettagli sul flusso d'aria dello switch Cisco Nexus 92300YC:

* Flusso d'aria di scarico lato babordo (aria standard): l'aria fredda entra nello chassis attraverso la ventola e i moduli di alimentazione nel corridoio freddo e viene espulsa attraverso l'estremità babordo dello chassis nel corridoio caldo.  Flusso d'aria di scarico lato sinistro con colorazione blu.
* Flusso d'aria di aspirazione lato babordo (aria inversa): l'aria fredda entra nel telaio attraverso l'estremità del portello nel corridoio freddo ed esce attraverso la ventola e i moduli di alimentazione nel corridoio caldo.  Presa d'aria lato sinistro con colorazione bordeaux.


.Documentazione disponibile
Nella tabella seguente è elencata la documentazione disponibile per gli switch Cisco Nexus 92300YC.

|===


| Titolo | Descrizione 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["_Configurare gli switch cluster Cisco® Nexus 92300YC_"^]
 a| 
Descrive come impostare e configurare gli switch del cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_Installa NX-OS e file di configurazione di riferimento (RCF)_"^]
 a| 
Descrive come installare NX-OS e i file di configurazione di riferimento (RCF) sullo switch cluster Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["_Configurare un nuovo switch Cisco Nexus 92300YC_"^]
 a| 
Descrive come migrare da ambienti che utilizzano switch Cisco meno recenti ad ambienti che utilizzano switch Cisco 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc.html["_Migrazione da uno switch Cisco più vecchio a uno switch Cisco Nexus 92300YC_"^]
 a| 
Descrive la procedura per sostituire uno switch Cisco più vecchio con uno switch cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_Migrazione da un cluster switchless a due nodi_"^]
 a| 
Descrive come migrare da un ambiente cluster switchless a due nodi a un ambiente switch a due nodi utilizzando gli switch cluster Cisco Nexus 92300YC.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_Sostituisci uno switch cluster Cisco Nexus 92300YC_"^]
 a| 
Descrive la procedura per sostituire uno switch Cisco Nexus 92300YC difettoso in un cluster e scaricare il sistema operativo dello switch e il file di configurazione di riferimento.

|===