---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati.  È possibile utilizzare switch di gestione aggiuntivi, che sono facoltativi. 
---
= Componenti e numeri di parte per gli switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch Cisco Nexus 92300YC, assicurarsi di esaminare tutti i componenti dello switch e i relativi codici articolo. Fare riferimento a link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per i dettagli. Fare riferimento a link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Quali informazioni aggiuntive mi servono per installare la mia attrezzatura che non è presente in HWU?"^] per ulteriori informazioni sui requisiti di installazione dello switch.

Nella tabella seguente sono elencati il codice articolo e la descrizione dello switch 92300YC, delle ventole e degli alimentatori:

[cols="1,2"]
|===
| Numero di parte | Descrizione 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = scarico lato porta)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = presa lato porta)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventola, flusso d'aria di aspirazione lato porta Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventola, flusso d'aria di scarico lato porta Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Alimentatore, Cisco 650W - presa lato porta



 a| 
X-NXA-PAC-650W-F
 a| 
Alimentatore, Cisco 650W - scarico lato sinistro

|===
Dettagli sul flusso d'aria dello switch Cisco Nexus 92300YC:

* Flusso d'aria di scarico lato babordo (aria standard): l'aria fredda entra nello chassis attraverso la ventola e i moduli di alimentazione nel corridoio freddo e viene espulsa attraverso l'estremità babordo dello chassis nel corridoio caldo.  Flusso d'aria di scarico lato sinistro con colorazione blu.
* Flusso d'aria di aspirazione lato babordo (aria inversa): l'aria fredda entra nel telaio attraverso l'estremità del portello nel corridoio freddo ed esce attraverso la ventola e i moduli di alimentazione nel corridoio caldo.  Presa d'aria lato sinistro con colorazione bordeaux.


.Cosa c'è dopo?
Dopo aver confermato i componenti e i numeri di parte, puoi rivedere il link:required-documentation-92300.html["documentazione richiesta"].
