---
permalink: switch-cisco-92300/configure-install-initial.html 
sidebar: sidebar 
keywords: install cisco 92300YC cluster switch, cisco nx 92300yc 
summary: 'Puoi usare questa procedura per eseguire l"installazione iniziale dello switch Cisco Nexus 92300YC.' 
---
= Configura lo switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Segui questa procedura per configurare lo switch Cisco Nexus 92300YC.

.Passi
. Collegare la porta seriale a un host o a una porta seriale.
. Collega la porta di gestione (sul lato non delle porte dello switch) alla stessa rete in cui si trova il tuo server SFTP.
. Sulla console, imposta le impostazioni seriali lato host:
+
** 9600 baud
** 8 bit di dati
** 1 bit di stop
** parità: nessuna
** controllo di flusso: nessuno


. Al primo avvio o al riavvio dopo la cancellazione della configurazione corrente, lo switch Nexus 92300YC entra in un ciclo di avvio. Interrompi questo ciclo digitando *yes* per annullare il Power on Auto Provisioning.
+
Viene visualizzata la schermata di configurazione dell'account amministratore di sistema.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
$ VDC-1 %$ %POAP-2-POAP_INFO:   - Abort Power On Auto Provisioning [yes - continue with normal setup, skip - bypass password and basic configuration, no - continue with Power On Auto Provisioning] (yes/skip/no)[no]: *y*
Disabling POAP.......Disabling POAP
2019 Apr 10 00:36:17 switch %$ VDC-1 %$ poap: Rolling back, please wait... (This may take 5-15 minutes)

          ---- System Admin Account Setup ----

Do you want to enforce secure password standard (yes/no) [y]:
----
====
. Digita *y* per applicare lo standard di sicurezza per le password:
+
[listing, subs="+quotes"]
----
Do you want to enforce secure password standard (yes/no) [y]: *y*
----
. Inserisci e conferma la password per l'utente admin:
+
[listing]
----
Enter the password for "admin":
Confirm the password for "admin":
----
. Digita *sì* per accedere alla finestra di dialogo Basic System Configuration.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus9000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus9000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.

Would you like to enter the basic configuration dialog (yes/no):
----
====
. Crea un altro account di accesso:
+
[listing]
----
Create another login account (yes/no) [n]:
----
. Configura le stringhe di community SNMP di sola lettura e di lettura/scrittura:
+
[listing]
----
Configure read-only SNMP community string (yes/no) [n]:

Configure read-write SNMP community string (yes/no) [n]:
----
. Configura il nome dello switch del cluster:
+
[listing, subs="+quotes"]
----
Enter the switch name : *cs2*
----
. Configura l'interfaccia di out-of-band management:
+
[listing, subs="+quotes"]
----
Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]: *y*

Mgmt0 IPv4 address : 172.22.133.216

Mgmt0 IPv4 netmask : 255.255.224.0

Configure the default gateway? (yes/no) [y]: *y*

IPv4 address of the default gateway : 172.22.128.1
----
. Configura le opzioni IP avanzate:
+
[listing, subs="+quotes"]
----
Configure advanced IP options? (yes/no) [n]: *n*
----
. Configura i servizi Telnet:
+
[listing, subs="+quotes"]
----
Enable the telnet service? (yes/no) [n]: *n*
----
. Configura i servizi SSH e le chiavi SSH:
+
[listing, subs="+quotes"]
----
Enable the ssh service? (yes/no) [y]: *y*

       Type of ssh key you would like to generate (dsa/rsa) [rsa]: *rsa*

       Number of rsa key bits <1024-2048> [1024]: *2048*
----
. Configura altre impostazioni:
+
[listing, subs="+quotes"]
----
Configure the ntp server? (yes/no) [n]: *n*

  Configure default interface layer (L3/L2) [L2]: *L2*

  Configure default switchport interface state (shut/noshut) [noshut]: *noshut*

  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]: *strict*
----
. Conferma le informazioni dello switch e salva la configurazione:
+
[listing, subs="+quotes"]
----
Would you like to edit the configuration? (yes/no) [n]: *n*

Use this configuration and save it? (yes/no) [y]: *y*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----


.Cosa succederà ora?
Dopo aver configurato gli switch, puoi link:install-nxos-overview.html["prepararsi a installare il software NX-OS e RCF"].
