---
permalink: switch-cisco-92300/install-nxos-rcf.html 
sidebar: sidebar 
keywords: install rcf,rcf configure 
summary: È possibile installare RCF dopo aver configurato lo switch Nexus 92300YC per la prima volta. 
---
= Installazione del file di configurazione di riferimento (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare RCF dopo aver configurato lo switch Nexus 92300YC per la prima volta.

.Nomenclatura di switch e nodi
Gli esempi di questa procedura utilizzano la seguente nomenclatura di switch e nodi:

* I nomi dei due switch Cisco sono `cs1` e. `cs2`.
* I nomi dei nodi sono `node1` e. `node2`.
* I nomi LIF del cluster sono `node1_clus1` e. `node1_clus2` per il node1 e. `node2_clus1` e. `node2_clus2` per il node2.
* Il `cluster1::*>` prompt indica il nome del cluster.
* Le porte del cluster su ciascun nodo sono denominate `e0a` e. `e0b`.
+
Vedere link:https://hwu.netapp.com/Home/Index["_Hardware Universe^_"] per le porte cluster effettivamente supportate sulla piattaforma.



.Porte e connessioni di nodi supportate
* I collegamenti Inter-Switch (ISL) supportati per gli switch Nexus 92300YC sono le porte 1/65 e 1/66.
* Le connessioni dei nodi supportate per gli switch Nexus 92300YC sono le porte da 1/1 a 1/66.
* Gli esempi di questa procedura utilizzano due nodi. Questi nodi utilizzano due porte di interconnessione cluster da 10 GbE `e0a` e. `e0b`. Vedere https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] per verificare le porte cluster corrette sulle piattaforme.


.Prima di iniziare
* È necessario disporre dell'RCF corrente.
* Il cluster deve essere completamente funzionante (non devono essere presenti errori nei log o problemi simili).
* Se si installa solo NX-OS e si mantiene la versione corrente di RCF, è necessario aver controllato o impostato la configurazione di boot desiderata in RCF per riflettere le immagini di boot desiderate.
* Se è necessario modificare la configurazione di avvio per riflettere le immagini di avvio correnti, è necessario farlo prima di riapplicare RCF in modo che venga creata un'istanza della versione corretta in caso di riavvio futuro.
* È necessario consultare la tabella di compatibilità degli switch sul https://support.netapp.com/NOW/download/software/cm_switches/["Switch Ethernet Cisco"^] Per le versioni supportate di ONTAP, NX-OS e RCF.
* Esistono dipendenze di comando tra la sintassi del comando in RCF e quella presente nelle versioni di NX-OS.


.A proposito di questa attività
La procedura richiede l'utilizzo di entrambi i comandi ONTAP e Cisco Nexus 9000 Series Switches; i comandi ONTAP vengono utilizzati se non diversamente indicato.

Gli output dei comandi possono variare a seconda delle diverse versioni di ONTAP.

.Fasi
. Collegare lo switch del cluster alla rete di gestione.
. Utilizzare il comando ping per verificare la connettività al server che ospita RCF.
+
Questo esempio verifica che lo switch possa raggiungere il server all'indirizzo IP 172.19.2.1:

+
[listing, subs="+quotes"]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Copiare l'RCF sullo switch Nexus 92300YC:
+
[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/Nexus_92300YC_RCF_v1.0.2.txt*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/Nexus_92300YC_RCF_v1.0.2.txt  /bootflash/nxos.9.2.2.bin
/code/Nexus_92300YC_R  100% 9687   530.2KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. Unire RCF con running-config dello switch:
+
[listing, subs="+quotes"]
----
cs2# *copy bootflash:Nexus_92300YC_RCF_v1.0.2.txt running-config*

Disabling ssh: as its enabled right now:
 generating ecdsa key(521 bits)......
generated ecdsa key

Enabling ssh: as it has been disabled
 this command enables edge port type (portfast) by default on all interfaces. You
 should now disable edge port type (portfast) explicitly on switched ports leading to hubs,
 switches and bridges as they may create temporary bridging loops.

Edge port type (portfast) should only be enabled on ports connected to a single
 host. Connecting hubs, concentrators, switches, bridges, etc...  to this
 interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
 Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet1/1 but will only
 have effect when the interface is in a non-trunking mode.

...

Copy complete, now saving to disk (please wait)...
Copy complete.
----
. Verificare sullo switch che l'RCF sia stato Unito correttamente:
+
`show running-config`

+
[listing, subs="+quotes"]
----
cs2# *show running-config*
!Command: show running-config
!Running configuration last done at: Wed Apr 10 06:32:27 2019
!Time: Wed Apr 10 06:36:00 2019

version 9.2(2) Bios:version 05.33
switchname cs2
vdc cs2 id 1
  limit-resource vlan minimum 16 maximum 4094
  limit-resource vrf minimum 2 maximum 4096
  limit-resource port-channel minimum 0 maximum 511
  limit-resource u4route-mem minimum 248 maximum 248
  limit-resource u6route-mem minimum 96 maximum 96
  limit-resource m4route-mem minimum 58 maximum 58
  limit-resource m6route-mem minimum 8 maximum 8

feature lacp

no password strength-check
username admin password 5 $5$HY9Kk3F9$YdCZ8iQJ1RtoiEFa0sKP5IO/LNG1k9C4lSJfi5kesl
6  role network-admin
ssh key ecdsa 521

banner motd #
********************************************************************************
*                                                                              *
*  Nexus 92300YC Reference Configuration File (RCF) v1.0.2 (10-19-2018)        *
*                                                                              *
*  Ports 1/1  - 1/48: 10GbE Intra-Cluster Node Ports                           *
*  Ports 1/49 - 1/64: 40/100GbE Intra-Cluster Node Ports                       *
*  Ports 1/65 - 1/66: 40/100GbE Intra-Cluster ISL Ports                        *
*                                                                              *
********************************************************************************
----
. Salvare la configurazione in esecuzione in modo che diventi la configurazione di avvio quando si riavvia lo switch:
+
[listing, subs="+quotes"]
----
cs2# *copy running-config startup-config*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. Per ONTAP 9.6P8 e versioni successive, attivare la funzione di raccolta dei log dello switch Ethernet per la raccolta dei file di log relativi allo switch, utilizzando i comandi seguenti: `system cluster-switch log setup-password` e. `system cluster-switch log enable-collection`
+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
. Riavviare lo switch e verificare che la configurazione in esecuzione sia corretta:
+
`reload`

+
[listing, subs="+quotes"]
----
cs2# *reload*

This command will reboot the system. (y/n)?  [n] *y*
----

