---
permalink: switch-cisco-92300/install-switch-92300yc.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 92300YC 
summary: Seguire questa procedura per installare lo switch Cisco Nexus 92300YC. 
---
= Installare lo switch cluster 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per impostare e configurare lo switch Cisco Nexus 92300YC.

.Prima di iniziare
Assicurati di avere quanto segue:

* Accesso a un server HTTP, FTP o TFTP nel sito di installazione per scaricare le versioni NX-OS e RCF (Reference Configuration File) applicabili.
* Versione NX-OS applicabile, scaricata da https://software.cisco.com/download/home["Download del software Cisco"^] pagina.
* Licenze applicabili, informazioni di rete e configurazione e cavi.
* Completatolink:setup-worksheet-92300yc.html["fogli di lavoro sul cablaggio"] .
* RCF applicabili alla rete cluster NetApp e alla rete di gestione scaricabili dal sito di supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^] .  Tutti gli switch di rete cluster e di rete di gestione Cisco vengono forniti con la configurazione predefinita di fabbrica Cisco . Questi switch dispongono anche della versione corrente del software NX-OS, ma non hanno gli RCF caricati.
* link:required-documentation-92300.html["Documentazione richiesta per switch e ONTAP"].


.Passi
. Installare gli switch e i controller della rete del cluster e della rete di gestione.
+
[cols="1,2"]
|===
| Se stai installando... | Poi... 


 a| 
Cisco Nexus 92300YC in un cabinet di sistema NetApp
 a| 
Per istruzioni sull'installazione dello switch in un cabinet NetApp , consultare la guida _Installazione di uno switch cluster Cisco Nexus 92300YC e di un pannello pass-through in un cabinet NetApp .



 a| 
Apparecchiature in un rack Telco
 a| 
Consultare le procedure fornite nelle guide all'installazione dell'hardware dello switch e nelle istruzioni di installazione e configurazione NetApp .

|===
. Cablare la rete del cluster e gli switch della rete di gestione ai controller utilizzando i fogli di lavoro di cablaggio compilati.
. Accendere la rete del cluster e gli switch e i controller della rete di gestione.


.Cosa succederà ora?
Facoltativamente, puoi link:install-switch-netapp-cabinet-92300yc.html["installare uno switch Cisco Nexus 3223C in un cabinet NetApp"]. Altrimenti vai a link:cabling-considerations-92300.html["Rivedere il cablaggio e la configurazione"].
