---
permalink: switch-cisco-92300/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: TNSC,migrate two-node,migrate 2-node 
summary: Quando si esegue la migrazione di un cluster senza switch a due nodi a un cluster con switch Cisco Nexus 92300YC, è necessario conoscere alcune informazioni di configurazione, le connessioni delle porte e i requisiti di cablaggio. 
---
= Migrazione a un cluster con switch a due nodi con switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si esegue la migrazione di un cluster senza switch a due nodi a un cluster con switch Cisco Nexus 92300YC, è necessario conoscere alcune informazioni di configurazione, le connessioni delle porte e i requisiti di cablaggio.

La procedura da seguire dipende dalla presenza di due porte cluster-network dedicate su ciascun controller o di una singola porta cluster su ciascun controller. Il processo documentato funziona per tutti i nodi che utilizzano porte ottiche o twinax, ma non è supportato su questo switch se i nodi utilizzano porte RJ45 10GB BASE-T integrate per le porte di rete del cluster.

La maggior parte dei sistemi richiede due porte cluster-network dedicate su ciascun controller.


NOTE: Al termine della migrazione, potrebbe essere necessario installare il file di configurazione richiesto per supportare il monitoraggio dello stato di salute dello switch cluster (CSHM) per gli switch cluster 92300YC. Consultare la sezione _Installazione del file di configurazione di Cluster Switch Health Monitor (CSHM) per gli switch 92300YC_ in link:../com.netapp.doc.hw-sw-cisco-setup/home.html["Configurazione"] guida.
