---
permalink: switch-cisco-92300/migrate-to-92300yc-overview.html 
sidebar: sidebar 
keywords: migrate to cisco nx 92300yc cluster switch,new cluster switch migration 
summary: Quando si sostituiscono alcuni switch cluster Cisco Nexus precedenti con switch cluster Cisco Nexus 92300YC, è necessario conoscere alcune informazioni di configurazione, le connessioni delle porte e i requisiti di cablaggio. 
---
= Migrare da uno switch Cisco a uno switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si sostituiscono alcuni switch cluster Cisco Nexus precedenti con switch cluster Cisco Nexus 92300YC, è necessario conoscere alcune informazioni di configurazione, le connessioni delle porte e i requisiti di cablaggio.

* Sono supportati i seguenti switch del cluster:
+
** Nexus 92300YC
** Nexus 5596UP
** Nexus 5020
** Nexus 5010


* Gli switch del cluster utilizzano le seguenti porte per le connessioni ai nodi:
+
** Porte e1/1-48 (10/25 GbE), e1/49-64 (40/100 GbE): Nexus 92300YC
** Porte e1/1-40 (10 GbE): Nexus 5596UP
** Porte e1/1-32 (10 GbE): Nexus 5020
** Porte e1/1-12, e2/1-6 (10 GbE): Nexus 5010 con modulo di espansione


* Gli switch del cluster utilizzano le seguenti porte ISL (Inter-Switch link):
+
** Porte e1/65-66 (100 GbE): Nexus 92300YC
** Porte e1/41-48 (10 GbE): Nexus 5596UP
** Porte e1/33-40 (10 GbE): Nexus 5020
** Porte e1/13-20 (10 GbE): Nexus 5010


* Il https://hwu.netapp.com/SWITCH/INDEX["_Hardware Universe_"^] contiene informazioni sul cablaggio supportato per tutti gli switch del cluster.
* Alcune porte degli switch Nexus 92300YC sono state configurate per funzionare a 10 GbE o 40 GbE.
* Hai pianificato, migrato e documentato la connettività 10 GbE e 40 GbE dai nodi agli switch di cluster Nexus 92300YC.
* Le versioni di ONTAP e NX-OS supportate in questa procedura sono disponibili in https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^] pagina.
+

NOTE: Al termine della migrazione, potrebbe essere necessario installare il file di configurazione richiesto per supportare il monitoraggio dello stato di salute dello switch cluster (CSHM) per gli switch cluster 92300YC. Vedere link:setup-install-cshm-file.html["Installare il file di configurazione di Cluster Switch Health Monitor (CSHM)"] per ulteriori informazioni.


