---
permalink: switch-cisco-92300/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: 2-node switched Cisco 92300YC cluster switch migration 
summary: Se si dispone di un ambiente cluster switchless a due nodi esistente, è possibile migrare a un ambiente cluster switchato a due nodi utilizzando gli switch Cisco Nexus 92300YC per poter scalare oltre due nodi nel cluster. 
---
= Migrare a un cluster commutato a due nodi con uno switch Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di un ambiente cluster a due nodi _senza switch_, è possibile migrare a un ambiente cluster a due nodi _con switch_ utilizzando gli switch Cisco Nexus 92300YC per poter scalare oltre due nodi nel cluster.

La procedura da utilizzare varia a seconda che si disponga di due porte di rete cluster dedicate su ciascun controller o di una singola porta cluster su ciascun controller.  Il processo documentato funziona per tutti i nodi che utilizzano porte ottiche o twinax, ma non è supportato su questo switch se i nodi utilizzano porte RJ45 BASE-T da 10 Gb integrate per le porte della rete cluster.

La maggior parte dei sistemi richiede due porte di rete cluster dedicate su ciascun controller.


NOTE: Una volta completata la migrazione, potrebbe essere necessario installare il file di configurazione richiesto per supportare Cluster Switch Health Monitor (CSHM) per gli switch cluster 92300YC. Vederelink:../switch-cshm/cshm-overview.html["Monitoraggio dello stato di salute degli switch (CSHM)"] .



== Requisiti di revisione

.Prima di iniziare
Assicurati di avere quanto segue:

Per una configurazione senza switch a due nodi, assicurarsi che:

* La configurazione switchless a due nodi è correttamente configurata e funzionante.
* I nodi eseguono ONTAP 9.6 e versioni successive.
* Tutte le porte del cluster sono nello stato *attivo*.
* Tutte le interfacce logiche del cluster (LIF) sono nello stato *attivo* e sulle loro porte home.


Per la configurazione dello switch Cisco Nexus 92300YC:

* Entrambi gli switch dispongono di connettività di rete di gestione.
* È disponibile l'accesso alla console per gli switch del cluster.
* Le connessioni da nodo a nodo e da switch a switch del Nexus 92300YC utilizzano cavi twinax o in fibra.
+
https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Interruttori"^]contiene maggiori informazioni sul cablaggio.

* I cavi Inter-Switch Link (ISL) sono collegati alle porte 1/65 e 1/66 su entrambi gli switch 92300YC.
* La personalizzazione iniziale di entrambi gli switch 92300YC è stata completata.  In modo che:
+
** Gli switch 92300YC eseguono l'ultima versione del software
** I file di configurazione di riferimento (RCF) vengono applicati agli switch. Qualsiasi personalizzazione del sito, come SMTP, SNMP e SSH, viene configurata sui nuovi switch.






== Migrare lo switch

.Informazioni sugli esempi
Gli esempi in questa procedura utilizzano la seguente nomenclatura di cluster switch e nodi:

* I nomi degli switch 92300YC sono cs1 e cs2.
* I nomi degli SVM del cluster sono node1 e node2.
* I nomi dei LIF sono node1_clus1 e node1_clus2 sul nodo 1, e node2_clus1 e node2_clus2 sul nodo 2, rispettivamente.
* IL `cluster1::*>` il prompt indica il nome del cluster.
* Le porte cluster utilizzate in questa procedura sono e0a ed e0b.
+
https://hwu.netapp.com["Hardware Universe"^]contiene le informazioni più recenti sulle porte cluster effettive per le tue piattaforme.





=== Fase 1: Prepararsi alla migrazione

. Cambia il livello di privilegio in avanzato, inserendo `y` quando viene richiesto di continuare:
+
`set -privilege advanced`

+
Il prompt avanzato(`*>` ) appare.

. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
dove x è la durata della finestra di manutenzione in ore.

+

NOTE: Il messaggio AutoSupport avvisa il supporto tecnico di questa attività di manutenzione, in modo che la creazione automatica dei casi venga soppressa durante la finestra di manutenzione.

+
.Mostra esempio
[%collapsible]
====
Il seguente comando sopprime la creazione automatica dei casi per due ore:

[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=2h*
----
====




=== Passaggio 2: configurare cavi e porte

. Disabilitare tutte le porte rivolte verso il nodo (non le porte ISL) su entrambi i nuovi switch del cluster cs1 e cs2.
+
Non è consentito disattivare le porte ISL.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1 a 64 rivolte al nodo sono disabilitate sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e/1-64*
cs1(config-if-range)# *shutdown*
----
====
. Verificare che l'ISL e le porte fisiche sull'ISL tra i due switch 92300YC cs1 e cs2 siano attivi sulle porte 1/65 e 1/66:
+
`show port-channel summary`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte ISL sono attive sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
----
+ L'esempio seguente mostra che le porte ISL sono attive sullo switch cs2:

+

[listing, subs="+quotes"]
----
(cs2)# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
----
====
. Visualizza l'elenco dei dispositivi vicini:
+
`show cdp neighbors`

+
Questo comando fornisce informazioni sui dispositivi collegati al sistema.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente elenca i dispositivi adiacenti sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2(FDO220329V5)    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 2
----
+ L'esempio seguente elenca i dispositivi adiacenti sullo switch cs2:

+

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1(FDO220329KU)    Eth1/65        177    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)    Eth1/66        177    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 2
----
====
. Verificare che tutte le porte del cluster siano attive:
+
`network port show -ipspace Cluster`

+
Ogni porta dovrebbe essere visualizzata per `Link` e sano per `Health Status` .

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. Verificare che tutti i cluster LIF siano attivi e operativi:
+
`network interface show -vserver Cluster`

+
Ogni cluster LIF dovrebbe visualizzare true per `Is Home` e avere un `Status Admin/Oper` di su/su

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. Verificare che il ripristino automatico sia abilitato su tutti i LIF del cluster:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. Scollegare il cavo dalla porta e0a del cluster sul nodo 1, quindi collegare e0a alla porta 1 sullo switch cs1 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 92300YC.
+
IL https://hwu.netapp.com/SWITCH/INDEX["_Universo Hardware - Interruttori_"^] contiene maggiori informazioni sul cablaggio.

. Scollegare il cavo dalla porta e0a del cluster sul nodo 2, quindi collegare e0a alla porta 2 sullo switch cs1 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 92300YC.
. Abilitare tutte le porte rivolte verso il nodo sullo switch del cluster cs1.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1/1 a 1/64 sono abilitate sullo switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-64*
cs1(config-if-range)# *no shutdown*
----
====
. Verificare che tutti i cluster LIF siano attivi, operativi e visualizzati come veri per `Is Home` :
+
`network interface show -vserver Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutti i LIF sono attivi su node1 e node2 e che `Is Home` i risultati sono veri:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. Visualizza informazioni sullo stato dei nodi nel cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra informazioni sullo stato di integrità e sull'idoneità dei nodi nel cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Scollegare il cavo dalla porta e0b del cluster sul nodo 1, quindi collegare e0b alla porta 1 sullo switch cs2 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 92300YC.
. Scollegare il cavo dalla porta e0b del cluster sul nodo 2, quindi collegare e0b alla porta 2 sullo switch cs2 del cluster, utilizzando il cablaggio appropriato supportato dagli switch 92300YC.
. Abilitare tutte le porte rivolte verso il nodo sullo switch cluster cs2.
+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che le porte da 1/1 a 1/64 sono abilitate sullo switch cs2:

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-64*
cs2(config-if-range)# *no shutdown*
----
====




=== Passaggio 3: verificare la configurazione

. Verificare che tutte le porte del cluster siano attive:
+
`network port show -ipspace Cluster`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutte le porte del cluster sono attive su node1 e node2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====
. Verificare che tutte le interfacce visualizzino true per `Is Home` :
+
`network interface show -vserver Cluster`

+

NOTE: L'operazione potrebbe richiedere diversi minuti.

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra che tutti i LIF sono attivi su node1 e node2 e che `Is Home` i risultati sono veri:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. Verificare che entrambi i nodi abbiano una connessione a ciascun switch:
+
`show cdp neighbors`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra i risultati appropriati per entrambi gli switch:

[listing, subs="+quotes"]
----
(cs1)# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         133    H         FAS2980       e0a
node2               Eth1/2         133    H         FAS2980       e0a
cs2(FDO220329V5)    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4


(cs2)# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         133    H         FAS2980       e0b
node2               Eth1/2         133    H         FAS2980       e0b
cs1(FDO220329KU)
                    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)
                    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
====
. Visualizza informazioni sui dispositivi di rete rilevati nel tuo cluster:
+
`network device-discovery show -protocol cdp`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.
----
====
. Verificare che le impostazioni siano disabilitate:
+
`network options switchless-cluster show`

+

NOTE: Potrebbero essere necessari diversi minuti affinché il comando venga completato.  Attendi l'annuncio "Scadenza della durata di 3 minuti".

+
.Mostra esempio
[%collapsible]
====
L'output false nell'esempio seguente mostra che le impostazioni di configurazione sono disabilitate:

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====
. Verificare lo stato dei membri del nodo nel cluster:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
L'esempio seguente mostra informazioni sullo stato di integrità e sull'idoneità dei nodi nel cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verificare la connettività delle interfacce del cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e versioni successive
--
Puoi usare il `network interface check cluster-connectivity` comando per avviare un controllo di accessibilità per la connettività del cluster e quindi visualizzare i dettagli:

`network interface check cluster-connectivity start`E `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Attendere alcuni secondi prima di eseguire il `show` comando per visualizzare i dettagli.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Tutte le versioni ONTAP
--
Per tutte le versioni ONTAP , è anche possibile utilizzare `cluster ping-cluster -node <name>` comando per verificare la connettività:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step8]] Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=END*
----
====
. Ripristinare il livello di privilegio su amministratore:
+
`set -privilege admin`



.Cosa succederà ora?
link:../switch-cshm/config-overview.html["Configurare il monitoraggio dello stato dello switch"].
