---
permalink: switch-cshm/config-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: Configura la raccolta dei log per permettere a CSHM di raccogliere i log degli switch e i dati diagnostici dagli switch di rete del cluster e di storage. 
---
= Configura la raccolta dei log per l'health monitor dello switch di rete Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configura la raccolta dei log sugli switch di rete Ethernet per consentire all'Ethernet switch health monitor (CSHM) di raccogliere i log degli switch per il debug e la segnalazione AutoSupport. Questa procedura configura sia la raccolta dei log di supporto su richiesta sia la raccolta periodica oraria dei dati in ONTAP.

.Prima di iniziare
* Se usi la modalità FIPS, completa quanto segue prima di configurare la raccolta dei log:
+
.. Rigenerare le chiavi SSH sullo switch seguendo le istruzioni del fornitore.
.. Rigenera le chiavi SSH in ONTAP utilizzando  `debug system regenerate-systemshell-key-pair`.
.. Esegui di nuovo la configurazione della raccolta dei log usando il comando  `system switch ethernet log setup-password`.


* Devi avere accesso ai comandi dello switch `show`. Se non ce l'hai, crea un nuovo utente dello switch e concedigli i privilegi necessari.
* Il monitoraggio dello stato di salute dello switch deve essere abilitato per lo switch. Verifica controllando che il  `Is Monitored:` campo sia impostato su *true* nell'output di  `system switch ethernet show`.
* Per la raccolta dei log con gli switch Broadcom e Cisco :
+
** L'utente locale deve disporre dei privilegi di amministratore di rete.
** Crea un nuovo utente switch per ogni cluster con la raccolta dei log abilitata. Questi switch non supportano più chiavi SSH per lo stesso utente, eseguire nuovamente la configurazione sovrascrive la chiave SSH esistente.


* Per la raccolta dei log di supporto con gli switch NVIDIA, l'utente addetto alla raccolta dei log deve poter eseguire il comando  `cl-support` senza password. Per permettere questo, esegui:
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`



.Passi
Segui i passaggi relativi alla tua versione di ONTAP per configurare la raccolta dei log, abilitare la raccolta periodica di dati e, facoltativamente, richiedere i log di supporto su richiesta.

[role="tabbed-block"]
====
.ONTAP 9.15.1 e versioni successive
--
. Per impostare la raccolta dei log, eseguire il seguente comando per ogni switch.  Ti verrà richiesto di immettere il nome dello switch, il nome utente e la password per la raccolta dei registri.
+
*NOTA:* Se si risponde *y* alla richiesta di specifica dell'utente, assicurarsi che l'utente disponga delle autorizzazioni necessarie come descritto in<<Prima di iniziare>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Per CL 5.11.1, creare l'utente *cumulus* e rispondere *y* al seguente prompt: Si desidera specificare un utente diverso da admin per la raccolta dei log?  {y|n}: *y*

. [[step2]]Abilita la raccolta periodica dei registri:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. Richiedi la raccolta dei registri di supporto:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. Per visualizzare tutti i dettagli della raccolta dei log, tra cui l'abilitazione, il messaggio di stato, il timestamp precedente e il nome del file della raccolta periodica, lo stato della richiesta, il messaggio di stato, il timestamp precedente e il nome del file della raccolta di supporto, utilizzare quanto segue:
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 e precedenti
--
. Per impostare la raccolta dei log, eseguire il seguente comando per ogni switch.  Ti verrà richiesto di immettere il nome dello switch, il nome utente e la password per la raccolta dei registri.
+
*NOTA:* Se si risponde `y` alla richiesta di specifica dell'utente, assicurarsi che l'utente disponga delle autorizzazioni necessarie come descritto in<<Prima di iniziare>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Per CL 5.11.1, creare l'utente *cumulus* e rispondere *y* al seguente prompt: Si desidera specificare un utente diverso da admin per la raccolta dei log?  {y|n}: *y*

. [[step2]] Per richiedere la raccolta del registro di supporto e abilitare la raccolta periodica, eseguire il seguente comando.  Questo avvia entrambi i tipi di raccolta dei log: il dettagliato `Support` registri e una raccolta oraria di `Periodic` dati.
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Attendi 10 minuti e poi verifica che la raccolta dei log sia completata:

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: Se la funzione di raccolta dei log segnala stati di errore (visibili nell'output di  `system switch ethernet log show`), fare riferimento a link:log-collection-troubleshoot.html["Risoluzione dei problemi di raccolta dei registri"] per ulteriori dettagli.

.Cosa succederà ora?
link:config-snmpv3.html["Configurare SNMPv3 (facoltativo)"].
