---
permalink: switch-cshm/log-collection-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: È possibile utilizzare i comandi forniti qui per ...... 
---
= Risoluzione dei problemi di raccolta dei registri
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si verifica uno dei seguenti stati di errore segnalati dalla funzionalità di raccolta dei log (visibili nell'output del `system switch ethernet log show` comando), provare i passaggi di debug corrispondenti:

|===


| *Stato di errore nella raccolta dei log* | *Risoluzione* 


 a| 
*Chiavi RSA non presenti*
 a| 
Rigenera le chiavi SSH ONTAP .



 a| 
*Errore di cambio password*
 a| 
Verificare le credenziali, testare la connettività SSH e rigenerare le chiavi SSH ONTAP .  Per istruzioni, consultare la documentazione dello switch o contattare l'assistenza NetApp .



 a| 
*Chiavi ECDSA non presenti per FIPS*
 a| 
Se la modalità FIPS è abilitata, è necessario generare le chiavi ECDSA sullo switch prima di riprovare.



 a| 
*Registro preesistente trovato*
 a| 
Rimuovere il file di raccolta dei registri precedente sullo switch.



 a| 
*Errore nel registro di dump dello switch*
 a| 
Assicurarsi che l'utente che effettua lo switch disponga delle autorizzazioni per la raccolta dei log.  Fare riferimento ai prerequisiti sopra indicati.

|===

NOTE: Se i dettagli della risoluzione non funzionano, contattare l'assistenza NetApp .
