---
permalink: switch-cshm/monitor-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Risolvi i problemi relativi agli avvisi di monitoraggio dello stato di salute dello switch Ethernet generati da CSHM nel tuo cluster ONTAP. 
---
= Risolvi i problemi degli avvisi dello switch di rete Ethernet dell'health monitor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Risolvi i problemi relativi agli avvisi generati dall'Ethernet switch health monitor (CSHM) quando viene rilevato un guasto, un rischio o una condizione critica per uno switch di rete nel tuo cluster ONTAP.

Se vengono generati avvisi, lo stato di integrità del sistema segnala uno stato degradato per il cluster.  Gli avvisi generati includono le informazioni necessarie per rispondere al degrado dello stato del sistema.

Per visualizzare gli avvisi di monitoraggio dello stato dello switch Ethernet disponibili, eseguire il comando: `system health alert definition show -monitor ethernet-switch`

Consultare l'articolo della Knowledge Base https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Cluster_Switch_Health_Monitor_CSHM_Alert_Resolution_Guide["Guida alla risoluzione degli avvisi di Switch Health Monitor"^] per dettagli avanzati sulla risoluzione degli avvisi.
