---
permalink: switch-nvidia-sn2100-storage/configure-overview-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Prima di configurare gli switch NVIDIA SN2100, consultare la panoramica della procedura. 
---
= Panoramica del processo di configurazione per gli switch storage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100 è uno switch storage che consente di instradare i dati tra server e storage array in una SAN (Storage Area Network).



== Panoramica della configurazione iniziale

Per configurare uno switch NVIDIA SN2100 sui sistemi che eseguono ONTAP, attenersi alla seguente procedura:

. link:install-hardware-sn2100-storage.html["Installare l'hardware per lo switch NVIDIA SN2100"].
+
Le istruzioni sono disponibili nella _Guida all'installazione dello switch NVIDIA_.

. link:configure-sn2100-storage.html["Configurare lo switch"].
+
Le istruzioni sono disponibili nella documentazione NVIDIA.

. link:cabling-considerations-sn2100-storage.html["Esaminare le considerazioni relative al cablaggio e alla configurazione"].
+
Esaminare i requisiti per le connessioni ottiche, l'adattatore QSA e la velocità di switchport.

. link:install-cable-shelves-sn2100-storage.html["Cablare gli shelf NS224 come storage collegato allo switch"].
+
Seguire queste procedure se si dispone di un sistema in cui gli shelf di dischi NS224 devono essere cablati come storage collegato allo switch (non come storage collegato direttamente).

. link:install-cumulus-mode-sn2100-storage.html["Installare Cumulus Linux in modalità Cumulus"] oppure link:install-onie-mode-sn2100-storage.html["Installare Cumulus Linux in modalità ONIE"].
+
È possibile installare il sistema operativo Cumulus Linux (CL) quando lo switch esegue Cumulus Linux o ONIE.

. link:install-rcf-sn2100-storage.html["Installare lo script del file di configurazione di riferimento"].
+
Sono disponibili due script RCF per le applicazioni di clustering e storage.

. link:setup-install-cshm-file.html["Installare il file CSHM"].
+
È possibile installare il file di configurazione applicabile per il monitoraggio dello stato degli switch Ethernet degli switch cluster NVIDIA.





== Ulteriori informazioni

Prima di iniziare l'installazione o la manutenzione, verificare quanto segue:

* link:configure-reqs-sn2100-storage.html["Requisiti di configurazione"]
* link:components-sn2100-storage.html["Componenti e numeri di parte"]
* link:required-documentation-sn2100-storage.html["Documentazione richiesta"]

