---
permalink: switch-nvidia-sn2100-storage/configure-reqs-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Per l"installazione e la manutenzione dello switch NVIDIA SN2100, assicurarsi di rivedere tutti i requisiti.' 
---
= Requisiti di configurazione per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NVIDIA SN2100, assicurarsi di rivedere tutti i requisiti.



== Requisiti di installazione

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati.  È possibile utilizzare switch di gestione aggiuntivi, che sono facoltativi.

Installare lo switch NVIDIA SN2100 (X190006/X190106) nell'armadio switch doppio/singolo NVIDIA con le staffe standard incluse con lo switch.

Per le linee guida sul cablaggio, vederelink:cabling-considerations-sn2100-storage.html["Considerazioni sul cablaggio e sulla configurazione"] .



== Supporto ONTAP e Linux

Lo switch NVIDIA SN2100 è uno switch Ethernet da 10/25/40/100 Gb che esegue Cumulus Linux.  Lo switch supporta quanto segue:

* ONTAP 9.10.1P3.  Lo switch SN2100 supporta applicazioni Cluster e Storage in ONTAP 9.10.1P3 su diverse coppie di switch.  A partire da ONTAP 9.10.1P3, è possibile utilizzare gli switch NVIDIA SN2100 per combinare funzionalità di storage e cluster in una configurazione di switch condivisa.
* Cumulus Linux (CL) versione 4.4.3 del sistema operativo.  Per informazioni sulla compatibilità attuale, vedere https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switch Ethernet NVIDIA"^] pagina informativa.
* È possibile installare Cumulus Linux quando lo switch esegue Cumulus Linux o ONIE.


.Cosa c'è dopo?
Dopo aver esaminato i requisiti di configurazione, puoi confermare il tuo link:components-sn2100-storage.html["componenti e numeri di parte"].
