---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'Il sistema operativo Cumulus Linux (CL) può essere installato quando lo switch esegue Cumulus Linux o ONIE.' 
---
= Installare Cumulus Linux in modalità ONIE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per installare il sistema operativo Cumulus Linux (CL) quando lo switch è in esecuzione in modalità ONIE.


NOTE: Il sistema operativo Cumulus Linux (CL) può essere installato quando lo switch esegue Cumulus Linux o ONIE (vedere link:install-cumulus-mode-sn2100-storage.html["Installare in modalità Cumulus"]).

.A proposito di questa attività
È possibile installare Cumulus Linux utilizzando Open Network Install Environment (ONIE) che consente il rilevamento automatico dell'immagine di un programma di installazione di rete. Questo semplifica il modello di sistema per la protezione degli switch con una scelta di sistemi operativi, come Cumulus Linux. Il modo più semplice per installare Cumulus Linux con ONIE consiste nel rilevamento HTTP locale.


NOTE: Se l'host è abilitato per IPv6, assicurarsi che sia in esecuzione un server Web. Se l'host è abilitato per IPv4, assicurarsi che sia in esecuzione DHCP oltre a un server Web.

Questa procedura illustra come aggiornare Cumulus Linux dopo l'avvio dell'amministratore in ONIE.

.Fasi
. Scaricare il file di installazione di Cumulus Linux nella directory principale del server Web. Rinominare il file `onie-installer`.
. Collegare l'host alla porta Ethernet di gestione dello switch utilizzando un cavo Ethernet.
. Accendere lo switch. Lo switch scarica il programma di installazione dell'immagine ONIE e si avvia. Al termine dell'installazione, nella finestra del terminale viene visualizzato il prompt di accesso di Cumulus Linux.
+

NOTE: Ogni volta che Cumulus Linux viene installato, l'intera struttura del file system viene cancellata e ricostruita.

. Riavviare lo switch SN2100:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Premere il tasto *Esc* nella schermata di GNU GRUB per interrompere il normale processo di avvio, selezionare *ONIE* e premere *Invio*.
. Nella schermata successiva, selezionare *ONIE: Install OS*.
. Il processo di ricerca del programma di installazione di ONIE esegue la ricerca dell'installazione automatica. Premere *Invio* per interrompere temporaneamente il processo.
. Quando il processo di rilevamento si è arrestato:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Se il servizio DHCP è in esecuzione sulla rete, verificare che l'indirizzo IP, la subnet mask e il gateway predefinito siano assegnati correttamente:
+
`ifconfig eth0`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. Se lo schema di indirizzamento IP viene definito manualmente, procedere come segue:
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Ripetere il passaggio 9 per verificare che le informazioni statiche siano inserite correttamente.
. Installare Cumulus Linux:
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Una volta completata l'installazione, accedere allo switch:
+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Verificare la versione di Cumulus Linux:
+
`net show version`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.Quali sono le prossime novità?
link:install-rcf-sn2100-storage.html["Installare lo script RCF"].
