---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 'Sostituzione di uno switch di archiviazione NVIDIA SN2100 difettoso in una procedura non distruttiva \(NDU\).' 
---
= Sostituisci uno switch di archiviazione NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire uno switch di archiviazione NVIDIA SN2100 difettoso. Si tratta di una procedura non distruttiva.

.Prima di iniziare
Prima di installare il software Cumulus e gli RCF su uno switch di archiviazione NVIDIA SN2100, assicurarsi che:

* Il tuo sistema può supportare gli switch di archiviazione NVIDIA SN2100.
* Hai scaricato gli RCF applicabili.


IL http://hwu.netapp.com["Hardware Universe"^] fornisce dettagli completi sulle porte supportate e sulle relative configurazioni.

La configurazione di rete esistente deve avere le seguenti caratteristiche:

* Completa tutti i passaggi per la risoluzione dei problemi per confermare che è necessario sostituire l'interruttore.
* Assicurarsi che la connettività di gestione sia presente su entrambi gli switch.
+

NOTE: Assicurati di aver completato tutti i passaggi per la risoluzione dei problemi per confermare che il tuo switch debba essere sostituito.



Lo switch NVIDIA SN2100 sostitutivo deve avere le seguenti caratteristiche:

* La connettività della rete di gestione è funzionale.
* È possibile accedere all'interruttore sostitutivo tramite la console.
* Sullo switch viene caricata l'immagine appropriata del sistema operativo RCF e Cumulus.
* La personalizzazione iniziale dello switch è completa.


.Riepilogo della procedura
Questa procedura sostituisce il secondo switch di archiviazione NVIDIA SN2100 sw2 con il nuovo switch NVIDIA SN2100 nsw2.  I due nodi sono node1 e node2.

Passaggi per completare:

* Verificare che l'interruttore da sostituire sia sw2.
* Scollegare i cavi dall'interruttore sw2.
* Ricollegare i cavi allo switch nsw2.
* Verificare tutte le configurazioni dei dispositivi sullo switch nsw2.


.Passi
. Se AutoSupport è abilitato su questo cluster, sopprimere la creazione automatica dei casi richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ è la durata della finestra di manutenzione in ore.

. Modificare il livello di privilegio in avanzato, immettendo *y* quando richiesto per continuare:
+
`set -privilege advanced`

. Controllare lo stato di integrità delle porte del nodo di archiviazione per confermare la connessione allo switch di archiviazione S1:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Verificare che lo switch di archiviazione sw1 sia disponibile:
+
`network device-discovery show -protocol lldp`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Esegui il `net show interface` comando sullo switch funzionante per confermare che puoi vedere entrambi i nodi e tutti gli scaffali:
+
`net show interface`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Verificare le porte degli scaffali nel sistema di archiviazione:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. Rimuovere tutti i cavi collegati allo switch di archiviazione sw2.
. Ricollegare tutti i cavi allo switch sostitutivo nsw2.
. Ricontrollare lo stato di integrità delle porte del nodo di archiviazione:
+
`storage port show -port-type ENET`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. Verificare che entrambi gli switch siano disponibili:
+
`net device-discovery show -protocol lldp`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. Verificare le porte degli scaffali nel sistema di archiviazione:
+
`storage shelf port show -fields remote-device, remote-port`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. Ripristinare il livello di privilegio su amministratore:
+
`set -privilege admin`

. Se hai disattivato la creazione automatica dei casi, riattivala richiamando un messaggio AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà ora?
Dopo aver sostituito gli interruttori, puoi link:../switch-cshm/config-overview.html["configurare il monitoraggio dello stato dello switch"].
