---
permalink: switch-nvidia-sn2100-storage/reset-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: SN2100 reset switch to factory defaults, SN2100 switches configuration, efos 
summary: Prima di configurare lo switch Cisco Nexus SN2100, leggere le seguenti informazioni. 
---
= Ripristinare lo switch di archiviazione SN2100 ai valori predefiniti di fabbrica
:allow-uri-read: 


[role="lead"]
Per ripristinare le impostazioni predefinite di fabbrica dello switch di archiviazione SN2100:

* Per Cumulus Linux 5.10 e versioni precedenti, applicare l'immagine Cumulus.
* Per Cumulus Linux 5.11 e versioni successive, utilizzare `nv action reset system factory-default` comando.


.A proposito di questa attività
* È necessario essere collegati allo switch mediante la console seriale.
* Per accedere ai comandi tramite sudo è necessario disporre della password di root.



NOTE: Per ulteriori informazioni sull'installazione di Cumulus Linux, vederelink:configure-software-overview-sn2100-cluster.html["Workflow di installazione del software per switch NVIDIA SN2100"] .

.Fasi
[role="tabbed-block"]
====
.Cumulus Linux 5.10 e versioni precedenti
--
. Dalla console Cumulus, scarica e metti in coda l'installazione del software dello switch con il comando `onie-install -a -i` seguito dal percorso del file al software di commutazione, ad esempio:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://<web-server>/<path>/cumulus-linux-5.10.0-mlx-amd64.bin*
----
. Il programma di installazione avvia il download.  Digitare *y* quando richiesto per confermare l'installazione quando l'immagine è stata scaricata e verificata.
. Riavviare lo switch per installare il nuovo software.
+
`sudo reboot`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
+

NOTE: Lo switch si riavvia e avvia l'installazione del software, operazione che richiede un po' di tempo.  Una volta completata l'installazione, lo switch si riavvia e rimane allo stato `log-in` richiesta.



--
.Cumulus Linux 5.11 e versioni successive
--
. Per ripristinare le impostazioni predefinite di fabbrica dello switch e rimuovere tutti i file di configurazione, di sistema e di registro, eseguire:
+
`nv action reset system factory-default`

+
Ad esempio:

+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *nv action reset system factory-default*

This operation will reset the system configuration, delete the log files and reboot the switch.
Type [y] continue.
Type [n] to abort.
Do you want to continue? [y/n] *y*
----


Vedi NVIDIA https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Installation-Management/Factory-Reset/["Ripristino delle impostazioni di fabbrica"^] documentazione per ulteriori dettagli.

--
====