---
permalink: switch-nvidia-sn2100/sn2100-overview.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 'Per l"installazione e la manutenzione dello switch NVIDIA SN2100, consultare tutti i requisiti e la documentazione consigliata.' 
---
= Panoramica e requisiti per gli switch NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per l'installazione e la manutenzione dello switch NVIDIA SN2100, consultare tutti i requisiti e la documentazione consigliata.

Se si desidera creare cluster ONTAP con più di due nodi, sono necessari due switch di rete cluster supportati. È possibile utilizzare switch di gestione aggiuntivi, opzionali.



== Supporto di ONTAP e Linux

Lo switch NVIDIA SN2100 è uno switch Ethernet da 10/25/40/100 GB con Cumulus Linux. Lo switch supporta quanto segue:

* ONTAP 9.10.1P3. Lo switch SN2100 serve applicazioni cluster e storage in ONTAP 9.10.1P3 su diverse coppie di switch. A partire da ONTAP 9.10.1P3, è possibile utilizzare gli switch NVIDIA SN2100 per combinare funzionalità di storage e cluster in una configurazione di switch condivisa.
* Sistema operativo Cumulus Linux (CL) versione 4.4.3. Per informazioni aggiornate sulla compatibilità, consultare https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switch Ethernet NVIDIA"^] pagina informativa.
* È possibile installare Cumulus Linux quando lo switch esegue Cumulus Linux o ONIE.




== Dettagli del cabinet e del kit di guide

Lo switch NVIDIA SN2100 (X190006/X190106) viene installato nel cabinet doppio/singolo NVIDIA con le staffe standard incluse con lo switch.

La seguente tabella elenca il codice ricambio e la descrizione degli switch e dei kit di guide MSN2100:

[cols="1,2"]
|===
| Codice del ricambio | Descrizione 


 a| 
X190006-PE
 a| 
Switch cluster, NVIDIA SN2100, 16 PUNTI 100G, PTSX



 a| 
X190006-PI
 a| 
Switch cluster, NVIDIA SN2100, 16 PUNTI 100G, PSIN



 a| 
X190106-FE-PE
 a| 
Switch, NVIDIA SN2100, 16PT 100G, PTSX, front-end



 a| 
X190106-FE-PI
 a| 
Switch, NVIDIA SN2100, 16PT 100G, PSIN, front-end



 a| 
X-MTEF-KIT-D
 a| 
Kit di guide, NVIDIA Dual Switch fianco a fianco



 a| 
X-MTEF-KIT-E
 a| 
Kit di guide, NVIDIA Single Switch a breve profondità

|===

NOTE: Consultare la documentazione NVIDIA per ulteriori informazioni su https://docs.nvidia.com/networking/display/sn2000pub/Installation["Installazione dello switch SN2100 e del kit guida"^].



== Documentazione disponibile

La seguente tabella elenca la documentazione disponibile per gli switch NVIDIA SN2100.

[cols="1,2"]
|===
| Titolo | Descrizione 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html["_Configurazione e configurazione degli switch NVIDIA SN2100_"^]
 a| 
Descrive come configurare e configurare gli switch NVIDIA SN2100, inclusa l'installazione di Cumulus Linux e degli RCF applicabili.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch.html["_Eseguire la migrazione da uno switch cluster Cisco a uno switch cluster NVIDIA SN2100_"^]
 a| 
Descrive come eseguire la migrazione da ambienti che utilizzano switch cluster Cisco a ambienti che utilizzano switch cluster NVIDIA SN2100.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-storage-switch-sn2100-storage.html["_Migrare da uno switch di storage Cisco a uno switch di storage NVIDIA_"^]
 a| 
Descrive come eseguire la migrazione da ambienti che utilizzano switch di storage Cisco a ambienti che utilizzano switch di storage NVIDIA SN2100.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["_Eseguire la migrazione a un cluster con switch a due nodi con switch cluster NVIDIA SN2100_"^]
 a| 
Descrive come migrare a un ambiente con switch a due nodi utilizzando gli switch cluster NVIDIA SN2100.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-cluster.html["_Sostituire uno switch cluster NVIDIA SN2100_"^]
 a| 
Descrive la procedura per sostituire uno switch NVIDIA SN2100 difettoso in un cluster e scaricare Cumulus Linux e il file di configurazione di riferimento.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-storage.html["_Sostituire uno switch di storage NVIDIA SN2100_"^]
 a| 
Descrive la procedura per sostituire uno switch di storage NVIDIA SN2100 difettoso e scaricare Cumulus Linux e il file di configurazione di riferimento.

|===